### ISSUE TITLE
Proxy HTTPS Central Collector

### ISSUE THREAD

**Issue by SpencerWoo** [glowroot/glowroot#1014]
Hi all, I'm using HTTPS central collector and want to proxy it to make it more secure.

- I can do the Central Collector with HTTP
- I can do the Central Collector with HTTPS
- I can do the Central with HTTP proxied with NGINX

```
server {
	listen 80 http2;
	location / {
		grpc_pass grpc://server:8181;
	}
}
```

-----

However I can't seem to Central with HTTPS with NGINX proxy.

I get this error on the Agent -- which obviously means NGNIX is blocking/failing to proxy the connection but I'm stuck figuring it out :(
```
2023-06-12 01:04:52.889 WARN  o.g.agent.central.CentralConnection - unable to establish connection with the central collector https://server:443 (will keep trying...): java.net.ConnectException: Connection refused
```

Here's some example files for sanity test:

Agent glowroot.properties with the crt
```
agent.id=x
collector.address=https://server:443
```

Glowroot glowroot-central.properties with the crt and key
```
...
grpc.httpPort=none
grpc.httpsPort=8181
...
```

NGINX nginx.conf
```
server {
    listen 443;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/cert.key;

	location / {
		grpc_pass grpc://server:8181;
	}
}
	
```

Please share your NGINX.conf for HTTPS central collector!  I'm definitely open to feedback or suggestions -- thanks all.

**Comment by Nowheresly** [comment]
Hi @SpencerWoo 
I may be wrong but I think you should try using
```
grpc_pass grps://yourglowroot:8181
```

**Comment by SpencerWoo** [comment]
thank you -- I should be using 
`grpc_pass grpcs://glowrootserver:8181`

Getting this error 
```
2023-06-12 15:11:52.739 WARN  o.g.agent.central.CentralConnection - unable to establish connection with the central collector https://glowroot-lxc2.lxc.liferay.com:443 (will keep trying...): sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

It's obvious to me my NGINX setup is wrong and it's not related to glowroot, but if anyone has thoughts to debug I'm all ears.

---

```
server {
    listen 443 ssl http2;
    server_name server;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/cert.key;

    location / {
        grpc_ssl_certificate /etc/nginx/cert.pem;
        grpc_ssl_certificate_key /etc/nginx/cert.key;

        grpc_pass grpcs://glowrootserver:8181;
    }
}
```

This cert/key is the same one used on the Agent and Collector for HTTPS.  Does this config make sense?

**Comment by SpencerWoo** [comment]
thank you -- I should be using 
`grpc_pass grpcs://glowrootserver:8181`

Getting this error 
```
WARN  o.g.agent.central.CentralConnection - unable to establish connection with the central collector https://server:443 (will keep trying...): sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

It's obvious to me my NGINX setup is wrong and it's not related to glowroot, but if anyone has thoughts to debug I'm all ears.

---

```
server {
    listen 443 ssl http2;
    server_name server;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/cert.key;

    location / {
        grpc_ssl_certificate /etc/nginx/cert.pem;
        grpc_ssl_certificate_key /etc/nginx/cert.key;

        grpc_pass grpcs://glowrootserver:8181;
    }
}
```

This cert/key is the same one used on the Agent and Collector for HTTPS.  Does this config make sense?

**Comment by Nowheresly** [comment]
Hi @SpencerWoo 
That's good news. I think your nginx config is correct now.

Now I think your problem is that you are using a self-signed certificate.
One way to fix this issue is to add your certificate in the `cacerts` file of the jvm on which you get this error message.
Usually, the `cacerts` file is in this folder: `$JAVA_HOME/lib/security`.

You can use the tool named `keytool` located in `$JAVA_HOME/bin/` to add your certificate in the `cacerts` file.
Assuming your certificate is in a file called `cert.pem`, you could try:
`keytool -import -alias glowrootAlias -keystore cacerts -file cert.pem`

Now, any java application using this jvm will trust your certificate. Thus, the connection to the glowroot collector should work.

**Comment by SpencerWoo** [comment]
Thanks for the help!  I actually had this other step with my implementation that was causing problems but the config is indeed valid!
