### ISSUE TITLE
Glowroot agent not working with java 8

### ISSUE THREAD

**Issue by abhinav-oyo** [glowroot/glowroot#1017]
Not using glowroot central but the agent only, shows this error -
```
java.lang.UnsupportedClassVersionError: org/glowroot/agent/embedded/shaded/org/glowroot/ui/SessionMapFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by abhinav-oyo** [comment]
Started with [Version 0.14.0-beta.4](https://github.com/glowroot/glowroot/releases/tag/v0.14.0-beta.4)

**Comment by abhinav-oyo** [comment]
@Nowheresly is there a release planned soon? Or otherwise could you please release an alpha/beta version with this patch? Thanks!

**Comment by Nowheresly** [comment]
Yes, a beta release should be available pretty soon.
