### ISSUE TITLE
Upgrading central collector 0.14.beta3 to beta4 or newer fails

### ISSUE THREAD

**Issue by MikaMLehtonen** [glowroot/glowroot#1019]
Under Tomcat9 (war-package) beta3 works, but beta4 doesn't. No errors can be found from the log, but it seems that for some reason, grpc http doesn't start.
2023-06-21 08:54:52.634 WARN o.g.agent.central.CentralConnection - unable to establish connection with the central collector http://hostname:8181/ (will keep trying...): java.net.ConnectException: Connection refused
Port 8181 doesn't listen nor any other for that service.

What has changed, grpc version?
How to debug?
Any idea?
Cassandra is version 4.0.3, works with beta3.

BR: Mika Lehtonen

**Comment by MikaMLehtonen** [comment]
Something to do with the Datastax driver 3.7.2 -> 4.15.0 ?
I upgraded Cassandra to 4.1.2, didn't change anything.

**Comment by Nowheresly** [comment]
Maybe same issue as #1006 ?

**Comment by MikaMLehtonen** [comment]
Cassandra is running on 127.0.0.1:9042, but with beta4, I don't see a single line in the log, that it would even try to use datastax driver or try to connect to Cassandra.

**Comment by Nowheresly** [comment]
Are you using embedded glowroot?
Or are you using a central collector ?
With embedded, you do not need Cassandra and there is no grpc.
Glowroot is embedded in your tomcat app and served by default on port 4000

**Comment by Nowheresly** [comment]
My bad, I should have realized sooner. Glad to see you were able to make it work!

**Comment by Nowheresly** [comment]
The documentation has been updated.
