### ISSUE TITLE
Agent with multiple steps to Central Collector

### ISSUE THREAD

**Issue by SpencerWoo** [glowroot/glowroot#1024]
If we have a setup that does Agent > A > B > ... Z > Collector

While it should be simple passthroughs, my assumption is somehow they're taking too long leading to problems such as:
* Agent drops connection 
* `WARN  o.g.agent.central.CentralConnection - unable to establish connection with the central collector .... org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR`
* 504 Gateway Timeout for fetching JVM settings
* etc

Any tips on configuring this setup to perform the same as Agent > Collector?  
Any tips on debugging the problems detailed above?
I don't see details on configuring the agent-collector liveness probe.

Thank you!

**Comment by SpencerWoo** [comment]
I'm looking over whether https://github.com/glowroot/glowroot/pull/842 via https://github.com/glowroot/glowroot/releases/tag/v0.14.0 might help here

**Comment by SpencerWoo** [comment]
We have logs that look like this
```
INFO 2023-07-07T20:10:40.800183130Z [resource.labels.containerName: redacted] 2023-07-07 20:10:40.799 WARN o.g.a.c.DownstreamServiceObserver - lost connection to the central collector (will keep trying to re-establish...): org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: INTERNAL: RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR
INFO 2023-07-07T20:10:40.803134694Z [resource.labels.containerName: redacted] 2023-07-07 20:10:40.802 INFO o.g.a.c.DownstreamServiceObserver - re-established connection to the central collector
```

It loses connection at .800 but reconnects at .803.  


How can I configure the connection grace period?  I'm also looking into confirming that each of the proxies are supporting HTTP2

**Comment by Nowheresly** [comment]
Hi @SpencerWoo 
you can find the settings of the grpcserver of the collector here:

https://github.com/glowroot/glowroot/blob/f3b70a8dc3f60384120b021877b82ca10d0a14ac/central/src/main/java/org/glowroot/central/GrpcServer.java#L123-L135

I suppose you should configure grpc proxies according to these settings (e.g. connection max age is set to 20 min, so proxies should have their max age connection set to more than 20 min)

**Comment by SpencerWoo** [comment]
Any thoughts on this error? 

```
WARN  o.g.a.c.DownstreamServiceObserver - lost connection to the central collector (will keep trying to re-establish...): 
org.glowroot.agent.shaded.io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
INFO  o.g.a.c.DownstreamServiceObserver - re-established connection to the central collector
```

I believe it's related to setting up my backend services to support HTTP2 https://cloud.google.com/load-balancing/docs/https#using_grpc_with_your_applications however it's interesting that it's successful and data comes through -- but not all data and there's repeated disconnections (and reconnection).

**Comment by SpencerWoo** [comment]
Hmm.  I've setup HTTP2 with the backend but the connection problem is still occurring so that wasn't the issue -- the agent constantly disconnects and reconnects with the central.  Any ideas?

**Comment by SpencerWoo** [comment]
Was a long journey but TLDR;
* HTTP2 for collector
* NGINX closing connections.
