### ISSUE TITLE
java.lang.ClassNotFoundException: org.owasp.html.HtmlPolicyBuilder

### ISSUE THREAD

**Issue by matthijsbierman** [glowroot/glowroot#1042]
Trying to run Glowroot [glowroot-0.14.1-beta.3-dist.zip](https://github.com/glowroot/glowroot/releases/download/v0.14.1-beta.3/glowroot-0.14.1-beta.3-dist.zip) results in:

```
java.lang.ClassNotFoundException: org.owasp.html.HtmlPolicyBuilder
```

I've compared the releases and it looks like these test dependencies made it into the `ConfigJsonService`:

https://github.com/glowroot/glowroot/compare/v0.14.1-beta.2...v0.14.1-beta.3#diff-a9da94eee3d7d9d3531bdcdb12884e2b2af7c58a5ac6029af13ffc863b9601cbR47-R48

**Comment by Nowheresly** [comment]
Thanks for the report!
