### ISSUE TITLE
Unable to run 0.14 in Java 8 with embedded collector

### ISSUE THREAD

**Issue by paul-mcculloch** [glowroot/glowroot#1046]
The classes in lib\glowroot-embedded-collector\org\glowroot\agent\embedded\shaded\org\glowroot\ui have been compiled with Java 11. When starting Glowroot on Java 8 an error is thrown:

"Glowroot failed to start: org/glowroot/agent/embedded/shaded/org/glowroot/ui/SessionMapFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

**Comment by Nowheresly** [comment]
Please use version 0.14.1 to get a fix.

Currently only available in beta

[https://github.com/glowroot/glowroot/releases/tag/v0.14.1-beta.4](https://github.com/glowroot/glowroot/releases/tag/v0.14.1-beta.4)

**Comment by may88s** [comment]
I'm trying to upgrade from 0.13.6 to 0.14.0, using java8 and getting the same error as Paul reported above.
I've just pulled down the 0.14.1-beta.4 version and I'm still getting the same error.

**Comment by Nowheresly** [comment]
Hello,

I suspect the lib you use is not the beta.4 lib.
You can check easily in which version of jdk a class has been compiled into by running this command:

```
javap -cp glowroot-embedded-collector.jar -verbose org/glowroot/agent/embedded/shaded/org/glowroot/ui/SessionMapFactory
Classfile jar:file:///home/richard/Downloads/beta4/glowroot/lib/glowroot-embedded-collector.jar!/org/glowroot/agent/embedded/shaded/org/glowroot/ui/SessionMapFactory.class
  Last modified Nov 6, 2023; size 335 bytes
  SHA-256 checksum 560bed2fdfd49ff51c8d056cb3c9ea009a6295982448183d3929b8d7179861f7
  Compiled from "SessionMapFactory.java"
public interface org.glowroot.agent.embedded.shaded.org.glowroot.ui.SessionMapFactory
  minor version: 0
  major version: 52

```

As you can see, the mentioned class is compiled in major version 52.

You should double check your `lib/glowroot-embedded-collector.jar` lib and use the one provided by beta.4 (or even beta.6) release.

**Comment by may88s** [comment]
I'm using Ansible unarchive module to install over the existing files (which were 1.4.0). It said it had replaced the files. The  date stamps and file sizes match the zip contents. The `javap` command above returns the same results other than my checksum is MD5.  I had saved the 0.14.1-beta.4 and switched back to 0.13.6. Switch back to beta.4 it works.  Gosh knows why that didn't work. Annoyed with myself as I thought I was being careful.  Sorry to waste you time.
My dilemma now is do I take a beta version into production.  Any eta on a date for the final 0.14.1 release (if it is not bad form to ask)?

**Comment by Nowheresly** [comment]
No problem @may88s 
I'm still struggling with some tough issues that prevent us from publishing the final 0.14.1 release.
Yet, except for these, beta.6 should be hopefully stable enough. Feedback from the community is always welcome and helps a lot.

**Comment by Nowheresly** [comment]
Please consider using the latest 0.14.1 release
