### ISSUE TITLE
Glowroot UI not started with version 0.14.1-beta.3

### ISSUE THREAD

**Issue by bcourtine** [glowroot/glowroot#1047]
Hello,

I upgraded from version 0.14.0-beta.2 to version 0.14.1-beta.3.

Agent seems to be started, but UI is not.

Here is my glowroot log file:

> 2023-10-31 09:22:57.513 INFO  org.glowroot - Glowroot version: 0.14.0-beta.2, built 2021-11-08 01:15:43 +0000
> 2023-10-31 09:22:57.519 INFO  org.glowroot - Java version: 17.0.4.1 (Oracle Corporation / Linux)
> 2023-10-31 09:22:57.526 INFO  org.glowroot - Java args: -Xmx3968M -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -javaagent:/opt/glowroot/glowroot.jar
> 2023-10-31 09:23:04.330 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)
> 2023-10-31 12:03:00.582 INFO  org.glowroot - Glowroot version: 0.14.1-beta.3, built 2023-09-04 16:39:43 +0000
> 2023-10-31 12:03:00.587 INFO  org.glowroot - Java version: 17.0.4.1 (Oracle Corporation / Linux)
> 2023-10-31 12:03:00.590 INFO  org.glowroot - Java args: -Xmx3968M -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -javaagent:/opt/glowroot/glowroot.jar

With the 0.14.1-beta.3 version, Iog line "UI listening on ..." is missing, and I can confirm that nothing is listening on port 4000.

Here is my start command:

```
/usr/bin/java \
  -Xmx3968M \
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 \
  -javaagent:/opt/glowroot/glowroot.jar \
  -Dglowroot.conf.dir=/etc/myapp/glowroot \
  -Dglowroot.data.dir=/var/myapp/glowroot/datadir \
  -Dglowroot.log.dir=/var/log/myapp/glowroot \
  -Dglowroot.tmp.dir=/var/myapp/glowroot/tmp \
  -jar /var/myapp/server/myapp.jar
```

In the conf dir, I have both admin.json and config.json (unchanged since 0.14.0 version).

Glowroot agent is started, since DB located at `/var/myapp/glowroot/datadir` is created and populated.
Only the UI is missing.

Any help would be appreciated.

**Comment by Nowheresly** [comment]
Hi @bcourtine , thanks for the report, this is really appreciated!
It should be fixed with the new release.
