### ISSUE TITLE
Incorrect central glowroot jar link in wiki

### ISSUE THREAD

**Issue by hepranshup** [glowroot/glowroot#1093]
There is a discrepancy between the Glowroot wiki download link for the glowroot-central jar and the actual latest version.

The current [wiki](https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation) download link points to version 0.13.6, while the latest version available is 0.14.2.
This inconsistency can lead to confusion for users who rely on the wiki for installation instructions, potentially resulting in them downloading an outdated version.

Currently to get the correct version, users need to go to the assets in the [release page](https://github.com/glowroot/glowroot/releases/tag/v0.14.2) to download the correct jar distribution.

**Comment by Nowheresly** [comment]
Thanks @hepranshup
