### ISSUE TITLE
[0.14.2][CENTRAL-COLLECTOR] CASSANDRA_SYMMETRIC_ENCRYPTION_KEY is not being set on glowroot-central.properties

### ISSUE THREAD

**Issue by FilipeCoelhoAlves** [glowroot/glowroot#1096]
I am setting the variable in podman-compose however due to the lack of the cassandra.symmetricEncryptionKey line in the glowroot-central.properties file it is not being saved and has to be configured manually

**Comment by Nowheresly** [comment]
Hi @FilipeCoelhoAlves 
thanks for the report. It will be fixed in version 0.14.3-beta5
