### ISSUE TITLE
APM with other languages?

### ISSUE THREAD

**Issue by equake** [glowroot/glowroot#136]
Hi @trask !

Now that Glowroot have the "central" collector, how hard would be to implement agents for languages other than Java?

Is the protocol between the agent and the collector java-centric? Is it documented somewhere?

Thanks!

**Comment by trask** [comment]
Hi, the agent/collector communication is over gRPC, so it shouldn't be difficult to generate bindings and send data from other languages supported by gRPC (http://www.grpc.io/about/#osp).

The main collector service proto "spec" is here:

https://github.com/glowroot/glowroot/blob/v0.9.6/wire-api/src/main/proto/CollectorService.proto

It may also be helpful to look at how the java agent sends data:

https://github.com/glowroot/glowroot/blob/v0.9.6/agent/core/src/main/java/org/glowroot/agent/central/CentralCollector.java

I'm happy to answer any questions.

**Comment by equake** [comment]
Nice! I will take a look.
