### ISSUE TITLE
Build error: AlertingServiceTest.testGaugeValueFormatting:229 expected:<"333[,]333"> but was:<"333[ ]333">

### ISSUE THREAD

**Issue by jazzdabbler** [glowroot/glowroot#138]
`
$ mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 37 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 37 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.11
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 11
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Glowroot Parent Project
[INFO] Glowroot Build License Bundle
[INFO] Glowroot Checker Annotations for JDK 6
[INFO] Glowroot Build Multi Lib Tests
[INFO] Glowroot Wire API
[INFO] Glowroot Common
[INFO] Glowroot UI
[INFO] Glowroot Agent API
[INFO] Glowroot Agent Plugin API
[INFO] Glowroot Agent Core
[INFO] Glowroot Agent Integration Test Harness
[INFO] Glowroot Agent Integration Tests
[INFO] Glowroot Agent Executor Plugin
[INFO] Glowroot Agent Cassandra Plugin
[INFO] Glowroot Agent Servlet Plugin
[INFO] Glowroot Agent Grails Plugin
[INFO] Glowroot Agent Hibernate Plugin
[INFO] Glowroot Agent Http Client Plugin
[INFO] Glowroot Agent JAX-RS Plugin
[INFO] Glowroot Agent Jdbc Plugin
[INFO] Glowroot Agent JMS Plugin
[INFO] Glowroot Agent JSF Plugin
[INFO] Glowroot Agent JSP Plugin
[INFO] Glowroot Agent Logger Plugin
[INFO] Glowroot Agent Netty Plugin
[INFO] Glowroot Agent Play Plugin
[INFO] Glowroot Agent Quartz Plugin
[INFO] Glowroot Agent Redis Plugin
[INFO] Glowroot Agent Spray Plugin
[INFO] Glowroot Agent Spring Plugin
[INFO] Glowroot Agent Struts Plugin
[INFO] Glowroot Agent Benchmarks
[INFO] Glowroot Agent UI Sandbox
[INFO] Glowroot Agent Distribution Maven Plugin
[INFO] Glowroot Agent
[INFO] Glowroot Central
[INFO] Glowroot WebDriver Tests
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowroot Parent Project 0.9.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ glowroot-parent ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ glowroot-parent ---
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ glowroot-parent ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (default) @ glowroot-parent ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ glowroot-parent ---
[INFO] Installing /Users/stanislavmakarchuk/glowroot/pom.xml to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/glowroot-parent/0.9.7/glowroot-parent-0.9.7.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowroot Build License Bundle 0.9.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ glowroot-build-license-bundle ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ glowroot-build-license-bundle ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:bundle (default) @ glowroot-build-license-bundle ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ glowroot-build-license-bundle ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ glowroot-build-license-bundle ---
[INFO] No sources to compile
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ glowroot-build-license-bundle ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ glowroot-build-license-bundle ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/build/license-bundle/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ glowroot-build-license-bundle ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ glowroot-build-license-bundle ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ glowroot-build-license-bundle ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/build/license-bundle/target/glowroot-build-license-bundle-0.9.7.jar
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (default) @ glowroot-build-license-bundle ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/build/license-bundle/target/glowroot-build-license-bundle-0.9.7-sources.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ glowroot-build-license-bundle ---
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/license-bundle/target/glowroot-build-license-bundle-0.9.7.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-license-bundle/0.9.7/glowroot-build-license-bundle-0.9.7.jar
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/license-bundle/pom.xml to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-license-bundle/0.9.7/glowroot-build-license-bundle-0.9.7.pom
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/license-bundle/target/glowroot-build-license-bundle-0.9.7-sources.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-license-bundle/0.9.7/glowroot-build-license-bundle-0.9.7-sources.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowroot Checker Annotations for JDK 6 0.9.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ glowroot-build-checker-jdk6 ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ glowroot-build-checker-jdk6 ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ glowroot-build-checker-jdk6 ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ glowroot-build-checker-jdk6 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/src/main/resources
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ glowroot-build-checker-jdk6 ---
[INFO] Compiling 5 source files to /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/target/classes
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ glowroot-build-checker-jdk6 ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ glowroot-build-checker-jdk6 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/src/test/resources
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ glowroot-build-checker-jdk6 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ glowroot-build-checker-jdk6 ---
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ glowroot-build-checker-jdk6 ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/target/glowroot-build-checker-jdk6-0.9.7.jar
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (default) @ glowroot-build-checker-jdk6 ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/target/glowroot-build-checker-jdk6-0.9.7-sources.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ glowroot-build-checker-jdk6 ---
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/target/glowroot-build-checker-jdk6-0.9.7.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-checker-jdk6/0.9.7/glowroot-build-checker-jdk6-0.9.7.jar
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/pom.xml to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-checker-jdk6/0.9.7/glowroot-build-checker-jdk6-0.9.7.pom
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/checker-jdk6/target/glowroot-build-checker-jdk6-0.9.7-sources.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-checker-jdk6/0.9.7/glowroot-build-checker-jdk6-0.9.7-sources.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowroot Build Multi Lib Tests 0.9.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ glowroot-build-multi-lib-tests ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ glowroot-build-multi-lib-tests ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ glowroot-build-multi-lib-tests ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ glowroot-build-multi-lib-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/src/main/resources
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ glowroot-build-multi-lib-tests ---
[INFO] Compiling 23 source files to /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/target/classes
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ glowroot-build-multi-lib-tests ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ glowroot-build-multi-lib-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/src/test/resources
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ glowroot-build-multi-lib-tests ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ glowroot-build-multi-lib-tests ---
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ glowroot-build-multi-lib-tests ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/target/glowroot-build-multi-lib-tests-0.9.7.jar
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (default) @ glowroot-build-multi-lib-tests ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/target/glowroot-build-multi-lib-tests-0.9.7-sources.jar
[INFO]
[INFO] --- maven-assembly-plugin:2.6:single (jar-with-dependencies) @ glowroot-build-multi-lib-tests ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/target/glowroot-build-multi-lib-tests-0.9.7-jar-with-dependencies.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ glowroot-build-multi-lib-tests ---
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/target/glowroot-build-multi-lib-tests-0.9.7.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-multi-lib-tests/0.9.7/glowroot-build-multi-lib-tests-0.9.7.jar
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/pom.xml to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-multi-lib-tests/0.9.7/glowroot-build-multi-lib-tests-0.9.7.pom
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/target/glowroot-build-multi-lib-tests-0.9.7-sources.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-multi-lib-tests/0.9.7/glowroot-build-multi-lib-tests-0.9.7-sources.jar
[INFO] Installing /Users/stanislavmakarchuk/glowroot/build/multi-lib-tests/target/glowroot-build-multi-lib-tests-0.9.7-jar-with-dependencies.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/build/glowroot-build-multi-lib-tests/0.9.7/glowroot-build-multi-lib-tests-0.9.7-jar-with-dependencies.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowroot Wire API 0.9.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ glowroot-wire-api ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ glowroot-wire-api ---
[INFO]
[INFO] --- protobuf-maven-plugin:0.5.0:compile (default) @ glowroot-wire-api ---
[INFO] Compiling 7 proto file(s) to /Users/stanislavmakarchuk/glowroot/wire-api/target/generated-sources/protobuf/java
[INFO]
[INFO] --- protobuf-maven-plugin:0.5.0:compile-custom (default) @ glowroot-wire-api ---
[INFO] Compiling 7 proto file(s) to /Users/stanislavmakarchuk/glowroot/wire-api/target/generated-sources/protobuf/grpc-java
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ glowroot-wire-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/wire-api/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ glowroot-wire-api ---
[INFO] Compiling 9 source files to /Users/stanislavmakarchuk/glowroot/wire-api/target/classes
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ glowroot-wire-api ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ glowroot-wire-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/wire-api/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ glowroot-wire-api ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ glowroot-wire-api ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ glowroot-wire-api ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/wire-api/target/glowroot-wire-api-0.9.7.jar
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (default) @ glowroot-wire-api ---
[INFO] Building jar: /Users/stanislavmakarchuk/glowroot/wire-api/target/glowroot-wire-api-0.9.7-sources.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ glowroot-wire-api ---
[INFO] Installing /Users/stanislavmakarchuk/glowroot/wire-api/target/glowroot-wire-api-0.9.7.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/glowroot-wire-api/0.9.7/glowroot-wire-api-0.9.7.jar
[INFO] Installing /Users/stanislavmakarchuk/glowroot/wire-api/pom.xml to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/glowroot-wire-api/0.9.7/glowroot-wire-api-0.9.7.pom
[INFO] Installing /Users/stanislavmakarchuk/glowroot/wire-api/target/glowroot-wire-api-0.9.7-sources.jar to /Users/stanislavmakarchuk/.m2/repository/org/glowroot/glowroot-wire-api/0.9.7/glowroot-wire-api-0.9.7-sources.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowroot Common 0.9.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ glowroot-common ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ glowroot-common ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ glowroot-common ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ glowroot-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stanislavmakarchuk/glowroot/common/src/main/resources
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ glowroot-common ---
[INFO] Compiling 61 source files to /Users/stanislavmakarchuk/glowroot/common/target/classes
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ glowroot-common ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ glowroot-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ glowroot-common ---
[INFO] Compiling 12 source files to /Users/stanislavmakarchuk/glowroot/common/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ glowroot-common ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.glowroot.common.config.PermissionParserTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec - in org.glowroot.common.config.PermissionParserTest
Running org.glowroot.common.config.SimplePermissionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in org.glowroot.common.config.SimplePermissionTest
Running org.glowroot.common.model.ErrorSummaryBaseTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in org.glowroot.common.model.ErrorSummaryBaseTest
Running org.glowroot.common.model.LazyHistogramTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.294 sec - in org.glowroot.common.model.LazyHistogramTest
Running org.glowroot.common.model.MutableProfileTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.298 sec - in org.glowroot.common.model.MutableProfileTest
Running org.glowroot.common.model.ScratchBufferTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.glowroot.common.model.ScratchBufferTest
Running org.glowroot.common.repo.util.AlertingServiceTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.612 sec <<< FAILURE! - in org.glowroot.common.repo.util.AlertingServiceTest
testGaugeValueFormatting(org.glowroot.common.repo.util.AlertingServiceTest)  Time elapsed: 0.008 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"333[,]333"> but was:<"333[ ]333">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.glowroot.common.repo.util.AlertingServiceTest.testGaugeValueFormatting(AlertingServiceTest.java:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Running org.glowroot.common.repo.util.EncryptionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.glowroot.common.repo.util.EncryptionTest
Running org.glowroot.common.repo.util.GaugesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.glowroot.common.repo.util.GaugesTest
Running org.glowroot.common.repo.util.LazySecretKeyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in org.glowroot.common.repo.util.LazySecretKeyTest
Running org.glowroot.common.util.ScheduledRunnableTest
2016-11-15 16:13:48.060 ERROR o.g.common.util.ScheduledRunnable - This is a test
java.lang.RuntimeException: This is a test
	at org.glowroot.common.util.ScheduledRunnableTest$ExceptionalScheduledRunnable.runInternal(ScheduledRunnableTest.java:102)
	at org.glowroot.common.util.ScheduledRunnable.run(ScheduledRunnable.java:49)
	at org.glowroot.common.util.ScheduledRunnableTest.testExceptionalScheduledRunnable(ScheduledRunnableTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
2016-11-15 16:13:48.063 ERROR o.g.common.util.ScheduledRunnable - command has already been scheduled: org.glowroot.common.util.ScheduledRunnableTest$TestScheduledRunnable@63f259c3
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec - in org.glowroot.common.util.ScheduledRunnableTest
Running org.glowroot.common.util.VersionTest
2016-11-15 16:13:48.091 WARN  org.glowroot.common.util.Version - invalid Build-Commit attribute in META-INF/MANIFEST.MF file, should be a 40 character git commit hash
2016-11-15 16:13:48.093 WARN  org.glowroot.common.util.Version - could not find Build-Time attribute in META-INF/MANIFEST.MF file
2016-11-15 16:13:48.095 WARN  org.glowroot.common.util.Version - url for class is unexpectedly null: long
2016-11-15 16:13:48.096 WARN  org.glowroot.common.util.Version - invalid Build-Commit attribute in META-INF/MANIFEST.MF file, should be a 40 character git commit hash
2016-11-15 16:13:48.096 WARN  org.glowroot.common.util.Version - could not find Build-Time attribute in META-INF/MANIFEST.MF file
2016-11-15 16:13:48.097 WARN  org.glowroot.common.util.Version - invalid Build-Commit attribute in META-INF/MANIFEST.MF file, should be a 40 character git commit hash
2016-11-15 16:13:48.097 WARN  org.glowroot.common.util.Version - could not find Build-Time attribute in META-INF/MANIFEST.MF file
2016-11-15 16:13:48.098 WARN  org.glowroot.common.util.Version - could not find Implementation-Version attribute in META-INF/MANIFEST.MF file
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec - in org.glowroot.common.util.VersionTest

Results :

Failed tests:
  AlertingServiceTest.testGaugeValueFormatting:229 expected:<"333[,]333"> but was:<"333[ ]333">

Tests run: 46, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Glowroot Parent Project ............................ SUCCESS [  1.294 s]
[INFO] Glowroot Build License Bundle ...................... SUCCESS [  1.029 s]
[INFO] Glowroot Checker Annotations for JDK 6 ............. SUCCESS [  0.859 s]
[INFO] Glowroot Build Multi Lib Tests ..................... SUCCESS [  1.763 s]
[INFO] Glowroot Wire API .................................. SUCCESS [  7.034 s]
[INFO] Glowroot Common .................................... FAILURE [  6.343 s]
[INFO] Glowroot UI ........................................ SKIPPED
[INFO] Glowroot Agent API ................................. SKIPPED
[INFO] Glowroot Agent Plugin API .......................... SKIPPED
[INFO] Glowroot Agent Core ................................ SKIPPED
[INFO] Glowroot Agent Integration Test Harness ............ SKIPPED
[INFO] Glowroot Agent Integration Tests ................... SKIPPED
[INFO] Glowroot Agent Executor Plugin ..................... SKIPPED
[INFO] Glowroot Agent Cassandra Plugin .................... SKIPPED
[INFO] Glowroot Agent Servlet Plugin ...................... SKIPPED
[INFO] Glowroot Agent Grails Plugin ....................... SKIPPED
[INFO] Glowroot Agent Hibernate Plugin .................... SKIPPED
[INFO] Glowroot Agent Http Client Plugin .................. SKIPPED
[INFO] Glowroot Agent JAX-RS Plugin ....................... SKIPPED
[INFO] Glowroot Agent Jdbc Plugin ......................... SKIPPED
[INFO] Glowroot Agent JMS Plugin .......................... SKIPPED
[INFO] Glowroot Agent JSF Plugin .......................... SKIPPED
[INFO] Glowroot Agent JSP Plugin .......................... SKIPPED
[INFO] Glowroot Agent Logger Plugin ....................... SKIPPED
[INFO] Glowroot Agent Netty Plugin ........................ SKIPPED
[INFO] Glowroot Agent Play Plugin ......................... SKIPPED
[INFO] Glowroot Agent Quartz Plugin ....................... SKIPPED
[INFO] Glowroot Agent Redis Plugin ........................ SKIPPED
[INFO] Glowroot Agent Spray Plugin ........................ SKIPPED
[INFO] Glowroot Agent Spring Plugin ....................... SKIPPED
[INFO] Glowroot Agent Struts Plugin ....................... SKIPPED
[INFO] Glowroot Agent Benchmarks .......................... SKIPPED
[INFO] Glowroot Agent UI Sandbox .......................... SKIPPED
[INFO] Glowroot Agent Distribution Maven Plugin ........... SKIPPED
[INFO] Glowroot Agent ..................................... SKIPPED
[INFO] Glowroot Central ................................... SKIPPED
[INFO] Glowroot WebDriver Tests ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.437 s
[INFO] Finished at: 2016-11-15T16:13:48+02:00
[INFO] Final Memory: 65M/806M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project glowroot-common: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/stanislavmakarchuk/glowroot/common/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :glowroot-common`

**Comment by trask** [comment]
Thanks again, should be fixed now.
