### ISSUE TITLE
Change Context Path

### ISSUE THREAD

**Issue by numiralofe** [glowroot/glowroot#139]
Hi,

On the agentconfig file, admin.json is it possible to set the context path other than "/", I would like to use something like 0.0.0.0:4000/servername

Thanks

**Comment by trask** [comment]
Thanks for submitting issue.  Is this so you can reverse proxy behind an http server?

**Comment by numiralofe** [comment]
Yes, multiple servers behind proxy_pass. The idea would be to have one domain with multiple paths, in the case each per server. 

location /server01 {
    proxy_pass http://server01:4000/server01;
}

Currently without applying rewrite rules or if possible change context path, scripts and styles are redirected to the root path.

Thanks.

**Comment by numiralofe** [comment]
thanks

**Comment by trask** [comment]
Good idea.  There was a way to deal with this reverse proxy issue previously, but this is much better.  Have a try with the latest snapshot [glowroot-agent-0.9.8-SNAPSHOT-dist.zip](https://oss.sonatype.org/content/repositories/snapshots/org/glowroot/glowroot-agent/0.9.8-SNAPSHOT/glowroot-agent-0.9.8-20161118.074503-2-dist.zip) when you have a chance.
