### ISSUE TITLE
Add some documentation for build process under MacOS X

### ISSUE THREAD

**Issue by jazzdabbler** [glowroot/glowroot#141]
I think, add some information to WIKI about build process under MacOS X may be useful for some users.
Especially, we need to correct set JAVA_HOME variable
bash-3.2$ cat ~/.bash_profile

JAVA_HOME=$(/usr/libexec/java_home)
export PATH="$JAVA_HOME:$PATH"

Obviously for most developers, but not for all system administrators. Only with this step we will get success build with all integration tests passed.

**Comment by trask** [comment]
Thanks for submitting an issue.  Would adding links to the latest snapshot artifacts avoid need to build locally?  Travis CI builds and deploys these on each commit.

e.g.

https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.8-SNAPSHOT

will download the latest glowroot-agent-0.9.8-SNAPSHOT-dist.zip
