### ISSUE TITLE
Install instruction for jetty 9.x

### ISSUE THREAD

**Issue by sirlordt** [glowroot/glowroot#144]
Install on jetty 9.3.6

Download and unzip the file java agent glowroot-0.9.7-dist.zip

My jetty setup is in /opt/jetty/

**Add to file /opt/jetty/start.ini the next lines**

> --exec
> -javaagent:/path/to/glowroot/glowroot.jar
> 

Ensure glowroot folder is user and group jetty. **Glowroot need write permissions in folder.**

**Comment by trask** [comment]
Good point about write access to the glowroot folder.  I added this to the install instructions.  Also good point about the location of JVM args not always being obvious.  I added a wiki link in the install instructions [[where are my application server's JVM args?](https://github.com/glowroot/glowroot/wiki/Where-are-my-application-server's-JVM-args%3F)] where this kind of wisdom can be accumulated.
