### ISSUE TITLE
Not able to get agents connected

### ISSUE THREAD

**Issue by ZeeTheComputerGeek** [glowroot/glowroot#147]
I am trying to get the agents get connected to the glowroot collector. The collector is running on a separate machine. UI works. However, agent is not getting connected to the collector. I probably need to give the IP of the collector somewhere in the agent config. Could you help out with the configuration so that the collector can communicate with the agent.

**Comment by trask** [comment]
Hi, thanks for reaching out. Have you seen the agent notes at https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation?

**Comment by ZeeTheComputerGeek** [comment]
Yes, I have checked the above link. I have the collector up and running. It is running: 
2016-12-01 12:59:17.283 INFO  org.glowroot - gRPC listening on localhost:8181
2016-12-01 12:59:17.584 INFO  org.glowroot - UI listening on 0.0.0.0:4000

Below is my glowroot-central.properties file 
# default is cassandra.contactPoints=127.0.0.1
cassandra.contactPoints=127.0.0.1

# default is cassandra.keyspace=glowroot
cassandra.keyspace=glowroot

# default is grpc.bindAddress=0.0.0.0
grpc.bindAddress=localhost

# default is grpc.port=8181
grpc.port=8181

**Comment by ZeeTheComputerGeek** [comment]
I am running agent in the same machine. I am running tomcat8 and have updated the jvm args in the catalina.sh file. 
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:/home/ubuntu/glowroot/glowroot.jar"

The glowroot.properties file contains the following 
agent.id=127.0.0.1
agent.rollup.id=
collector.host=127.0.0.1
collector.port=4000

The admin.json contains this:
"web": {
    "port": 4000,
    "bindAddress": "127.0.0.1",
    "sessionTimeoutMinutes": 30,
    "sessionCookieName": "GLOWROOT_SESSION_ID"
  }

Here is the screenshot of the screen that I am getting. It does not show the agent.
![glowrootscreenshot](https://cloud.githubusercontent.com/assets/12229905/20795617/18db8228-b7f8-11e6-97c3-7da568ca5c42.png)
After starting the collector I make these changes and restart the tomcat service. What am I doing wrong?

**Comment by trask** [comment]
Thanks for posting the properties files.  `collector.port` in the agent properties file should match the `grpc.port` in the central properties file.  This is good to know the port confusion, I just updated the wiki to clarify.

**Comment by ZeeTheComputerGeek** [comment]
Thank you for the clarification. I changed the collector.port and the grpc.port to 8181. However, I am still unable to get the agent connected. Is this a problem because I am using tomcat instead of jetty?

**Comment by trask** [comment]
Can you post `glowroot.log` from both agent and central?

**Comment by ZeeTheComputerGeek** [comment]
Sure:
The agent log was empty.

Here is the collector log-
glowroot-central$ cat glowroot.log 
2016-12-02 06:17:57.466 INFO  org.glowroot - Glowroot version: 0.9.7, built 2016-11-14 23:01:20 +0000
2016-12-02 06:17:57.929 INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2016-12-02 06:17:58.046 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2016-12-02 06:17:59.163 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2016-12-02 06:17:59.165 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2016-12-02 06:18:02.186 INFO  org.glowroot - gRPC listening on localhost:8181
2016-12-02 06:18:02.522 INFO  org.glowroot - UI listening on 0.0.0.0:4000

**Comment by trask** [comment]
That's strange that the agent log is empty.  Are you sure you have `-javaagent:path/to/glowroot.jar` in your JVM args?  Does glowroot print anything to stdout?

**Comment by trask** [comment]
Check your tomcat/logs/catalina.log, and look for the JVM args that tomcat is using there.

E.g. I checked and the demo.glowroot.org site (which is running tomcat also) shows:

```
19-Nov-2016 01:03:32.467 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.36
19-Nov-2016 01:03:32.472 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 12 2016 18:14:42 UTC
19-Nov-2016 01:03:32.472 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.36.0
19-Nov-2016 01:03:32.472 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
19-Nov-2016 01:03:32.474 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.1.17-22.30.amzn1.x86_64
19-Nov-2016 01:03:32.475 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
19-Nov-2016 01:03:32.475 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64/jre
19-Nov-2016 01:03:32.476 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_101-b13
19-Nov-2016 01:03:32.476 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
19-Nov-2016 01:03:32.476 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/share/tomcat8
19-Nov-2016 01:03:32.477 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
19-Nov-2016 01:03:32.477 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -javaagent:/usr/share/tomcat8/glowroot/glowroot.jar
19-Nov-2016 01:03:32.482 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/share/tomcat8
19-Nov-2016 01:03:32.482 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
19-Nov-2016 01:03:32.483 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=
19-Nov-2016 01:03:32.483 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/var/cache/tomcat8/temp
19-Nov-2016 01:03:32.484 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/share/tomcat8/conf/logging.properties
19-Nov-2016 01:03:32.484 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
```

**Comment by ZeeTheComputerGeek** [comment]
Here is my catalina.log: 

02-Dec-2016 06:20:33.311 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.32 (Ubuntu)
02-Dec-2016 06:20:33.315 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 16 2016 13:11:41 UTC
02-Dec-2016 06:20:33.318 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.32.0
02-Dec-2016 06:20:33.319 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Dec-2016 06:20:33.319 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.4.0-51-generic
02-Dec-2016 06:20:33.320 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Dec-2016 06:20:33.320 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-oracle/jre
02-Dec-2016 06:20:33.321 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_111-b14
02-Dec-2016 06:20:33.321 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
02-Dec-2016 06:20:33.326 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
02-Dec-2016 06:20:33.329 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
02-Dec-2016 06:20:33.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
02-Dec-2016 06:20:33.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Dec-2016 06:20:33.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
02-Dec-2016 06:20:33.334 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx128m
02-Dec-2016 06:20:33.334 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
# 02-Dec-2016 06:20:33.334 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -javaagent:/home/ubuntu/glowroot/glowroot.jar
02-Dec-2016 06:20:33.335 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/usr/share/tomcat8/endorsed
02-Dec-2016 06:20:33.335 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
02-Dec-2016 06:20:33.336 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
02-Dec-2016 06:20:33.336 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp

**Comment by trask** [comment]
Does the tomcat user have write access to `/home/ubuntu/glowroot`?

**Comment by trask** [comment]
Also, does glowroot log anything in `catalina.out`?

**Comment by ZeeTheComputerGeek** [comment]
Yes, it seemed to be a permission issue. I changed the permissions and am now connected to the agent. Thank you for the quick response.

**Comment by ZeeTheComputerGeek** [comment]
I changed the permissions and got this in the log 

2016-12-02 06:53:07.624 INFO  org.glowroot - Glowroot version: 0.9.7, built 2016-11-14 23:01:20 +0000
2016-12-02 06:53:09.150 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spray Plugin, Spring Plugin, Struts Plugin
2016-12-02 06:53:09.272 INFO  org.glowroot - agent id: 127.0.0.1
2016-12-02 06:53:12.864 INFO  org.glowroot - connected to the central collector 127.0.0.1:8181, version 0.9.7, built 2016-11-14 23:01:20 +0000
2016-12-02 06:53:13.057 INFO  org.glowroot - downstream connection established with the central collector

**Comment by trask** [comment]
Great, thanks for working through it.  It's really helpful to know where people get stuck.  I just started a [Troubleshooting](https://github.com/glowroot/glowroot/wiki/Troubleshooting) wiki page with some of these notes.
