### ISSUE TITLE
Is possible develop plugin to add new ui funcionalities?

### ISSUE THREAD

**Issue by sirlordt** [glowroot/glowroot#149]
We need develop section to expose dropwizard metrics it is posible?

Or we need expose the metric to mx and show in mx section of glowroot?

**Comment by trask** [comment]
Exposing dropwizard metrics would be nice.  I'll have a look in the next week or so to see how that might work.

**Comment by sirlordt** [comment]
Maybe you can create a dropwizard writer?

**Comment by trask** [comment]
Sorry for the late reply.  Using dropwizard's [JmxReporter](http://metrics.dropwizard.io/3.1.0/getting-started/#reporting-via-jmx) worked pretty well in my simplistic test.  I'm not a dropwizard user though, so would be great to know what ideas you have for better integration?  Thanks.

**Comment by sirlordt** [comment]
Maybe you can upload you test project please?

**Comment by trask** [comment]
Hi, I was running https://github.com/dropwizard/dropwizard/tree/master/dropwizard-example.

**Comment by trask** [comment]
Hi, any luck with this?  Happy to take another look at this if needed.  Thanks.

**Comment by trask** [comment]
Closing, but please re-open if you (or anyone) has additional comments about dropwizard integration. Thanks.
