### ISSUE TITLE
Impossible to start glowroot UI

### ISSUE THREAD

**Issue by spouansi** [glowroot/glowroot#154]
Hi,

I'm trying to test Glowroot APM.
I downloaded glowroot-0.9.8-dist.zip and I attached the java agent to my application.
I started my application.
But I cannot start glowoot UI at http://localhost:4000.
Did i miss something ?
Thanks for help

**Comment by trask** [comment]
Hi, can you post your glowroot log file?

**Comment by trask** [comment]
Closing, but please re-open if you are still having any issue. Thanks.
