### ISSUE TITLE
Dynamically removing inactive agents

### ISSUE THREAD

**Issue by ZeeTheComputerGeek** [glowroot/glowroot#155]
It would be nice to have the inactive agents removed automatically and be shown only when the range specified comes within the life of the agent.

**Comment by trask** [comment]
Thanks for submitting the issue.  This is a nice idea to only display agents in the dropdown that were active during the selected time period.  I can see this being very helpful when monitoring auto scaling clusters where there can be a lot of agent churn.

**Comment by hgomez-sonarsource** [comment]
Dynamically removing inactive agents is still in the radar ?
Alternativly, would it be possible to remove metrics for agents (inactive or not) via UX ?

**Comment by trask** [comment]
Hi @hgomez-sonarsource, good news, I just pushed this change to prod last night. Planning to push to github later today.

**Comment by hgomez-sonarsource** [comment]
Great news @trask 
Any release date for 0.9.29 ?

**Comment by hgomez-sonarsource** [comment]
Glowroot deserve a 0.10.0 !

Great job @trask

**Comment by trask** [comment]
This is available now in the latest central snapshot [glowroot-central-0.10.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.0-SNAPSHOT) (or [glowroot-central-0.10.0-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.10.0-SNAPSHOT)).

**Comment by anishkh** [comment]
I have tested the #155 and #195 but didn't get expected results.   Could you look into this. See attached test results.  tested in 0.10.0 version . 

[AgentsTimeFilterisnotworking.docx](https://github.com/glowroot/glowroot/files/1687628/AgentsTimeFilterisnotworking.docx)
[GaugesIss_v10.docx](https://github.com/glowroot/glowroot/files/1687629/GaugesIss_v10.docx)

**Comment by trask** [comment]
Hi @anishkh, for performance considerations active agents and active gauges are only tracked at 24 hour intervals (daily UTC time).  So for example, if your time range includes any time during Feb 1 (UTC), and the agent or gauge was active/collected any time during Feb 1 (UTC) then you will see that agent/gauge displayed.  Does this explain what you are seeing?

**Comment by hgomez-sonarsource** [comment]
Just tested on 0.10.1 and inactives agents are no more there. Great !

**Comment by anishkh** [comment]
Thanks @trask  . Thanks for clarifying the interval.  Both gauge and agent dynamic display worked great with the 24 hour interval.    Also Is there any enhancement request out there to highlight the active agents in different color or in bold based on last reported time? This will be really helpful to identify agents that are active vs. non active within the 24 hour interval.

**Comment by trask** [comment]
Hi @anishkh, what about something like 30-min tracking for the last 2 days, 4-hour tracking for the last 7 days and 24-hour tracking beyond that?

**Comment by anishkh** [comment]
@trask , That would be great but our core issue is quickly identifying running vs. non running since the agent names are dynamically generated so  hard to recognize . Is it a big performance hit within interval to show active vs. non active (using last reported date time)  by highlighting  or color coding or sorting agents?

**Comment by trask** [comment]
@anishkh Can you explain a bit what you do/look at once you identify which agent(s) are active?  Will help me with maybe alternate solution.  Thanks.

**Comment by anishkh** [comment]
@trask , We have micro services based on kubernetes in multiple DCs . The agents/pods could scale up , down or restart and it will have random pod name every time scale up or restart happens . I wanted to make sure when we look at roll up level we can easily find out the agents restarted and not active when there are 15 or more agents under a rollup.  We can then investigate what happened to the agent like heap  or memory leak or other  issues.
