### ISSUE TITLE
jdk1.8.0_112.jdk Class JavaLaunchHelper error while launching the application

### ISSUE THREAD

**Issue by bhanujarugula** [glowroot/glowroot#156]
Getting the below error while trying to launch the application after attaching the glowroot-0.9.8-dist s glowroot.jar as javaagent. 

```
objc[22154]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Error opening zip file or JAR manifest missing : ~/Downloads/glowroot/glowroot.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

This works neatly till jdk7u25. I think every update after that has issues. Would it be possible to put a workaround for the glowroot.jar file? ref [http://stackoverflow.com/questions/23590613/java-8-class-javalaunchhelper-is-implemented-in-both](this) I think new relic has a workaround for this, as I don't see issues while adding new relic as the java agent

**Comment by trask** [comment]
Hi, thanks for posting an issue.  I believe the issue you are having is due to using `~` when specifying the javaagent location.  Check out
http://stackoverflow.com/questions/38449982/javaagent-option-does-not-expand-the-tilde-but-why-not

**Comment by bhanujarugula** [comment]
Thanks a lot trask. That did the trick. I have done a bit of research before raising the bug, but I couldn't find this.

**Comment by trask** [comment]
No problem, glad it's resolved.
