### ISSUE TITLE
Histogram.encodeIntoByteBuffer

### ISSUE THREAD

**Issue by adnaan** [glowroot/glowroot#159]
Hi,
      Not an issue. 

I was wondering whether there was a reason of choosing,

encodeIntoByteBuffer, https://github.com/glowroot/glowroot/blob/master/common/src/main/java/org/glowroot/common/model/LazyHistogram.java#L73

 over : 

encodeIntoCompressedByteBuffer:
https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/AbstractHistogram.java#L1835 

The reason I ask is because I have been playing with glowroot  codebase to create a Go & NodeJS agent.  I looked at other ports of HdrHistogram(C: https://github.com/HdrHistogram/HdrHistogram_c/blob/master/src/hdr_histogram_log.c#L217, https://github.com/uluyol/hdrhist/blob/master/encode.go#L12, nodejs implementation wraps over C) and found that default encoding for them is compressed. 

Right now I am sending uncompressed bytes easy enough but thought I should ask anyway.

And kudos for choosing protobuf! It's making a lot of difference.

**Comment by trask** [comment]
Hi, thanks for posting the question.  The java agent is compressing the whole gRPC payload, so no need to compress the histogram separately:

https://github.com/glowroot/glowroot/blob/v0.9.8/agent/core/src/main/java/org/glowroot/agent/central/CentralCollector.java#L114

Let me know how the Go/NodeJS agents go, sounds cool.  Happy to make accommodations in the central collector for other languages if needed.

**Comment by adnaan** [comment]
That makes sense. Began working on the agents just a couple of weeks ago. Hopefully I will have something to show soon. Thanks!
