### ISSUE TITLE
Can u add some documents about the architecture of glowroot?

### ISSUE THREAD

**Issue by littletiny** [glowroot/glowroot#160]
I have read early version of glowroot's source code to understand how glowroot work.
I think so many people will have the same idea，can you add some document of the 
architecture of glowroot or a simple java apm? 
I think the document will be helpful for the persons who want to contribute to glowroot.

**Comment by trask** [comment]
Hi, thanks for your interest.  If you would like to contribute, it's easiest to let me know what you are interested in working on, and I can provide targeted guidance.

**Comment by littletiny** [comment]
1. The processing of the class bytecode modify by glowroot
2. Why we need write a classloader to load glowroot's core jar
3. How can I write a glowroot plugin when i want use glowroot for my own frame

**Comment by trask** [comment]
Hi, sorry for the late reply.

Question # 3 is a great place to start.  Check out the `Plugin API` section under https://glowroot.org/instrumentation.html.  You can also check out Pull Requests with the `plugin` label: https://github.com/glowroot/glowroot/pulls?utf8=%E2%9C%93&q=is%3Apr%20label%3Aplugin to see some plugins that other users have contributed.  And feel free to post more specific questions as you get started.

I'm not sure about your question # 2, are you referring to [IsolatedWeavingClassLoader.java](https://github.com/glowroot/glowroot/blob/v0.9.11/agent/core/src/main/java/org/glowroot/agent/weaving/IsolatedWeavingClassLoader.java)?  That is only used for running tests to make them easier to debug.

Question # 1 (bytecode manipulation) is one of the most complex areas.  I don't recommend this as a starting point, unless you have something very specific you are trying to accomplish, and in that case let me know what it is so I can help point you in that very specific direction.

**Comment by trask** [comment]
Closing, but please re-open if you are have additional questions about this. Thanks.
