### ISSUE TITLE
In Central mode, some settings are not visible.

### ISSUE THREAD

**Issue by bill23-kim** [glowroot/glowroot#161]
Nice APM glowroot, Thank you .

In Central mode, some settings are not visible.

For example alarm, slow trace threshold value stack dump interval, etc ...

Are you planning to put these settings in central mode?

**Comment by trask** [comment]
Hi, thanks for posting. These settings are available in central UI also. Prior to 0.9.9 they are under Config menu. Now in 0.9.9 they are under the gear icon menu, then under Agent Configuration.

**Comment by bill23-kim** [comment]
Oh I found it! I did not see the Config menu. Thank you for quick response.

**Comment by trask** [comment]
Great, hopefully the new location in 0.9.9 is better and will avoid this
confusion.
