### ISSUE TITLE
Possibility to set different threshold per transaction type

### ISSUE THREAD

**Issue by cecrdle** [glowroot/glowroot#163]
Hi,
now it is possible to set only one threshold for showing slow query per agent. Typical for web request one value for web transaction value would be fine, but for background request (quartz job) there would fine to set another value or value per transaction. (Typical it long time running job).

Thanks
Milan

**Comment by trask** [comment]
Thanks for submitting.  This sounds good.  I will target for next release.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).

**Comment by trask** [comment]
Re-opening. Also need per transaction name. See https://groups.google.com/forum/#!topic/glowroot/bh60N5TfhNk.

**Comment by trask** [comment]
This is available now in the latest snapshot release [glowroot-agent-0.10.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.1-SNAPSHOT).
