### ISSUE TITLE
Glowroot central as war file

### ISSUE THREAD

**Issue by jazzdabbler** [glowroot/glowroot#164]
Hi. 
It would be useful to optionally publish Glowroot central as WAR file for deploy to any already existent environment.
For me, for example, `yum install tomcat` command for install tomcat from centos repo is much easer, then create by scratch start-stop scripts for `java -jar glowroot-central.jar`
Not to mention when the the company already has deployed application server, and all you need is to copy the war file
What do you think?

**Comment by trask** [comment]
Thanks for submitting! Yes, this sounds like a good idea. I will target for release after next.

**Comment by jazzdabbler** [comment]
Big thnx!

**Comment by trask** [comment]
Thanks for updating the wiki!
