### ISSUE TITLE
Is it possible to support capturing backend scheduled transaction db query duration?

### ISSUE THREAD

**Issue by wynet321** [glowroot/glowroot#165]
glowroot can capture db queries for requests, but the backend scheduled transaction was not requested by end user. glowroot can't get db query duration for these transactions. Is there any way I can try to get it done? thanks!

**Comment by trask** [comment]
Thanks for posting!  If you are using quartz scheduler, glowroot should capture these transactions under the 'Background' transaction type, e.g. https://demo.glowroot.org/transaction/average?transaction-type=Background

If you are using something else for scheduled execution, you will need to tell glowroot what method to use for demarcating the scheduled transaction.  Generally the easiest way to do this is by adding a new instrumentation via the glowroot UI, e.g. https://demo.glowroot.org/config/instrumentation-list.  Under 'What to capture', you want to select 'Transaction' and then you can assign the transaction type for it to be categorized under (e.g. 'Background').

See https://glowroot.org/instrumentation.html for other instrumentation options.

Post back if you have any trouble with this.

**Comment by wynet321** [comment]
Thanks for your quick response. I will take a try later. Thanks!
