### ISSUE TITLE
Multiple Java Services Running on one server

### ISSUE THREAD

**Issue by varunchauhan49** [glowroot/glowroot#170]
How do we handle multiple services running on a server with single tomcat. What are the configurations we need to support following cases.
1) We can capture data for both of the services.
2) What if we want to ensure that while capturing data for one service other services running on the server are not affected.(When we have only one tomcat server)

**Comment by trask** [comment]
Hi, so you have a single tomcat process (single JVM process) running multiple war files? If so,

1.  Glowroot should be capturing requests for all of the war files.
2.  The overhead should be low enough to not affect other services.

Let me know if this answers your questions or not.

Thanks,
Trask

**Comment by varunchauhan49** [comment]
How do we define the parameters in the properties file for two services. Like agent.id=<appname-hostname>
agent.rollup.id=<appname1>
agent.rollup.id=<appname2>

**Comment by trask** [comment]
Hi, you can either use a separate glowroot directory for each JVM process, or you can use a single glowroot directory and specify `-Dglowroot.base.dir=path/to/dir` for each JVM process, where `path/to/dir` is different for each JVM process and is where glowroot will read/store properties, local config and logs.

**Comment by trask** [comment]
Running multiple agents on one box is now better supported, and better documented, see https://github.com/glowroot/glowroot/wiki/Agent-Installation#multiple-agents-on-one-box and https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation#multiple-agents-on-one-box

**Comment by Ajithkumar-Lakshmikanthan** [comment]
Hi,
I have 3 applications running on my tomcat9 server. I added glowroot to my tomcat by following this article, [Where are my application server's JVM args?](https://github.com/glowroot/glowroot/wiki/Where-are-my-application-server's-JVM-args%3F).

can anyone help me restrict glowroot to use only one application, instead of all three?
I am totally new to glowroot. 

Thanks all.

**Comment by trask** [comment]
Hi @Ajithkumar-Lakshmikanthan, Glowroot does not support this use case (monitoring only specific applications within a given JVM).  Can you expand on why you don't want to monitor all three?  Thanks.

**Comment by Ajithkumar-Lakshmikanthan** [comment]
Hi @trask, Thank you for the respose. coz the requirment is to monitor only one application(High priority).
The other two application is for internal purpose(Low priority), only 2 people will have access to those two apps.

**Comment by varunchauhan49** [comment]
Hi Ajith,

I think we solved this problem.

@Adnaan: Can you suggest.

Regards
Varun Chauhan
