### ISSUE TITLE
Double-byte character support

### ISSUE THREAD

**Issue by Foolishlive** [glowroot/glowroot#171]
Hi, Sir:

I do some test in our test environment, I find out glowroot agent not support dobule-byte character that it will show unknow character when I capture http request parameters.
Will it support double character ?

B/R

Chinsheng

**Comment by trask** [comment]
Thanks for reporting this!  I can repro the same locally.  The problem is that the UI is currently encoding responses using ISO-8859-1 instead of UTF-8.  This will be fixed in the next release.

**Comment by Foolishlive** [comment]
Hi, Trask:

Thanks for your reply, I also find out servlet-plugin also has the same problem.
It also cause application parameter value or standard output show unknow characters.
Here is part of my test application log message:
Feb 07, 2017 4:12:05 PM org.apache.cxf.transport.servlet.AbstractCXFServlet replaceDestinationFactory
INFO: Servlet transport factory already registered
LuLu WebChat????
Feb 07, 2017 4:12:05 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /root/apache-tomcat-7.0.42-lulu-checkout/webapps/ODSHistory.war
Feb 07, 2017 4:12:05 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
So, how can I correct this issue in agent plugin ?

B/R

Edward Chen

**Comment by trask** [comment]
Hi, can you explain this in a bit more detail, I don't quite understand.  Thanks.

**Comment by Foolishlive** [comment]
Hi, 

I explain my issue, my test application will print out double-byte messages in standard output, it will show unknow-character after I apply agent to my test application.
Some of http request parameters' value are double-byte character.
Setvlet-plugin can capture request parameters' value, but it also show unknow-characer if parameters' value is double-byte.

**Comment by Foolishlive** [comment]
Hi, 

For example, my application log original message is "LuLu WebChat系統啟動", but it log as "LuLu WebChat????" after I applied to my application.

**Comment by trask** [comment]
Thanks, is "LuLu WebChat系統啟動" a query string parameter, or part of a POST body?

**Comment by Foolishlive** [comment]
Hi, 

"LuLu WebChat系統啟動" is my application operation log message.
Http request parameters is post method body.

**Comment by trask** [comment]
Hi, I'm having trouble reproducing this.  Here's what I tried below, and I entered "LuLu WebChat系統啟動" into the text input and hit submit from browser, and on the server it prints true (both with and without glowroot agent running).  Can you post a repro for this, or point out how your test case is different from below?  Thanks.

```
package org.example;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/")
public class TestServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        resp.setContentType("text/html; charset=utf-8");
        PrintWriter out = resp.getWriter();
        out.write("<html>"
                + "<head>"
                + "  <meta charset=\"utf-8\">"
                + "</head>"
                + "<body>"
                + "  <form method=post><input name=one><input type=submit></form>"
                + "</body>"
                + "</html>");
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        req.setCharacterEncoding("UTF-8");
        String param = req.getParameter("one");
        System.out.println(param.equals("LuLu WebChat系統啟動"));
    }
}
```

**Comment by trask** [comment]
Or maybe in your environment (app server, etc) the test servlet above causes the issue and prints false?

**Comment by trask** [comment]
Hi, the latest snapshot release ([glowroot-agent-0.9.11-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.11-SNAPSHOT)) has the fix for the issue with double byte characters displayed in the Glowroot UI, but I'm still unsure how to reproduce the other issue you are seeing.

**Comment by Foolishlive** [comment]
Hi, 0.9.11 is solve log message in standard output at agent side, but glowroot central still has double-character issue.
I set two string attribute with double-character in session, servlet-plugin capture my session data, but it show unknow-character.
You can set my double-character message to session attribute to reproduce this issue.
I also set encoding ISO8859_1 on glowroot central, but it still show unknow-character in session data.
So, I think this issue is relate to servlet-plugin to capture data in session and http request parameters.
I hope this information is useful for you to investigate this issue.

**Comment by trask** [comment]
Hi, can you try with glowroot central 0.9.11 (just released) and see if it resolves the issue you are still seeing?

**Comment by Foolishlive** [comment]
Hi, I do some test  0.9.11, but this issue still occurred.
The servlet-plugin retrieve double-byte data in the session still show in unknown characters, even I set encoding as ISO8895_1.

**Comment by trask** [comment]
Hi, I created a test web app that sets a session attribute with double byte character data, but I am not seeing unknown characters anymore in 0.9.11.

I posted my test web app to a github repo: https://github.com/trask/glowroot-issue-171, can you take a look at it and let me know how my test web app is different from what you are doing?

Also, here is screenshot from my test:

![trace](https://cloud.githubusercontent.com/assets/218610/23145031/74096670-f780-11e6-96b0-044bb986d618.png)

It sounded to me like you are capturing the session attributes in glowroot using:

![config](https://cloud.githubusercontent.com/assets/218610/23144774/cc5ba86c-f77e-11e6-8a2d-81589c2bc463.png)

Thanks for your help.  I'd very much like to be able to reproduce and fix the issue you are seeing.

**Comment by Foolishlive** [comment]
Hi, Trask:

I upgrade to 0.9.12, this issue was solved.
Thanks you.

**Comment by trask** [comment]
Great to hear.
