### ISSUE TITLE
Glowroot calls instance methods of AsyncResult when these are returned by @Asynchronous methods

### ISSUE THREAD

**Issue by andyba** [glowroot/glowroot#172]
When Glowroot instruments @Asynchronous EJB methods which return a Future in the form of an AsyncResult instance the instance methods of AsyncResult are called resulting in "java.lang.IllegalStateException: Object does not represent an acutal Future".

These exceptions are to be expected as such instance methods are, according to the JavaDoc for AsyncResult, never to be called.
Relevant stack trace
Caused by: java.lang.IllegalStateException: Object does not represent an acutal Future
	at javax.ejb.AsyncResult.isDone(AsyncResult.java:99)
	at org.glowroot.agent.plugin.executor.ExecutorAspect$FutureGetAdvice.isEnabled(ExecutorAspect.java:230)
	at javax.ejb.AsyncResult.get(AsyncResult.java)

Returning AsyncResult instances is how Future results are meant to be returned from such methods.

Reproducible 100% of the time.

Link to AsycResult JavaDoc: http://docs.oracle.com/javaee/7/api/javax/ejb/AsyncResult.html

**Comment by andyba** [comment]
Thanks for moving on this, it will help us roll Glowroot out for a particular application we want to monitor.
Do you have an idea when 0.9.12 will be released?

**Comment by trask** [comment]
Thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.9.12-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.12-SNAPSHOT).  0.9.12 will probably be released in a week or so.

**Comment by andyba** [comment]
Many thanks for the prompt fix!
