### ISSUE TITLE
Is it possible to migrate data from local agent to central collector?

### ISSUE THREAD

**Issue by vpelaez** [glowroot/glowroot#173]
Hello,

For the last months we have been using glowroot as a local agent attached to a Tomcat server. We are now planning to migrate to a setup with the central collector to group data from several servers. 

We have tried the new setup with the centrall collector by adding to the agent installation the glowroot.properties file to specify the collector host and port and the agent id. After this operation, the agent is shown in the central collector and new metrics are shown, however old metrics seem not to be exported to the central collector. 

It is possible to send the data already collected by local agents to the central collector? 

Environment: 
- glowroot-central: 0.9.10
- glowroot agent: 0.9.0

Thank you very much for this great project.

**Comment by trask** [comment]
Hi, thanks for posting.  Sorry, there's no mechanism to send this data that was previously collected up to the central collector.
