### ISSUE TITLE
org.glowroot.common.util.FormattingTest.testFormattingBytes() fails when run on systems that do not use . as a decimal separator

### ISSUE THREAD

**Issue by andyba** [glowroot/glowroot#174]
The org.glowroot.common.util.Formatting#formatBytes method uses a DecimalFormat instance on line#50, this uses the default locale as a source of formatting symbols. My machine uses the German Locale which uses , for a decimal separator thus failing the test.

**Comment by trask** [comment]
Thanks for reporting!  This should be fixed now.
