### ISSUE TITLE
Publish latest version of central/agent with stable link

### ISSUE THREAD

**Issue by jazzdabbler** [glowroot/glowroot#176]
Hi.
I think, may be a good idea to publish all artefacts (agent/central zip/central war) with additional stable link to latest release.
For example, for now, latest release 0.9.11 can be downloaded by link https://github.com/glowroot/glowroot/releases/download/v0.9.11/glowroot-central-0.9.11-dist.zip, but if we have additional link https://github.com/glowroot/glowroot/releases/download/latest/glowroot-central-latest-dist.zip, always pointing to latest release, we can deploy new version (with ansible, for example) without modify scenario for  specific version. Just run scenario and get freshest release.
What you think?

**Comment by trask** [comment]
Sounds good:

https://glowroot.org/latest/glowroot-latest-dist.zip
https://glowroot.org/latest/glowroot-central-latest-dist.zip
https://glowroot.org/latest/glowroot-central-latest-dist.war

Thanks,
Trask

**Comment by witrdotnet** [comment]
Hi,

It seems that https://glowroot.org/latest/glowroot-latest-dist.zip is not up-to-date ! 
@trask the link point to 0.9.12 while actually the latest is the 0.10.12.

Thanks,
Mabrouk

**Comment by trask** [comment]
Hi @witrdotnet, thanks for reporting this! The "latest" links are fixed now, and I fixed the release script so they should continue to get updated now.
