### ISSUE TITLE
Can we have 90th/95th Percentile of execution times for queries/service calls instead of avg per execution

### ISSUE THREAD

**Issue by vs955248** [glowroot/glowroot#177]
Hi Team, 
Is there any way i can see 90th/95th Percentile of execution times for queries/service calls instead of avg time per execution displayed of the queries or service calls.  That will give a better view.  Also, is there any video or demo how to setup and use instrumentation feature.  

Thanks, 
Viswanath

**Comment by trask** [comment]
Closing for now, tagged with `wishlist` label (lower priority enhancements that have been closed to keep the open backlog manageable).
