### ISSUE TITLE
Performance problem - consuming much memory

### ISSUE THREAD

**Issue by cecrdle** [glowroot/glowroot#184]
The problem would be batchUpdate which is widely used in application(memory using glowroot is about 1GB)

Thread 25440: (state = IN_JAVA) consuming 2 processor of 100%
 - java.lang.String.valueOf(java.lang.Object) @bci=10, line=2994 (Compiled frame; information may be imprecise)
 - org.glowroot.agent.plugin.jdbc.message.PreparedStatementMessageSupplier.appendParameters(java.lang.StringBuilder, org.glowroot.agent.plugin.jdbc.message.BindParameterList) @bci=95, line=57 (Compiled frame)
 - org.glowroot.agent.plugin.jdbc.message.BatchPreparedStatementMessageSupplier.get() @bci=110, line=47 (Compiled frame)
 - org.glowroot.agent.impl.TraceEntryImpl.toProto(int, long, long, java.util.Map) @bci=211, line=150 (Compiled frame)
 - org.glowroot.agent.impl.Transaction.addProtobufChildEntries(org.glowroot.agent.impl.TraceEntryImpl, org.glowroot.agent.shaded.google.common.collect.ListMultimap, long, long, int, java.util.List, java.util.Map, boolean) @bci=118, line=918 (Compiled frame)
 - org.glowroot.agent.impl.Transaction.getEntriesProtobuf(long, java.util.Map) @bci=151, line=479 (Compiled frame)
 - org.glowroot.agent.impl.TraceCreator.createFullTrace(org.glowroot.agent.impl.Transaction, boolean, boolean, long, long) @bci=10, line=87 (Compiled frame)
 - org.glowroot.agent.impl.TraceCreator.createCompletedTrace(org.glowroot.agent.impl.Transaction, boolean) @bci=11, line=49 (Compiled frame)
 - org.glowroot.agent.impl.TransactionCollector$2.run() @bci=8, line=139 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1142 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=79, line=617 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)

**Comment by cecrdle** [comment]
I attach report from my college.

[heap-dump-20170308-082214_Leak_Suspects.zip](https://github.com/glowroot/glowroot/files/829224/heap-dump-20170308-082214_Leak_Suspects.zip)

**Comment by trask** [comment]
Can you try with agent v0.9.11 or later?

This looks like an issue I ran into/fixed recently, see 00c1827cd854a46465ea14a74a48f4c9170d4d8a.

Thanks,
Trask

**Comment by cecrdle** [comment]
Thanks you for advice.
We have 0.9.12 central and the agent is version 0.9.10. We are upgrading and after performace test, I tell you the result.

Milan

**Comment by trask** [comment]
Closing, but please re-open if this is still an issue.

**Comment by JalajAsher** [comment]
Hi Trask, 
the we downloaded the latest Glowroot package and we ran into the same error when there was a batch insert being done. any suggestions ?
