### ISSUE TITLE
improvements for Spring RestTemplate

### ISSUE THREAD

**Issue by cecrdle** [glowroot/glowroot#185]
The spring rest template with URI and possibility specify URI variables,
for example
 restTemplate.postForEntity(baseURL+"/something/{uriVariable}",null,String.class,idUriVariableValue);

In service call is expected grouping by URI pattern "baseURL+/something/{uriVariable}". Now are every calling on separate row with calling 1times.

Maybe would be better to make aspect on execute method instead doExecute method
https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/client/RestTemplate.java

Thanks
Milan

**Comment by trask** [comment]
Thanks, I agree, this makes more sense.  Targeting for next release.
