### ISSUE TITLE
Improvement - possibility to show which transactions contains selected query or service call

### ISSUE THREAD

**Issue by cecrdle** [glowroot/glowroot#187]
Showing statistics for all web transactions is fine, but typically there are many transactions(for example  over 800]. It's hard to find which transactions cointans selected query or service call.

**Comment by trask** [comment]
Hi @cecrdle, is the main goal to find slow traces that contain a given query/service call (if any)?

**Comment by cecrdle** [comment]
Hi,
typically one of the problem of applications is that sql is using in many request and in one http request is called many times (select sql). The optimalization could be decrease the calling of SQL.
The showing corresponding slow traces would be fine, the would be easy find the URL of request.

**Comment by rolandkool** [comment]
A filter to find requests/traces that contain more than x number of sql/service calls would indeed be nice.

**Comment by trask** [comment]
Closing for now, tagged with `wishlist` label (lower priority enhancements that have been closed to keep the open backlog manageable).
