### ISSUE TITLE
Improvement: show retained heap space

### ISSUE THREAD

**Issue by ftkg** [glowroot/glowroot#188]
Hi,
currently the Heap histogram displays the shallow heap space. Can it also show the retained heap space?
Thanks

**Comment by trask** [comment]
Thanks for posting!  I wish this were possible, but I don't know of any way to calculate retained heap without taking a heap dump first (at which point I recommend opening with [Eclipse MemoryAnalyzer](http://www.eclipse.org/mat/)).
