### ISSUE TITLE
No data in queries

### ISSUE THREAD

**Issue by dviviani** [glowroot/glowroot#190]
Hi there.

My environment (app + glowroot) is set up in weblogic 12.1.2 using a jdbc connection. I can get all the traces but no database queries. I don't know if doing something wrong. Do you have any tip about that?

Regards.

**Comment by trask** [comment]
Thanks for posting!  What jdbc driver are you using?

**Comment by dviviani** [comment]
oracle.jdbc.xa.client.OracleXADataSource

**Comment by trask** [comment]
Are there any warnings/errors in the glowroot log (inside the glowroot folder)?

**Comment by trask** [comment]
I was able to reproduce this.  Will target fix for next release.  Thanks for reporting!

**Comment by dviviani** [comment]
Sorry for the late reply (different time zone). Alright, thanks for your support :)

**Comment by trask** [comment]
This should be fixed now in the latest snapshot [glowroot-agent-0.9.14-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.14-SNAPSHOT).

**Comment by dviviani** [comment]
its working :)
tks a lot!!
