### ISSUE TITLE
glowroot.log.dir on agent not used

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#191]
Hi,

When I start the glowroot agent (version 0.9.13, in a setup with a central collector) with the -Dglowroot.log.dir=/path/to/logdir option, the glowroot.log is still created in the same directory as where the .jar file is located.

**Comment by trask** [comment]
Thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.9.14-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.14-SNAPSHOT).

**Comment by khiradeshubham** [comment]
Hi,
Is there a way to disable Glowroot's logging? if I don't specify the _log dir_ explicitly, it will by default create it in _agent dir_. 
Thanks

**Comment by trask** [comment]
Hi @khiradeshubham, you can make a copy of `glowroot.logback.xml` from inside glowroot.jar, and place it in the glowroot (agent) dir, then you can customize the logging in that file (e.g. remove the FILE logger and only keep the CONSOLE logger).
