### ISSUE TITLE
Application with glowroot agent sometime hangs

### ISSUE THREAD

**Issue by cecrdle** [glowroot/glowroot#192]
He,
we have problem in production. When the server is restarted, the process hang somewhere in glowroot. We tested both 0.0.12 and 0.0.13 and the result the same. Our collage to tested and from 50x restart after 17 minuts, 4 restart hangs. In central collector not logging from this agent in this time.

In log we had
2017-03-23 11:49:02
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /apps/olin/boot/jboss

  JAVA: /opt/java/jre8/bin/java

  JAVA_OPTS: -server -Xms6144M -Xmx6144M -XX:PermSize=1024M -XX:MaxPermSize=1024M -XX:ReservedCodeCacheSize=150M -Duser.language=cs -Duser.country=CZ -Dfile.encoding=CP1250 -Dsun.jnu.encoding=UTF-8 -Dcom.sun.management.jmxremote.port=7001 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djboss.web.http.port=8180 -XX:+PrintCommandLineFlags -Xloggc:/apps/olin/log/gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:-TraceClassUnloading -XX:ErrorFile=/apps/olin/log/jvm-err.log -javaagent:/apps/olin/boot/jboss/bin/jboss-cfg.jar=/apps/olin/conf/00-system.properties -javaagent:/apps/olin/boot/jboss/bin/aspectjweaver.jar -javaagent:/apps/olin/glowroot/glowroot.jar

  CLASSPATH: /apps/olin/boot/jboss/bin/run.jar

=========================================================================

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=1024M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
-XX:ErrorFile=/apps/olin/log/jvm-err.log -XX:InitialHeapSize=6442450944 -XX:+ManagementServer -XX:MaxHeapSize=6442450944 -XX:+PrintCommandLineFlags -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:ReservedCodeCacheSize=157286400 -XX:-TraceClassUnloading -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseParallelGC 

set apps.base.dir = /apps/olin

--> Loading system properties from /apps/olin/conf/00-system.properties
set apps.base.url = file:/apps/olin
set java.endorsed.dirs = /apps/olin/boot/jboss/lib/endorsed
set apps.config.url = file:/apps/olin/conf/
set apps.config.dir = file:/apps/olin/conf/
set javax.net.ssl.trustStore = /apps/olin/conf/cacerts.jks
set java.net.preferIPv4Stack = true
set jboss.server.name = web8
set java.version = 1.7.0_888
set jboss.server.home.dir = /apps/olin/var
set jboss.server.log.dir = /apps/olin/log
set java.io.tmpdir = /apps/olin/var/javatmp
set jboss.web.http.maxThreads = 500
set jcifs.properties = /apps/olin/conf/01-jcifs-config.properties
set sun.rmi.dgc.client.gcInterval = 3600000
set sun.rmi.dgc.server.gcInterval = 3600000
set mail.mime.multipart.allowempty = true
set cfg.jms-config.url = file:/apps/olin/deploy/xml/.jms-config.xml

2017-03-23 11:49:03.061 INFO  org.glowroot - Glowroot version: 0.9.13, built 2017-03-13 18:05:25 +0000
2017-03-23 11:49:05.119 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spray Plugin, Spring Plugin, Struts Plugin
2017-03-23 11:49:05.233 INFO  org.glowroot - agent id: jboss-olin-SB, rollup id: PRODUKCE
2017-03-23 11:55:00.001 WARN  o.g.a.i.Aggregator$TransactionProcessor - not storing an aggregate because of an excessive backlog of 5 aggregates already waiting to be stored
/apps/olin/boot/jboss/bin/jboss-run.sh: line 241: 27353 Killed                  $JAVA $JAVA_OPTS -classpath "$CP" org.jboss.Main -b 0.0.0.0
=========================================================================
2017-03-23 11:55:07
---- JBoss stopped with status 137 ----
Startup:  2017-03-23 11:49:02 (Thursday)
Shutdown: 2017-03-23 11:55:07 (Thursday)
Duration:     0 days 00:06:05 (365 s)
---> Found valid stop-it file, exiting.

Do you have some idea, where the problem could be ?

**Comment by trask** [comment]
Thanks for posting!  Can you capture a JVM thread dump when it hangs?

**Comment by cecrdle** [comment]
Hi,
thread dump attached, it's seem that deadlock occurs
thread_dump.txt](https://github.com/glowroot/glowroot/files/875140/thread_dump.txt)

**Comment by tibiter** [comment]
Hi @trask,

I am currently running a "problem invoker" script to get more insight. First, some clarification:
- the problem only occurs at (JBoss) startup (if the startup was successful the problem never occured during the JVM life)
- we are using Java 8 and JBoss 4.2.3.GA

The occurrence is intermittent: sometimes there are 90 starts without problems, sometimes there are 3 failed starts in a row (these are the extremes, usually between 5 to 20 starts are necessary to invoke the problem). We were blissfully unaware of the problem until it hit us in the production (after cca. one week on a machine which is restarted once a day).

It seems that the problem always arises between two threads: "main" (= JBoss Server init) and some Glowroot-related thread:
- 153x Glowroot-GRPC-Executor
- 3x Glowroot-GRPC-Worker-ELG
- 3x pool-7-thread-1 (running org.glowroot.agent.init.NettyWorkaround)
- 1x Glowroot-Aggregate-Flushing

On the "main" side there is always the org.jboss.system.server.NoAnnotationURLClassLoader which is locked.
There are two "variants" (one is cca. 6-times more frequent than the other):
- type1 = "openConnection" vs "openConnection" (152x)
- type2 = "forName" vs "getDeclaredConstructors" (24x)

I attached example thread dumps for these two types:
[deadlock-type1.txt](https://github.com/glowroot/glowroot/files/877030/deadlock-type1.txt)
[deadlock-type2.txt](https://github.com/glowroot/glowroot/files/877031/deadlock-type2.txt)

I don't fully comprehend the explanation but it seems very similar to this problem:
[https://github.com/stagemonitor/stagemonitor/issues/179#issuecomment-232321030](url)

If you need more information / source code / thread dumps / heap dump etc. I would be happy to help.

**Comment by trask** [comment]
Thanks!  This is a great find.  I'm able to reproduce locally (also after some number of startups).  Working on fix now...

**Comment by trask** [comment]
I think this should be fixed now in the latest snapshot release [glowroot-agent-0.9.15-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.15-SNAPSHOT).

**Comment by tibiter** [comment]
Wow, that was a fast response! **Thank you very much!** I will test the snapshot today.

**Comment by tibiter** [comment]
Hi,

the test was successful: 4000 successful starts (in 6 hours) without any failure.
**Thanks again for your excellent work!**

If I understand correctly the fix is to (pre)load the JBoss-specific URL handler classes BEFORE JBoss calls `URL.setURLStreamHandlerFactory()`. The way to do that is to put the following code at the beginning of `org.jboss.system.server.ServerImpl.internalInitURLHandlers()`:
```java
try {
    Class.forName("org.jboss.net.protocol.file.Handler");
    Class.forName("org.jboss.net.protocol.file.FileURLConnection");
    Class.forName("org.jboss.net.protocol.resource.Handler");
    Class.forName("org.jboss.net.protocol.resource.ResourceURLConnection");
} catch (Throwable ex) {
    ex.printStackTrace();
}
```

From the comment on this method it seems that - at least for Linux - another solution might be just skipping this method:
```java
   /**
    * Set up our only URLStreamHandlerFactory.
    * This is needed to ensure Sun's version is not used (as it leaves files
    * locked on Win2K/WinXP platforms.
    */
   private void internalInitURLHandlers()
```

**Comment by trask** [comment]
Yes, you are understanding the patch correctly.  The problem is that JBoss registers its URLStreamHandlerFactory, but the actual handler `org.jboss.net.protocol.file.Handler` class gets loaded lazily when JVM tries to load first "file:" URL after this registration.  Glowroot's ClassFileTransformer sometimes needs to load "file:" URLs, and if this happens to be the first "file:" URL loaded after the registration, it then triggers loading of the `org.jboss.net.protocol.file.Handler` class, which is what leads to the deadlock involving the class loader.  Normally, Glowroot pre-initializes all classes that are used in the ClassFileTransformer (see https://github.com/glowroot/glowroot/blob/e21c1ed1a2e2ebb734ded9bee55f7f4a78d17f99/agent/core/src/main/java/org/glowroot/agent/weaving/PreInitializeWeavingClasses.java#L27) to avoid this issue.  But this is a strange case.  And so it gets a strange (and hacky) solution :-).

Nice find on the `internalInitURLHandlers()` comment.  I hadn't seen that (I was looking at the decompiled class).  I was wondering why JBoss was registering its own "file:" URL handler.

**Comment by cecrdle** [comment]
@trask 
Hi thank for quick fix. We could confirm, that fix is work for us. But we are still waiting for release, we can't deploy snapshot. When you plan release new version ?.

**Comment by trask** [comment]
Hi @cecrdle, thanks for posting, v0.9.15 is just released now.

**Comment by mezzatto** [comment]
@trask I'm suspecting that glowroot might be the cause of some strange behaviors inside Solr. I'm seeing a thread that runs forever when glowroot agent is enabled and the code is instrumented. The stack of the thread that runs eternally is:

```
"searcherExecutor-7-thread-1-processing-n:10.154.62.67:8983_solr x:inmuebles_shard1_replica2 s:shard1 c:inmuebles r:core_node2" - Thread t@73
  java.lang.Thread.State: RUNNABLE
at java.nio.Bits.copyToArray(Bits.java:834)
at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:280)
at org.apache.lucene.store.ByteBufferGuard.getBytes(ByteBufferGuard.java:93)
at org.apache.lucene.store.ByteBufferIndexInput.readBytes(ByteBufferIndexInput.java:89)
at org.apache.lucene.codecs.blocktree.SegmentTermsEnumFrame.loadBlock(SegmentTermsEnumFrame.java:176)
at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:507)
at org.apache.lucene.queries.TermsQuery$1.rewrite(TermsQuery.java:300)
at org.apache.lucene.queries.TermsQuery$1.bulkScorer(TermsQuery.java:359)
at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:666)
at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:473)
at org.apache.solr.search.SolrIndexSearcher.buildAndRunCollectorChain(SolrIndexSearcher.java:241)
at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:1823)
at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:1640)
at org.apache.solr.search.SolrIndexSearcher.lambda$initRegenerators$3(SolrIndexSearcher.java:604)
at org.apache.solr.search.SolrIndexSearcher$$Lambda$109/937761293.regenerateItem(Unknown Source)
at org.apache.solr.search.LRUCache.warm(LRUCache.java:290)
at org.apache.solr.search.SolrIndexSearcher.warm(SolrIndexSearcher.java:2376)
at org.apache.solr.core.SolrCore.lambda$getSearcher$2(SolrCore.java:2054)
at org.apache.solr.core.SolrCore$$Lambda$151/1942476236.call(Unknown Source)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$$Lambda$20/1346825140.run(Unknown Source)
```

I got this stack from a SolrCloud Cluster 6.4.1 with glowroot 0.9.11. When we do not run a code instrumented by glowroot, no locked thread.

However, I'm not 100% that the cause is glowroot since we have many variables (I'm trying to narrow it down).

I've just deployed 2 clusters:
 - glowroot upgraded to 0.9.16
 - no glowroot agent

I'll just get the results in a few hours. What's your feeling about this?

**Comment by trask** [comment]
Hi @mezzatto, so the thread isn't blocked, but is stuck in some kind of a loop?  Let me know how your test goes.  If you're still seeing a correlation between glowroot and the loopy thread, let me know, and I'll take a closer look at it.  Thanks.

**Comment by mezzatto** [comment]
@trask both clusters still failed. Doesn't look something related with glowroot. Sorry about that :)

**Comment by trask** [comment]
@mezzatto no worries, maybe you can use glowroot to debug.

I'd probably start with trying to find out which method in that stack trace is doing the endless looping.  It looks like there are a few methods in that stack trace that have loops.  Profiles are not very helpful for this since they don't show method execution counts, so I'd start with instrumenting the methods in that stack trace that have loops, e.g. import the following in the glowroot instrumentation UI:

```
[
  {
    "className": "org.apache.lucene.codecs.blocktree.SegmentTermsEnum",
    "methodName": "seekExact",
    "methodParameterTypes": [
      "org.apache.lucene.util.BytesRef"
    ],
    "captureKind": "timer",
    "timerName": "SegmentTermsEnum seekExact"
  },
  {
    "className": "org.apache.lucene.queries.TermsQuery$1",
    "methodName": "rewrite",
    "methodParameterTypes": [
      "org.apache.lucene.index.LeafReaderContext"
    ],
    "captureKind": "timer",
    "timerName": "TermsQuery 1 rewrite"
  },
  {
    "className": "org.apache.lucene.search.IndexSearcher",
    "methodName": "search",
    "methodParameterTypes": [
      "java.util.List",
      "org.apache.lucene.search.Weight",
      "org.apache.lucene.search.Collector"
    ],
    "captureKind": "timer",
    "timerName": "IndexSearcher search"
  },
  {
    "className": "org.apache.solr.search.LRUCache",
    "methodName": "warm",
    "methodParameterTypes": [
      "org.apache.solr.search.SolrIndexSearcher",
      "org.apache.solr.search.SolrCache"
    ],
    "captureKind": "timer",
    "timerName": "LRUCache warm"
  },
  {
    "className": "org.apache.solr.search.SolrIndexSearcher",
    "methodName": "warm",
    "methodParameterTypes": [
      "org.apache.solr.search.SolrIndexSearcher"
    ],
    "captureKind": "transaction",
    "transactionType": "SolrIndexSearcher warm",
    "transactionNameTemplate": "SolrIndexSearcher warm",
    "traceEntryMessageTemplate": "SolrIndexSearcher warm",
    "timerName": "SolrIndexSearcher warm"
  }
]
```

Then the timer counts will correspond to method execution counts (with the whole transaction being captured under a new transaction type in Glowroot UI `SolrIndexSearcher warm`)

**Comment by mezzatto** [comment]
Wow, thanks a lot! Really appreciate it.

**Comment by tibiter** [comment]
Hi @mezzatto, I believe that this discussion has nothing to do with JBoss 4. Would you mind creating a new issue? Thanks!
