### ISSUE TITLE
Improvement: add glowroot.conf.dir for agent

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#193]
Similar to the glowroot.log.dir, allow configuring a root configuration directory for all glowroot agent configuration files. Currently they are stored in the same directory as the jar file. In version 0.9.5 (which we are currently on) there is a base.dir param that allows you to separate out code and configuation/data. That param no longer seems available, hence request for a conf.dir one.

Thanks.

**Comment by trask** [comment]
Hi @rolandkool, is this so that you can run multiple JVMs on the same box?  If so, check out https://github.com/glowroot/glowroot/wiki/Agent-Installation#multiple-agents-on-one-box

**Comment by rolandkool** [comment]
Hi Trask,
My request is primarily so I can separate the binary from the configuration directory. As I put the binary somewhere in /usr/share, I'd rather not make that directory writeable but prefer the configuration dir to be configurable per instance so I can point it to /etc.

**Comment by trask** [comment]
Hi @rolandkool, thanks for reporting this, the following properties are now supported in 0.9.17:

`glowroot.conf.dir`
`glowroot.log.dir`
`glowroot.tmp.dir`
`glowroot.data.dir` (if not reporting to central)

You can also set these in `glowroot.properties` file in same directory as `glowroot.jar`, but without using the `glowroot.` prefix for the property names, e.g.

```
conf.dir=/etc/glowroot
log.dir=/var/log/glowroot
tmp.dir=/tmp/glowroot
data.dir=/var/lib/glowroot
```

**Comment by rolandkool** [comment]
Hi Trask,

Thanks, I'll give it a go when .17 is released.

**Comment by rolandkool** [comment]
Hi Trask,

I was playing with the new release and try these settings. Do I understand correctly that when setting the conf.dir, the per-agent subdirs are no longer created? For multi-instance, this could be an issue (as there is one glowroot.properties file)

**Comment by trask** [comment]
Hi @rolandkool, if you use `-Dglowroot.conf.dir=/etc/glowroot -Dglowroot.agent.id=xyz`, it should read and write config.json and admin.json to `/etc/glowroot/xyz`.  Are you are seeing something different?

**Comment by rolandkool** [comment]
Hi Trask,

I added all settings in the glowroot.properties. If I just add the glowroot.agent.id to the commandline and keep the conf.dir in the properties file, it works as expected. Didn't know there was a subtle difference between cmdline and property file for the agent.id.
