### ISSUE TITLE
Glowroot with Weblogic

### ISSUE THREAD

**Issue by shravan05** [glowroot/glowroot#194]
Hi,

I just configured glowroot with weblogic and I can see the transactions only for Adminserver. We have multiple managed servers on the same machine, please advise how can I get the stats of managed servers on the glowroot UI.

Here is the argument I added in startupscript (setDomainEnv.sh)

 JAVA_OPTIONS="-javaagent:path to glowroot/glowroot.jar ${JAVA_OPTIONS}"
export JAVA_OPTIONS

Thanks,
Shravan.

**Comment by trask** [comment]
Each managed server runs in its own JVM, so each managed server needs JVM arg
`-javaagent:path/to/glowroot.jar`

Also, for some more notes on running multiple agents on one box, see https://github.com/glowroot/glowroot/wiki/Agent-Installation#multiple-agents-on-one-box and post back with any additional questions.

**Comment by trask** [comment]
Closing, but please re-open if you have additional questions about this.
