### ISSUE TITLE
Gauges not removed

### ISSUE THREAD

**Issue by anishkh** [glowroot/glowroot#195]
JMX Gauges added through agent configuration are not deleted even if it's removed . It seems the config.json file is updated but GUI continue to show the deleted gauge metrics.  I'm using version 0.9.11

**Comment by trask** [comment]
Thanks for posting!  Deleting the gauge configuration prevents the gauge from being collected going forward, but it does not delete already captured metrics for that gauge.  I agree this is confusing.  I'm thinking that a good fix would be to only display metrics that were captured during the interval you are looking at, so you will no longer see them on the metrics page unless you are looking at an older time period.

**Comment by anishkh** [comment]
Thanks Trask.  Your suggested fix is the perfect solution which will preserve the collected data in that interval and avoid confusion. Also one of the main features I was looking was the load balancing of the central collector . Thanks for the latest version with the LB feature. I will test that version soon.

**Comment by trask** [comment]
Great, I need to do something similar for #155 (only showing agents in the agent dropdown that were active during the interval you are looking at).  Let me know if you run into issues/questions with LB.  Since it is new, I'm expecting there will be a few thing (including doc) that need to be ironed out.  Thanks.

**Comment by trask** [comment]
Thanks for your patience.  This is available now in the latest snapshot release [glowroot-agent-0.9.29-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.29-SNAPSHOT).

**Comment by trask** [comment]
If you are using central, this is available now in the latest central snapshot [glowroot-central-0.9.29-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.9.29-SNAPSHOT) (or [glowroot-central-0.9.29-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.9.29-SNAPSHOT)).

**Comment by anishkh** [comment]
Thanks @trask . I will test the central collector with the latest snapshot.  Also are you planning to work on  agent list based on time interval #155 so inactive agents can be filtered out?

**Comment by trask** [comment]
Hi @anishkh, #155 is on the short list, hopefully available in the next month.
