### ISSUE TITLE
Spring plugin missing context path

### ISSUE THREAD

**Issue by lyahim** [glowroot/glowroot#196]
Hi all!

I love your application, becauser easy to use and know lots of feature.

Our applications use Spring Restfor serving. And we run more similar application in one application server.
The result is we have the same reguest path in different app. In GUI we see only the request path, therefore we didn't decide which app served the requests.
If it's possible please put the context path before the request path in Spring plugin.(With JSF displayed correctly the context path).

Thank you,
Mihaly

**Comment by trask** [comment]
Thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.9.16-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.16-SNAPSHOT).

**Comment by lyahim** [comment]
Thank you for quick fix.
