### ISSUE TITLE
Implementing Node agent.

### ISSUE THREAD

**Issue by varunchauhan49** [glowroot/glowroot#199]
Hi Trask,

Thanks for your previous replies. I am opening one issue here for those queries.

I think would like to add some more to my queries of sending error via traces and totalduration value not reflecting correctly.

Q 1 When I am sending totalduration which I am calculating in nanoseconds The same value is not getting reflected in UI. In your api UI where you are calculating the tracepoints, you are dividing total duration with 1000000 * count and displaying the result in milliseconds.

https://github.com/glowroot/glowroot/blob/master/ui/src/main/java/org/glowroot/ui/ReportJsonService.java#L229

 So when I am multiplying the total duration with transaction count it's giving the relatively correct response time but the wrong percentage. When I am sending just duration in nano. It's giving right percentage value and wrong response time. 

If I am sending the totalduration in nanoseconds why the same value not reflecting glowroot UI. Please suggest.

Q2 When you say TraceStreamMessage is for sending only one trace? Then for a transaction with 10 errors how should be sent trace data.
Should we loop over the error list and send transaction data for each error. Which means opening a trace stream for each error. (This case is working but I feel like it might add overhead on App)
Loop over the error list and send transaction data for each error but open one stream and write all traces one after another. (Not working as error count in error traces and error messages is not reflecting )
Just send one trace with multiple Trace.Entry. (Not working since error traces and error message is considering the error sent in header only)
For your reference, I have attached GitHub link for our node agent.
https://github.com/varunchauhan49/myntnodeagent

**Comment by trask** [comment]
Hi Varun,

Q1 - are you having trouble with Aggregate.total_duration_nanos or with Trace.duration_nanos?  Since only some transaction are sent to the collector as Traces (e.g. exceeding slow treshold or having error), the sum of Trace.duration_nanos over all traces is not the same as Aggregate.total_duration_nanos.  Aggregate.total_duration_nanos is the sum of all transaction times (including those which are not sent to the collector as Traces).

Q2 - For a single transaction (request) with 10 errors, those 10 errors can be captured as separate trace entries, but it is still a single trace, with a single trace header, all sent over a single trace stream.

Hope that helps, please post back with further clarifications in case I'm not understanding your question(s).

**Comment by varunchauhan49** [comment]
Hi Trask,
Q1. Yes, I am facing issue with Aggregate.total_duration_nanos. If I am sending x value from the agent then an entirely different value is reflecting on UI. Which means some calculation is being done because of which my values are getting changed.

For eg. 
This the data I am sending from the agent.
`Total Data 9388441572 8378
Data /api/search/test6 28232847 80
Data /api/search/test2 161458664 888
Data /api/search/test1 555647186 3540
Data /api/search/test4 573486163 3540
Data /api/search/test3 46034891 200
Data /api/search/test5 4856850 10
Data /api/get/getpool 3456416796 50
Data /fetch 1316260016 20
Data /api/get/pool 3246048159 50`

The API response is also reflecting the same values.

`{  
   "overall":{  
      "totalDurationNanos":9.388441572E9,
      "transactionCount":8378
   },
   "transactions":[  
      {  
         "transactionName":"/api/get/getpool",
         "totalDurationNanos":3.456416796E9,
         "transactionCount":50
      },
      {  
         "transactionName":"/api/get/pool",
         "totalDurationNanos":3.246048159E9,
         "transactionCount":50
      },
      {  
         "transactionName":"/fetch",
         "totalDurationNanos":1.316260016E9,
         "transactionCount":20
      },
      {  
         "transactionName":"/api/search/test4",
         "totalDurationNanos":5.73486163E8,
         "transactionCount":3540
      },
      {  
         "transactionName":"/api/search/test1",
         "totalDurationNanos":5.55647186E8,
         "transactionCount":3540
      },
      {  
         "transactionName":"/api/search/test2",
         "totalDurationNanos":1.61458664E8,
         "transactionCount":888
      },
      {  
         "transactionName":"/api/search/test3",
         "totalDurationNanos":4.6034891E7,
         "transactionCount":200
      },
      {  
         "transactionName":"/api/search/test6",
         "totalDurationNanos":2.8232847E7,
         "transactionCount":80
      },
      {  
         "transactionName":"/api/search/test5",
         "totalDurationNanos":4856850.0,
         "transactionCount":10
      }
   ],
   "moreAvailable":false
}`

But a different value of response time is reflecting on glowroot UI i.e. Aggregate.total_duration_nanos which we sent for `/api/get/getpool was 3456416796` and what it's reflecting on UI is `69.1 ms`

<img width="1400" alt="screen shot 2017-04-24 at 10 34 57 am" src="https://cloud.githubusercontent.com/assets/12985829/25322967/4f87ff98-28d9-11e7-9ba2-4f2175020740.png">

Q2 **For a single transaction (request) with 10 errors, those 10 errors can be captured as separate trace entries, but it is still a single trace, with a single trace header, all sent over a single trace stream.**
Okay, this is fine we were handling errors like that only. 
**Problem:** It's considering only the error appended to the header which means if we are sending multiple errors via trace entry it's either not considering them or some parameter need to be changed for this?

**Comment by trask** [comment]
Hi Varun,

Q1 - in the screenshot, you are sorting by average time, so the `/api/get/getpool` number in the sidebar (69.1 ms) is the average time (total duration / transaction count), which appears to match your data (3456416796 / 50).

Q2 - can you see the other errors when you open the trace and view the trace entries?  where are you wanting to see the other errors that you are not currently seeing them?

**Comment by varunchauhan49** [comment]
Hi trask,

Q1: Got your point but will get back to you on this point. Meanwhile, will provide you additional information regarding question number 2.

Q2: I am getting the error count but not error messages and traces in UI even I am sending them as trace entry.
Reference images attached in comparison to demo.glowroot.org.

<img width="1396" alt="screen shot 2017-04-25 at 10 43 02 am" src="https://cloud.githubusercontent.com/assets/12985829/25369796/066233d0-29a4-11e7-93c2-910a671a6562.png">
<img width="1382" alt="screen shot 2017-04-25 at 10 37 52 am" src="https://cloud.githubusercontent.com/assets/12985829/25369797/06656366-29a4-11e7-9903-a16d164b40f3.png">

**Comment by trask** [comment]
Q2 - this screenshot is very helpful, thanks, I will look into it

**Comment by trask** [comment]
Q2 - the sidebar counts come from the aggregates that are sent to the central collector, while the "Error messages" and "Error traces" tab data comes from the traces that are sent to the central collector.

Can you check that you have pushed traces to the central collector in that same time frame, and make sure that the traces have a [Header.error](https://github.com/glowroot/glowroot/blob/v0.9.15/wire-api/src/main/proto/Trace.proto#L38) and that the [Header.partial](https://github.com/glowroot/glowroot/blob/v0.9.15/wire-api/src/main/proto/Trace.proto#L26) field is `false`?

**Comment by varunchauhan49** [comment]
Hi trask,

Q2- It will reflect if sent via Header.error with Header.partial field as false. 
Consider a transaction /api/get/address as an example which got 20 random errors as 10(**401 UNAUTHORIZED**) + 5(**408 Request Timeout Error**) + 5(**440 Login Timeout**). With this example as reference following are my concerns.

A) Why do trace consider error only when sent via Header.error.
B) With reference to your reply in trailing discussion for a single transaction with multiple error we will send only one trace.header and multiple trace.entry it will consider only the error sent via header.error. What should be done to communicate other errors to the glowroot collector?
C) Which error should be sent via trace.header if we have multiple error entries with us but header.error can accommodate only one value.

**Comment by trask** [comment]
In your example, are you saying there were 20 HTTP requests to /api/get/address which received errors, or are you saying there was a single HTTP request to /api/get/address which then gathered a lot of data from other services?

If the latter (single HTTP request/response with 20 embedded errors), what is the error that it returns back to the user in the response?  That error (returned to the user) could be the error placed in the trace header.  And the 20 embedded errors could be trace entries.  At least that's generally how the java agent works (there's some additional logic on top to capture logged errors that may get handled by the request and do not result in error back to the user, see https://demo.glowroot.org/config/plugin?plugin-id=logger, also see the javadoc comment for https://github.com/glowroot/glowroot/blob/v0.9.15/agent/plugin-api/src/main/java/org/glowroot/agent/plugin/api/ThreadContext.java#L263).

**Comment by varunchauhan49** [comment]
Yes 20 HTTP requests to /api/get/address.

I think there is little confusion will try to pitch it gain. For node agent, I am storing the data in local agent collector and harvesting after regular interval of time. So all HTTP request for a url like /api/get/address are captured along with all information like whether the HTTP request was completed if so will update the Http count and if transaction it fails will update error data.
In the end, this how JSON for our example `url /api/get/address`  would be.
`{  
   "url":"/api/get/address",
   "method":"GET",
   "duration":1234567890,
   "hdr":"hdr_data",
   "count":1000,
   "error_count":20,
   "errors":[  
      {  
         "count":10,
         "timestamp":"sometime",
         "method":"GET",
         "url":"someurl",
         "message":"401 UNAUTHORIZED",
         "status":401
      },
      {  
         "count":5,
         "timestamp":"sometime",
         "method":"GET",
         "url":"someurl",
         "message":"408 Request Timeout Error",
         "status":408
      },
      {  
         "count":5,
         "timestamp":"sometime",
         "method":"GET",
         "url":"someurl",
         "message":"440 Login Timeout",
         "status":440
      }
   ]
}`

So this JSON capture data for a URL with 1000 transaction out which 20 failed and captured in errors. Now currently I am sending only error data in Trace, not slow_transactions. I was considering `url /api/get/address` a Trace and 20 errors as multiple trace.entry.
So as per your reply should I consider 20 errors for this url as 20 transactions and send individual error as Trace.Header.error with one trace on one stream.

**Comment by trask** [comment]
Ok, yep, in glowroot a "Trace" = a trace of a single request.  If you have 20 requests that failed, you would send 20 traces.
