### ISSUE TITLE
tanuki sofware wrapper based jboss application fails to start using glowroot

### ISSUE THREAD

**Issue by goldentigerindia** [glowroot/glowroot#202]
The earlier fix didn't work attaching the logs.
[wrapper.txt](https://github.com/glowroot/glowroot/files/957185/wrapper.txt)
[stdout.txt](https://github.com/glowroot/glowroot/files/957186/stdout.txt)

**Comment by trask** [comment]
Please add `wrapper.debug=TRUE` to your `wrapper.conf` file and run both with and without the glowroot javaagent arg and post stdout for both so we can compare what the difference might be.  Thanks.

**Comment by goldentigerindia** [comment]
sure will do that and update

**Comment by trask** [comment]
Hi @goldentigerindia, any luck with this?  Thanks.
