### ISSUE TITLE
snap package for glowroot-central

### ISSUE THREAD

**Issue by robokaso** [glowroot/glowroot#211]
It would be great to have a frictionless install and upgrade experience and snap enables this across linux distributions. There is already a [Cassandra snap](https://uappexplorer.com/app/cassandra.ev) so it's likely not difficult to add Glowroot-central on top of it.

If packaging is unlikely to get attention in the upcoming months I'll try to find time to contribute a working example to help push things forward.

https://snapcraft.io/

**Comment by trask** [comment]
Closing for now, tagged with `wishlist` label (lower priority enhancements that have been closed to keep the open backlog manageable).
