### ISSUE TITLE
How to backup configuration stored in the Cassandra DB?

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#212]
Hi,

I'd like to create a backupscript that backs up all configuration that is stored in the Cassandra DB (like the LDAP settings, agent configuration and other global settings).
To do this, which tables need to be backed up? All trace data I consider less important to restore in case of a 'disaster'.
Could you help out?
Thanks

**Comment by trask** [comment]
Sure, here you go:

`user` (Administration > Users)
`role` (Administration > Roles)
`central_config` (Administration > Web, Storage, SMTP, LDAP)
`agent_rollup` (Administration > Agents, and the &lt;agent&gt; dropdown on various pages)
`config` (Agent configuration) <-- I'm going to rename this table to `agent_config` in 0.9.18 for clarity
```
