### ISSUE TITLE
Question Regarding ServletAspect

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#214]
This may be a stupid question, but in the ServletAspect.java file, it states that it only captures the top-most servlet and top-most filter.

What does this mean exactly? I have a project with, perhaps, 10 .WAR files, in one .EAR, and each .WAR has multiple servlet entries defined in their web.xml. 

Will glowroot then only trace the "first" <servlet> tag it meets in each web.xml file, or the one with the highest *load-on-startup* tag, or does the comment mean something else?

**Comment by trask** [comment]
Hi, thanks for posting!  The comment is really not clear (and slightly outdated at that), but what it should say is that glowroot captures the request data at the first filter or servlet to process a request (e.g. in the case that there are multiple filters processing each request).  It's not related to web.xml or load-on-startup ordering.

**Comment by asgerjensen** [comment]
Ah, ok. Thanks for the clarification
