### ISSUE TITLE
ImmutableTimerNameImpl is missing

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#215]
After cloning repo, and doing ```mvn clean install``` i get a bunch of exceptions that

```
Caused by: java.lang.Error: Unresolved compilation problem: 
	ImmutableTimerNameImpl cannot be resolved
```
I'm not sure if its something that has been removed, or something that is missing from the repo

**Comment by trask** [comment]
Thanks for posting!  Can you post the output from `mvn -v`, and also run `mvn -X clean install` and attach the full build output from that?

**Comment by trask** [comment]
Closing, feel free to re-open if there is any update, thanks
