### ISSUE TITLE
Filter capability not available in certain pages

### ISSUE THREAD

**Issue by haiyingwang** [glowroot/glowroot#216]
I found filter capability are not available in certain pages under 'Transactions', such as the transaction list panel on the left, Queries page and Service Calls page. When there are large number of items available, filtering could be helpful to find the interested one(s) quickly. Any chance these pages will support filtering in the future releases?

**Comment by trask** [comment]
Closing for now, tagged with `wishlist` label (lower priority enhancements that have been closed to keep the open backlog manageable).

**Comment by drmulligan** [comment]
I would like to vote for this feature.  It would be helpful to be able to filter All Web Transactions and Response Time tabs by user.  I understand that the most useful tab, Slow Traces, is already filtered by user but it would be nice to have other stats to see when performance was not a problem.
Queries and Continuous Profiling might also be nice but I am less sure they would be as useful.
