### ISSUE TITLE
Is possible to configure default gauges to be displayed?

### ISSUE THREAD

**Issue by monkiki** [glowroot/glowroot#217]
Hi there,

Every time I go to http://localhost:4000/jvm/gauges I've to check the wanted gauges. Is possible to configure someones to be already checked?

Thanks in advance!

**Comment by trask** [comment]
You'll be able to configure dashboards in the near-ish future.  In the meantime, you can bookmark the gauges page after selecting the gauges you are interested in (gauges are added to the url when you select them).

**Comment by monkiki** [comment]
Thanks for the workaround :P
Anyway be able to configure it would be pretty nice :)

**Comment by trask** [comment]
You were right, being able to configure the default gauges is pretty nice :-).  This is implemented now (under Configuration > UI).  Thanks for requesting!

**Comment by monkiki** [comment]
Thanks for implementing ;)
