### ISSUE TITLE
Allow configuration of trace data retention per instance

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#223]
Hi,

Currently, retention of trace data can be configured globally and then applies to all instances.
We have a mix of production and non-production instances in our glowroot setup, so it would be nice to have trace data retention configurable for the different instances. I.e. have trace data retention for a production instance set to 7 days and for a test instance set to 3.
Would it be possible to support such a feature?
Regards,

Roland

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
