### ISSUE TITLE
Question about what constitutes a transaction

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#224]
In the Average/Throughput graphs, when it says 750 transactions pr minute, does that only count "Outer transactions" or does it also include any instrumented code (set up as transactions) that may or may not run within other transactions?

Or, put differently, in a struts application, can the transactions pr minute be said to translate to number of pages served?

**Comment by trask** [comment]
Hi @asgerjensen, thanks for posting!  This includes outer transactions only, so should match number of pages served in your scenario.  Instrumentation marked as "transaction" that is encountered inside of an existing transaction is treated the same as a "trace entry".

**Comment by asgerjensen** [comment]
Fantastic, thanks.
