### ISSUE TITLE
Support StartTLS encryption in SMTP configuration

### ISSUE THREAD

**Issue by john-keysight** [glowroot/glowroot#226]
I'm trying to use office 365 SMTP server and it appears Their configuration like TLS/Start TLS.  We've not been able to get SSL to work with it or not checking SSL.
530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [DM5PR21CA0024.namprd21.prod.outlook.com]
When I used another application through office SMTP server,  it worked with TLS enabled, but when TLS was disabled it gave the same error I was getting with glowroot test message.

From Office documentation, it appears TLS is expected:
How to set up SMTP client submission

Enter the following settings directly on your device or in the application as their guide instructs (it might use different terminology than this article). As long as your scenario meets the requirements for SMTP client submission, the following settings will enable you to send email from your device or application.

Device or Application setting                         Value
Server/smart host                                           smtp.office365.com
Port                                                                 Port 587 (recommended) or port 25
TLS/ StartTLS                                                  Enabled
Username/email address and password        Enter the sign in credentials of the hosted mailbox being used

https://support.office.com/en-us/article/How-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4

**Comment by trask** [comment]
Hi @john-keysight, thanks for posting!  This was definitely a missing feature.  It is no longer missing now in the just releases 0.9.20.  You'll find the new STARTTLS option under the new "Connection security" dropdown on the smtp config page.  Let me know if you have any trouble with it.  Thanks.
