### ISSUE TITLE
Support embedded WireMock server

### ISSUE THREAD

**Issue by eostermueller** [glowroot/glowroot#231]
Hi,

I continue to get a lot of great use out of glowroot.  Thanks for that.
Here is an issue that I've been seeing.

I'm running a configuration like this, every part is on my box:
JMeter --> HTTP Request --> Spring Boot --> HTTP Request --> Embedded HTTP Server (Wiremock).

...where the embedded HTTP Server, wiremock, runs in the same JVM as Spring Boot.
So just two JVMs:  jmeter jvm (not monitored by glowroot) and the Spring Boot JVM, which does have glowroot.
You can download and run this example yourself -- glowroot is plugged in by default -- just run test 01a as detailed here:
https://github.com/eostermueller/javaPerformanceTroubleshooting

In general, glowroot roughly looks like it thinks my two HTTP urls (/randomInquiry and /perfSandboxBackend) run in parallel as separate requests, when they are actually called in serial like this: 
JMeter calls /randomInquiry (Spring Boot), and Spring Boot calls /perfSandboxBackend (localhost), and the embedded wiremock services that request.

JMeter is applying  3 thread of load, 0 think time.  I'm getting two requests per second (very repeatable) as shown here:
![image](https://user-images.githubusercontent.com/175773/27847910-9ccfe206-6106-11e7-8cc1-9c39829ee666.png)

2 per second is 120 per minute, right?
Glowroot throughput metrics instead show 240-ish / minute.  It looks like its doubling throughput; looks wrong to me. 
![image](https://user-images.githubusercontent.com/175773/27847941-e34a44ec-6106-11e7-8217-d4bdbc4dafe4.png)

The "Spring Controller" and "other" metrics below don't look right.  Glowroot seems to arbitrarily attribute about 750 to each, but actually wiremock has been configured to wait 1500ms....
![image](https://user-images.githubusercontent.com/175773/27847960-10761306-6107-11e7-874b-71b1c71a83d8.png)

--Erik

**Comment by trask** [comment]
Hi @eostermueller, thanks for posting!

I think I'm understanding that the purpose of the WireMock service is to be a black box that introduces latency into the service that you are troubleshooting.

I think a good solution would be to import this instrumentation (under Configuration > Instrumentation):

```
{
  "className": "com.github.tomakehurst.wiremock.jetty9.JettyHandlerDispatchingServlet",
  "methodName": "service",
  "methodParameterTypes": [
    "javax.servlet.http.HttpServletRequest",
    "javax.servlet.http.HttpServletResponse"
  ],
  "captureKind": "other",
  "transactionType": "WireMock"
}
```

(the configured instrumentation is saved to the config.json file, so it could be part of the pom-startWar.xml)

This will capture the wiremock requests under a new "WireMock" transaction type (in the dropdown under Web), e.g.

![image](https://user-images.githubusercontent.com/218610/27902431-92074c08-61ea-11e7-8fd9-72bf87791de6.png)

And then the wiremock requests will no longer affect the throughput/metrics/profiles for the Web transactions.

Let me know what you think.

Also, I noticed you are using `java.net.HttpURLConnection` to make the http calls to WireMock.  I've been meaning to instrument that for a while, so finally did in #234.  If you try with the latest snapshot release [glowroot-agent-0.9.22-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.22-SNAPSHOT), you will see a metric for "http client" (the outgoing http request) and also you will see the outgoing http request inside of traces and aggregated under the "Service calls" tab.

Thanks,
Trask

**Comment by eostermueller** [comment]
Trask, I tried your release and it looks good.  wow, thanks for that.

TS wrote:
>>I think I'm understanding that the purpose of the WireMock 
>>service is to be a black box that introduces latency into the service 
>>that you are troubleshooting.

yep.

Below is my run.  I chose the live instrumentation route -- and the right side of the graph is _after_ I configured your json wiremock magic, and it looks like I'd expect it.
![image](https://user-images.githubusercontent.com/175773/27937222-0c4b7080-627b-11e7-8e3c-a7ad091b0109.png)


TS wrote:
>>I think this makes enough sense (and WireMock is only used in tests anyways).  
>>Then it wouldn't require any special config.json file for your usage.

that would be great, please keep me posted. you saved my bacon, thanks for that.
--Erik

**Comment by trask** [comment]
WireMock is handled now without additional configuration.  When you have a chance, try the latest snapshot release [glowroot-agent-0.9.22-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.22-SNAPSHOT).

**Comment by eostermueller** [comment]
sorry for the delay, I tried that snapshot release and it looks good.  Thanks for the quick turn-around.
--Erik
