### ISSUE TITLE
Websphere instrumentaion issue

### ISSUE THREAD

**Issue by anishkh** [glowroot/glowroot#241]
I'm getting an exception with websphere  8.5 with glowroot agent 0.9.15 with IBM J9 VM 1.7 and 1.8.  Also I had to add many permissions to policy file to get it started. 

2017-07-18 07:46:46.212 ERROR org.glowroot - channel
java.lang.NullPointerException: channel
        at org.glowroot.agent.shaded.google.common.base.Preconditions.checkNotNu
ll(Preconditions.java:787)
        at org.glowroot.agent.shaded.grpc.netty.WriteQueue.<init>(WriteQueue.jav
a:76)
        at org.glowroot.agent.shaded.grpc.netty.NettyClientHandler.startWriteQue
ue(NettyClientHandler.java:225)
        at org.glowroot.agent.shaded.grpc.netty.NettyClientTransport.start(Netty
ClientTransport.java:172)
        at org.glowroot.agent.shaded.grpc.internal.ForwardingConnectionClientTra
nsport.start(ForwardingConnectionClientTransport.java:45)
        at org.glowroot.agent.shaded.grpc.internal.TransportSet.startNewTranspor
t(TransportSet.java:222)
        at org.glowroot.agent.shaded.grpc.internal.TransportSet.obtainActiveTran
sport(TransportSet.java:192)
        at org.glowroot.agent.shaded.grpc.internal.ManagedChannelImpl$3.getTrans
port(ManagedChannelImpl.java:651)
        at org.glowroot.agent.shaded.grpc.internal.ManagedChannelImpl$3.getTrans
port(ManagedChannelImpl.java:592)
        at org.glowroot.agent.shaded.grpc.internal.RoundRobinServerList.getTrans
portForNextServer(RoundRobinServerList.java:83)
        at org.glowroot.agent.shaded.grpc.util.RoundRobinLoadBalancerFactory$Rou
ndRobinLoadBalancer.pickTransport(RoundRobinLoadBalancerFactory.java:115)
        at org.glowroot.agent.shaded.grpc.internal.ManagedChannelImpl$2.get(Mana
gedChannelImpl.java:314)
        at org.glowroot.agent.shaded.grpc.internal.ClientCallImpl.start(ClientCa
llImpl.java:213)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls.startCall(ClientCalls
.java:273)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls.asyncUnaryRequestCall
(ClientCalls.java:252)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls.asyncUnaryRequestCall
(ClientCalls.java:240)
        at org.glowroot.agent.shaded.grpc.stub.ClientCalls.asyncUnaryCall(Client
Calls.java:80)
        at org.glowroot.agent.shaded.glowroot.wire.api.model.CollectorServiceGrp
c$CollectorServiceStub.collectInit(CollectorServiceGrpc.java:253)
        at org.glowroot.agent.central.CentralCollector$1.call(CentralCollector.j
ava:142)
        at org.glowroot.agent.central.CentralConnection.callInit(CentralConnecti
on.java:187)
        at org.glowroot.agent.central.CentralCollector.init(CentralCollector.jav
a:139)
        at org.glowroot.agent.init.GlowrootThinAgentInit$1.execute(GlowrootThinA
gentInit.java:111)
        at org.glowroot.agent.init.NettyWorkaround$1.run(NettyWorkaround.java:74
)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1157)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:627)
        at java.lang.Thread.run(Thread.java:798)
2017-07-18 07:46:46.212 WARN  o.g.a.s.n.u.c.DefaultPromise - An exception was th
rown by org.glowroot.agent.shaded.grpc.netty.NettyClientTransport$3.operationCom
plete()
java.lang.NullPointerException: null
        at org.glowroot.agent.shaded.grpc.netty.NettyClientTransport$3.operation
Complete(NettyClientTransport.java:160)
        at org.glowroot.agent.shaded.grpc.netty.NettyClientTransport$3.operation
Complete(NettyClientTransport.java:156)
        at org.glowroot.agent.shaded.netty.util.concurrent.DefaultPromise.notify
Listener0(DefaultPromise.java:514)
        at org.glowroot.agent.shaded.netty.util.concurrent.DefaultPromise.notify
ListenersNow(DefaultPromise.java:488)
        at org.glowroot.agent.shaded.netty.util.concurrent.DefaultPromise.access
$000(DefaultPromise.java:34)
        at org.glowroot.agent.shaded.netty.util.concurrent.DefaultPromise$1.run(
DefaultPromise.java:438)
        at org.glowroot.agent.shaded.netty.util.concurrent.GlobalEventExecutor$T
askRunner.run(GlobalEventExecutor.java:233)
        at org.glowroot.agent.shaded.netty.util.concurrent.DefaultThreadFactory$
DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:798)
2017-07-18 07:46:50.658 INFO  org.glowroot - could not load platform mbean serve
r, using com.ibm.ws.management.PlatformMBeanServer

**Comment by anishkh** [comment]
Tried the latest version (0.9.22) which needed more policy to be added but no exception this time but mbean issue. 

2017-07-18 08:48:49.477 INFO  org.glowroot - could not load platform mbean serve
r, using com.ibm.ws.management.PlatformMBeanServer

**Comment by trask** [comment]
Thanks for reporting this!  I'm able to repro, and looking into solution.

**Comment by anishkh** [comment]
Thanks @trask

**Comment by trask** [comment]
Hi, this should be fixed now in my fork https://github.com/trask/glowroot. I'm having trouble with the travis-ci build servers right now though, which is why I haven't pushed it to the main repo.

I posted a local build in case you have a chance to try it out https://glowroot.org/issues-241-and-244/glowroot-agent-0.9.23-SNAPSHOT-dist.zip.

**Comment by anishkh** [comment]
Thanks @trask for the quick fix. It's working fine now . I had to add these permissions to java (1.7)  policy file . 

permission java.util.PropertyPermission "org.glowroot.agent.shaded.google.appengine.runtime.environment", "read";
permission java.util.PropertyPermission "com.google.appengine.runtime.environment", "read";
permission java.lang.RuntimePermission "getenv.GLOWROOT_GRPC_PROXY_EXP";
permission java.lang.management.ManagementPermission "monitor";
permission java.util.PropertyPermission "java.io.tmpdir", "read";
permission java.util.PropertyPermission "glowroot.transaction.throwable.frame.limit", "read";
permission java.util.PropertyPermission "ibm.system.encoding", "read";
permission java.lang.RuntimePermission "setContextClassLoader";
