### ISSUE TITLE
BusyPoolExceptions with central collector

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#243]
Hi,

I've got a central collector running in Tomcat8 and java8 with Cassandra 2.1.8, all on a single machine.
Even when there is not a whole lot of traces being sent to the central collector, I regularly see these stacktraces in the logfiles and I don't understand why:
`ERROR org.glowroot.central.GrpcServer - agent-id - com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127
.0.0.1:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [/127.0.0.1] Pool is busy (no available connection and the queue has reached its max size 4096)))
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.c
ore.exceptions.BusyPoolException: [/127.0.0.1] Pool is busy (no available connection and the queue has reached its max size 4096)))`

All exceptions are from same agent id (a production machine that regularly sends traces but only a handful per five minutes)
Any idea what this can be and if there are some thing that can be tuned?
Thanks

**Comment by trask** [comment]
Are you running central 0.9.22?  I possibly just fixed this (see #237)

**Comment by rolandkool** [comment]
No not yet, I have preparations ready for the upgrade, so I'll try that.
Does it matter which to upgrade first? agents or central collector? (coming from .16)

**Comment by trask** [comment]
Yeah, upgrade central collector first https://github.com/glowroot/glowroot/wiki/Central-Collector-Upgrade

**Comment by rolandkool** [comment]
The upgrade to 0.9.22 did indeed fix this issue for me. Running for a day now and not a single PoolBusy exception in the logs.

**Comment by trask** [comment]
That's great to hear, thanks.
