### ISSUE TITLE
JBoss fails to start with glowroot agent enabled

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#245]
Hi,

Yesterday I upgraded agent to 0.9.22 and today one JBoss instance all of a sudden failed to start with this message:
`ERROR o.g.a.util.LazyPlatformMBeanServer - platform mbean server was never created by container`

This is JBoss 4 EAP and started with `-Djboss.platform.mbeanserver=true`

A subsequent start had no issues.
Any idea what that could be?

Regards,

Roland

**Comment by trask** [comment]
Hi @rolandkool, thanks for reporting this.  Did the JBoss startup just hang?  It sounds to me related to #192.  If it happens again, can you grab a thread dump so I can see what the threads are blocked on?  Thanks.

**Comment by rolandkool** [comment]
The JBoss process was still running and the log said it was shutdown, but that is probably from the restart. If we run into this again, I'll take a threaddump.

**Comment by trask** [comment]
I just added deadlock detection for class weaving, so if/when this happens in the future (after updating to 0.9.23), glowroot will log the stack traces of the deadlocked threads.  I'm closing this issue for now, but please re-open and attach glowroot log if/when this happens again.  Thanks.
