### ISSUE TITLE
java.util.logging support

### ISSUE THREAD

**Issue by Albertus82** [glowroot/glowroot#246]
Dear Trask,
I added [**this aspect**](/Albertus82/glowroot/blob/master/agent/plugins/logger-plugin/src/main/java/org/glowroot/agent/plugin/logger/JavaLoggingAspect.java) to the _Logger Plugin_ in order to catch `java.util.logging` log records; I referenced it in [glowroot.plugin.json](/Albertus82/glowroot/blob/master/agent/plugins/logger-plugin/src/main/resources/META-INF/glowroot.plugin.json) but I don't see any Error in Glowroot's **Errors** tab even if I log at SEVERE level. Can you tell me if I'm missing something? I'm monitoring a simple Java client application (jar), not a web app. Thank you a lot.

Alberto

**Comment by trask** [comment]
Hi @Albertus82, thanks for posting!  Are you logging an exception at SEVERE, or only a message?  By default it will only mark the trace as error when an error is logged with an exception (see logic in https://github.com/glowroot/glowroot/blob/v0.9.22/agent/plugins/logger-plugin/src/main/java/org/glowroot/agent/plugin/logger/LoggerPlugin.java#L43)

Check out the logger configuration https://demo.glowroot.org/config/plugin?plugin-id=logger.  I think maybe the default configuration is not the best, and maybe should change https://github.com/glowroot/glowroot/blob/v0.9.22/agent/plugins/logger-plugin/src/main/resources/META-INF/glowroot.plugin.json#L16.

By the way, java.util.logging support would be a great addition.  Let me know if you plan to send PR, otherwise I will plan to add at some point.

Thanks,
Trask

**Comment by Albertus82** [comment]
Hi @trask, thank you for your reply. Let's start clean:
```java
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GlowrootJulTest {

	private static final int RUNNING_TIME_SECS = 300;

	private static final Logger logger = Logger.getLogger(GlowrootJulTest.class.getName());

	public static void main(final String... args) throws InterruptedException {
		System.out.println("Starting " + GlowrootJulTest.class.getName() + "...");
		for (int i = 0; i < RUNNING_TIME_SECS; i++) {
			TimeUnit.SECONDS.sleep(1);
			logger.log(i % 2 == 0 ? Level.SEVERE : Level.WARNING, "log message #" + i, new IllegalStateException("exception message #" + i));
		}
		System.out.println("Terminating " + GlowrootJulTest.class.getName() + '.');
	}
}
```
Running this code with the javaagent that includes my additions, I see no errors logged in Glowroot, but probably I'm missing something because if I run the same code using Log4j, I still have no errors in Glowroot:
```java
import java.util.concurrent.TimeUnit;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

public class GlowrootLog4jTest {

	private static final int RUNNING_TIME_SECS = 300;

	private static final Logger logger = Logger.getLogger(GlowrootLog4jTest.class.getName());

	public static void main(final String... args) throws InterruptedException {
		System.out.println("Starting " + GlowrootLog4jTest.class.getName() + "...");
		for (int i = 0; i < RUNNING_TIME_SECS; i++) {
			TimeUnit.SECONDS.sleep(1);
			logger.log(i % 2 == 0 ? Level.ERROR : Level.WARN, "log message #" + i, new IllegalStateException("exception message #" + i));
		}
		System.out.println("Terminating " + GlowrootLog4jTest.class.getName() + '.');
	}

}
```
`log4j.properties`:
```ini
# Root logger option
log4j.rootLogger=INFO, stdout

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
```
I'm sorry I'm not able to detect what's wrong.

Anyway I'll be glad to make a pull request when this thing will work properly, of course. Thank you again.

**Comment by trask** [comment]
Ah, I see, you don't have any transactions defined.

Try this:

```
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GlowrootJulTest {

    private static final int RUNNING_TIME_SECS = 300;

    private static final Logger logger = Logger.getLogger(GlowrootJulTest.class.getName());

    public static void main(final String... args) throws InterruptedException {
        System.out.println("Starting " + GlowrootJulTest.class.getName() + "...");
        for (int i = 0; i < RUNNING_TIME_SECS; i++) {
            sleepAndLog(i);
        }
        System.out.println("Terminating " + GlowrootJulTest.class.getName() + '.');
    }

    private static void sleepAndLog(int i) throws InterruptedException {
        TimeUnit.SECONDS.sleep(1);
        logger.log(i % 2 == 0 ? Level.SEVERE : Level.WARNING, "log message #" + i,
                new IllegalStateException("exception message #" + i));
    }
}
```

and import this instrumentation through the UI (under Configuration > Instrumentation):

```
  {
    "className": "GlowrootJulTest",
    "methodName": "sleepAndLog",
    "methodParameterTypes": [
      "int"
    ],
    "captureKind": "transaction",
    "transactionType": "Test",
    "transactionNameTemplate": "Test",
    "traceEntryMessageTemplate": "test",
    "timerName": "test"
  }
```

This will define a transaction for each call to sleepAndLog(int), and you will hopefully start seeing the errors in Glowroot.

**Comment by Albertus82** [comment]
Thank you, it works! I'm now refining the work. Can I assume that `java.util.logging` package is present in Glowroot classpath? I think that use @Shim in this case may be overkill and can make log message formatting complicated.

**Comment by trask** [comment]
Great.  Yes, good point, you can assume `java.util.logging` is available and avoid the `@Shim`.

**Comment by Albertus82** [comment]
@trask I'm experiencing troubles running the test, maybe a classloader issue? The advice doesn't run, but it works properly outside the test environment. Any ideas? TY

**Comment by Albertus82** [comment]
Hi @trask, solved: the tests run fine but, like `LogbackIT`, work only when shaded, so I added an _assume_ in the test's `setUp()` method. [Travis CI builds fine](https://travis-ci.org/Albertus82/glowroot/builds/258890027).

I'm going to open a PR containing this improvement as well as a new plugin named **Java HTTP Server Plugin** that I wrote to support the [Java HTTP Server](https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/index.html) bundled with JRE since version 6. Tests are included.
This new plugin is similar to the **Servlet Plugin** but it's simpler because _Java HTTP Server_ doesn't have native support for sessions, async requests and parameters. I used that server for a standalone application ([RouterLogger](/Albertus82/RouterLogger)) that I use for monitoring purposes, so I'm already using the plugin on a real scenario. I hope you appreciate it. Of course, feel free to rename the plugin if you don't like the name I choose; I took the name from the title of the documentation page.

Thank you a lot for you great work.

**Comment by trask** [comment]
Closed by #248

**Comment by godhanairi** [comment]
Hi,
I have integrated glow root on my system which is running but I don't understand how I attach my java application in glow root for monitoring?

**Comment by trask** [comment]
Hi @godhanairi, have you followed instructions at https://github.com/glowroot/glowroot/wiki/Agent-Installation? Can you provide more details about what you've tried and where you are stuck?
