### ISSUE TITLE
Permissions of a rollup should imply permissions to its agents

### ISSUE THREAD

**Issue by haiyingwang** [glowroot/glowroot#249]
When configuring a role, I found that adding permissions of a rollup does not automatically imply permissions to its agents; permissions to rollup and its agents are considered independent. For a multiple tenants setup, I think it would be much easier to manage a tenant user's permissions if permissions of a rollup can cover it's agents permissions, especially in case of large number of JVMs could be created/removed dynamically under a rollup, such as a micro-services env. Do you think Glowroot could support this function in the near future?

**Comment by risrikanth** [comment]
Do we have any time frame when we get  version 1.0.0..  I am also looking for this future..

**Comment by trask** [comment]
Hi @risrikanth, hopefully in the next month.

**Comment by risrikanth** [comment]
Thank you very much for your update on the dates..

**Comment by trask** [comment]
This is available now in the latest central snapshot [glowroot-central-0.10.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.0-SNAPSHOT) (or [glowroot-central-0.10.0-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.10.0-SNAPSHOT)).
