### ISSUE TITLE
How to define my own probe

### ISSUE THREAD

**Issue by solio** [glowroot/glowroot#251]
How to define my own probe?For example, defining a probe to watch the specific method's runtime status?

**Comment by trask** [comment]
Hi @solio, thanks for posting!  Do you mean a method that returns a numeric value that you want to display under JVM > Gauges?

**Comment by trask** [comment]
Or a method that you want to create a timer on, and display in the breakdown under Transaction > Response time?

**Comment by solio** [comment]
@trask ，Yes，just like a method's performance monitor,but I want collect more Information that I focus on.That will help me watching some very strange issues

**Comment by trask** [comment]
Have you already seen https://glowroot.org/instrumentation.html?

**Comment by saurabh256** [comment]
Hi Trask,
I have a spring boot with camel application. When I go on instrumentation page and try to see class and method. It allows me to enter a method with option signature as per Glowroot documentation and live demo.  Just for the try I selected only timer option. 

I was expecting it will show me all the methods call below in chain with time taken by each method. However on "Web" tab I am not able to see any performance data. 

JVM tab shows me various objects and stats from JMX . 
Just want to understand what I am doing is correct?

Regards
Saurabh

**Comment by trask** [comment]
The timer name you chose should show up under the response time breakdown, e.g. the way "thymeleaf view" shows up on https://demo.glowroot.org/transaction/average?transaction-type=Web

But timers are only captured inside of transactions.  And transactions are only captured out of the box for servlets (under Web) and quartz jobs (under Background).  Try the `transaction` option for your instrumentation and see if that helps.

**Comment by trask** [comment]
Closing, but feel free to re-open if you have additional questions about this.
