### ISSUE TITLE
ERROR after change cassandra.contactPoints from one to another

### ISSUE THREAD

**Issue by sunfc** [glowroot/glowroot#253]
When I change cassandra.contactPoints, I get this Exception.
How to repair this? 
Thanks.

2017-08-04 14:26:17.548 ERROR org.glowroot.ui.LayoutService - group1/store
org.glowroot.common.repo.ConfigRepository$AgentConfigNotFoundException: group1/store
...

**Comment by trask** [comment]
Hi @sunfc, thanks for posting!  What version of glowroot central are you using?

**Comment by sunfc** [comment]
Hi @trask, thanks for replying. I am using 0.9.21.

**Comment by trask** [comment]
Is the glowroot central UI working normally?  What do you mean by changing cassandra.contactPoints?  Did you switch to a new Cassandra instance/cluster?  Thanks.

**Comment by sunfc** [comment]
Glowroot central UI can not work as well. At first, I use cassandra instance A, it's not a cluster. Then, I expand the cassandra from one instance A to a cluster with two instances A and B. And I change the contactPoints from A to B. Thanks.

**Comment by trask** [comment]
What error do you get in glowroot central UI?

**Comment by sunfc** [comment]
Sorry, I said 'Glowroot central UI can not work', this is not clear. Glowroot central UI is working, but without any data from the agents which shows the exceptions.

**Comment by trask** [comment]
It sounds like glowroot is not finding some `agent_config` records after adding the second cassandra node.  What are you using for `cassandra.consistencyLevel` in your `glowroot-central.properties` file?

**Comment by sunfc** [comment]
I keep it as default: QUORUM.

**Comment by trask** [comment]
Can you connect with `cqlsh` and run

`select agent_rollup_id from glowroot.agent_config`

on both nodes?

Do you see the agent configs that missing on both nodes?

**Comment by trask** [comment]
(by the way, these agent config records will be re-inserted the next time those agents are restarted and make their initial connection to glowroot central, but it would be good to understand what happened here, and why they have gone missing in the first place)

**Comment by sunfc** [comment]
Some of the agent configs lost in both of the nodes. I haven't restarted the agents. Actually, they will be restart when we release our projects next time.

**Comment by sunfc** [comment]
I transfered the cassandra of glowroot-central to another cluster which contains two toplogical rings. And I changed the 'cassandra.contactPoints' from one ring to the other. This problem didn't happen again. So I think that some inproper configure of the cassandra before might be the reason that raised this problem.

**Comment by trask** [comment]
Hi @sunfc, thanks for the update.
