### ISSUE TITLE
Unable to instrument java in TIBCO-BW application

### ISSUE THREAD

**Issue by vijayninave** [glowroot/glowroot#256]
Hi Team,

We are unable to instrument java agent in TIBCO-BW application.
Please find the attached TRA file for your reference. Kinldy check & let us know where we need to put the java parameter for this instrumentation.

Regards,
Vijay Ninave.
[ASCustomerConfigurationInquiry-2-1-CustomerConfigInquiry-4.zip](https://github.com/glowroot/glowroot/files/1207354/ASCustomerConfigurationInquiry-2-1-CustomerConfigInquiry-4.zip)

**Comment by trask** [comment]
Hi @vijayninave, it looks like you added it to the right place, but maybe you need to escape the `:` character similar to the other jvm args listed, e.g.

```
java.extended.properties=-XX\:+UseConcMarkSweepGC -XX\:+CMSPermGenSweepingEnabled -XX\:+CMSClassUnloadingEnabled -XX\:PermSize\=512m -XX\:MaxPermSize\=512m -javaagent\:/app/tibcobw/glowroot-agent/glowroot.jar
```

**Comment by vijayninave** [comment]
Hi Trask,

Thanks for your response.
Where should i inject the path in TRA file, Could you please explain in details as this is TIBCO application.

Note:- TRA file is attached in earlier mail.

Regards,
Vijay.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by trask** [comment]
I opened your TRA file and it was already in there.  See my previous comment on what you probably need to change.

**Comment by vijayninave** [comment]
Hi Trask,

Just wanted to confirm the changes as per attached screenshot. 1st line is existed in tra file & the 2nd one which we need to implement for same. Kindly validate & confirm this.
![tibco](https://user-images.githubusercontent.com/30725196/29109768-e0458d44-7d01-11e7-94f1-ab675555eb75.JPG)

**Comment by trask** [comment]
Yes, that is what I was suggesting.

**Comment by vijayninave** [comment]
Hi Trask,

Appreciate your support here. We have successfully instrumented glowroot agent for TIBCO application.

Thanks & Regards,
Vijay.

**Comment by vijayninave** [comment]
Issue resolved, hence closing this.

**Comment by SurenKR** [comment]
Hi,
Im also trying to instrument glowroot Tibco BW application. 

1. Unzipped glowroot zip file
2. I have added the same java.extended.properties line in my application TRA file with my glowroot path.
3. Restarted the application.
.lock file was created in tmp folder. 
UI was not started, so I manually started glowroot agent by 'java -javaagent glowroot.jar' command.

I have opend UI, i could see 'No data'


Please help on understanding the instrumentation of glowroot with Tibco BW. Thanks in advance.
