### ISSUE TITLE
Agent limitation for 1 controller

### ISSUE THREAD

**Issue by vijayninave** [glowroot/glowroot#258]
Hi Team,

Could you please confirm, how many agent we can deploy in 1 controller.
Is there any limitation on agent or OS configuration for same.

Regards,
Vijay.

**Comment by vijayninave** [comment]
Hi Team,

Awaiting for your kind response.

Regards,
Vijay.

**Comment by trask** [comment]
Sorry for the late response, I was not sure how to respond to the central collector capacity question. 
It depends on many factors, but in the end, I think the best advice is to start with a small number of agents and monitor the central collector itself as you increase the number of agents. You can of course monitor glowroot central using glowroot agent :-).

As a ballpark reference, I have 100 agents sending data to a 4 core / 16gb memory box that is running both the central collector and the Cassandra backend.

Let me know if you have additional questions.

**Comment by trask** [comment]
Closing, but feel free to re-open if you have additional questions about this.
