### ISSUE TITLE
Deadlock on Glowroot 0.9.22

### ISSUE THREAD

**Issue by hgomez-sonarsource** [glowroot/glowroot#264]
Today, one of my application, using Tomcat Embedded was unresponding. No problem reported in logs but my monitoring system show httpd threads where high and never reclaimed.

I did a jstack and see a deadlock on Glowroot

    Found one Java-level deadlock:
    =============================
    "Glowroot-Aggregate-Processing":
      waiting to lock Monitor@0x00007f9958004848 (Object@0x00000000803c6648, a org/glowroot/agent/util/RateLimitedLogger),
      which is held by "Glowroot-Gauge-Flushing"
    "Glowroot-Gauge-Flushing":
      waiting to lock Monitor@0x00007f99580049a8 (Object@0x00000000801e6290, a org/glowroot/agent/init/CollectorLogbackAppender),
      which is held by "Glowroot-Aggregate-Processing"

I had to quickly restart service and cannot perform a hprof.
I also upgraded to 0.9.24 as I see a mention of deadlock (for JBoss BTW) in closed issues

**Comment by trask** [comment]
Thanks for reporting this, can you post the full stack traces in the
deadlock?

**Comment by hgomez-sonarsource** [comment]
Hi Trask

Sadly I had no stack trace nor hprof, only this report from jstack was available :(

**Comment by trask** [comment]
That's ok, this is still really useful.

**Comment by hgomez-sonarsource** [comment]
I updated machine to Java 8u144 and Glowroot Agent 0.9.24. If problem strike back, I'll try to get an hprof before restarting

**Comment by trask** [comment]
Hi Henri, I wasn't able to fix this before leaving town, but I think I have enough to go on and will work on it when I return in a bit under 2 weeks

**Comment by hgomez-sonarsource** [comment]
That's a very good news. Thanks a lot !

**Comment by trask** [comment]
Thanks again for reporting this. It should be fixed now in the latest snapshot release [glowroot-agent-0.9.25-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.25-SNAPSHOT).

**Comment by hgomez-sonarsource** [comment]
Thanks a lot Trask
