### ISSUE TITLE
Partially collected (stuck) traces are not visible in glowroot central after agent JVM restart

### ISSUE THREAD

**Issue by trask** [glowroot/glowroot#269]
E.g. clicking on the partially collected (stuck) trace below (e.g. after JVM hung and had to be restarted)

![partial-trace-1](https://user-images.githubusercontent.com/218610/30411180-494e3682-98c4-11e7-864f-fc4e11181f46.png)

displays empty trace:

![partial-trace-2](https://user-images.githubusercontent.com/218610/30411223-8707864a-98c4-11e7-914a-8e42c165d43c.png)

Browser network tab shows response:

`{"agent":"...","startTime":0,"captureTime":0,"durationNanos":0,"transactionType":"","transactionName":"","headline":"","user":"","auxThreadRootTimers":[],"asyncTimers":[],"entryCount":0,"mainThreadProfileSampleCount":0,"auxThreadProfileSampleCount":0,"entriesExistence":"no","profileExistence":"no"}`

**Comment by rolandkool** [comment]
+1 , ran into this myself this week. 
In addition, I initially got an error that it couldn't retrieve the trace. A stacktrace in the glowroot central logfile showed that to be caused by the java agent not being active anymore (which was correct in my case).

**Comment by trask** [comment]
This should be fixed now in the latest snapshot release [glowroot-agent-0.9.25-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.25-SNAPSHOT).
