### ISSUE TITLE
Inconsistent behavior in left side transaction filter functionality.

### ISSUE THREAD

**Issue by khushalwadake** [glowroot/glowroot#271]
H Team,

I have configured glowroot on 7 instances from same layer like shown in below image using centralized Glowroot setup.
![image](https://user-images.githubusercontent.com/25651436/30642283-1c634732-9e02-11e7-80c5-d74a65cf2716.png)

In left side panel, for some servers it shows transaction like "GET /xxxxx/xxxxx/*/status" and for some servers it shows all requests individually like "/xxxxx/xxxxx/1234/status", "/xxxxx/xxxxx/5678/status". 

Where config and agent version is same. I would prefer to have "GET /xxxxx/xxxxx/*/status" representation across all servers. please share your thoughts on how to make it consistent. 

Thanks,
Khushal wadake

**Comment by trask** [comment]
Hi @khushalwadake, sorry for the very late reply :-(. Are you still seeing this? What web framework are you using? The servlet plugin uses the full request path as the transaction name (e.g. "/xxxxx/xxxxx/5678/status"), but then some of the other plugins (e.g. spring plugin, jaxrs plugin) override the transaction name with the mapping used by that web framework (e.g. "/xxxxx/xxxxx/*/status").

**Comment by trask** [comment]
Closing, but feel free to re-open if you'd like to continue discussing. Thanks.
