### ISSUE TITLE
Can't login after session timeout was set to 0

### ISSUE THREAD

**Issue by rafaelszp** [glowroot/glowroot#272]
I set my session timeout to 0. Now I cant login into the app. Is there any way to fix this?

**Comment by trask** [comment]
Thanks for reporting this, that's not a good behavior for 0. You can edit the value in the config.json file, it will require JVM restart to pick up the new value.

**Comment by rafaelszp** [comment]
Thank you. I made an update right into database and everything is fine now. Keep the great work.
