### ISSUE TITLE
Steps to verify the logs

### ISSUE THREAD

**Issue by mchadda** [glowroot/glowroot#275]
Hi Team,

Can anyone from the team please provide us the steps in order to verify the logs.

Thanks,
Manav

**Comment by mchadda** [comment]
Hi Team,

Can you please provide us the steps in order to verify the logs.

Thanks,
Manav

**Comment by trask** [comment]
Hi @mchadda, I'm not sure what you mean.  Can you provide more context around the issue you are having?

**Comment by trask** [comment]
Closing, but feel free to re-open if there is any update, thanks.
