### ISSUE TITLE
InfluxDB integration?

### ISSUE THREAD

**Issue by v4vamsee** [glowroot/glowroot#279]
We currently utilize influxDB+telegraf+grafana in our organization to collect various metrics. I found glowroot to be interesting. Are there any plans to store the data to influxdb  for historical view in future?

**Comment by v4vamsee** [comment]
We currently use JavaMelody as our APM. We would like to implement glowroot but it would be great if it can integrate with influxdb.

**Comment by trask** [comment]
Hi @v4vamsee, thanks for posting!  See related question at https://groups.google.com/forum/#!topic/glowroot/fKJJHukx_ok and let me know if the response there is helpful.

**Comment by v4vamsee** [comment]
Hi @trask  I myself am a Web administrator. I don't have too much background into Java Development. The link you provided is kinda related to my needs. But still not clear how to accomplish what I need (since I lack the programming background).

**Comment by trask** [comment]
Hi @v4vamsee, I don't have plan at this point for the central collector to support storage option other than Cassandra.
