### ISSUE TITLE
Mask request parameters should be extended to query string

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#283]

**Comment by trask** [comment]
Hi @ionutursuleanu, thanks for posting!  JAX-RS and the other plugins piggy back on the servlet plugin. 
 The request parameters are captured by the servlet plugin, so the masking configuration should be set there.  Or are you seeing/thinking of something different?  Thanks.

**Comment by trask** [comment]
@ionutursuleanu Thanks for the screenshot!  I will fix this in the next release.

**Comment by trask** [comment]
Thanks for reporting this. It should be fixed now in the latest snapshot release [glowroot-agent-0.9.27-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.27-SNAPSHOT).
