### ISSUE TITLE
http thread pool & DB connection pool gauge for payara

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#285]
Hi @trask 

I saw on the demo site that, for tomcat, gauges for thread & db connection pool are available. For payara I can't find something similar. Is this something that needs development or I just not found the right setting?

Thanks

**Comment by trask** [comment]
Hi @ionutursuleanu, thanks for posting!  For the demo site, I configured the Tomcat gauges based on mbeans exposed by Tomcat, see https://demo.glowroot.org/config/gauge-list and https://demo.glowroot.org/jvm/mbean-tree.  Check under JVM > MBean tree in your environment to see what Payara exposes and then you can configure gauges based on what you find.  Let me know if this makes sense / works out for you.

**Comment by ionutursuleanu** [comment]
Hi @trask 

See the attached zip for MBean tree available on payara. I don't see anything for thread & DB connection pools.

[JVM · Glowroot.zip](https://github.com/glowroot/glowroot/files/1453375/JVM.Glowroot.zip)

**Comment by ionutursuleanu** [comment]
I might found something in payara settings. It seems that almost all MBeans are disabled by default. I will come back with more feedback in a few days

**Comment by ionutursuleanu** [comment]
Hi,

It seems that not all MBeans properties are available for gauges.

currentthreadcount is present on MBean tree 

![mbean_tree](https://user-images.githubusercontent.com/6136404/32784613-fc7f45c0-c957-11e7-8f89-902bc9cc1c88.png)

but not on new gauge

![gauges_add](https://user-images.githubusercontent.com/6136404/32784737-560b5b60-c958-11e7-8376-915d12150e8f.png)

This properties are available on visualvm also

![visualvm](https://user-images.githubusercontent.com/6136404/32784844-9eb2d46a-c958-11e7-8d3a-ad273deb28dc.png)

**Comment by trask** [comment]
Can you enter just `thread-pool-mon` when creating a new MBean and see if the `network/http-listener-1/thread-pool` MBean shows up in autocomplete?

**Comment by ionutursuleanu** [comment]
Yes, the MBean shows up in the autocomplete, but nothing is available on the attributes section.

![thread-pool-mon](https://user-images.githubusercontent.com/6136404/32827593-62584f16-c9f5-11e7-861b-f1138f8b08b0.png)

**Comment by trask** [comment]
Thanks for reporting this. It should be fixed now in the latest snapshot release [glowroot-agent-0.9.27-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.27-SNAPSHOT).
