### ISSUE TITLE
sample tutorial?

### ISSUE THREAD

**Issue by raulvillalbamedina** [glowroot/glowroot#293]
Hello, 
I need the basic steps to use glowroot.
I try these:
FIRST TEST. I am testing this steps "Download and unzip glowroot-0.9.28-dist.zip, add -javaagent:path/to/glowroot.jar to your JVM args, start your app, point browser to http://localhost:4000, and see all this! " but glowroot is not starting with my app.

SECOND TEST. I try start first glowroot.jar with "java -jar glowroot.jar" and start after my application with this "java -jar myspringbootapplication.jar -javaagent:/home/myuser/glowroot/glowroot.jar". Now I can enter to localhost:4000 and see the glowroot ui. I call to some endpoints in my app but I do not see anything in glowroot ui.

THIRD TEST. I try to add de dependency to my pom.xml and add to one of my rest endpoints this annotation @Instrumentation.Timer("process invoice")

               <dependency>
			<groupId>org.glowroot</groupId>
			<artifactId>glowroot-agent-api</artifactId>
			<version>0.9.27</version>
		</dependency>

Now I try the first and the second test with this annotation but I do not view anything in glowroot ui.

Could you tell me what I'm doing wrong?

Thanks

**Comment by trask** [comment]
Hi Raul,

Your first test is the correct way.

JVM args go before -jar, did you try with:

```
java -javaagent:/home/myuser/glowroot/glowroot.jar -jar myspringbootapplication.jar
```

Thanks,
Trask

**Comment by trask** [comment]
Closing, but feel free to re-open if you have additional questions about this.

**Comment by Vidyack** [comment]
Hi Raul,

I am also facing same problem? how to solve this?
