### ISSUE TITLE
Could you explain the source I do not understand?

### ISSUE THREAD

**Issue by bill23-kim** [glowroot/glowroot#295]
Hello,

There is a part that does not understand well when looking at agent core source.

The part that adds the InitListener to the lazyPlatformMBeanServer in the constructor of the GaugeCollector

~~~
Class<?> sunManagementFactoryHelperClass = Class.forName("sun.management.ManagementFactoryHelper");
Method registerInternalMBeansMethod = sunManagementFactoryHelperClass.getDeclaredMethod("registerInternalMBeans", MBeanServer.class);
registerInternalMBeansMethod.setAccessible(true);
registerInternalMBeansMethod.invoke(null, mbeanServer);
~~~

Why does force a call to registerInternalMBeans in the ManagementFactoryHelper class?

Thank you.

**Comment by trask** [comment]
Hi @bill23-kim, thanks for posting!  That method registers a few MBeans, e.g. see the four MBeans under `sun.management` at https://demo.glowroot.org/jvm/mbean-tree.

In particular, sometimes I use the `sun.management:type=HotspotRuntime` MBean to create gauges to monitor JVM safepoint time.

**Comment by bill23-kim** [comment]
@trask Thank you for your response.
