### ISSUE TITLE
Dynamic Agent Creation and Deletion in Microservices env

### ISSUE THREAD

**Issue by pavanie** [glowroot/glowroot#296]
We are using glowroot to monitor our microservices (a couple hundreds) and noticing that because of the dynamic nature of the microservice pods, as they get created and deleted often and the name of each agent/jvm that spins up is different, they appear in central collector as a new jvm.  Any ideas on how to protect the central collector from an issue in the microservices env which might lead to frequent loss of connection to agents and reconnects to new agents?

**Comment by trask** [comment]
Hi @pavanie, thanks for posting!  Can you clarify the issue you are seeing?  Is the problem that the dropdown list of agents is getting too large (see #155)?  Or something else?  Thanks.

**Comment by pavanie** [comment]
Dropdown is one issue. Layoutservice seems to be getting all the rollup and agent information, so more the agents, the longer it seems to be taking. Overall the controller gui seems slow.

**Comment by trask** [comment]
Thanks, that makes sense, I'll target this for v0.10.0 along with #155.

**Comment by trask** [comment]
Thanks for reporting this!  It should be fixed now in the latest central snapshot [glowroot-central-0.10.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.0-SNAPSHOT) (or [glowroot-central-0.10.0-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.10.0-SNAPSHOT)).
