### ISSUE TITLE
Glowroot on Payara Server

### ISSUE THREAD

**Issue by OndrejM** [glowroot/glowroot#297]
Hi, Payara Server is derived from GlassFish server. Since Glowroot is already being used with Payara Server and found issues are being fixed (#285, #262 as examples), could you add Payara Server to the list of tested servers on the page https://glowroot.org/features.html ?  It can also stand next to Glassfish, e.g. mentioned as:

...
- Jetty
- Glassfish / Payara

...

**Comment by trask** [comment]
Hi @OndrejM, thanks for the suggestion!  Payara is now included.
