### ISSUE TITLE
User should be able to select environment variables that needs to be hidden

### ISSUE THREAD

**Issue by pkgajulapalli** [glowroot/glowroot#298]
There might be some environment variables such as private keys (jasypt.encryptor.password) are visible on glowroot webpage. Some configuration should be available to hide selected environment variables.

**Comment by trask** [comment]
Hi @pkgajulapalli, thanks for requesting this! This is a good idea, and should be available in the next release.

**Comment by trask** [comment]
Thanks for requesting this!  It is available now in the latest snapshot releases:

* [glowroot-agent-0.10.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.0-SNAPSHOT)
* [glowroot-central-0.10.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.0-SNAPSHOT) (or [glowroot-central-0.10.0-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.10.0-SNAPSHOT))

The new setting is under Configuration > JVM, e.g., https://demo.glowroot.org/config/jvm.
