### ISSUE TITLE
Does glowroot support undertow?

### ISSUE THREAD

**Issue by WangHouLing** [glowroot/glowroot#301]
Hi,
Excuse me, my springboot application use undertow container, does glowroot can collect message  from undertow?
Than you!

**Comment by trask** [comment]
Hi @WangHouLing, thanks for posting! Glowroot should work with any embedded servlet container because it instruments the servlets themselves (not the container). Let me know if you see any issues.

**Comment by WangHouLing** [comment]
@trask Thank you!  I would like to have a try.
