### ISSUE TITLE
Is the data folder location configurable?

### ISSUE THREAD

**Issue by dknlam** [glowroot/glowroot#302]
Is there a way to change the location of data, logs, and tmp folders? Or do I need to use symbolic links?

**Comment by trask** [comment]
Hi @dknlam, thanks for posting!  Yes, the following system properties can be set at the command line:

`-Dglowroot.conf.dir=...`
`-Dglowroot.log.dir=...`
`-Dglowroot.tmp.dir=...`
`-Dglowroot.data.dir=...`

You can also set these in `glowroot.properties` file in the same directory as `glowroot.jar`, but without using the `glowroot.` prefix in the property names, e.g.

```
conf.dir=/etc/glowroot
log.dir=/var/log/glowroot
tmp.dir=/tmp/glowroot
data.dir=/var/lib/glowroot
```

**Comment by dknlam** [comment]
Hi @trask

Thanks for the information. This is excellent!
