### ISSUE TITLE
Multiple instances of an application

### ISSUE THREAD

**Issue by WangHouLing** [glowroot/glowroot#303]
Hi,
Excuse me, If my application has multiple instances, how can I name agent.id?
**version**
0.9.28

Thank you!

**Comment by trask** [comment]
Hi @WangHouLing, if you using a central collector, see https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation#agent-installation.  If you are not using a central collector, see https://github.com/glowroot/glowroot/wiki/Agent-Installation#multiple-agents-on-one-box.  Let me know if you have further questions.  Thanks.

**Comment by WangHouLing** [comment]
Thank you. 
I'm using a central collector. When I start multiple instances of an application, setting the same agent.id will cause error, setting different agent.id that will appear two names in the glowroot web. Actually, it is different instance of an application. So, is there any way to avoid this problem?

**Comment by WangHouLing** [comment]
Ok, thank you.
