### ISSUE TITLE
Need to Generate Thread dump for a particular Alert condition

### ISSUE THREAD

**Issue by ypsharad** [glowroot/glowroot#304]
Hello,

Your tool is so awesome. It has helped us monitor and find the bottlenecks in our application

I need a little help regarding below requirement

I have set few Alerts on my glowroot instance to send email when 99 percentile of  Transactions are taking time more than  20s or Heap Dump size increases more than 6.5 Gb
I need to auto generate a thread dump for that particular interval on some location on the disk when this condition is reached

Unable to find any way to do this

**Comment by ypsharad** [comment]
Hi trask,

I am looking for your response.. 
Can you please update me on that??... 
Is it possible auto thread dump when threshold crossed limit??
Waiting of your positive response??

**Comment by trask** [comment]
Hi @ypsharad, thanks for posting! This is not currently possible. Adding an option to generate a heap dump on some alerts would be nice, I could use this myself. It sounds like you also want a thread dump? Is this so you can see if there are any thread deadlocks?

**Comment by ypsharad** [comment]
yes, that's exactly what i am looking for. Would be nice  to have feature

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
