### ISSUE TITLE
Is glowroot appropriate for running in Docker containers?

### ISSUE THREAD

**Issue by rendion** [glowroot/glowroot#305]
I ask because I see these data, tmp and log dirs storing data from current dir where the app launches.  Im not sure writing to the docker container fs is a good idea.  Can you suggest a way to centralize the glowroot console external to say an ecosystem of hundreds of docker containers running java if this is possible at all with glowroot?

**Comment by trask** [comment]
Hi @rendion, thanks for posting!  These directory locations are configurable (e.g. you can point them to an external volume). I just added a wiki section on how to configure the directory locations, see https://github.com/glowroot/glowroot/wiki/Agent-Installation#changing-directory-locations.  Another way to go would be to set up the [central collector](https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation) and point all the agents to the central collector.
