### ISSUE TITLE
Monitoring of websocket connections

### ISSUE THREAD

**Issue by Robbe64** [glowroot/glowroot#306]
It seems that it isn't possible to monitor requests of an active websocket connection.
Even instrumentation doesn't help.

**Comment by trask** [comment]
Hi @Robbe64, thanks for posting! What framework/library are you using for handling websocket requests, and what instrumentation have you tried?

**Comment by Robbe64** [comment]
I'm using Spring websocket 4.3.6. I tried instrumentation with Instrumentation UI and Agent API.

**Comment by trask** [comment]
Hi @Robbe64, can you export and share the instrumentation you tried via the UI?

**Comment by trask** [comment]
Spring WebSocket requests (specifically STOMP messages to `@MessageMapping` controller methods) are now captured in the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT).

**Comment by Robbe64** [comment]
Many thanks. Seems to work great!
