### ISSUE TITLE
I need clarification

### ISSUE THREAD

**Issue by narasimhacalsoft** [glowroot/glowroot#309]
Hi Team,
                shall i build jar file from source code of glow root. if it's possible please let me know step by step.

Please can any one give replay on this.

**Comment by trask** [comment]
Hi @narasimhacalsoft, please see the instructions at https://github.com/glowroot/glowroot#building.

**Comment by narasimhacalsoft** [comment]
Hi,
 so we cann't  customized source code of the Glow root right?

**Comment by trask** [comment]
Hi @narasimhacalsoft, please see the license details at https://github.com/glowroot/glowroot#license.
