### ISSUE TITLE
Too much storage usage on the central collector 

### ISSUE THREAD

**Issue by rsang** [glowroot/glowroot#310]
Hi,

First of all, love the product. It has been helpful in troubleshooting several critical issues. Thank you very much Glowroot team!!!

Secondly, I have a central collector Glowroot server monitoring two Tomcat servers. The central collector uses over 17 GB storage, and I'd like to reduce it to 8~9 GB if possible. I don't need to monitoring the Tomcat servers all the time, so the coarse-grain data collecting works for me. I've been played with the storage configuration settings but I still haven't get the result I want. Is there a way to reduce the number of sampling? Or is there a way to clean up the tables in cassandra easily?

Thanks!

Sean

**Comment by trask** [comment]
Hi @rsang, thanks for the kind words!

Glowroot inserts data into Cassandra using a TTL (time-to-live) based on the storage config settings. This means that changing the storage config settings in the central collector does not affect the TTL of data already inserted into Cassandra.

The easiest way to clean up (start over with new storage config settings) is to stop the central collector, truncate all tables in the glowroot keyspace except for these:

```
agent_config
agent_rollup
central_config
role
schema_version
user
v09_agent_rollup (if you are on central collector v0.10.0+)
```

and then re-start the central collector.

Cassandra takes snapshots of the data before it truncates or drops tables (for data safety), so you'll want to use `nodetool clearsnapshot <glowroot keyspace>` afterwards to clear the snapshots and reclaim disk space.

**Comment by trask** [comment]
Closing, but feel free to re-open if you'd like to continue discussing.  Thanks.
