### ISSUE TITLE
Missing Queries in Web Transactions

### ISSUE THREAD

**Issue by v4vamsee** [glowroot/glowroot#314]
Hello,

We currently have both Glowroot and JavaMelody integrated with our application together. In order to compare both, we ran a test case and found that some queries were missing in Glowroot where as they were listed in JavaMelody.

One thing to point out, JavaMelody is integrated within our ".war" file where as Glowroot in integrated with tomcat.

To further make sure we are doing it right, we enabled only one APM at a time and generated reports respectively. We still found missing queries in glowroot.

**Question:**

In what scenarios would a query not show up in Glowroot? Can it be resolved by making configuration changes in Glowroot? 

Any help is appreciated.

We are using Glowroot version 0.10.0,

**Comment by trask** [comment]
Hi @v4vamsee, have you checked for the queries under Background or Startup transactions? (e.g. https://demo.glowroot.org/transaction/queries?transaction-type=Background)

Another possibility is that you are exceeding "Max aggregate queries per query type" (see Configuration > Advanced, e.g. https://demo.glowroot.org/config/advanced).  In this case you will see "LIMIT EXCEEDED BUCKET" reported as one of the queries and the metrics for those missing queries would be aggregated into that bucket.

Another possibility is that the query is not inside of a transaction/thread that Glowroot knows about.  A stack trace to see the location where the missing query is executed would be helpful to identify/resolve if this is the case.

**Comment by trask** [comment]
Closing, but feel free to re-open if you'd like to continue discussing.  Thanks.
