### ISSUE TITLE
Reduce the glowroot agent jar size

### ISSUE THREAD

**Issue by anveshgkumar** [glowroot/glowroot#315]
We are using the central collector and don't want to use the embedded jar files. As we are using the micro services environment, when we deployed the jar file on docker image it's occupying storage space (15MB) on docker. Is it possible, that you can reduce the size of jar (agent) file by removing the embedded jars.

**Comment by trask** [comment]
Hi @anveshgkumar, thanks for posting!  Yes, I think this will be good.  I need to break some pieces apart for Java 9 support anyways.

**Comment by anveshgkumar** [comment]
ok, great. Thanks @trask.

**Comment by trask** [comment]
Hi @anveshgkumar, embedded collector is now in separate jar file (under lib directory) and can be deleted if not needed.  Also, central collector https support is broken out into separate jar files that can be deleted if not needed.  See the latest snapshot release [glowroot-agent-0.10.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.3-SNAPSHOT).
