### ISSUE TITLE
Is issue 233 supposed to be in v0.10.0?  

### ISSUE THREAD

**Issue by john-keysight** [glowroot/glowroot#316]
In v0.10.0, I'm not seeing the "Agent display name" displayed in the title name as in v.0.09.29, per issue 233 which was resolved in v.0.09.29 snapshot.

In v0.10.0 I see this:
![image](https://user-images.githubusercontent.com/29761642/35528216-094178ee-04e2-11e8-9a2b-5556e1946526.png)

In 9.29 I saw this:
![image](https://user-images.githubusercontent.com/29761642/35528254-24615f5e-04e2-11e8-8de3-4508fde7912d.png)

**Comment by trask** [comment]
Hi @john-keysight, thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.10.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.1-SNAPSHOT).
