### ISSUE TITLE
How to remove agent from central UI

### ISSUE THREAD

**Issue by Sohailjp** [glowroot/glowroot#324]
Dear Glowroot Team,

I am using glow root version 0.10.0. Would like to know how to delete the agent from central UI. I believe this was there but now I am not able to find that option.

**Comment by trask** [comment]
Hi @Sohailjp, starting with v0.10.0, the agent dropdown only shows agents that were active during the selected period (see #155), so old agents automatically age out of the Central UI.  Does this work for you, or do you have a different reason for wanting to delete agents from the Central UI?  Thanks.

**Comment by Sohailjp** [comment]
Thank you very much for your quick response. 

Initially I set the wrong glowroot.agent.id and later on when I correct it, I can see booth in the agent dropdown.

The automatically age out is really a good feature. This will fulfil my requirement. Thank you very much again.
