### ISSUE TITLE
Providing acess to muliple users to one one or more specific roles at one time.

### ISSUE THREAD

**Issue by risrikanth** [glowroot/glowroot#329]
Hi Trask,

When we want to add more users to specific role or roles, it is taking long time to add users(more then 25) to specific role and we need to do multiple requests to backend.
Could you please enhance admin user page to add multiple users at a time to specific roles.

Thanks,
Srikanth

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
