### ISSUE TITLE
SQL Queries

### ISSUE THREAD

**Issue by gtnarg** [glowroot/glowroot#330]
Hi,

If I add custom instrumentation to a class/method, what is required in order to capture the queries executing within the scope of that method call?  Right now, it's indicating "No data for this time period" on the queries tab.

Thanks,
Grant

**Comment by trask** [comment]
Hi @gtnarg, thanks for posting!  Glowroot should capture queries executing within a transaction automatically.  Can you check in the profiles and see if the jdbc driver methods are being captured there?  If they are, can you post profile data (it would be very helpful to see call path that goes from your custom instrumentation to the jdbc driver).  Also, what jdbc driver are you using and what application server (if any)?  Thanks.

**Comment by gtnarg** [comment]
The application server is jetty 8 and the jdbc driver is jdts.

I'm seeing queries under the startup transaction so I know that is working correctly but when I create my own instrumentation there is no profile data.

![image](https://user-images.githubusercontent.com/1252704/37096438-94bd5f66-21e6-11e8-9967-b5676d5916f8.png)

**Comment by trask** [comment]
Hi @gtnarg, can you expand the profile in that screenshot (click on sun.misc.Unsafe.park)?

**Comment by gtnarg** [comment]
I see what the problem is - the database work is being done in another thread.

**Comment by gtnarg** [comment]
I have worked around the thread issue - now seeing queries - thanks :)

What is the purpose of the "Service calls" tab?  Nothing currently shows there.

**Comment by trask** [comment]
Hi @gtnarg, how were you starting/passing off work to the other thread?  Glowroot instruments `java.util.concurrent.Executor`, `java.util.concurrent.ExecutorService` and `java.util.concurrent.ForkJoinPool`.  Were you using `java.lang.Thread` directly, e.g. `new Thread(...).start()`, or some other mechanism?

Thanks for the kind words.

"Service calls" tab captures outbound http requests (e.g. calls to external services).

**Comment by gtnarg** [comment]
You were correct - I was using Thread(task).start().  I have changed it to use an ExecutorService and it sql queries are logged correctly.

I noticed that some of the breakdown in the response time view no longer appears in the graph for those things that occur in the auxilliary thread.  Is there any way to accomplish this?

![image](https://user-images.githubusercontent.com/1252704/37259391-fae500fa-255b-11e8-9d6c-710427950ce9.png)

Also, I'm using currently using this to tune some hibernate queries and would find it useful to see the "Queries" display for a specific slow trace.  I'm currently doing this by performing one query and filtering the start and end times so that I only have one request showing.  Just curious if I'm missing something.

Once again I have to say that I'm blown away by how simple and useful this tool is!

**Comment by trask** [comment]
Hi @gtnarg, I have created #348 to track the issue about charting the auxiliary thread breakdown.

Regarding viewing queries just for a single trace, I have wanted the same many times also, and this is now available in the latest release 0.10.6.

**Comment by gtnarg** [comment]
Hi @trask - that's great - thank you!

I have one small question regarding auxilliary threads.  If a new Thread is manually started (i.e., new Thread(...).start() ), is there a technical reason that you can't track it?  In my original case I had control over the code and could change it.  In other cases, I don't.

**Comment by trask** [comment]
Hi @gtnarg, I've been meaning to instrument `java.lang.Thread` for a while.  This is done now, and available in the latest snapshot release [glowroot-agent-0.10.7-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.7-SNAPSHOT).

**Comment by gtnarg** [comment]
Once again - thanks for making these changes.

Grant
