### ISSUE TITLE
[Feature] Ability to configure default heap dump location from admin.json or config.json

### ISSUE THREAD

**Issue by ReillyProcentive** [glowroot/glowroot#335]
Can you add the ability to configure a default location for heapdumps to go to either to admin.json or config.json? Our use case for this feature is that we have a file share mounted into many different Docker containers filesystems that we would like heapdumps to be put into. Allowing us to configure the default would reduce the risk that engineers would generate a heapdump in the wrong directory by mistake (which in Kubernetes land may require that they generate a new one in the correct directory as they might not have the appropriate permissions to open a shell to a container to move the file).

**Comment by trask** [comment]
Hi @ReillyProcentive, thanks for posting!  You can change the default heap dump location using the JVM arg `-XX:HeapDumpPath=<directory>`, does this address what you need?

**Comment by ReillyProcentive** [comment]
Hi @trask, that does work for us, thank you!
