### ISSUE TITLE
Glow root not working with WAS 8.5 / Java 6

### ISSUE THREAD

**Issue by stlpedro** [glowroot/glowroot#336]
Hi there,

the latest version 10.5 does not work with WAS 8.5 and JAVA 6. No errors are shown in the log, it just does not accept any connection. When I downgrade to 10.2 it works. Any version above 10.2 it does not work.

Any idea as to what could be wrong?

**Comment by trask** [comment]
Hi @stlpedro, thanks for reporting this!  I was able to reproduce also, and will look into it.

**Comment by stlpedro** [comment]
Thank you for your prompt replay and dedication to such as wonderful project. May God bless you with wisdom to continue this good work.

**Comment by trask** [comment]
Hi @stlpedro, this should be fixed now in the latest snapshot release [glowroot-agent-0.10.6-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.6-SNAPSHOT).  Thanks again for reporting it.
