### ISSUE TITLE
"Allocated Memory:" is not displaying any value

### ISSUE THREAD

**Issue by vgmonnet** [glowroot/glowroot#339]
env:
glowroot v0.10.4
websphere  v8.5.5.11

![image](https://user-images.githubusercontent.com/10453780/37586316-fde82058-2b81-11e8-99f2-b8baeaf11ef3.png)

**Comment by trask** [comment]
Hi @vgmonnet, thanks for reporting this!  Allocated memory per thread is not available under IBM JVM, but Glowroot is not supposed to display Allocated memory field when it is not available.  I've fixed this, hopefully should be less confusing now in the latest snapshot release [glowroot-agent-0.10.6-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.6-SNAPSHOT).

**Comment by vgmonnet** [comment]
thanks! now, it is not showing "Allocated Memory" for WebSphere.
