### ISSUE TITLE
about implementing https for UI part -- glowroot-central

### ISSUE THREAD

**Issue by vgmonnet** [glowroot/glowroot#341]
I have an existing signed cert - it can either be a x509 or pkcs#7. As per the documentation(https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation) you are asking for a private key and a pkcs#8 cert which is currently not available with me.

Is there any alter method you can suggest?

Thanks.

**Comment by vgmonnet** [comment]
@trask Sure. Let me check and update.

**Comment by trask** [comment]
Great to hear that!
