### ISSUE TITLE
Provide a way to check the health of central collectors

### ISSUE THREAD

**Issue by pavanie** [glowroot/glowroot#344]
For any load balancing option between clusters of central collectors, we need a way to check the health of collector status and at the least its database connection status. Can health check url be added to glowroot central collector?

**Comment by trask** [comment]
Hi @pavanie, thanks for requesting this!  The health check url `/health` (e.g. https://demo.glowroot.org/health) is available now in the latest snapshot release [glowroot-central-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.9-SNAPSHOT). When the `/health` url returns 200 OK, things are good.  When it returns anything else, things are bad.
