### ISSUE TITLE
Running glowroot test cases

### ISSUE THREAD

**Issue by anveshgkumar** [glowroot/glowroot#350]
I'm trying to run the test cases for glowroot (glowroot-webdriver-tests). While building the glowroot-webdriver-tests project (not skipping tests), results in build failure with compilation problems. As per my understanding, the webdriver-tests project runs in embeeded mode, we want to run the tests by pointing to our own cassandra instance. Any suggestions to move forward would be helpful.

**Comment by trask** [comment]
Hi @anveshgkumar, thanks for posting!

What build failure are you getting?

You can run the webdriver-tests against the central collector with `-Dglowroot.internal.webdriver.useCentral=true`.  For example, the travis build does this: https://github.com/glowroot/glowroot/blob/v0.10.6/build/travis-ci/build.sh#L169.

**Comment by trask** [comment]
Closing, but please re-open if you are still having any issue.  Thanks.
