### ISSUE TITLE
Is there any detailed documentation for Glowroot. Any link?

### ISSUE THREAD

**Issue by vipin0991** [glowroot/glowroot#352]
Is there any detailed documentation for Glowroot. Any link?

**Comment by trask** [comment]
Hi @vipin0991, thanks for posting!  The wiki (https://github.com/glowroot/glowroot/wiki) has installation documentation.  The UI itself has help text to explain some of the features.  And any kinds of questions are always welcome here and on the mailing list https://groups.google.com/forum/#!forum/glowroot.
