### ISSUE TITLE
ElasticSearch, more requests parameters than query required for investigation

### ISSUE THREAD

**Issue by hgomez** [glowroot/glowroot#353]
We're using Glowroot to track ES requests and noticed that only the 'query part' is captured by glowroot.

Here is a typical request, there is query but also from, size, _source, sort and aggregations

    {
      "from" : 0,
      "size" : 100,
      "query" : {
        "bool" : {
          "must" : [
            {
              "match_all" : {
                "boost" : 1.0
              }
            }
          ],
          "filter" : [
            {
              "bool" : {
                "must" : [
                  {
                    "term" : {
                      "isMainBranch" : {
                        "value" : "true",
                        "boost" : 1.0
                      }
                    }
                  },
                  {
                    "bool" : {
                      "must_not" : [
                        {
                          "exists" : {
                            "field" : "resolution",
                            "boost" : 1.0
                          }
                        }
                      ],
                      "disable_coord" : false,
                      "adjust_pure_negative" : true,
                      "boost" : 1.0
                    }
                  },
                  {
                    "bool" : {
                      "disable_coord" : false,
                      "adjust_pure_negative" : true,
                      "boost" : 1.0
                    }
                  },
                  {
                    "has_parent" : {
                      "query" : {
                        "bool" : {
                          "filter" : [
                            {
                              "bool" : {
                                "should" : [
                                  {
                                    "term" : {
                                      "allowAnyone" : {
                                        "value" : true,
                                        "boost" : 1.0
                                      }
                                    }
                                  }
                                ],
                                "disable_coord" : false,
                                "adjust_pure_negative" : true,
                                "boost" : 1.0
                              }
                            }
                          ],
                          "disable_coord" : false,
                          "adjust_pure_negative" : true,
                          "boost" : 1.0
                        }
                      },
                      "parent_type" : "authorization",
                      "score" : false,
                      "ignore_unmapped" : false,
                      "boost" : 1.0
                    }
                  }
                ],
                "disable_coord" : false,
                "adjust_pure_negative" : true,
                "boost" : 1.0
              }
            }
          ],
          "disable_coord" : false,
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      },
      "_source" : false,
      "sort" : [
        {
          "project" : {
            "order" : "asc",
            "missing" : "_first"
          }
        },
        {
          "filePath" : {
            "order" : "asc",
            "missing" : "_first"
          }
        },
        {
          "line" : {
            "order" : "asc",
            "missing" : "_first"
          }
        },
        {
          "severityValue" : {
            "order" : "desc",
            "missing" : "_first"
          }
        },
        {
          "key" : {
            "order" : "asc",
            "missing" : "_first"
          }
        }
      ],
      "aggregations" : {
        "severities" : {
          "global" : { },
          "aggregations" : {
            "severities_filter" : {
              "filter" : {
                "bool" : {
                  "must" : [
                    {
                      "match_all" : {
                        "boost" : 1.0
                      }
                    },
                    {
                      "term" : {
                        "isMainBranch" : {
                          "value" : "true",
                          "boost" : 1.0
                        }
                      }
                    },
                    {
                      "bool" : {
                        "must_not" : [
                          {
                            "exists" : {
                              "field" : "resolution",
                              "boost" : 1.0
                            }
                          }
                        ],
                        "disable_coord" : false,
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    },
                    {
                      "bool" : {
                        "disable_coord" : false,
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    },
                    {
                      "has_parent" : {
                        "query" : {
                          "bool" : {
                            "filter" : [
                              {
                                "bool" : {
                                  "should" : [
                                    {
                                      "term" : {
                                        "allowAnyone" : {
                                          "value" : true,
                                          "boost" : 1.0
                                        }
                                      }
                                    }
                                  ],
                                  "disable_coord" : false,
                                  "adjust_pure_negative" : true,
                                  "boost" : 1.0
                                }
                              }
                            ],
                            "disable_coord" : false,
                            "adjust_pure_negative" : true,
                            "boost" : 1.0
                          }
                        },
                        "parent_type" : "authorization",
                        "score" : false,
                        "ignore_unmapped" : false,
                        "boost" : 1.0
                      }
                    }
                  ],
                  "disable_coord" : false,
                  "adjust_pure_negative" : true,
                  "boost" : 1.0
                }
              },
              "aggregations" : {
                "severities" : {
                  "terms" : {
                    "field" : "severity",
                    "size" : 15,
                    "min_doc_count" : 1,
                    "shard_min_doc_count" : 0,
                    "show_term_doc_count_error" : false,
                    "order" : [
                      {
                        "_count" : "desc"
                      },
                      {
                        "_term" : "asc"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "types" : {
          "global" : { },
          "aggregations" : {
            "types_filter" : {
              "filter" : {
                "bool" : {
                  "must" : [
                    {
                      "match_all" : {
                        "boost" : 1.0
                      }
                    },
                    {
                      "term" : {
                        "isMainBranch" : {
                          "value" : "true",
                          "boost" : 1.0
                        }
                      }
                    },
                    {
                      "bool" : {
                        "must_not" : [
                          {
                            "exists" : {
                              "field" : "resolution",
                              "boost" : 1.0
                            }
                          }
                        ],
                        "disable_coord" : false,
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    },
                    {
                      "bool" : {
                        "disable_coord" : false,
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    },
                    {
                      "has_parent" : {
                        "query" : {
                          "bool" : {
                            "filter" : [
                              {
                                "bool" : {
                                  "should" : [
                                    {
                                      "term" : {
                                        "allowAnyone" : {
                                          "value" : true,
                                          "boost" : 1.0
                                        }
                                      }
                                    }
                                  ],
                                  "disable_coord" : false,
                                  "adjust_pure_negative" : true,
                                  "boost" : 1.0
                                }
                              }
                            ],
                            "disable_coord" : false,
                            "adjust_pure_negative" : true,
                            "boost" : 1.0
                          }
                        },
                        "parent_type" : "authorization",
                        "score" : false,
                        "ignore_unmapped" : false,
                        "boost" : 1.0
                      }
                    }
                  ],
                  "disable_coord" : false,
                  "adjust_pure_negative" : true,
                  "boost" : 1.0
                }
              },
              "aggregations" : {
                "types" : {
                  "terms" : {
                    "field" : "type",
                    "size" : 10,
                    "min_doc_count" : 1,
                    "shard_min_doc_count" : 0,
                    "show_term_doc_count_error" : false,
                    "order" : [
                      {
                        "_count" : "desc"
                      },
                      {
                        "_term" : "asc"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }

Would it be possible to catch them all in ES, they are highly required for investigations.

Thanks

**Comment by trask** [comment]
Hi @hgomez, thanks for posting!  The full query should be captured now in the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT).

**Comment by hgomez** [comment]
Thanks  @trask, you rocks !
