### ISSUE TITLE
Slow traces chart with small & very large values

### ISSUE THREAD

**Issue by bit-ionutursuleanu** [glowroot/glowroot#354]
Hi,

Is it possible to have a vertical selection for the slow traces chart? When there is a very slow transaction all the others are at the base of the chart...and empty space between

Thanks,
Ionut

**Comment by trask** [comment]
Hi @bit-ionutursuleanu, thanks for requesting this!  I've run into this issue also.  Check out the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT) (if you are using the central collector then [glowroot-central-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.9-SNAPSHOT)).  Now if you drag up/down it will zoom in on "response time" range.  If you drag left/right it will (still) zoom in on time range.  You can also give this feature a spin on the updated demo site https://demo.glowroot.org/transaction/traces?transaction-type=Web.
