### ISSUE TITLE
accounting for all threads in the jvm

### ISSUE THREAD

**Issue by manmathan** [glowroot/glowroot#355]
it seems glowroot is not accounting/tracking all threads in the vm, and thereby not all activity is shown.

**Comment by trask** [comment]
Hi @manmathan, thanks for posting!  Glowroot only captures transactions it knows about (e.g. Servlets, Quartz, JMS).  You can capture additional transactions by adding your own [instrumentation](https://glowroot.org/instrumentation.html).  Is the activity that is not being captured part of a servlet request, or part of something else?  If you can provide more details that would be great.  Thanks.

**Comment by manmathan** [comment]
But should it not be possible to capture activity of all JVM threads maybe filtering out JVM internal threads  (if it needed to filter them out) and somehow account for which class methods are using cpu?

**Comment by trask** [comment]
Hi @manmathan, by merging instrumentation and profiling, Glowroot can provide a lot more context compared to profiling alone.  What activity are you seeing that Glowroot is not capturing?  I'm curious if it's something Glowroot should know about / be capturing already.

**Comment by trask** [comment]
Closing, but feel free to re-open with if you want to continue discussing.  Thanks.
