### ISSUE TITLE
How to test glowroot server on Tomcat?

### ISSUE THREAD

**Issue by Vidyack** [glowroot/glowroot#356]
Hi,
I am totally new to glowroot and tomcat.I want Configure the built Glowroot agent with any j2ee web application (use sample application from tomcat). For installation I have followed the instruction of followed link []( https://github.com/glowroot/glowroot/blob/master/README.md).In that they have mentioned that "Add -javaagent:path/to/glowroot.jar to your JVM args" where to add this line tomcat.I am not getting how to do this one.But, I can access the glowroot with localhost:4000 port. How to test any j2ee web application using tomcat? Can you suggest me any tutorial to study about glowroot?

**Comment by vijaynet10** [comment]
Hi i have completed below steps 
1.Download and unzip glowroot-0.12.3-dist.zip
2.Add -javaagent:path/to/glowroot.jar to your application's JVM args [where are my application server's JVM args?]
3.Check that the user account that runs the JVM has write access to the glowroot folder
4.Start your application

but i cant start the application.please help me to configure
