### ISSUE TITLE
Option or configuration to delete or filter old agents

### ISSUE THREAD

**Issue by webjoel** [glowroot/glowroot#357]
I have already seen that there are other issues (#332, #135, #324, #155) on this subject, where an expiration time has been set for old agents to stop appearing for a while, and I also noticed if I am not mistaken that the expiration time of the agent is in 7 days (check attached image).

![captura de tela de 2018-04-12 11-52-56](https://user-images.githubusercontent.com/1946348/38687641-85743f2e-3e4d-11e8-85d6-894c2e9cca98.png)

With this, I have some suggestions:

1 - Configure in the Storage option an expiration in days or hours of agents not sending data.

2 - Option to remove old agents that are not sending data from certain hours.

3 - In the "Transactions, Errors, JVM and Synthetic" menus, make the selected period filter the list of agents.

I am requesting this because I have agents within AWS EC2 instances and every night we disconnect our instances and start again in the morning, so the agent id changes, and the old one becomes obsolete.

**Comment by trask** [comment]
Hi @webjoel, thanks for posting!  If you are using central collector v0.10.0 or later, you should be seeing the behavior you described above in (3).  However, the filtering is only at the daily level, see comment https://github.com/glowroot/glowroot/issues/155#issuecomment-362442726.  Is this what you are seeing?  Would it be less confusing if I implemented https://github.com/glowroot/glowroot/issues/155#issuecomment-364684322?  Thanks.

**Comment by webjoel** [comment]
I'm using Glowroot 0.10.5.

In my opinion, at a minimum this behavior should be parameterized in Administration, with default behavior being: 24h, preventing other users from being confused by this change.

But the most correct would be to display the agents according to the selected period, being the same behavior of the "Ad hoc report", just like issue #332.

**Comment by trask** [comment]
Hi @webjoel, the latest snapshot release [glowroot-central-0.10.12-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.12-SNAPSHOT) now uses 5-minute precision to calculate agent activity when populating the dropdown. This new 5-min precision is only captured going forward after upgrading to the latest version, so there will still be 24-hour rounding errors when viewing a time range prior to upgrade.
