### ISSUE TITLE
Error on switching agent with open alert configuration

### ISSUE THREAD

**Issue by webjoel** [glowroot/glowroot#358]
When switching agent in the drop-down list with the configuration of the alert in edit mode error occurs according to the image below:

![captura de tela de 2018-04-12 13-44-32](https://user-images.githubusercontent.com/1946348/38693017-00159c1a-3e5c-11e8-9866-f4c97b11dc01.png)

Steps for simulation:

1 - Select agent from the dropdown list;
2 - Open Configuration;
3 - Select Alerts;
4 - Edit an alert;
5 - Change the agent from the drop-down list.

If click in "Return to list Alerts", it's works fine.

**Comment by trask** [comment]
Hi @webjoel, thanks for reporting this!  It is fixed now in the latest snapshot release [glowroot-central-0.10.8-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.8-SNAPSHOT).
