### ISSUE TITLE
Implement central collector and UI to manage and view data across many servers

### ISSUE THREAD

**Issue by trask** [glowroot/glowroot#36]
Slowly refactoring existing collector and UI to support both local "fat agent" deployment, as well as central collector / central UI deployment for managing and viewing data across many servers.

* 65da9a1ef676c0603831a6ac1e7b977e7566f446 Major restructuring for remote collection
* 68d68c00c6560530c3d1c3514cf11ff3e3d0b4f2 More major restructuring for remote collection
* 06c9696da7b10a84fcc648f8a6da6b914edb27da Use protobuf for remote collection
* d377759947b3714bc10f686a64ce6048d994048c Add server id throughout
* 647b21e796e804e802e5fa350ab573086c6c8439 Introduce gRPC
* 221587036c3aac0034ad39f0d0069e986a60fd96 More restructuring for remote collection
* 083c4a352e9aadd8ada22e1fee6d62562ba625df Support rolling up to server groups
* 300338eae33e2d16247d5a78c1a1b740b7d09ff9 And more restructuring for remote collection

**Comment by trask** [comment]
dbe33fe43d6bf8298ff5cfd669d18d7ba43d34aa Yet more restructuring for remote collection
6c84bbffc378d83bac99e33d3ef618348c775e5e Generate protobuf/grpc classes during build
70faca468a3f28d37b9a48593b5dd43a49ed684c And yet more restructuring for remote collection

**Comment by trask** [comment]
6e88742440d5ac0a5d18d45cd67d9ca70a0d71b0 Initial central implementation
30eff38ca6043f6d0b47bde6666814605fbfc4c9 Switch central to Cassandra (Part I)

**Comment by trask** [comment]
fc249c26bfd7487fe33b699463d43ce5db77809d Cassandra storage impl for central (Part II)
ef7b7668d2920abdc1262aa81c01e203a5a50233 Cassandra storage impl for central (Part III)
67aecdb13f87e2bd0e8812d3298737144437d530 Handle connection failures to central

**Comment by trask** [comment]
fecc613736cc1d7b4482a2d1fea880d0d59342e4 More central work
dc76f9dc16b6ee8f48e508198e3b320ea50d11d6 And more central work
e498a8c740547acd9825200cea4d1b3180b3ce28 Still more central work
71bf37da8d1b537b6448b00bb42a86c5819da3c6 Central time-based rollups
5d7a09e753f15d2160a93cae54890e63c5355348 Implement central live trace view

**Comment by jmatis** [comment]
would there be a possibility of adding a 'group' of agents?  and some kind of 'overall' view of this group? 
App I administer consists of various  groups of services (api, rest, web, ... ) and it would be great to see how is each of theses groups doing because high response time on each group suggests different issue in the app

it would be also amazing to have some kind of 'iconized' view to see overall status of all agents within one group. (i'd gladly offer help but i'm affraid i'm not skilled enough )
