### ISSUE TITLE
Turn off Web Transaction

### ISSUE THREAD

**Issue by gtnarg** [glowroot/glowroot#362]
I'm trying instrument a specific class and configuring it to use a new transaction type.  Since it is only accessed as part of a web transaction it only appears under a "Web" transaction.  Is there a way to turn off the default web transactions so I only see my instrumented class/ transaction type - or am I not understanding something more fundamental.

Thanks,
Grant

**Comment by trask** [comment]
Hi @gtnarg, thanks for posting!  Try setting the transaction type under "Optional transaction overrides" (lower down on the instrumentation page).  The transaction will still capture all the Web stuff, but it should then be categorized under your new transaction type.  Let me know if this is what you are looking for.  Thanks.

**Comment by gtnarg** [comment]
Works like a charm - thanks!
