### ISSUE TITLE
SQL Queries (continued)

### ISSUE THREAD

**Issue by aro-tech** [glowroot/glowroot#364]
Hi, @trask.

Since issue #330 is closed, I decided to open a new issue which is similar.  I got the latest stable version (0.10.8) of glowroot and I still have the issue, which is that the SQL queries and web service calls triggered asynchronously via javax.ejb.Timeout in wildfly 10.1.0 do not show up in glowroot in the "Web" transactions (BTW, there also is no data at all in the "Startup" transactions despite the fact that the app in question executes a lot of queries on startup, triggered via a servlet's init() method).

Thanks in advance, and thanks for what is already an awesome tool.

**Comment by trask** [comment]
Hi @aro-tech, thanks for reporting this!  I have added support for EJB Timers in the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT).  Those transaction should now show up under "Background" transactions.  I think I have also resolved the issue with Glowroot not always capturing Servlet init() methods in this snapshot release.
