### ISSUE TITLE
Regarding the "other" transactions

### ISSUE THREAD

**Issue by monkiki** [glowroot/glowroot#365]
Hi,

I'm trying to use Glowroot in my web application but I always see an "other" transactions in the graphs.  It's about the 70-90% of the graph and I wonder how can I know how can I get more information about this. I see the time used by servlets, Hibernate, and other stuff but it's very odd that almost all the time is consumed by "other" stuff.

Using last Glowroot v0.10.8 release with embedded collector.

Thanks in advance.

**Comment by trask** [comment]
Hi @monkiki, thanks for posting!  That's when I go look in the continuous profiling tab.  You can filter out profiling samples that are running hibernate code using `-hibernate` (e.g. https://demo.glowroot.org/transaction/thread-profile?transaction-type=Web&filter=-hibernate) to see what's left.  If you don't have much server load and need more profiling samples, you can reduce the profiling interval under Configuration > Transactions.  Let me know if this gets you what you need.

**Comment by monkiki** [comment]
I'm not sure I we're talking about the same thing. This is the graph from demo:
![image](https://user-images.githubusercontent.com/130590/39288376-0818e3a0-4928-11e8-834b-66e418f48a9d.png)

And this the the graph in my web app:
![image](https://user-images.githubusercontent.com/130590/39288396-1501e738-4928-11e8-8138-41bc2c3b9862.png)

In the demo, the grey value (labeled as "Other") is tiny, but in my app this is huge.

**Comment by trask** [comment]
Hi @monkiki, In the demo site, I have added instrumentation for "thymeleaf view", see https://demo.glowroot.org/config/instrumentation?v=10080f4227da91edcd730bfc1a35851f318aa588.  Without this "thymeleaf view" instrumentation, all the yellow "thymeleaf view" section of the demo chart would be gray "Other" like in your chart.

When I see lots of gray "Other" in the chart, I go and look at the continuous profiling tab to work out what's taking up lots of time other than those things that are already instrumented (jdbc/etc).

[there's another possibility if your app is doing most of the work in other threads, are you seeing lots of time in "Breakdown (Auxiliary Thread)", e.g.[https://github.com/glowroot/glowroot/issues/330#issuecomment-372156790](https://github.com/glowroot/glowroot/issues/330#issuecomment-372156790)?]

**Comment by monkiki** [comment]
Most time is included in the main thread:
![image](https://user-images.githubusercontent.com/130590/39300952-c987af42-494d-11e8-9b8b-56c2e70d306c.png)

I will try you advice about the continuous profiling tab and let's see if improves the graph.

Thanks.

**Comment by trask** [comment]
Hi @monkiki, did this work out for you, or maybe I was not understanding your issue/question?  Thanks.

**Comment by monkiki** [comment]
Sorry, I had to do more test but I think the issue is solved.

Thanks!

**Comment by abhishek-das-gupta** [comment]
Hi @trask , I started using Glowroot recently and I also see a lot of time spent in "Other" in all transactions.  So wdym by "continuous profiling tab"? . Can you please elaborate? Thank you!

> When I see lots of gray "Other" in the chart, I go and look at the continuous profiling tab to work out what's taking up lots of time other than those things that are already instrumented (jdbc/etc).
