### ISSUE TITLE
Exception on JBoss 5.1 startup

### ISSUE THREAD

**Issue by aro-tech** [glowroot/glowroot#372]
Not a blocking issue (and similar to issue 370), but for info, I was using the 0.10.9-SNAPSHOT release you pointed me to for the fix of my previously entered issue, and one time, on startup of JBoss 5.1, (JDK 1.6.0_30_64), I got the following exception : 

2018-05-02 09:12:38.123 INFO  org.glowroot - Glowroot version: 0.10.9-SNAPSHOT, commit da7843f9a9, built 2018-04-29 06:34:19 +0000
2018-05-02 09:12:38.128 INFO  org.glowroot - Java version: 1.6.0_21
2018-05-02 09:12:39.418 INFO  org.glowroot - plugins loaded: Cassandra Plugin, EJB Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2018-05-02 09:12:54.778 ERROR org.glowroot.agent.weaving.Weaver - deadlock detected in class weaving, please report to the Glowroot project:

"main" #31
   java.lang.Thread.State: RUNNABLE
        org.jboss.net.protocol.file.Handler.openConnection(Handler.java:40)
        java.net.URL.openConnection(URL.java:945)
        sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:66)
        sun.net.www.protocol.jar.Handler.openConnection(Handler.java:24)
        java.net.URL.openConnection(URL.java:945)
        java.net.URL.openStream(URL.java:1010)
        org.glowroot.agent.shaded.com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
        org.glowroot.agent.shaded.com.google.common.io.ByteSource.read(ByteSource.java:285)
        org.glowroot.agent.shaded.com.google.common.io.Resources.toByteArray(Resources.java:98)
        org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClass(AnalyzedWorld.java:274)
        org.glowroot.agent.weaving.AnalyzedWorld.getOrCreateAnalyzedClass(AnalyzedWorld.java:224)
        org.glowroot.agent.weaving.AnalyzedWorld.getSuperClasses(AnalyzedWorld.java:181)
        org.glowroot.agent.weaving.AnalyzedWorld.getAnalyzedHierarchy(AnalyzedWorld.java:138)
        org.glowroot.agent.weaving.ClassAnalyzer.<init>(ClassAnalyzer.java:115)
        org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:233)
        org.glowroot.agent.weaving.Weaver.weave(Weaver.java:146)
        org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
        org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
        sun.instrument.TransformerManager.transform(TransformerManager.java:169)
        sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
        java.lang.ClassLoader.defineClass1(Native Method)
        java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
        java.lang.ClassLoader.defineClass(ClassLoader.java:616)
        java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        java.security.AccessController.doPrivileged(Native Method)
        java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        -  locked org.jboss.bootstrap.NoAnnotationURLClassLoader@8523a0
        java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        java.lang.Class.getDeclaredConstructors0(Native Method)
        java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
        java.lang.Class.getConstructor0(Class.java:2699)
        java.lang.Class.newInstance0(Class.java:326)
        java.lang.Class.newInstance(Class.java:308)
        org.jboss.net.protocol.URLStreamHandlerFactory.createURLStreamHandler(URLStreamHandlerFactory.java:188)
        java.net.URL.getURLStreamHandler(URL.java:1107)
        java.net.URL.<init>(URL.java:393)
        java.net.URL.<init>(URL.java:283)
        org.jboss.net.protocol.URLStreamHandlerFactory.preload(URLStreamHandlerFactory.java:126)
        org.jboss.bootstrap.AbstractServerImpl.internalInitURLHandlers(AbstractServerImpl.java:300)
        org.jboss.bootstrap.AbstractServerImpl.initURLHandlers(AbstractServerImpl.java:268)
        org.jboss.bootstrap.AbstractServerImpl.doInit(AbstractServerImpl.java:207)
        org.jboss.bootstrap.AbstractServerImpl.init(AbstractServerImpl.java:173)
        org.jboss.bootstrap.AbstractServerImpl.init(AbstractServerImpl.java:143)
        org.jboss.Main.boot(Main.java:218)
        org.jboss.Main$1.run(Main.java:556)
        java.lang.Thread.run(Thread.java:619)

"Glowroot-Init-UI" #30
   java.lang.Thread.State: BLOCKED
        org.jboss.net.protocol.file.Handler.openConnection(Handler.java:40)
        -  blocked on org.jboss.bootstrap.NoAnnotationURLClassLoader@8523a0
        java.net.URL.openConnection(URL.java:945)
        sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:66)
        sun.net.www.protocol.jar.Handler.openConnection(Handler.java:24)
        java.net.URL.openConnection(URL.java:945)
        java.net.URL.openStream(URL.java:1010)
        org.glowroot.agent.shaded.com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
        org.glowroot.agent.shaded.com.google.common.io.ByteSource.read(ByteSource.java:285)
        org.glowroot.agent.shaded.com.google.common.io.Resources.toByteArray(Resources.java:98)
        org.glowroot.agent.weaving.AnalyzedWorld.createAnalyzedClass(AnalyzedWorld.java:274)
        org.glowroot.agent.weaving.AnalyzedWorld.getOrCreateAnalyzedClass(AnalyzedWorld.java:224)
        org.glowroot.agent.weaving.AnalyzedWorld.getSuperClasses(AnalyzedWorld.java:181)
        org.glowroot.agent.weaving.AnalyzedWorld.getAnalyzedHierarchy(AnalyzedWorld.java:138)
        org.glowroot.agent.weaving.ClassAnalyzer.<init>(ClassAnalyzer.java:115)
        org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:233)
        org.glowroot.agent.weaving.Weaver.weave(Weaver.java:146)
        org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
        org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
        sun.instrument.TransformerManager.transform(TransformerManager.java:169)
        sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
        java.util.regex.Pattern$CharProperty.complement(Pattern.java:3335)
        java.util.regex.Pattern.clazz(Pattern.java:2278)
        java.util.regex.Pattern.sequence(Pattern.java:1818)
        java.util.regex.Pattern.expr(Pattern.java:1752)
        java.util.regex.Pattern.compile(Pattern.java:1460)
        java.util.regex.Pattern.<init>(Pattern.java:1133)
        java.util.regex.Pattern.compile(Pattern.java:823)
        java.lang.String.replaceAll(String.java:2189)
        org.glowroot.agent.shaded.io.netty.util.internal.PlatformDependent.isOsx0(PlatformDependent.java:950)
        org.glowroot.agent.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:75)
        org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:259)
        org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
        org.glowroot.agent.shaded.io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
        org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
        org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
        org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
        org.glowroot.agent.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        org.glowroot.agent.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
        org.glowroot.agent.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
        org.glowroot.agent.shaded.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
        org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
        org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
        org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
        org.glowroot.agent.embedded.shaded.org.glowroot.ui.HttpServer.<init>(HttpServer.java:85)
        org.glowroot.agent.embedded.shaded.org.glowroot.ui.UiModule.createUiModule(UiModule.java:219)
        org.glowroot.agent.embedded.shaded.org.glowroot.ui.CreateUiModuleBuilder.build(CreateUiModuleBuilder.java:471)
        org.glowroot.agent.embedded.init.EmbeddedAgentModule.initEmbeddedServer(EmbeddedAgentModule.java:265)
        org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit$1$1.run(EmbeddedGlowrootAgentInit.java:82)
        java.lang.Thread.run(Thread.java:619)

When I restarted JBoss the problem disappeared.

**Comment by trask** [comment]
Hi @aro-tech, thanks for reporting this!  It should be fixed now in the latest snapshot release [glowroot-agent-0.10.9-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.9-SNAPSHOT).
