### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by onurmamati** [glowroot/glowroot#373]
Hi,

I have some questions about glowroot agent.

1 - Is it possible to trace only some of the applications in a server? For example I have 5 war 3 jar in my tomcat but I want to trace only 2 war and 1 jar. How can I configure it? Is it possible without changing source code of applications?

2 - Is distributed tracing available? If not, are you considering adding this feature to Glowroot? 

3 - I want to instrument all java methods transactionally except java, sun, spring, tomcat methods. How can I configure and filter them?

Thanks for help.

**Comment by akash-shindhe86** [comment]
@trask My I know how to enable continuous profiling?
