### ISSUE TITLE
Agent is unable to connect to Collector

### ISSUE THREAD

**Issue by mani8884** [glowroot/glowroot#375]
We are using glowroot version 0.10.4 for collector and agent. As per the below link, 
https://github.com/glowroot/glowroot/issues/315, we have removed the "lib" directory. When starting agent with out "lib" directory, its unable to connect to Collector and we keep getting the below error.

WARN  o.g.agent.central.CentralConnection - unable to establish connection with the central collector http://collectoripaddress:8181 (will keep trying...): UNKNOWN

Could you please fix this issue and let me know if you need more information. Thanks for the help.

**Comment by trask** [comment]
Hi @mani8884, I just checked locally and working for me on 0.10.4 without "lib" directory.  Can you provide full agent logs when you run with "lib" directory and without "lib" directory?  Thanks.

**Comment by mani8884** [comment]
Hi Transk,

Thanks for the quick response. There was typo in the glowroot.properties file. We are able to run it now with out the lib directory. Thanks.

**Comment by trask** [comment]
Great, I'm glad to hear this is working now.
