### ISSUE TITLE
Debug Agent Module

### ISSUE THREAD

**Issue by mani8884** [glowroot/glowroot#377]
Hi Trask,

I am trying to debug agent module using  java -javaagent:glowroot-agent-0.10.4.jar on my windows command line prompt but I am getting the following message. Please help me in this. THanks.

C:\Users\git\git_0.10.4\apm_glowroot\glowroot\agent\dist>java -javaagent:C:\Users\git\git_0.
10.4\apm_glowroot\glowroot\agent\dist\target\glowroot-agent-0.10.4.jar -jar target\glowroot-agent-
0.10.4.jar
2018-05-03 22:27:31.399 INFO  org.glowroot - Glowroot version: 0.10.4, built 2018-05-04 02:30:06 +00
00
2018-05-03 22:27:31.401 INFO  org.glowroot - Java version: 1.8.0_144
2018-05-03 22:27:32.350 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Elasticsearch Plugin,
 Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-
RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin
, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
Error: Could not find or load main class org.glowroot.agent.ToolMain

**Comment by trask** [comment]
Hi @mani8884, I'm not clear what you are trying to do. Why are you using `-jar target\glowroot-agent-0.10.4.jar`? Thanks.

**Comment by mani8884** [comment]
Hi Trask,

I am trying to debug the Agent module and see how it is connecting to the cluster line by line.  
If I try to run java -javaagent:glowroot-agent-0.10.4.jar, I am getting the following message. 
C:\Users\git\git_restapi\pm_glowroot\glowroot\agent\dist\target>java -javaagent:glowroot-agent
-0.10.4.jar
2018-05-04 08:32:49.475 INFO  org.glowroot - Glowroot version: 0.10.4, built 2018-05-04 01:23:49 +00
00
2018-05-04 08:32:49.477 INFO  org.glowroot - Java version: 1.8.0_144
2018-05-04 08:32:59.643 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Elasticsearch Plugin,
 Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-
RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin
, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.

**Comment by mani8884** [comment]
Hi Trask,

I am trying to debug the Agent module and see how it is connecting to the cluster line by line.  
If I try to run java -javaagent:glowroot-agent-0.10.4.jar, I am getting the following message. 
C:\Users\git\git_restapi\pm_glowroot\glowroot\agent\dist\target>java -javaagent:glowroot-agent
-0.10.4.jar
2018-05-04 08:32:49.475 INFO  org.glowroot - Glowroot version: 0.10.4, built 2018-05-04 01:23:49 +00
00
2018-05-04 08:32:49.477 INFO  org.glowroot - Java version: 1.8.0_144
2018-05-04 08:32:59.643 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Elasticsearch Plugin,
 Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, Java HTTP Server Plugin, JAX-
RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin
, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.

**Comment by trask** [comment]
Hi @mani8884, if you want to debug the agent itself, I recommend attaching a remote debugger, e.g. run your application as normal with glowroot agent, but add the following JVM args (in same place where you are adding `-javaagent:path/to/glowroot.jar`):
```
-Xdebug -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=y
```

The `suspend=y` is important, it will make the JVM pause so you can attach the debugger before Glowroot connects to the central collector.

**Comment by mani8884** [comment]
Thanks Trask. It worked. Appreciate your help :)

**Comment by trask** [comment]
:thumbsup:
