### ISSUE TITLE
Transaction name rollup

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#379]
Hi,

Is it possible to have roll up functionality for transaction name? Usually, a web service looks like this(only the last part, method identifier, of the URI is different):

restapi/invoice/list
restapi/invoice/create
restapi/invoice/print

restapi/order/list
restapi/order/create
restapi/order/print

Thanks,
Ionuț

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
