### ISSUE TITLE
Percents confusing in JVM Gauges

### ISSUE THREAD

**Issue by webjoel** [glowroot/glowroot#380]
The percents stay confusing on periods change, see:

24 horas:
![glowroot_24](https://user-images.githubusercontent.com/1946348/39700694-8eb9b100-51d4-11e8-8c97-6180bc195153.png)
8 horas:
![glowroot_8](https://user-images.githubusercontent.com/1946348/39700697-9361a384-51d4-11e8-99f6-e60541d50de8.png)
30 minutos
![glowroot_030](https://user-images.githubusercontent.com/1946348/39700700-97905144-51d4-11e8-8440-4a8cff008125.png)

Why is happend?

Glowroot version 0.10.8-SNAPSHOT, commit a5b22e5ac7, built 2018-04-13 02:08:54 +0000

**Comment by trask** [comment]
Hi @webjoel, thanks for posting!  Are you referring to the scale?  Maybe I need to move the scale into the label where it would be more prominently displayed, e.g.

![image](https://user-images.githubusercontent.com/218610/39737940-0f8361d8-523d-11e8-925e-784adb669221.png)

**Comment by webjoel** [comment]
Actually the problem is the vertical percentages, it is the same graph with different time interval and they are with different maximum percentages, example: 80, 30, 60. It is confusing, for example process CPU load, red line in the above images, at 8:25 am, the processing peak was 75, 25, or 50 ??

**Comment by webjoel** [comment]
Another question: why do scales change between changes in periods?

In my opinion the numbers should remain the same in periodic changes, that is, if the processing of my CPU reached 80% in the last 24 hours, it should also appear in the last 8 hours if it is within the period.

Is it possible to better explain how this graph works, scales, percentages?

**Comment by webjoel** [comment]
This example is possible see what average value are pratically identical, but the percents (vertical graphic) are very different:
![1_5_pm](https://user-images.githubusercontent.com/1946348/40115011-63898722-58e5-11e8-9eb5-7d17d9c5612f.png)
![24_h](https://user-images.githubusercontent.com/1946348/40115015-68b89df0-58e5-11e8-8f80-7a4605f11807.png)

**Comment by webjoel** [comment]
v0.10.10 milestone ??

**Comment by trask** [comment]
Yep, [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT), or if you are running central collector [glowroot-central-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.10-SNAPSHOT).

**Comment by webjoel** [comment]
Ok, is that a milestone has not been defined here.. hehe

**Comment by trask** [comment]
Oh! I missed the emoji reaction above. Thanks for reporting this!
