### ISSUE TITLE
glowroot central: Limit users to certain "projects"

### ISSUE THREAD

**Issue by adrianbader** [glowroot/glowroot#390]
It would be very great, if we could assign "projects" to users or roles. With "projects" I mean the _rollup id_ portion of the` agent.id`.
This would be useful if a central glowroot is used for multiple projects to support multitenancy. Are the plans for this? Or is it already possible somehow?

**Comment by trask** [comment]
Hi @adrianbader, thanks for posting! You can assign permissions to roles at the rollup level, does that get you what you are looking for?

**Comment by adrianbader** [comment]
Yes, this sounds very good. Hmm, in this case I missed where to setup this. I will check. Is it possible in the Web UI?

**Comment by trask** [comment]
Yes, check out Administrator > Roles, and post back if anything doesn't make sense.

**Comment by adrianbader** [comment]
Oh, yes, I see it. It is amazing. Thanks for your work! I think soon, there is no reason to use NewRelic :)
