### ISSUE TITLE
Ability to configure instrumentation in config.json and push changes to central

### ISSUE THREAD

**Issue by aoganesi** [glowroot/glowroot#402]
Hi,

Would really like to start by acknowledging what an amazing tool glowroot is. We recently started using it and are finding it to be very powerful and easy to use at the same time. 

My question pertains to the configuration mode of instrumentation for our agents. We would like to maintain instrumentation configuration in the code (we currently tried to do it in config.json) and deploy changes whenever we deploy updates to our software to different client sites (that way, as method names change with refactoring, etc ... we maintain a consistent set of instrumentation configuration that matches the code).

Is there a way to ensure that instrumentation configuration in config.json always overrides the settings in central? Currently system behavior is different depending on whether agent.id exists in central or not (see your quote from another issue below ). Is there possibly another approach to ensure the same instrumentation configuration (other than putting in in config.json and redistributing it with our software)?

Would greatly appreciate any suggestions.

Tony

>  if the agent.id does not exist yet in glowroot central, the configuration from config.json is pushed to glowroot central for that agent.id. If the agent.id already exists, then the configuration stored in glowroot central will override whatever is in the config.json file (and will update the config.json file to match what is in glowroot central on first startup).

**Comment by aoganesi** [comment]
Answered my own question:
- Proper configuration for our scenario is not to mess with config.json, but rather drop our own my_plugin.json into the plugins sub-folder

**Comment by trask** [comment]
👍
