### ISSUE TITLE
ObservingMemoryLeak_Glowroot

### ISSUE THREAD

**Issue by dowonderatwill** [glowroot/glowroot#407]
Recently observed that Glowroot packages are coming in the top 4 Leak Suspects in Memory Analyzer Tool.
Our java batch program runs multi threaded class and had configured glowroot agent in the jvm. The program gradually becomes slow. Then too slow and heap usage also goes high. Took the heap dump and found that it is glowroot which is coming as leak suspects.
Server is AIX. Java is 1.8 IBM. 
Please see the MAT result in the attached file. Is this a known issue?
![heapdump_glowrootleak](https://user-images.githubusercontent.com/16149643/41186743-bf7e7c96-6bd6-11e8-9e23-08938f25b186.png)

`One instance of "org.glowroot.agent.shaded.io.netty.buffer.PoolChunk" loaded by "<system class loader>" occupies 16,793,752 (23.90%) bytes. The memory is accumulated in one instance of "byte[]" loaded by "<system class loader>".

Keywords
byte[]
org.glowroot.agent.shaded.io.netty.buffer.PoolChunk`

**Comment by trask** [comment]
Hi @dowonderatwill, thanks for posting! 16mb is Netty's default PoolChunk size (see https://github.com/netty/netty/blob/netty-4.1.22.Final/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L40). Are you trying to run in a low memory environment? You could reduce the PoolChunk size to 8mb by specifying `-Dorg.glowroot.agent.shaded.io.netty.allocator.maxOrder=10`, or to 4mb by specifying `-Dorg.glowroot.agent.shaded.io.netty.allocator.maxOrder=9`.

**Comment by dowonderatwill** [comment]
Thanks for reply done the setting of 4mb. Will see the result. So far okay.

**Comment by dowonderatwill** [comment]
Further we don’t see any leak problem. Thank you.

**Comment by trask** [comment]
👍
