### ISSUE TITLE
ERROR o.glowroot.agent.init.GaugeCollector - The database has been closed [90098-176]

### ISSUE THREAD

**Issue by fstreboot** [glowroot/glowroot#409]
Hello,
Few days ago, we faced some OOM errors on our server like we never had before running Glowroot on the server.

Since the last OOM error on June 8th, the following stack trace appears in Jboss/Glowroot logs each minute or so:

2018-06-08 12:00:21,955 INFO  [STDOUT] 2018-06-08 12:00:21.955 ERROR o.glowroot.agent.init.GaugeCollector - The database has been closed [90098-176]
org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcSQLException: The database has been closed [90098-176]
	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:178)
	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:154)
	at org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:143)
	at org.glowroot.agent.embedded.shaded.org.h2.engine.Database.checkPowerOff(Database.java:490)
	at org.glowroot.agent.embedded.shaded.org.h2.command.Command.executeUpdate(Command.java:274)
	at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.setQueryTimeout(JdbcConnection.java:735)
	at org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcStatement.setQueryTimeout(JdbcStatement.java:599)
	at org.glowroot.agent.embedded.util.DataSource.prepareStatement(DataSource.java:588)
	at org.glowroot.agent.embedded.util.DataSource.batchUpdate(DataSource.java:388)
	at org.glowroot.agent.embedded.repo.GaugeValueDao.store(GaugeValueDao.java:142)
	at org.glowroot.agent.embedded.init.CollectorImpl.collectGaugeValues(CollectorImpl.java:109)
	at org.glowroot.agent.init.CollectorProxy.collectGaugeValues(CollectorProxy.java:86)
	at org.glowroot.agent.init.GaugeCollector$2.run(GaugeCollector.java:127)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)

Right now, I tend to point out Glowroot as the main reason of the issue but still not 100% sure if Glowroot is the source of the OOM problem or a victim...

One sure thing is that this trace stacks A LOT and I am unable to login in Glowroot. It says "An error occured". I am also unable to stop Glowroot without shuting JBoss down.

Any advice would be appreciated. Thanks!
Guillaume

**Comment by trask** [comment]
Hi @fstreboot, thanks for reporting this!

It looks like H2 database closes itself when it encounters an OutOfMemoryError:

https://groups.google.com/d/msg/h2-database/hCGftF0AiAs/1v1v-Tov0ZwJ

https://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90098

I will look at catching the "database has been closed" exception code (90098) and re-opening it.

As far as tracking down whether Glowroot is the source of the OOM, I recommend running with `-XX:+HeapDumpOnOutOfMemoryError`, and if there's any chance you can provide me with the heap dump I can review it (I can give you a private dropbox url to upload it).

**Comment by fstreboot** [comment]
That is exactly what I did, adding the -XX:+HeapDumpOnOutOfMemoryError. This OOM error seems to reappear quite often, so I'll be able to better understand the reason soon :)

For your information, I am using Glowroot 0.10.3.
I'll keep you informed soon.
Thank you!

**Comment by trask** [comment]
Hi @fstreboot, in the latest snapshot release [glowroot-agent-0.10.12-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.12-SNAPSHOT), the H2 database will now be re-opened after OOM (assuming the JVM is able to recover), so you should no longer get the never ending "The database has been closed" stack traces. Please re-open this issue (or open a new one), if the memory issues continue pointing to Glowroot. Thanks.

**Comment by nicStuff** [comment]
Hello, here to notify you that I encountered a database closed issue because of a "no space left on device" on glowroot `0.13.6`: the database hasn't been re-opened even after i freed a lot of space and many days have passed by, here follows the json that the glowroot web interface returns me:

    {"message":"java.io.IOException: Stream Closed","stackTrace":"org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcSQLException: IO Exception: \"java.io.IOException: Stream Closed\"; \"/opt/glowroot-0.13.6/glowroot/data/data.h2.db\" [90031-176]\n\tat org.glowroot.agent.embedded.shaded.org.h2.message.DbException.getJdbcSQLException(DbException.java:344)\n\tat org.glowroot.agent.embedded.shaded.org.h2.message.DbException.get(DbException.java:167)\n\tat org.glowroot.agent.embedded.shaded.org.h2.message.DbException.convertIOException(DbException.java:329)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.FileStore.write(FileStore.java:332)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.writePage(PageStore.java:1369)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.PageStreamData.write(PageStreamData.java:107)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.PageOutputStream.storePage(PageOutputStream.java:148)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.PageOutputStream.write(PageOutputStream.java:131)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.PageLog.write(PageLog.java:551)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.PageLog.commit(PageLog.java:571)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.PageStore.commit(PageStore.java:1477)\n\tat org.glowroot.agent.embedded.shaded.org.h2.engine.Database.commit(Database.java:1926)\n\tat org.glowroot.agent.embedded.shaded.org.h2.engine.Session.commit(Session.java:494)\n\tat org.glowroot.agent.embedded.shaded.org.h2.command.Command.stop(Command.java:152)\n\tat org.glowroot.agent.embedded.shaded.org.h2.command.Command.executeUpdate(Command.java:284)\n\tat org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcConnection.setQueryTimeout(JdbcConnection.java:735)\n\tat org.glowroot.agent.embedded.shaded.org.h2.jdbc.JdbcStatement.setQueryTimeout(JdbcStatement.java:599)\n\tat org.glowroot.agent.embedded.util.DataSource.prepareStatementUnderLock(DataSource.java:538)\n\tat org.glowroot.agent.embedded.util.DataSource.query(DataSource.java:317)\n\tat org.glowroot.agent.embedded.util.DataSource.queryForStringList(DataSource.java:261)\n\tat org.glowroot.agent.embedded.repo.TransactionTypeDao.read(TransactionTypeDao.java:56)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.LayoutService.buildLayoutEmbedded(LayoutService.java:201)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.LayoutService.buildLayout(LayoutService.java:177)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.LayoutService.getLayoutJson(LayoutService.java:90)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.IndexHtmlHttpService.handleRequest(IndexHtmlHttpService.java:54)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleHttpService(CommonHandler.java:255)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:231)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.CommonHandler.handle(CommonHandler.java:159)\n\tat org.glowroot.agent.embedded.shaded.org.glowroot.ui.HttpServerHandler.channelRead(HttpServerHandler.java:128)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat org.glowroot.agent.shaded.io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat org.glowroot.agent.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)\n\tat org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)\n\tat org.glowroot.agent.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)\n\tat org.glowroot.agent.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat org.glowroot.agent.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat org.glowroot.agent.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)\n\tat org.glowroot.agent.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)\n\tat org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)\n\tat org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)\n\tat org.glowroot.agent.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)\n\tat org.glowroot.agent.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.io.IOException: Stream Closed\n\tat java.base/java.io.RandomAccessFile.writeBytes(Native Method)\n\tat java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:559)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.fs.FileDisk.write(FilePathDisk.java:468)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.fs.FileUtils.writeFully(FileUtils.java:361)\n\tat org.glowroot.agent.embedded.shaded.org.h2.store.FileStore.write(FileStore.java:329)\n\t... 59 more\n"}
