### ISSUE TITLE
Build @Pointcut advices based on annotations

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#41]
It would be nice if you could build `@Pointcut` advices based on annotations, i.e. a Spring Controller:

```java
@Controller
public class TodoController {
    @RequestMapping("/user/todos/new")
    public String redirectToCreateTodoPage(Model model) {
        ...
```

**Comment by trask** [comment]
Thanks for the interest.  Yes, this is nice.

I just added support via new Pointcut attributes classAnnotation and methodAnnotation.

You can download and test the snapshot build from https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip (and maven snapshot repo is at https://oss.sonatype.org/content/repositories/snapshots).  Or you can build locally.

I gave a little shot at starting a Spring plugin using this feature here:

https://github.com/trask/glowroot-agent-spring-plugin

It may be helpful as example code, especially if you want to capture annotation attributes (e.g. the RequestMapping path), which requires the non-obvious BindMethodMeta.

**Comment by ajdevries** [comment]
Hi @trask. Thank you so much. This is very nice. I was already working on a spring plugin based on the previous wire api. But this is so much better. Great!

I'm trying it out right now ;-)

**Comment by ajdevries** [comment]
Issue could be closed, new feature is working great.
