### ISSUE TITLE
How to change parameter values (Input) using advices and pointcuts?

### ISSUE THREAD

**Issue by jagadeesh52423** [glowroot/glowroot#410]
I would like to change parameter values (Input) using advices and pointcuts. I know that we have @around annotation in AspectJ but I didn't find equivalent of it here.
Please provide me solution if it is possible with @onBefore , or how to implement @around !
Thank you!

**Comment by trask** [comment]
Hi @jagadeesh52423, thanks for posting! This is not currently possible. Can you explain your use case for this? Thanks.

**Comment by jagadeesh52423** [comment]
Thanks for quick reply!
We can able to detect SQL injection but we can't able to stop it from execution so I would like to change the SQL to some dump!
Thank you.

**Comment by vksethi77** [comment]
Hi @trask 
If we detect a sql injection or xss, we want to stop further execution of the code. We want to return from that place in such validation failure cases. For sql checks, I can write the code in StatementAspect.java to do the validation. If validaton detects no issues, code execution should proceed

**Comment by vksethi77** [comment]
@trask  - Thanks. Yeah, definitely we can throw an exception. 

But is it possible to implement onAround? Can we return an empty resultset to avoid blind sql injection?

**Comment by trask** [comment]
Closing, I think this is out of scope for Glowroot for now.
