### ISSUE TITLE
Provide ability to alert on text in error messages and error trace

### ISSUE THREAD

**Issue by pavanimanthana** [glowroot/glowroot#411]
Glowroot should be able to alert based on an error message or text in error trace. Certain exceptions like Cassandra's NoHostAvailableException are not recovering and need manual intervention. Having alerts based on such alerts will help.

**Comment by hallzy7** [comment]
This would be a very nice feature! I would also love the ability to configure alerts based on error messages.

**Comment by willsilvano** [comment]
Hi @trask ! That's is a very nice feature! Today we need custom alert's message, but if it was based on error messages would be better.

**Comment by trask** [comment]
Hi all, thanks for your comments, it helps to know this would be useful for several people. It is available now in the latest snapshot releases [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT) and [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT).
