### ISSUE TITLE
Agent version number is not shown on Collector pages

### ISSUE THREAD

**Issue by drmulligan** [glowroot/glowroot#412]
Glowroot shows the installed version at the bottom of each page.  It would be helpful to see the agent Glowroot version too if an agent is selected or otherwise contextually relevant.

**Comment by trask** [comment]
Hi @drmulligan, thanks for posting! This is available now in the latest snapshot release [glowroot-central-0.10.13-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.13-SNAPSHOT).
