### ISSUE TITLE
Alerts at roll up level

### ISSUE THREAD

**Issue by anveshgkumar** [glowroot/glowroot#414]
Hi,
When we configure alerts at rollup level, how alerting functionality works. For example, if i configure Heartbeat alert at rollup level, and the rollup has 5 agents active and reporting to collector. Will it send alert even if one of the agent heartbeat not received for a give time period.

**Comment by trask** [comment]
Hi @anveshgkumar, sorry for the late reply! Heartbeat alert at rollup level will only fire if none of the agent heartbeats were received for given time period.
