### ISSUE TITLE
Spring @Scheduled jobs does not appear in Transactions menu

### ISSUE THREAD

**Issue by fhperuchi** [glowroot/glowroot#416]
Is it possible to see the background transactions (i.e: https://demo.glowroot.org/transaction/average?transaction-type=Background) using Spring 4.1.6.RELEASE **org.springframework.scheduling.annotation.Scheduled** annotation? I have several scheduled jobs in my Spring application and I can't see the "Background" option in the combo at "Transactions" menu. See image below.

![image](https://user-images.githubusercontent.com/4641123/42177244-6e17944e-7e02-11e8-8a67-0184cf60e101.png)

In another JEE application, I see it normally.
![image](https://user-images.githubusercontent.com/4641123/42177452-29291bf4-7e03-11e8-8e8a-eb7e7eec6010.png)

Thanks a lot for this great tool!
Kindest regards.

**Comment by trask** [comment]
Hi @fhperuchi, thanks for posting! Try importing this instrumentation (similar to https://github.com/glowroot/glowroot/blob/v0.10.12/agent/plugins/ejb-plugin/src/main/resources/META-INF/glowroot.plugin.json#L5):

```
    {
      "classAnnotation": "org.springframework.stereotype.Component",
      "methodAnnotation": "org.springframework.scheduling.annotation.Scheduled",
      "methodParameterTypes": [
        ".."
      ],
      "captureKind": "transaction",
      "transactionType": "Background",
      "transactionNameTemplate": "Spring scheduled: {{this.class.simpleName}}#{{methodName}}",
      "traceEntryMessageTemplate": "Spring scheduled: {{this.class.name}}.{{methodName}}()",
      "timerName": "spring scheduled"
    }
```

Let me know how this works, I can add to the core Spring plugin (https://github.com/glowroot/glowroot/blob/v0.10.12/agent/plugins/spring-plugin/src/main/resources/META-INF/glowroot.plugin.json#L13).

**Comment by fhperuchi** [comment]
@trask thank you! But I'm not sure how to I import this instrrumentation. Where do I have to put this JSON content? Can you help me again, please?

**Comment by trask** [comment]
Hi @fhperuchi, sorry, go to Glowroot UI > Configuration > Instrumentation and you should see an Import button. You'll need to "Apply changes without restart", or you'll need to restart your JVM for the new instrumentation to get applied.

**Comment by fhperuchi** [comment]
@trask I got this error: **Missing className, Missing methodName**

![image](https://user-images.githubusercontent.com/4641123/42192617-50675658-7e40-11e8-9892-86f6db2661a6.png)

**Comment by trask** [comment]
Ah, that's a little bug I need to fix, for now try:

```
{
      "className": "",
      "classAnnotation": "org.springframework.stereotype.Component",
      "methodName": "",
      "methodAnnotation": "org.springframework.scheduling.annotation.Scheduled",
      "methodParameterTypes": [
        ".."
      ],
      "captureKind": "transaction",
      "transactionType": "Background",
      "transactionNameTemplate": "Spring scheduled: {{this.class.simpleName}}#{{methodName}}",
      "traceEntryMessageTemplate": "Spring scheduled: {{this.class.name}}.{{methodName}}()",
      "timerName": "spring scheduled"
    }
```

(you will see it get added into your config.json file under the glowroot directory)

**Comment by fhperuchi** [comment]
Thanks again @trask!

Now the JSON snippet was imported with success. I clicked the "Apply changes without restart" button and it worked very well.

![image](https://user-images.githubusercontent.com/4641123/42193110-2f56a150-7e43-11e8-9675-648336c83a1c.png)

**Comment by trask** [comment]
👍

**Comment by gamefundas** [comment]
@trask does the latest spring plugin support Scheduled annotation? I see that master doesnt have the instrumentation for @Scheduled.

Can open a new issue if I am not mistaken about the support.
