### ISSUE TITLE
Google account login support

### ISSUE THREAD

**Issue by fhperuchi** [glowroot/glowroot#417]
Hi!

I think it is very useful if we have a way to login via Google account in Glowroot web console. I have it in my Grafana (https://grafana.com/) installation here and it is so cool. Do you think is this possible?

Thanks in advance.
Fábio

**Comment by trask** [comment]
Hi @fhperuchi, this sounds nice, but probably won't make the priority list for a while unless someone else contributes it, so I'm closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
