### ISSUE TITLE
Coldfusion 10 JVM Monitoring - only shows /index.cfm

### ISSUE THREAD

**Issue by ecedwards** [glowroot/glowroot#419]
Hello,

I was just wondering if anyone has used Glowroot specifically for ColdFusion instances. I'm trying to monitor specific paths on the flow of my application, but the only thing Glowroot is registering is "/index.cfm". The only thing that changes on the app's step by step, is the query string, but not the path.

Is there a way to separate this or any setting to pull/detect the query string with path?

Thanks in advance!

**Comment by trask** [comment]
Hi @ecedwards, thanks for posting! Do you want to include the whole query string in the transaction name, or just part of the query string?

**Comment by ecedwards** [comment]
Hey Trask, I would like to include the whole query string in the transaction name.

**Comment by ecedwards** [comment]
Hey Trask, sorry for the delay response. Here are some of the queries that the application runs:

/index.cfm?event=ehOBE.dspPolling&requoteflag=false
/index.cfm?event=ehOBE.dspAvailability&requoteflag=false
/index.cfm?event=ehOBE.dspGuestInfo&

Hope this helps on how it can be handled... The application uses the query string for routing different steps of a process.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).

**Comment by ghedwards** [comment]
Is it possible to do this by defining a list or wildcard on the URL params we'd like to capture ?
