### ISSUE TITLE
Enhancement - Plugin EJB

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#425]
Hi,

We think it will be usefull if ejb plugin can be configured to get more information like servlet plugin : 
- Source 
- Parameter
- Timing
- All kind of information from the ejb

Thanks

**Comment by trask** [comment]
Hi @lfen21,

Thanks for posting!  I'm not very familiar with EJBs myself, so need some guidance here:

* Source - can you provide more details? I'm not sure what this would be.
* Parameters - capture toString() on each parameter?
* Timing - can you provide more details? It's already capturing overall time.
* All kind of information from the ejb - can you provide more details?

Thanks,
Trask

**Comment by lfen21** [comment]
Hi

I'm not so good too :)

Hm

Source : We have some serveurs who are calling others by EJB, and we need to know who is the caller.
Parameters : I think so.
Timing : Sure it's ok. Maybe if we had the ejb in "service calls" it will be cool 
All kind of information : if we can inspect what the response of the call.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
