### ISSUE TITLE
Enhancement - Collector compatible with MySQL

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#427]
Hi,

Cassandra isn't very user friendly when we have an error and we want to debug the configuration in the database.

Also we are using MySQL in our plateform and it's better than add a cassandra :)

Thank you

**Comment by trask** [comment]
Hi @lfen21, this would be nice, but also a lot of work.  I'm going to close for now tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
