### ISSUE TITLE
Building the ThinAgent package only

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#43]
Is it possible to make a Thin agent package only. When using a custom collector and a alternative backend, the FatAgent (backend) is not needed.

**Comment by trask** [comment]
Yeah, for a little while it was building both a thin agent distribution and a fat agent distribution (last time was in b772ce31385765b4e03e50f326398fb8b12704c8).  But the thin agent distribution was not as "thin" as I had hoped at 9.4mb (vs 12.9mb for the fat agent distribution), and it didn't seem like enough to justify having two separate distributions.  Is distribution size the reason you were interested in a separate distribution, or maybe something else?

**Comment by ajdevries** [comment]
Size does matter, but also the additional libraries that are added and not needed. But this seems okay.
