### ISSUE TITLE
Slow traces are not capturing for  WebLogic Server Version: 12.2.1.2.0

### ISSUE THREAD

**Issue by risrikanth** [glowroot/glowroot#432]
Hi Trask,

Central collector is not showing  slow trances in UI. 
Below are the details
Web server : WebLogic Server Version: 12.2.1.2.0
Glowroot Agent Version : 0.10.4-11-SNAPSHOT
Glowroot Collector Version :   0.10.4

I am also attaching agent debug log for your reference.

[glowroot1.2018-07-20-2.log](https://github.com/glowroot/glowroot/files/2219991/glowroot1.2018-07-20-2.log)

Thanks,
Srikanth

**Comment by trask** [comment]
Hi @risrikanth, thanks for reporting this!

The agent log shows lots of this:

```
WARN  o.g.agent.central.CentralConnection - unable to send data to the central collector: UNKNOWN
```

From https://github.com/grpc/grpc/blob/master/doc/statuscodes.md:

> UNKNOWN
> Server side application throws an exception (or does something other than returning a Status code to terminate an RPC)

Can you check the collector log corresponding to the time when the agent gets the `unable to send data to the central collector: UNKNOWN` error?

Thanks,
Trask

**Comment by risrikanth** [comment]
Hi Trask,
Thanks for your response. I couldn't find collector logs during that time. Now we have captured  agent and collector logs and UI screen shot. I am attaching for your ref. 

Agent logs : EST time
Collector logs : PDT time
UI image : CST time..
[glowroot1.2018-07-24-1.30PM-ET.log](https://github.com/glowroot/glowroot/files/2225225/glowroot1.2018-07-24-1.30PM-ET.log)
[WIIT-Collector-2018-24-10.30.log](https://github.com/glowroot/glowroot/files/2225226/WIIT-Collector-2018-24-10.30.log)

[responsetme-2018-24-12.30CST.docx](https://github.com/glowroot/glowroot/files/2225234/responsetme-2018-24-12.30CST.docx)

Thanks,
Srikanth.

**Comment by trask** [comment]
Hi @risrikanth, the collector log ends at 2018-07-24 11:32:38, while the agent log doesn't start until after that (at 2018-07-24 13:40:48).

I'd like to see the central collector log for the time period covering when the agent receives the error back from the central collector.

**Comment by risrikanth** [comment]
Hi Trask,

Thanks for your time. Sorry for confusion.   Collector runs at 2018-07-24 09:23:20.631 to 2018-07-24 11:32:38.225   PST time zone(2018-07-24 12:23:20.631 to 2018-07-24 13:32:38.225  EST) and  Agents runs at EST time zone 13:26:27.936 TO 2018-07-24 13:40:48.015.  There is only few 5 mins of logs matching for both collector and agent.  while uploading logs it is accepting only 1 MB of data so I am narrowing down the logs.. If you need more logs, i will look other ways to send the full logs.

Thanks,
Srikanth.

**Comment by risrikanth** [comment]
Hi Trask,

I have uploaded the files. Please check if those are not good, I will  take fresh data of one data for both collector and agent and send you.

Thanks,
Srikanth.

**Comment by trask** [comment]
Hi @risrikanth, can you double check the agent version? I see it is using `grpc-java-netty/1.12.0`, which means it is Glowroot version v0.10.10+, which means it is sending QueryStats to the central collector, which would explain why the central collector is throwing error since v0.10.4 doesn't understand QueryStats.

**Comment by risrikanth** [comment]
Hi Trask,

Yes. we are using  v0.10.10 agent as they are having  https proxy jvm arguments,  v0.10.4 agent is having issues to connect to collector when we have proxy setting arguments.

To resolve this issue do we need to  upgrade collector to v0.10.10 or more  or do we have any other solution?

Thanks,
Srikanth.

**Comment by trask** [comment]
Hi @risrikanth, you could comment out this line in the v0.10.4 collector for now if you need:

https://github.com/glowroot/glowroot/blob/v0.10.4/central/src/main/java/org/glowroot/central/CollectorServiceImpl.java#L560

**Comment by risrikanth** [comment]
Thanks trask for quick
