### ISSUE TITLE
Optimizer Hint is hidden in Oracle Queries

### ISSUE THREAD

**Issue by bmhm** [glowroot/glowroot#433]
Hi,

another edge case, but might be easily fixed. So tag this as low priority.

I tried to view a formatted SQL of an SQL with optimizer hints. An optimizer hint (sometimes a query hint) looks like a c-style comment in SQL, but Oracle does actually interpret it.

I attatched two screenshots. In the overview, you can see the hint.
In the detail view, it is gone. So this means it got parsed (perhaps)?
If so, would it be possible to inject a javascript using SQL commands? :laughing: 

## Expected Behaviour

When I click the SQL detail view, I'd expect the SQL  to contain the optimizer hint.
It is already visible in the overview:

![issue-optimizer-hint-overview](https://user-images.githubusercontent.com/1413391/43146802-1cd33bb2-8f62-11e8-9407-a70ccebe204b.png)

## Actual behaviour

The optimizer hint is gone.

![issue-optimizer-hint-detail-gone](https://user-images.githubusercontent.com/1413391/43146801-1ca4d8da-8f62-11e8-8064-6f4c68e0c034.png)

## Testability

Should easily be testeable. Just create a SQL statement with such a hint manually. Or, if using hibernate, make sure to use both limit and offset for your query, and set the Mode to OraclePlatform (Oracle9 or Oracle8).

## Severity

Edge case. Not too important.
BUT: Please check your SQL parser for injections.

Thanks for this GREAT software!

**Comment by trask** [comment]
Hi @bmhm, thanks for posting! Comments should now be preserved in the latest snapshot releases [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT) and [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT).

**Comment by bmhm** [comment]
Yay, you're the best! Going to try it tomorrow!
