### ISSUE TITLE
Show query caller methods 

### ISSUE THREAD

**Issue by giovanicascaes** [glowroot/glowroot#436]
Hello!

Is it possible show the method that has called the query listed in the Query Stats, in the trace details?

**Comment by trask** [comment]
Hi @giovanicascaes, thanks for posting! If you set "Stack trace threshold (millis)" to `0` under Configuration > Plugins > Jdbc Plugin, it will capture and display a stack trace for every query.

**Comment by giovanicascaes** [comment]
Thanks for the reply, @trask . I got it, the stack trace is shown in the trace entries. But may I ask you if it is possible to show this info in the query stats too? I think it is more convenient, because there you can see if a query is lasting too much (it has the time in ms) and I can't see this in the trace entries.

**Comment by trask** [comment]
Hi @giovanicascaes, if you hover over the bar to the left of the trace entry you can see the timing. Though I agree this is less convenient than the query stats.

**Comment by giovanicascaes** [comment]
Hi @trask . You're right, I can see the milis at left. However it is less convenient than query stats also because of the grouping of queries that sums their duration. May I ask you if it is too hard to implement the stack trace in the query stats?
