### ISSUE TITLE
Atlassian JIRA plugin "Configuration Management Toolkit" fails to start

### ISSUE THREAD

**Issue by kRaVeda** [glowroot/glowroot#437]
Hi, Team,
 I tried to use Glowroot with JIRA, but it was unsuccessful unfortunately. The  JIRA plugin "Configuration Management Toolkit" failed to start with the error below
`2018-07-31 09:06:24,071 localhost-startStop-1 WARN      [c.a.jira.startup.JiraStartupLogger] 
    
    ********************************************************************************************************************************************************************************************************
    ___ FAILED PLUGIN REPORT _____________________
    
    1 plugin failed to load during JIRA startup.
    
    	'com.deniz.jira.versioning' - 'Configuration Management Toolkit'  failed to load.
    		Stack map does not match the one at exception handler 109
    Exception Details:
      Location:
        com/deniz/jira/versioning/versiongraph/VersionGraphResource.b(Ljava/lang/String;)Ljavax/ws/rs/core/Response; @109: iload
      Reason:
        Type top (current frame, locals[1]) is not assignable to 'java/lang/String' (stack map, locals[1])
      Current Frame:
        bci: @68
        flags: { }
        locals: { 'com/deniz/jira/versioning/versiongraph/VersionGraphResource', top, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/api/TraceEntry', 'com/atlassian/jira/project/Project' }
        stack: { 'java/lang/Throwable' }
      Stackmap Frame:
        bci: @109
        flags: { }
        locals: { 'com/deniz/jira/versioning/versiongraph/VersionGraphResource', 'java/lang/String', 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/plugin/api/TraceEntry' }
        stack: { 'java/lang/Throwable' }
      Bytecode:
        0x0000000: 014d 014e 0336 0401 3a05 b800 2859 4db6
        0x0000010: 002e 594e c600 0704 a700 0403 3604 1504
        0x0000020: 9900 0c2d b201 0eb8 0040 3a05 2a2b b700
        0x0000030: e93a 0619 06c7 000f b200 ecb8 009b b600
        0x0000040: 6ca7 0021 2ab4 001c 1906 b900 f101 00b6
        0x0000050: 0054 b601 103a 0719 07b8 00f7 b600 6ca7
        0x0000060: 0003 1504 9900 0819 05b8 00ac b015 0499
        0x0000070: 0009 5919 05b8 00b2 bf                 
      Exception Handler Table:
        bci [44, 98] => handler: 109
      Stackmap Table:
        full_frame(@27,{Object[#2],Object[#227],Object[#42],Object[#50],Integer,Object[#52]},{})
        same_locals_1_stack_item_frame(@28,Integer)
        same_frame(@44)
        full_frame(@68,{Object[#2],Top,Object[#42],Object[#50],Integer,Object[#52],Object[#238]},{})
        full_frame(@98,{Object[#2],Object[#227],Object[#42],Object[#50],Integer,Object[#52]},{Object[#98]})
        same_locals_1_stack_item_frame(@108,Object[#98])
        same_locals_1_stack_item_frame(@109,Object[#174])
        same_locals_1_stack_item_frame(@120,Object[#174])
    
    `
Thanks

**Comment by trask** [comment]
Hi @kRaVeda, thanks for reporting this! What version of Glowroot agent are you using, and what version of JIRA?

**Comment by kRaVeda** [comment]
Hi @trask, 
JIRA v7.10.1
Configuration Management Toolkit v1.11.2
Glowroot agent v0.10.12

**Comment by kRaVeda** [comment]
Thank You, @trask !
It works and it is really cool and helpful

**Comment by trask** [comment]
👍
