### ISSUE TITLE
allert not triggert

### ISSUE THREAD

**Issue by DinoDeWaen** [glowroot/glowroot#440]
Hi,

I have a few servers running glowroot and a few servers in a loadbalanced setup. Each agent is configured in the same way. environment::ip of that server (to make it unique for that environment). 

This means I have for instance connected-prod:ip1, connected-prod::ip2
![screen shot 2018-08-02 at 10 55 13](https://user-images.githubusercontent.com/9537715/43573692-9d721ffe-9642-11e8-9c71-69898824d93b.png)

I added alerts on the root connected-prod because the servers of that environment can change, it can be 1 or 2 and I want to know for that environment if I need to react without adding the allarms for each new server in that environment.  
![screen shot 2018-08-02 at 10 58 29](https://user-images.githubusercontent.com/9537715/43573871-0b5608fa-9643-11e8-8047-e646f71f6e25.png)

the problem is that I don't get any alerts. This morning there was an job with errors and the alarm should trigger I think. 
![screen shot 2018-08-02 at 11 04 03](https://user-images.githubusercontent.com/9537715/43574187-d467affa-9643-11e8-9122-a800f9960331.png)

Could you indicate what configuration change i need? This is my configuration for that alarm. 
![screen shot 2018-08-02 at 11 01 50](https://user-images.githubusercontent.com/9537715/43574068-86b1fd06-9643-11e8-97f6-53e28a146d5f.png)

version central: 0.10.12 docker verion
kind regards 

Dino

**Comment by DinoDeWaen** [comment]
update:
the heartbeat alarm works. The rest doesn't trigger.

**Comment by DinoDeWaen** [comment]
- added synthetic monitor for the sync and added an allert. This works once again. 

- response time alerts still fail to trigger.

**Comment by trask** [comment]
Hi @DinoDeWaen, thanks for the updates.

I just noticed in your screenshot above it has Transaction name "backend errors". This should be empty in order to monitor "All Background Transaction".

**Comment by DinoDeWaen** [comment]
hi Trask,

Thanks for the info, that was indeed the problem. Works like a charm now. 

kind regards Dino
