### ISSUE TITLE
 Warning collection rejected due to backlog 

### ISSUE THREAD

**Issue by risrikanth** [glowroot/glowroot#441]
Hi Trask,

We have upgraded collector to v0.10.12 and we are floating with below warning message. Could you plz explain what scenario we will get below warning message.  

2018-08-03 10:58:56.439 WARN  o.g.central.CollectorServiceImpl - IDP-27531-idp-ms-product-configuration :: zlp30255-idp-ms-product-configuration-3181340871 - collection rejected due to backlog

Thanks,
Srikanth.

**Comment by trask** [comment]
Hi @risrikanth, thanks for posting! Are you still having this issue? If so, can you monitor the central collector itself using (embedded/standalone) glowroot agent for a few hours (at least) and zip and upload the agent directory (including the data directory) to https://www.dropbox.com/request/cDuuIx5ffVWk48mhIBRy?

**Comment by risrikanth** [comment]
Hi Trask,
Thanks for your response.  We observed, this issue is occurring when ever heavy load. Like more slow transactions from agents,  slow transactions from gRPC. more pending actions from aggregation data.
We are also monitoring our collectors with glowroot agent. 
I will send you the log files when we see  these errors due to heavy traffic from agents.  Will send you logs as soon as we see the errors.

Thanks,
Srikanth.

**Comment by risrikanth** [comment]
Hi Trask,
We are already  monitoring our collector with  glowroot pointing to our central collector. 
Today also we got some backlog warning messages.  We are seeing this issue when we are having lot of data coming.
I have uploaded both central collector log and  glowroot agent log . We observed issue 05:33:21 . Please let us know if you need more logs.
https://www.dropbox.com/request/cDuuIx5ffVWk48mhIBRy

Thanks,
Srikanth.

**Comment by mani8884** [comment]
Hi Trask,

Could you please let us know if you have any update on this issue. Thanks for the help.

Regards,
Manikanth

**Comment by trask** [comment]
Hi @mani8884, sorry forgot about this, can you try with the latest snapshot release [glowroot-central-0.10.13-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.13-SNAPSHOT)? I fixed an issue with the Cassandra connection pool management that could have been causing this.

**Comment by mani8884** [comment]
Sure Trask. Will try that. Thank for providing the fix.

**Comment by mani8884** [comment]
Hi @trask , Is it possible to provide the exact commit id ?

**Comment by trask** [comment]
Hi @mani8884, sure, the problem was fixed in f761741e144e48b426d851063cf4d46a1d4e1f99

**Comment by mani8884** [comment]
Thank you so much @trask
