### ISSUE TITLE
Skip creation of subdirectories if agent.id is defined

### ISSUE THREAD

**Issue by ReillyProcentive** [glowroot/glowroot#442]
### Issue
We currently use Glowroot with Tomcat containers in our Kubernetes cluster. Each of these containers is configured to run with a read-only root fs with temporary and persistent mounted directories. Previously we configured Glowroot with a `glowroot.properties` that had the configuration directory on the read-only fs (we create the `admin.json` and `config.json` ahead of time) while the other directories are configured to point to mounted volumes.

This worked well for us up until we started working on getting the central collector setup. We then discovered that when an `agent.id` is provided Glowroot attempts to create a subdirectory under the config directory which obviously fails as that directory is read-only. Changing the config directory to point to a separate writeable directory goes against our goal of having all configuration and application directories be read-only and also means we need to have a separate mechanism to copy our `admin.json` and `config.json` into this new folder or give up on customizing these files.

### Solution
Can we add an optional property to `glowroot.properties` that when present disables the subdirectory creation and forces usage of the directories that are specified in `glowoot.properties`? This should give us the behavior we need while posing little risk of breaking existing setups.

**Comment by trask** [comment]
Hi @ReillyProcentive, thanks for posting! Are you specifying the `agent.id` via command line, e.g. `-Dglowroot.agent.id=...` or via the `glowroot.properties` file?  It should only create the subdirectory if you specify the `agent.id` via the command line.

**Comment by ReillyProcentive** [comment]
@trask we're specifying it via command line. The initial `glowroot.properties` file is created during the image creation process and thus ends up read-only.

**Comment by ReillyProcentive** [comment]
I'm going to close this. We were able to get the desired behavior by using Helm to template the `glowroot.properties` file and using a barely documented Kubernetes feature to mount said individual file into the container.

**Comment by trask** [comment]
Re-opening. I think the current behavior is confusing anyways (having different behavior depending on whether `agent.id` is specified via system property or via `glowroot.properties` file). I'm thinking to change this (with next major release `v0.11.0`) and require `agent.multi=true` (either via `glowroot.properties` or via command line `-Dglowroot.agent.multi=true`) in order to trigger the (subdirectory) behavior that is needed for running multiple agents on a single box.

**Comment by trask** [comment]
Closed by f4519f8687eb0fa555a609caa3c85bc702d501da.

Using `-Dglowroot.agent.id=...` no longer has any affect on the multi-directory behavior.

Multi-directory behavior now must be explicitly enabled via `multi.dir=true` in the agent's `glowroot.properties` file, or via `-Dglowroot.multi.dir=true` on the command line.

**Comment by trask** [comment]
Hi @ReillyProcentive, there's a new setting in the latest snapshot release [glowroot-agent-0.12.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.0-SNAPSHOT) to tell Glowroot that you want the local configuration to be read-only.

It's specified as either

* `config.readOnly=true` in the glowroot.properties file, or
* `-Dglowroot.config.readOnly=true` on the command line

When this is enabled, Glowroot won't try to write to the `config.json` file, and the agent's configuration will appear as read-only in the Central Collector UI.

More importantly, when this is enabled, Glowroot won't try to write out the new `config.synced` file which now gets written in the same directory as the `config.json` file (that file doesn't make sense in the read-only config use case anyways).

**Comment by ReillyProcentive** [comment]
Hi @trask, we just updated our agents and can confirm that the new flag is working as expected (and it is perfect for our use-case, thanks!).

**Comment by trask** [comment]
👍
