### ISSUE TITLE
DCEVM compatibility

### ISSUE THREAD

**Issue by atallahade** [glowroot/glowroot#445]
Starting a jetty server using glowroot and with the alternative JVM [DCEVM](http://dcevm.github.io) produces this output before exiting:
```
ERROR: JDWP Transport dt_socket failed to initialize, INVALID_THREAD(10)
JDWP exit error JVMTI_ERROR_INVALID_THREAD(10): No transports initialized [debugInit.c:750]
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=JVMTI_ERROR_INVALID_THREAD(10)
Aborted
```

It's not a big issue for me as I usually use DCEVM for dev and glowroot to monitor production environments but it would be interesting if there was a way to use these two projects together.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
