### ISSUE TITLE
springbatch and glowroot

### ISSUE THREAD

**Issue by quochoangnguyen** [glowroot/glowroot#448]
Hi Trask,

with Glowroot, I known that we can use this tool to make profiling operations with java batch programs
developed with spring batch framework.

With Spring Batch Framework, I want to make profiling the method write in the class ItemWriter like the extract example code below :

public class StringItemWriter implements ItemWriter {

private static final Logger LOGGER =LoggerFactory.getLogger(StringItemWriter.class);

public void write(List<? extends String> items) throws Exception {

for(String item : items) {
				LOGGER.info("writing "+item);
			 }

}

}

Do you have an idea to help me writing the json configuration file ?

Thank in advance

**Comment by trask** [comment]
Hi @quochoangnguyen, try adding instrumentation via the UI, e.g. under Configuration > Instrumentation. Depending on what exactly you want, here's a starting point:

* **Class name:** org.springframework.batch.item.ItemWriter
* **Method name:** write
* **What to capture:** Transaction
* **Transaction type:** Spring Batch
* **Transaction name:** Write Items
* **Trace headline:** {{this.class.name}}.write(<{{0.size}} items>)
* **Timer name:** write items
* **What to do if already in a transaction:** Capture a new transaction

**Comment by quochoangnguyen** [comment]
Hi Trask, 

thank for your help

But I want to ask you to confirm me the attribute Trace headline in the two  configuration instrumentation for two methods.

1) If I have the class class CrlFileItemReader extends AbstractItemStreamItemReader<CrlFileItem> 
	implements ItemReader<CrlFileItem>, ResourceAwareItemReaderItemStream<CrlFileItem> 
  and If I have the signature of the read() method like :
public CrlFileItem read()
			throws UnexpectedInputException, ParseException, NonTransientResourceException, IOException {
		...
	}

I must set the Trace headline like Trace headline:  {{this.class.name}}.read()
Is it exact ?

2) If I have the class class CrlFileItemNotPresentProcessor implements ItemProcessor<String, String> 
     and if I have the signature of process method like :

public String process(String crlAlias) {
		...
	}
I must set the Trace headline like Trace headline:  {{this.class.name}}.process({{0.size}}.crlAlias)
Is it exact ?

Thanks in advance,

**Comment by trask** [comment]
Hi @quochoangnguyen, sorry for the late reply. The "Trace headline" is just the text that will be shown when you open a trace, so it can be any text (doesn't need to be anything exact). See the help text for that field when you are creating Instrumentation through the UI:

> This is a template which can be populated with values from the method invocation:
> * {{0}}, {{1}}, ... resolve to the method parameters
> * {{this}} resolves to the object that the method is invoked on (except for static methods)
> * {{_}} resolves to the return value (if not void)
> * {{methodName}} resolves to the method name, which can be useful if * or | are used to define the method name above
>
> Nested paths are resolved as well, e.g. {{0.size}} and {{this.class.name}}. If a path resolves to null at any point, then the entire path will resolve to null. Finally, resolved value is rendered into the template using String.valueOf().

**Comment by quochoangnguyen** [comment]
Hi Trask,

Thanks a lot for your help.

Best Regards
