### ISSUE TITLE
Unique Glowroot agent for multiple java instances

### ISSUE THREAD

**Issue by fstreboot** [glowroot/glowroot#451]
Hi, here is my situation:
our team is slowly migrating our JBoss hosted applications to spring-boot apps. 
Then, on the same Windows server, we'll have a JBoss server hosting 3 applications, and also few spring-boot applications hosted and running on the same Windows server as JBoss is running.
For the time this migration will last (a year or so), I would like that our Glowroot agent tracks the JBoss applications and also the spring-boot, so I could get only one Glowroot dashboard to manage.

Is it doable or I need to create different Glowroot agents for each and every spring-boot and JBoss instance?
Thank you for your answer

**Comment by trask** [comment]
Hi @fstreboot, thanks for posting! Are you using the Glowroot central collector or the embedded collector?

**Comment by fstreboot** [comment]
Hi @trask, sorry for the delay.
We use the embedded collector.

**Comment by trask** [comment]
Hi @fstreboot, have you already seen https://github.com/glowroot/glowroot/wiki/Agent-Installation-%28with-Embedded-Collector%29#running-multiple-agents-on-a-single-box?

**Comment by fstreboot** [comment]
Yes I did. But at first view, I think it isn't what I was looking for.
I want to have a unique Glowroot UI dashboard/database that group my JBoss applications AND spring-boot apps.
So when I have to monitor all the applications hosted on server "my-server-abc", I'll reach out:
http://my-server-abc:4000 
and see all the apps (JBoss and spring-boot).

And not have to reach out a bunch of different UI, ie:
http://my-server-abc:4000 (JBoss applications)
http://my-server-abc:4001 (My-Spring-boot-app-1)
http://my-server-abc:4002 (My-Spring-boot-app-2)
http://my-server-abc:4003 (My-Spring-boot-app-3)
...

Hoping my explanations are clear enough!
Thanks

**Comment by trask** [comment]
Hi @fstreboot, the embedded collector doesn't support this, but the central collector does :-).

**Comment by fstreboot** [comment]
All right then, I'll see if we can switch to a central collector. Thank you!

**Comment by trask** [comment]
👍
