### ISSUE TITLE
Could not find TLS ALPN provider in Alpine Linux

### ISSUE THREAD

**Issue by verglor** [glowroot/glowroot#452]
Hi, I cannot get agent to communicate with central collector via https.

I have configured the follwing:
 - `grpc.httpsPort=8282` in `glowroot-central.properties` on central collector server
 - copied my letsencrypt's `fullchain.pem` to `grpc-cert.pem` and `key.pem` to `grpc-key.pem`.
 - `collector.address=https://glowroot.domain.com:8282` in the agent's `glowroot.properties`

And I am getting the following error in my application's log:
```
ERROR org.glowroot.agent.impl.BytecodeServiceImpl - Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:256)
        at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at org.glowroot.agent.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at org.glowroot.agent.central.CentralConnection.<init>(CentralConnection.java:131)
        at org.glowroot.agent.central.CentralCollector.<init>(CentralCollector.java:111)
        at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit$1.run(NonEmbeddedGlowrootAgentInit.java:134)
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMainCommon(BytecodeServiceImpl.java:178)
        at org.glowroot.agent.impl.BytecodeServiceImpl.enteringMain(BytecodeServiceImpl.java:67)
        at org.glowroot.agent.bytecode.api.Bytecode.enteringMainMethod(Bytecode.java:33)
```

With `collector.address=http://glowroot.domain.com:8181` everything works OK.

`java -version` on agent:
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Comment by trask** [comment]
Hi @verglor, thanks for posting!

What glowroot agent version are you running?

What operating system are you running?

Do you have the `lib/glowroot-central-collector-https-*.jar` files under your glowroot agent directory?

Thanks,
Trask

**Comment by verglor** [comment]
Hi @trask,

here is the missing information:

- central collector [v10.0.12](https://github.com/glowroot/glowroot/releases/download/v0.10.12/glowroot-central-0.10.12-dist.zip) @ Debian 9 in docker container [glowroot/glowroot-central:latest](https://hub.docker.com/r/glowroot/glowroot-central)
- agent [v10.0.12](https://github.com/glowroot/glowroot/releases/download/v0.10.12/glowroot-0.10.12-dist.zip) @ Alpine Linux 3.8.0 in docker container [openjdk:8-jre-alpine](https://hub.docker.com/_/openjdk)

Dockerfile of my app image:
```
FROM openjdk:8-jre-alpine
WORKDIR "/war"
RUN apk add bash curl --no-cache
SHELL ["/bin/bash", "-c"]
ARG GLOWROOT_AGENT_VERSION=0.10.12
RUN mkdir -p /glowroot;\
    curl https://github.com/glowroot/glowroot/releases/download/v${GLOWROOT_AGENT_VERSION}/glowroot-${GLOWROOT_AGENT_VERSION}-dist.zip
    unzip /tmp/glowroot.zip -d /;\
    rm /tmp/glowroot.zip /glowroot/lib/glowroot-embedded-collector.jar;\
    rm /glowroot/lib/glowroot-central-collector-https-{windows,osx}.jar
CMD ["java", "-javaagent:/glowroot/glowroot.jar", "-jar", "/war/ROOT.war", "-server"]
EXPOSE 8080
VOLUME /war
```

Now I realized that when I replace parent image `openjdk:8-jre-alpine` by `openjdk:8-jre` it works.
Is it possible to make it work in Alpine Linux ? Probably by installing some missing packages ?

**Comment by trask** [comment]
Check out https://github.com/netty/netty-tcnative/search?q=alpine&type=Issues.

Also check out https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty:

> If you are using `musl` libc (e.g., with Alpine Linux), then `netty-tcnative-boringssl-static` won't work. There are several alternatives:
>
> * Use [netty-tcnative-alpine](https://github.com/pires/netty-tcnative-alpine)
> * Use a distribution with glibc

I couldn't get the OpenSSL variants of [netty-tcnative-alpine](https://github.com/pires/netty-tcnative-alpine) to build clean (similar to a couple of the issues reported in netty-tcnative).

But I was able to build the LibreSSL variant cleanly, and use that to build [glowroot-central-https-linux](https://github.com/glowroot/glowroot/tree/v0.10.12/agent/shaded/central-https-linux), and that actually worked:

* See my fork of [netty-tcnative-alpine](https://github.com/trask/netty-tcnative-alpine)
* Then install result to local maven repo
    ```
    mvn install:install-file
            -Dfile=netty-tcnative-libressl-static-2.0.14.Final-linux-x86_64.jar \
            -DgroupId=io.netty
            -DartifactId=netty-tcnative-libressl-static
            -Dclassifier=linux-x86_64 \
            -Dversion=2.0.14.Final
            -Dpackaging=jar
    ```
* Then change central-https-linux [pom.xml](https://github.com/glowroot/glowroot/tree/v0.10.12/agent/shaded/central-https-linux/pom.xml) dependency from boringssl to libressl (in 3 places) and build that (result is `target/original-glowroot-agent-central-https-linux-0.10.12.jar`), and that becomes your `glowroot-central-collector-https-linux.jar`.

I'm curious if https://bugs.alpinelinux.org/issues/4970 is related to the problems with building the OpenSSL variants of netty-tcnative on Alpine Linux.

**Comment by verglor** [comment]
Hi, @trask, thank you for your investigation.

Do you think it is possible to distribute this patched `glowroot-central-collector-https-linux.jar` as something like `glowroot-central-collector-https-alpine.jar` together with other agent libs ?

It would be also ideal if agent was able to pick it if it's running in alpine (or in general in distribution with musl) however it is not a big deal to replace linux jar by alpine jar in a Dockerfile.

**Comment by trask** [comment]
Hi @verglor, I hadn't realized how popular Alpine Linux has become in the container world, thanks for raising this issue! I added a new `glowroot-central-collector-https-linux-alpine.jar` artifact and the Glowroot agent should now detect and use that if it's running on Alpine Linux (it checks for existence of the file `/etc/alpine-release`).

**Comment by yosaku01** [comment]
Dear trask,
        Whether the glowroot-central-collector-https-linux-alpine.jar supports gRpc HTTPS support in other Linux environment? Because the glowroot-central 0.13.1 distribution does not contain this jar file?
Because we need add grpc TLS proxy in our production environment, we want to know whether the default glowroot-central distribution supports the grpc https protocol. Can you answer my question? Thank you very much.
        Best Regards,
        Yours Rick

**Comment by trask** [comment]
Hi @yosaku01, are you running the central collector on Alpine Linux or another Linux distribution?
