### ISSUE TITLE
How to use with NodeJS for monitoring

### ISSUE THREAD

**Issue by dharanchandar** [glowroot/glowroot#453]
I have node JS server which hosted the angular JS and type script code , I need to know how to use glowroot to monitor the nodeJS server

**Comment by trask** [comment]
Hi @dharanchandar, thanks for posting! Glowroot only supports monitoring Java, so no NodeJS sorry.

**Comment by risrikanth** [comment]
Hi Trask,
Thanks for clarification and sorry for asking again same question as I found couple of links in google.  I  see couple of post for node.js with glowroot.   Can you please conform glowroot with node JS support.
https://github.com/varunchauhan49/glowroot-node-agent
https://www.npmjs.com/package/glowroot-node-agent

Thanks,
Srikanth.

**Comment by trask** [comment]
Hi @risrikanth, that is @varunchauhan49's node agent that reports to the glowroot central collector.

**Comment by dharanchandar** [comment]
Looks like no official support from glowroot team

**Comment by varunchauhan49** [comment]
@dharanchandar Both of the links belongs to the same agent. You can use this agent to integrate with glowroot. If you need to customize the agent as per your need, just clone the agent from github.

**Comment by monperrus** [comment]
Very interesting thread. Do you know any other Glowroot-like technology for NodeJS?
