### ISSUE TITLE
Push Config Changes Without Restarting

### ISSUE THREAD

**Issue by epyonavenger** [glowroot/glowroot#454]
Creating a GitHub issue as per conversation in the mailing list.

We were looking for some sort of method/API to push changes to systems without having to restart Tomcat in order to have them picked up.

Originally, this started with wanting to deploy glowroot and add user accounts to it, but has since expanded to needing to adjust retention and some other bits and bobs.

I know creating a whole new set of API endpoints or such is probably too large of an ask, but if we could deploy the config files and they'd be read from disk every so often, that'd work too. Every 5 mins is probably fine for us, more than 10 might be less than ideal, less than 5 is probably overkill.

I'm not sure if that is all the necessary info, but if you need anything else, just say 'hey' and I'll add/attach it. >:]

**Comment by epyonavenger** [comment]
Will try it out as soon as I can!

Apologies if it's a dumb question, but is there any documentation for the API?

**Comment by trask** [comment]
Hi @epyonavenger,

POST the config.json to `/backend/config/json` and POST the admin.json to `/backend/admin/json`. I think that's all, but definitely let me know if you run into any troubles.

Thanks,
Trask
