### ISSUE TITLE
No field `cassandra.symmetricEncryptionKey` in glowroot-central.properties

### ISSUE THREAD

**Issue by blademainer** [glowroot/glowroot#455]
[docker-entrypoint.sh](https://github.com/glowroot/glowroot/blob/master/central/docker-entrypoint.sh) replace field `cassandra.symmetricEncryptionKey` by environment `CASSANDRA_SYMMETRIC_ENCRYPTION_KEY `， but no field `cassandra.symmetricEncryptionKey` in the glowroot-central.properties file, so that the environment is no use even it's presented.

**Comment by trask** [comment]
Hi @blademainer, thanks for reporting this! This should be fixed in the next release.
