### ISSUE TITLE
::ffff:127.0.0.1:4000 

### ISSUE THREAD

**Issue by beeant0512** [glowroot/glowroot#456]
i am using -javaagent: path/glowroot.jar .. in docker, and i expose 4000 port, but in docker container , the 4000 ports is 

```
State      Recv-Q Send-Q                                                                                      Local Address:Port                                                                                        Peer Address:Port 
LISTEN     0      128                                                                                      ::ffff:127.0.0.1:4000                                                                                                  :::*     
```

how to fix this?

**Comment by trask** [comment]
Hi @beeant0512, thanks for posting! Check out https://github.com/glowroot/glowroot/wiki/Agent-Installation-(with-Embedded-Collector)#optional-post-installation-steps. Probably you need to add an `admin.json` file to the glowroot agent directory with this content:

```
{
  "web": {
    "bindAddress": "0.0.0.0"
  }
}
```

**Comment by beeant0512** [comment]
@trask  Thanks.
