### ISSUE TITLE
Flame graph tooltip renders outside of browser window

### ISSUE THREAD

**Issue by tml** [glowroot/glowroot#457]
I am unable to view the entire tooltip of items on the left edge of my flame graph; screenshot attached. The left edge of the screenshot is the extreme left edge of the browser (and OS/desktop viewable space).

<img width="649" alt="screen shot 2018-09-24 at 9 48 01 am" src="https://user-images.githubusercontent.com/35148/45962866-238f3480-bfdf-11e8-97b0-e12ececc26bd.png">

**Comment by trask** [comment]
Thanks for reporting this! It should be fixed now in the latest snapshot releases [glowroot-agent-0.11.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.11.1-SNAPSHOT) and [glowroot-central-0.11.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.11.1-SNAPSHOT).
