### ISSUE TITLE
How to programmatically determine agent version

### ISSUE THREAD

**Issue by reshippie** [glowroot/glowroot#458]
I'm trying to automate detecting if we need to upgrade the installed instance, but running into a small hiccup determining the currently installed version.  The embedded collector nicely displays the version at the bottom of the page, but the actual `glowrootVersion` variable is defined as part of the `layout` var inside of the script tag.  I am currently finding it by downloading the login page then parsing the line that contains `glowrootVersion":`, to guarantee I'm only getting the line that defines the version and not the line that prints is.  

It would be preferable if there was either a version file in the unpacked directory or a `/version` URL endpoint.  That way I would not have to depend on the HTML never changing.

**Comment by reshippie** [comment]
That exactly the kind of solution I was looking for!  Thanks so much for your help.

**Comment by trask** [comment]
👍

**Comment by trask** [comment]
Starting in `v0.11.1` you will also be able to run `java -jar glowroot.jar version` to get the version (e.g. if you are on Windows where the above solution probably won't work).
