### ISSUE TITLE
How to delete data older than X hours

### ISSUE THREAD

**Issue by Hervian** [glowroot/glowroot#459]
Hi

Does the directories in which glowroot stores it's data keep growing in size or is there some option to delete data older than fx one week? My concern is that the directory will just keep growing until the server runs out of diskspace. In my use case I am only interested in inspecting what happened during the last 24 hours, so data older than that I would like to be deleted. 

Best regards, Anders

**Comment by trask** [comment]
Hi @Hervian, thanks for posting!

Check out the options under Administration > Storage, e.g. https://demo.glowroot.org/admin/storage
