### ISSUE TITLE
Unformatted sql on slow trace export (v0.11)

### ISSUE THREAD

**Issue by bit-ionutursuleanu** [glowroot/glowroot#460]
Hi,

I tried to export a slow trace on the last version and all the sqls are not formatted

**Comment by trask** [comment]
Thanks for reporting this! It should be fixed now in the latest snapshot releases [glowroot-agent-0.11.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.11.1-SNAPSHOT) and [glowroot-central-0.11.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.11.1-SNAPSHOT).
