### ISSUE TITLE
[Transactions] a way to research with 2 keywords ?

### ISSUE THREAD

**Issue by nboucly** [glowroot/glowroot#464]
hello

I search a way to use 2 keywords in headline/URL with "Does no contain" in Slow traces tab, in transaction page.

Have an idea to do it ?

for example : pdf OR txt

Thank you for your help
![image](https://user-images.githubusercontent.com/8500683/46613983-f4b3ab00-cb14-11e8-8f2c-63e8e8eec6a4.png)

**Comment by trask** [comment]
Hi @nboucly, thanks for posting! There is not currently a way to do this.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
