### ISSUE TITLE
Invalid transaction time for WebFlux applications

### ISSUE THREAD

**Issue by lukaszun** [glowroot/glowroot#467]
Transactions monitoring is not working as expected for Webflux applications. Transation time is counted in miliions of miliseconds for such applications. Do you have any idea how to fix it?
![obraz](https://user-images.githubusercontent.com/2979158/47342936-33b13700-d6a5-11e8-9fd2-60d85391fc8d.png)

**Comment by trask** [comment]
Hi @lukaszun, thanks for reporting this! Are you using Webflux over Netty or Tomcat (or other)?

**Comment by trask** [comment]
Also, what versions of Spring/Netty/Tomcat/etc are you using? Thanks.

**Comment by lukaszun** [comment]
Spring Boot 2.0.1
Netty 4.1

**Comment by trask** [comment]
Hi @lukaszun, I'm not able to reproduce this problem. Can you export and attach (or email me) one of those traces? Maybe I can get some clues from that how to repro. Thanks.

**Comment by lukaszun** [comment]
[trace-20181029-001534-200.zip](https://github.com/glowroot/glowroot/files/2547275/trace-20181029-001534-200.zip)
Here you are

**Comment by trask** [comment]
Yes! I was able to repro using spring-cloud-gateway! Thanks.

**Comment by lukaszun** [comment]
Great!
Can't wait for the fix. When can it be?

**Comment by trask** [comment]
This should be fixed now in the latest snapshot release [glowroot-agent-0.12.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.2-SNAPSHOT).
