### ISSUE TITLE
Webhook integration

### ISSUE THREAD

**Issue by willsilvano** [glowroot/glowroot#469]
Hello @trask !
There is any way to send POST requests when we have active alerts?
We have Slack here and I would like to send Slack bot messages notificatons instead of e-mail.

**Comment by trask** [comment]
Hi @willsilvano, thanks for posting! Does the POST body need to have a specific format?

**Comment by trask** [comment]
I found slack documentation and integration is now available in the latest snapshot releases [glowroot-agent-0.12.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.2-SNAPSHOT) and [glowroot-central-0.12.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.12.2-SNAPSHOT), configure under Administration > Integrations > Slack, then you can configure individual alerts to go to Slack channels.

**Comment by willsilvano** [comment]
@trask Wow! That's nice! Thank you!

**Comment by willsilvano** [comment]
When are you planning to release the next version with this feature?

**Comment by trask** [comment]
Probably sometime in the next couple of days.
