### ISSUE TITLE
Jetty Plug-in

### ISSUE THREAD

**Issue by anishkh** [glowroot/glowroot#472]
Hi Trask,

Thanks for releasing Kafka and MongoDB plug-ins. Any plans to have Jetty plug-in support in Glowroot?

Anish

**Comment by trask** [comment]
Hi @anishkh, thanks for posting! Jetty should already be supported by the Servlet plugin. Can you clarify what kind of Jetty support you are meaning?

**Comment by trask** [comment]
Closing, but please re-open if you still have any questions. Thanks.
