### ISSUE TITLE
Spring cloud gateway memory leak

### ISSUE THREAD

**Issue by lukaszun** [glowroot/glowroot#473]
There is some problem with glowroot objects in Webflux applications:

![obraz](https://user-images.githubusercontent.com/2979158/47986407-f0ab8680-e0dc-11e8-800b-91a52798ab7a.png)

These values keep rising.

**Comment by trask** [comment]
This should be fixed now in the latest snapshot release [glowroot-agent-0.12.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.2-SNAPSHOT).
