### ISSUE TITLE
Slow threshold override for user 

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#474]

**Comment by trask** [comment]
Thanks for the PR! I merged it and the feature should be available now in the latest snapshot release [glowroot-agent-0.13.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.0-SNAPSHOT).
