### ISSUE TITLE
Solr support

### ISSUE THREAD

**Issue by gaeljw** [glowroot/glowroot#481]
Hello,

After discovering glowroot yesterday, I wanted to immediately give it a try and use it on one of our critical application which is a Solr instance but I was a bit disappointed to not see anything in the profile/trace.

See screenshot:
![2018-11-22_13-30](https://user-images.githubusercontent.com/18280708/48903146-ffbf6200-ee5a-11e8-80d5-46a869c36aab.png)

Do you think there is something to do in glowroot? Or maybe I'm not using it the right way?
Do I have to add specific classes to monitor?

Note that Solr embed a Jetty instance and run over Lucene so I thought it would be supported right away :)

Thanks for your support,

**Comment by gaeljw** [comment]
If I look at a call stack with VisualVM I get much more methods like on this screenshot (not the exact same call):
![screenshot from 2018-11-27 08-34-04](https://user-images.githubusercontent.com/18280708/49065886-a7ec7680-f21f-11e8-8f3b-8016a36d6e40.png)

I was hoping to see pretty much the same thing in Glowroot.

Again, maybe I'm not using Glowroot the right way. If I add some classes to watch in the Instrumentation admin tab, I see more things but still not the whole stack

**Comment by trask** [comment]
Hi @gaeljw, you can click on the profile entries to expand them and see the whole stack. Also, you can increase the number of profile samples by decreasing "Profiling interval" under Configuration > Transactions. Let me know if this is what you are looking for. Thanks.

**Comment by gaeljw** [comment]
I think was I was looking for is the "Profiling interval".
Any method whose execution time is below this interval won't appear in the "profile" section, right?
Still I was expecting to see more things in the "Trace" section.

I have to admit I didn't spend much time on it in the last days, I'll look deeper to better understand the features and how Glowroot works.
Thanks your support @trask ;)
