### ISSUE TITLE
Certificates reloading

### ISSUE THREAD

**Issue by verglor** [glowroot/glowroot#483]
Does glowroot autoreload `grpc-cert.pem` and `grpc-key.pem` when they change ?
I have setup auto renewing let's encrypt certificates and would like glowroot to automatically pick them.
It would be enough if it reload them once a day without watching file changes.

**Comment by trask** [comment]
Hi @verglor, thanks for posting! These are not reloaded currently. What is the downside for you of restarting the central collector to pick up the new cert? Thanks.

**Comment by verglor** [comment]
It's not very convenient workaround. I would need another docker container (with access to docker daemon) to periodically kill glowroot container. Also there will be a short outage. It's doable - just not very nice - it would be much more pleasant if glowroot could handle it by itself without restart. I assume it is a common case to use auto-renewing (let's encrypt) certificates for glowroot.

**Comment by verglor** [comment]
Great, thank you very much @trask !
That was really fast. 👍

**Comment by trask** [comment]
👍 Try out the latest snapshot release when you have a chance [glowroot-central-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.12.3-SNAPSHOT). It should reload the grpc cert 5 seconds after it is updated and log an INFO message to let you know it was reloaded (the 5 second delay is to handle case where the cert/key are copied over one by one).
