### ISSUE TITLE
Displaying Password

### ISSUE THREAD

**Issue by DenysLP** [glowroot/glowroot#484]
Hi,

I have the following problem, in JVM the pool of a datasource is displaying the password, and this would not happen, it should hide as the demo shows.

**Comment by trask** [comment]
Hi @DenysLP, thanks for posting! This should be addressed now in the latest snapshot releases [glowroot-agent-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.12.3-SNAPSHOT) and [glowroot-central-0.12.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.12.3-SNAPSHOT).

(there's a new configuration setting to control mbean attribute masking under Configuration > JVM, but the default `*password*` I believe should take care of your case)
