### ISSUE TITLE
Modal window close button is not fixed anymore

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#490]
Hi @trask ,

After a certain version the scrolling behaviour has changed for the modal windows (slow trace, for example). On 0.10.11 the scrolling is applied to the modal itself and the close button is always visible. On 0.12.2 the scrolling is applied to the browser page and the whole modal window slides

<img width="1392" alt="screenshot 2018-12-07 at 13 46 29" src="https://user-images.githubusercontent.com/6136404/49646026-8f057180-fa26-11e8-9ab3-8df5e4c327db.png">

<img width="1392" alt="screenshot 2018-12-07 at 13 32 20" src="https://user-images.githubusercontent.com/6136404/49645451-acd1d700-fa24-11e8-88ed-e2c9f3b1da4f.png">

**Comment by trask** [comment]
Hi @ionutursuleanu, thanks for posting! The new behavior is the default for modals in Bootstrap, e.g. https://getbootstrap.com/docs/4.1/components/modal/#scrolling-long-content. I agree I like the previous look better, but there were edge cases previously (e.g. #359), and I found it worked better when I changed it to follow the Bootstrap default behavior (I think they know reasons to do it this way).

**Comment by ionutursuleanu** [comment]
Thank you for the explanations @trask

**Comment by trask** [comment]
Re-opening, looking at ways to get the close icon to stay visible within the new structure.
