### ISSUE TITLE
Trace entry copy button not displayed 

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#491]
Hi,

For some trace entries (all text has enough space in preview, it seems) the copy button is not displayed after selecting it.

<img width="1392" alt="screenshot 2018-12-07 at 13 55 45" src="https://user-images.githubusercontent.com/6136404/49646497-e8ba6b80-fa27-11e8-9147-a495eadc6a4b.png">

**Comment by trask** [comment]
Hi @ionutursuleanu, thanks for posting! This is available now in the latest snapshot releases [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT) and [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT).
