### ISSUE TITLE
Startup issue on Tomcat 8/Java 8/CentOS

### ISSUE THREAD

**Issue by phax** [glowroot/glowroot#493]
Hi,
I have issues running that it inside Tomcat with Java 8 on CentOS.
Tomcat startup says:
```
Error opening zip file or JAR manifest missing : /root/glowroot-0.12.3/glowroot.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```
That file exists and is valid. When I launch ` java -jar glowroot.jar` it gives me
```
2018-12-13 22:37:17.832 INFO  org.glowroot - To run Glowroot, you need to add "-javaagent:/root/glowroot-0.12.3/glowroot.jar" to your application's JVM args.
```

That's what I do...
The directory has recursively full rights (777) and the log file was created when launching it standalone.
`logs/glowroot.2018-12-13.log` exists and contains the "how to statements".

`uname -a` gives:
```
Linux XXXXXX 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
OS version is `CentOS Linux release 7.6.1810 (Core)`

Java version:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
Update 1: I tried adding it to "CATALINA_OPTS" and to "JAVA_OPTS" - no difference.

I'm stuck - any help is appreciated.
// Philip

**Comment by trask** [comment]
Hi @phax, thanks for posting! Try putting the glowroot directory somewhere else besides `/root`. The permissions on the `/root` directory typically only let `root` user see anything inside of it.

**Comment by phax** [comment]
Thanks @trask - that did the trick. So no more `/root` :)

**Comment by trask** [comment]
👍
