### ISSUE TITLE
Not getting trace in thread profile

### ISSUE THREAD

**Issue by mayankjain9005** [glowroot/glowroot#495]
Not able to  get class and methods details in thread profile tab. Even the class and methods are getting called with respect to request mapping. we are able to get query details related in query tab but the related classes and methods are not coming in thread profile trace.
PFA the attached screenshot for the same.

Please revert asap.

![1 png](https://user-images.githubusercontent.com/19286983/50158127-463c9b00-02f9-11e9-82f9-08ca0b857201.jpg)
![2 png](https://user-images.githubusercontent.com/19286983/50158131-476dc800-02f9-11e9-8582-16db3b01c368.jpg)
![3 png](https://user-images.githubusercontent.com/19286983/50158132-48065e80-02f9-11e9-8bf6-a8725209c45c.jpg)

**Comment by trask** [comment]
Hi @mayankjain9005, thanks for posting! Try reducing the `Profiling interval` (under Configuration > Transactions). The default is to sample stack traces only once per second.

**Comment by trask** [comment]
Closing, but please re-open if you are still facing this issue. Thanks.
