### ISSUE TITLE
Glowroot deployment and usage in production

### ISSUE THREAD

**Issue by arunavijay** [glowroot/glowroot#497]
Hi,

I have been using Glowroot in my performance environment for a while now and I'm finding it very helpful. As a next step, I would like to have it installed in our production environment. 
Would like to know if anyone has tried this out in production and how successful has the experience been. Looking for inputs from people who have Glowroot deployed in their production environment.

Thanks in advance!

**Comment by trask** [comment]
Hi @arunavijay, I'm using it in production and it is very useful for me :-).

**Comment by ionutursuleanu** [comment]
@arunavijay

The embedded collector is just very easy to install and I'm monitoring a few servers...so I didn't find a major reason for using the central collector.

No docker/container for deployment

**Comment by trask** [comment]
Closing, but please re-open if you still want to discuss. Thanks.
