### ISSUE TITLE
Some questions about Glowroot

### ISSUE THREAD

**Issue by arunavijay** [glowroot/glowroot#498]
Hi,

I have some questions regarding the Glowroot features. 
1) Plugin: Could you please explain what plugins are intended for and how can I use them? Some documentation around plugins would be great too.
2) Is it possible to test asynchronous requests using Glowroot?

**Comment by trask** [comment]
Hi @arunavijay, thanks for posting!

1. Plugins provide instrumentation for different frameworks.
2. Yes, asynchronous requests are supported, e.g. Async Servlets and Netty.
