### ISSUE TITLE
Spring Async annotation support

### ISSUE THREAD

**Issue by gamefundas** [glowroot/glowroot#506]
#90 seems to indicate this was added to spring plugin but I see that it isn't working in my case.
Any chance this was added only to support Spring controller as Async applies to @Service, @Component, @RestController classess as well.

**Comment by trask** [comment]
Hi @gamefundas, the existing support mentioned is for `@Controller` and `@RestController` that return either `Callable` or `DeferredResult`, e.g.

```
    @RestController
    public static class CallableAsyncController {
        @RequestMapping("test")
        public @ResponseBody Callable<String> test() {
            return new Callable<String>() {
                @Override
                public String call() throws Exception {
                    Thread.sleep(5000);
                    return "hello world";
                }
            };
        }
    }
```

Can you provide more details what your code looks like that you want to capture?

Thanks,
Trask

**Comment by trask** [comment]
Are you calling the `@Async` methods from inside of a Servlet request (or something Glowroot is already capturing)?

**Comment by gamefundas** [comment]
Glowroot captures till the point the @Async annotated method is invoked. Beyond that there is no tracing.
For instance my controller endpoint appears and then the controller is invoking a @Service class method (@Async annotation on it). I see the controller method in the trace and then beyond that nothing. No reference of the service method.

**Comment by trask** [comment]
Thanks for the details, I think I understand, I'll try it out.

**Comment by gamefundas** [comment]
Hi @trask do you forsee this as a much bigger change to support.

**Comment by trask** [comment]
Hi @gamefundas, I ran the sample application at https://github.com/spring-guides/gs-async-method/tree/master/complete and the trace picked up the work performed inside of the `@Async` method (see attached trace [trace-20190110-204837-507.zip](https://github.com/glowroot/glowroot/files/2748106/trace-20190110-204837-507.zip)).

(I added transaction instrumentation around `AppRunner.run()` since the sample application is command-line and so there's no default transaction capture, but this shouldn't be necessary if your code is already inside of a glowroot transaction capture, e.g. inside of a Servlet)

What is the `taskExecutor` you are using in your configuration? (e.g. the equivalent of https://github.com/spring-guides/gs-async-method/blob/master/complete/src/main/java/hello/Application.java#L21)

Any other details you can provide?

Thanks,
Trask

**Comment by trask** [comment]
One other question, what do you do with the `Future` that is returned from the `@Async` method? Or are you using the `@Async` method as fire-and-forget and not using the returned `Future`? The reason I ask is that once the transaction ends, nothing else is captured, so if you fire-and-forget, and then the transaction ends immediately afterwards, then nothing would be captured in the `@Async` method.

**Comment by gamefundas** [comment]
Yes I am using a custom executor on the application level using the following so that all Async operations gets executed in this custom threadpool

`
@Configuration
@EnableAsync
public class SpringAsyncConfig implements AsyncConfigurer {
     
    @Override
    public Executor getAsyncExecutor() {
        return new ThreadPoolTaskExecutor();
    }
     
}
`

As for the other question, yes these are independent steps in the processing chain wherein calculations are done off the main thread and then notified to another application via web service calls. My controller returns back to the user immediately as they are coming from a UI. So no future here.

The idea is not to lose trace-ability beyond the aysnc step.

**Comment by trask** [comment]
Yes, this makes sense, you can create instrumentation (under UI > Configuration > Instrumentation) on those methods and use `What to capture` value of `Transaction` and then `What to do if already in a transaction` value of `Capture a new transaction` (see also #396).

**Comment by gamefundas** [comment]
Any way this can be done through the Agent API? I tried using the @Instrumentation annotation but it didn't work.

**Comment by trask** [comment]
Hi @gamefundas, can you post the `@Instrumentation` annotation (with the attributes) that you tried? Thanks.

**Comment by trask** [comment]
Closing, but please re-open if you still want to discuss. Thanks.
