### ISSUE TITLE
Cached Memory

### ISSUE THREAD

**Issue by DenysLP** [glowroot/glowroot#509]
Hi,

Glowroot collector is consuming enough cache memory.
any parameter that limits this consumption?

thankful,

**Comment by trask** [comment]
Hi @DenysLP, thanks for posting! Can you provide some more details? Can you tell which caches are taking up too much memory? Any chance you can take a heap dump and upload so I can have a look?

https://www.dropbox.com/request/l5oO3bu0sfmkQ3nhFYCH

Thanks,
Trask

**Comment by DenysLP** [comment]
Hi

Server is a rhel7 with 8vCpu's and 16GB of RAM.

When the 2 containers are raised, the memory consumption starts in less than 30s, swapping what is available.

I saw that it is the cassandra container, which is receiving many requests.

Are there any configures or improvements to the performance of this container?

Thankful,
