### ISSUE TITLE
admin.json with central collector

### ISSUE THREAD

**Issue by vguna** [glowroot/glowroot#510]
I'm currently trying to auto-setup glowroot using the docker central collector. I thought I could do it with providing a `admin.json` like with the embedded variant, putting it next to `glowroot-central.jar`. But this doesn't seem to be picked up (?). Is this supported? Or how could I auto-setup e.g. username/password for the UI on the central collector?

**Comment by trask** [comment]
Hi @vguna, thanks for posting! This was not documented, so I just added it to wiki https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation:

> If you want to set a username and password before starting up, run java -jar glowroot-central.jar setup-admin-user <username> <password> from inside the glowroot-central directory.

**Comment by vguna** [comment]
Hey, thanks for adding it to the docs!

But that probably means, I have to extend the origin docker image to now make two calls of the jar, right? First time to set the credentials (I guess the jar exits after that?) and second time for the actual service start. Maybe one has to set also some kind of flag, to know not having to do the first credentials set everytime. It would be nice if those credentials could be specified via ENV vars and the docker image would do the rest :).

Hm, what about the other admin settings that normally can be specified via `admin.json`? So thinking about slack integration, SMTP and storage configs?

**Comment by trask** [comment]
Hi @vguna, in the latest snapshot release [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT), you can now place an `admin-default.json` file in the glowroot-central directory and it will be imported on the first startup. Check out the help text at the bottom of UI > Administration > admin.json for some tips, and post back with any questions / issues.

**Comment by vghero** [comment]
Wow nice! Thanks! I'll give it a try and report back.

**Comment by vguna** [comment]
Wow nice! Thanks! I'll give it a try and report back.

**Comment by vguna** [comment]
Hey.
I just tested the SNAPSHOT, setting the `password` like described in the admin UI. But it dies with
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "password" (class org.glowroot.common2.config.ImmutableUserConfig$Json), not marked as ignorable (4 known properties: "passwordHash", "roles", "username", "ldap"])
```
Looks like `password` is not supported but only `passwordHash` :)?

**Comment by trask** [comment]
Re-opening, to support `password` as well.

**Comment by trask** [comment]
`password` should now be supported in the latest snapshot release [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT). Thanks.
