### ISSUE TITLE
navbar issue

### ISSUE THREAD

**Issue by darren-henderson** [glowroot/glowroot#512]
Upgraded from 0.10.10 to 0.12.3

On the current version of chorme ( 71.0.3578.98 ), IE 11, and Edge the navbar takes up most of the screen hight. The text is valigned and the correct size but the brownish container takes up most of the screen. Can't see anything but the navbar without scrolling down.  The navbar returns to the proper size if you narrow the browser down to about 765 pixels.

Works fine on firefox.

Tried on multiple systems.

**Comment by trask** [comment]
Hi @darren-henderson, thanks for posting! I tried in Chrome (same version), IE 11 and Edge, but I'm not seeing this behavior. Do you see the same behavior when you go to https://demo.glowroot.org?

**Comment by darren-henderson** [comment]
I don't see the behavior on the demo and I don't see it in previous versions of glowroot.

After some additional testing I have to assume the problem is on my side. 

We use an apache webserver to proxy in https connections to localhost and if I bypass that it works as it should. Hard to see how a proxy setup would be responsible for this kind of issue but that's what it looks like.

**Comment by trask** [comment]
Are you reverse proxying from a non-root context path? e.g. https://webserver/abc ==> http://glowroot:4000?

**Comment by darren-henderson** [comment]
I am,

https://webserver/gr0/  to http://localhost:4000/

Lightly sanitized version of the proxy config attached. gr0 has the new release, gr1 and gr2 have the older versions and are working fine. 

[proxy.txt](https://github.com/glowroot/glowroot/files/2747188/proxy.txt)

**Comment by trask** [comment]
Are you using the central collector or embedded collector?

**Comment by trask** [comment]
If using embedded collector, have you set `Context path` to `/gr0` under https://demo.glowroot.org/admin/web (or correspondingly in the `admin.json` file)?

If using central collector, have you set `ui.contextPath=/gr0` inside of the `glowroot-central.properties`?

Thanks,
Traks

**Comment by darren-henderson** [comment]
That was not set to "gr0", it was set to "/".  

Setting it to "gr0" still exhibits the problem and leads to the links being incorrect, (they all contain "/gr0/gr0/") though they continue to work. I believe the reason that it functions either way is down to the "proxyHTMLURLMap / /gr0/"


It feels like something is having problem in non-gecko based browsers determining the screen size when behind the proxy. 

I'll try comparing the source of the page from behind the proxy and bypassing the proxy to see if that turns anything up.

**Comment by trask** [comment]
Hi @darren-henderson, I tried the same proxy setup and ran into the same bizzare navbar issue! I was able to fix the css so it should work now in the latest snapshot release [glowroot-agent-0.13.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.0-SNAPSHOT).

Also, I remembered how the `Administration > Web > Context path` works.  If you set the `Context path` to `/gr0`, then the UI will run on `http://localhost:4000/gr0` and then you can reverse proxy from `https://localhost/gr0` ==> `http://localhost:4000/gr0` which avoids having to do any url rewriting, e.g. you don't need `ProxyHTMLURLMap`.

Thanks again for reporting this!
