### ISSUE TITLE
glowroot cause exception for Bitronix

### ISSUE THREAD

**Issue by WillWei1983** [glowroot/glowroot#513]
After release of 0.9.25, glowroot cause glowroot$getStatementMirror() exception for bitronix when init the datasource.
0.9.24 works well.

**Comment by trask** [comment]
Hi @WillWei1983, thanks for posting! I tried to reproduce the error using `spring-boot-sample-jta-bitronix` (which uses bitronix btm 2.1.4) at https://github.com/spring-projects/spring-boot/blob/v2.1.2.RELEASE/spring-boot-samples/spring-boot-sample-jta-bitronix/src/main/java/sample/bitronix/SampleBitronixApplication.java, but did not get any error.

What version of bitronix btm are you using? What underlying data source / jdbc driver are you using? Can you post the full stack trace of the error? Thanks.

**Comment by WillWei1983** [comment]
Hi @trask , Thanks for your reply, I am using the latest version The BTM 3.0 of custome build from btm's source https://github.com/bitronix/btm

**Comment by WillWei1983** [comment]
I have also tested in the btm2.1.4, it works well with any version of the glowroot, but the btm3.0 is not since the 0.9.25.

**Comment by gagaboy** [comment]
the same error with btm branch 2.2.0 and  master(3.0.0-SNAPSHOT)

**Comment by trask** [comment]
Thanks! I was able to repro today using btm 3.0.0-SNAPSHOT. I have a local fix, will push to master (and update this issue) in the next day or two.

**Comment by trask** [comment]
This should be fixed now in the latest snapshot release [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT).

**Comment by gagaboy** [comment]
It works，thx

**Comment by trask** [comment]
👍
