### ISSUE TITLE
Standalone/desktop Java applications monitoring with glowroot

### ISSUE THREAD

**Issue by AditiS06** [glowroot/glowroot#515]
Can we monitor standalone/desktop java applications using glowroot?
If yes, what is the process? and where on glowroot UI can we track the classes and methods details?

**Comment by Niks1820** [comment]
How do you start the standalone / desktop java application ? Is the aaplication file type .jar or some other ?

**Comment by Niks1820** [comment]
Hye, the UI opens by default at http://localhost:4000 and if you have not mentioned the agent name then on the transactions the names will appear, else if you have given the agent id name then you need to change the drop downs. Also you might need to refresh the screen to see the transaction data.

**Comment by AditiS06** [comment]
Hey,I don't see any data under transactions -> Web for the custom date range for my standalone application.

**Comment by Niks1820** [comment]
The data will appear : 
in startup drop down screen when there is some transaction for starting the application
in web drop down screen when your application calls some method or completes a transaction.
You can customize the transaction display / error displays and other UI displays by updating the config json by going into the settings and updating the values there.

**Comment by trask** [comment]
Hi @AditiS06, if your standalone application is handling servlet requests (e.g. a spring boot application), then Glowroot will capture these under Web. If your standalone application is running quartz jobs or spring batch jobs (or something else Glowroot knows about already) then it will capture these under Background.

If your application is doing something else, you will need to add at least one instrumentation (under Configuration > Instrumentation) and specify `Transaction` under `What to capture` in order to tell Glowroot what you consider a "transaction". Let us know if this helps, or if you are still having any issues. Thanks.

**Comment by AditiS06** [comment]
Thanks Trask, using instrumentation I can see class and method details are getting captured under Transactions -> Startup.
I have one last question, is it possible to instrument all the classes of the desktop application in one go? Currently what I have done is, I have created different instrumentations per java class depending on the functionality (Application is not spring boot/quartz jobs/spring batch jobs), but what if I want to instrument it by default for all the java classes and tracking should be done on the basis of java classes getting called in the back end?

**Comment by trask** [comment]
Hi @AditiS06, you can use wildcards when defining the instrumentation, but instrumenting too many classes/methods can impact performance, so I suggest isolating the classes/methods that handle your application's "transactions". Can you give high level what a "transaction/request/job" means in your application that you want to capture? Do you use any frameworks that listen for requests/jobs and call your application code? Thanks.

**Comment by AditiS06** [comment]
Hi Trask, So my application is core java application, the UI is developed using swing technology. The tool creates/updates and deletes the test cases, configure database connection details, file details inside the test cases and finally execute the test cases. 
     With transaction, I mean functionality. E.g: Create test case is one functionality which I am triggering on Swing UI, so first, main method of my UI class is getting called and from there the object of test creation class is getting created, which is accessing functions of test case class. With glowroot when I had done instumentation for my UI class it gave all the methods called for the UI class, but to fetch the details of test case creation class I had to write separate instrumentation. 
   Can you please help on how to sort this?

**Comment by trask** [comment]
Hi @AditiS06, is there a common (or set of common) callback interfaces, e.g. `ActionListener`, that could be instrumented?

**Comment by AditiS06** [comment]
Yes, can you give an example of ActionListener instrumentation?

**Comment by trask** [comment]
Try importing this under UI > Configuration > Instrumentation:

```
{
  "captureKind": "transaction",
  "alreadyInTransactionBehavior": "do-nothing",
  "transactionType": "Swing",
  "transactionNameTemplate": "Action listener: {{this.class.name}}",
  "traceEntryMessageTemplate": "Action listener: {{this.class.name}}",
  "timerName": "action listener",
  "className": "java.awt.event.ActionListener",
  "methodName": "actionPerformed",
  "methodParameterTypes": [
    "java.awt.event.ActionEvent"
  ]
}
```

**Comment by AditiS06** [comment]
Thanks Trask it worked for few of the transactions but not for all.
I have done following settings to capture transactions: Can't we capture the transactions, which took **less than 1 milliseconds?**

![transaction_configuration](https://user-images.githubusercontent.com/46598865/51467702-33533580-1d93-11e9-9b59-7d9e01a721b2.JPG)

**Comment by trask** [comment]
Slow threshold can be set to 0

**Comment by trask** [comment]
Hi @AditiS06, I think you are talking about `Profiling interval`?

When you set `Slow threshold` to `0`, it will capture traces under the `Slow traces` tab for all transactions.

When you open those traces, the `Thread Profile` section at the bottom of those traces is what is controlled by the `Profiling interval`.

Why do you want to see `Thread profile` for traces < 1 millisecond? The sampling is randomized (~based on the `Profiling interval` setting). So some traces < 1 millisecond may have one sample captured, some may not. All profile samples are aggregated under the `Thread profile` tab to the right of the `Slow traces` tab.

Does this help?

Thanks,
Trask

**Comment by trask** [comment]
Closing, but please re-open if you still want to discuss. Thanks.
