### ISSUE TITLE
Glowroot Central's Collector Address can use nginx reverse proxy?

### ISSUE THREAD

**Issue by yosaku01** [glowroot/glowroot#517]
I have installed two Glowroot Central  instances and their collector address is http://A:8181,http://B:8181. And I want to use nginx to reverse proxy these two instances' address. Is the two addresses are gprc address? 
If yes, how can I configure grpc proxy settings in nginx server? 
If no,  when I access the nginx server's proxy address(http://C:7000) and the nginx server return 400 error, need I use http_v2 protocol?
![image](https://user-images.githubusercontent.com/1314082/51825859-a83ce700-2320-11e9-8bca-ce26080ec21d.png)

**Comment by trask** [comment]
Hi @yosaku01, thanks for posting!

Check out https://www.nginx.com/blog/nginx-1-13-10-grpc, I think you want something like:

```
upstream grpcservers {
    server A:8181;
    server B:8181;
}
 
server {
    listen 80 http2;

    location / {
        grpc_pass grpc://grpcservers;
    }
}
```

**Comment by yosaku01** [comment]
@trask, Thank you very much. I have established the grpc servers load balance with Nginx 1.14.0.
And we need install ngx_http_v2_module into nginx before configure load balance.

**Comment by trask** [comment]
👍
