### ISSUE TITLE
Does glowroot agent collects the http rest request information based on servlet specification?

### ISSUE THREAD

**Issue by yosaku01** [glowroot/glowroot#519]
I have collected the http rest request information using glowroot agent. 

But when I developed a http rest interface in Mule ESB container based on its custom http component, I found the rest request information can not be collected.

![image](https://user-images.githubusercontent.com/1314082/51967784-37760600-24ab-11e9-9d61-fce95092bf64.png)

Does glowroot agent collects the rest request info based on standard servlet component, such as Tomcat, JBoss? If I want to collected the rest request in Mule ESB Container, need I use glowroot api in my source code?

**Comment by trask** [comment]
Hi @yosaku01, thanks for posting! Yes, the [servlet plugin](https://github.com/glowroot/glowroot/tree/v0.13.0/agent/plugins/servlet-plugin) captures requests by instrumenting based on the Servlet API.

**Comment by yosaku01** [comment]
Dear trask, thank you for your answer. If I want to captures the http request based on non-servlet  spec, need I use the glowroot api in my application?

**Comment by trask** [comment]
Hi @yosaku01, you can instrument either your application code or the library code (in this case mule). There are a few different options when it comes to instrumentation (see https://glowroot.org/instrumentation.html), I generally recommend trying the Instrumentation UI to start out with, at least for experimenting.

**Comment by yosaku01** [comment]
Thank you very much, dear trask. I will try instrument in my Mule ESB code.
