### ISSUE TITLE
New plugins

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#52]
Hi,

I wrote several additional plugins for glowroot, instrumenting the following frameworks:
- JSF
- JSP (views)
- Grails (working on)
- and Spring based on (https://github.com/trask/glowroot-agent-spring-plugin)

Maybe it is possible to add those to the glowroot repo, or do you have other ideas.

**Comment by trask** [comment]
These would be great additions.  Go ahead and submit pull request per plugin.  Thanks.

**Comment by trask** [comment]
You can put them under [agent-parent/plugins](/glowroot/glowroot/tree/master/agent-parent/plugins) along side the other plugins.  And add them to the [parent pom](/glowroot/glowroot/tree/master/pom.xml#L49), and add them to the [distribution pom](/glowroot/glowroot/blob/master/agent-parent/distribution/pom.xml#L27), which should cover integrating it into the build.
