### ISSUE TITLE
what is logging

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#525]
Hello

Can you tell me what is exactly "logging" please

![image](https://user-images.githubusercontent.com/38753048/52783470-4683b900-3052-11e9-8907-8b2385337e7a.png)

**Comment by trask** [comment]
Hi @lfen21, thanks for posting!

The [logging plugin](https://github.com/glowroot/glowroot/tree/v0.13.0/agent/plugins/logger-plugin/src/main/java/org/glowroot/agent/plugin/logger) captures logging calls made to JUL, Log4j (1 and 2) and Logback.

**Comment by lfen21** [comment]
Hi

Ok but the time is the time to write it on disk ?

I have some time on that plugin 

Envoyé de mon iPhone

**Comment by trask** [comment]
Most likely, but the loggers do a bit more internally before actually writing to disk (e.g. formatting the message). I recommend looking at the thread profile tab next and filter by `log4j`, `logback` or `java.util.logging` to get more details on where exactly the time is spent.

**Comment by trask** [comment]
Closing, but please re-open if you still want to discuss. Thanks.

**Comment by aslam-ahmed** [comment]
First of all thanks for creating such a wonderful tool. It really helps a lot in troubleshooting performance issues.

1.  Is there any way to turn off logging completely?
2. How to configure logging levels for this plugin? It seems like it capture trace level logs by default.
3. If there is  a way to configure logging, is it possible to tune for certain classes or packages?

Please do let me know if the above features are not available then how to contribute for them. Happy to be a part of this, keep doing the good work.
