### ISSUE TITLE
[New Feature] JFR Recording Support

### ISSUE THREAD

**Issue by goldentigerindia** [glowroot/glowroot#527]
Can we have JFR recording support implemented in glowroot? It would work with JDK that has JFR implemented. Basically Azure Zulu 8,9,10 jdk, open jdk 11, oracle jdk 8,9,10. Also if we could parse the JFR and show a flame graph it would be an added advantage. We could have something like the HeapDump option .

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
