### ISSUE TITLE
ldap user test validation failed

### ISSUE THREAD

**Issue by yosaku01** [glowroot/glowroot#528]
Dear trask, 
      I have used ldap plugin to validate the login user ,my ldap settings is following
      
![image](https://user-images.githubusercontent.com/1314082/52940354-4dd3fb00-33a1-11e9-8722-52733d469f00.png)
     I saved the ldap settings and validation the settings. I used my ldap account and password.
The result message shows:
     **_Authentication succeeded, but the LDAP group query did not find any groups for this user_**
    And I still can not login into glowroot central UI with ldap account, the error message is **_password incorrect._**
     But the same ldap settings is valid in Jenkins' ldap plugin. 
     Can you explain why the user group validation failed? Because I can not find the related source code in glowroot repository. 
     We validated this account  successfully with client code in Java and python.
     Yours rick

**Comment by trask** [comment]
Hi @yosaku01, thanks for posting! From the Jenkins LDAP Plugin docs, it looks like they support two different mechanisms for retrieving the groups of a given user, [Search for groups containing user](https://wiki.jenkins.io/display/JENKINS/LDAP+Plugin#LDAPPlugin-Searchforgroupscontaininguser) and [Parse user attribute for list of groups](https://wiki.jenkins.io/display/JENKINS/LDAP+Plugin#LDAPPlugin-Parseuserattributeforlistofgroups). Glowroot LDAP only supports the first mechanism "Search for groups containing user", so "Group search filter" needs to be a search filter (with `{0}` placeholder).

**Comment by yosaku01** [comment]
Dear trask, 
         Thank you for answering my question. I have set the Group search filter to "cn={0}" and register a new account same as the ldap account. And the validation test passed. 
         Originally I have thought the LDAP plugin supports SSO function, so I did not register new glowroot account first. Can the Glowroot supports SSO function? Then we need not register user account and only assign role to ldap user account.
         Yours Rick

**Comment by trask** [comment]
Hi @yosaku01, you don't need to create glowroot users if you are using LDAP. What was the issue before you created the glowroot user? Thanks.

**Comment by yosaku01** [comment]
Dear trask, 
      If we did not create glowroot user account, only bind ldap server. When I login in with ldap account, the error message is "Password incorrect"(shown as below graph).       
![image](https://user-images.githubusercontent.com/1314082/52985836-7b1bba00-3430-11e9-8d98-568b8b92fc8d.png)
       But when I create glowroot account same as the ldap account and use ldap password, I login in successfully.  
![image](https://user-images.githubusercontent.com/1314082/52985908-d5b51600-3430-11e9-9396-a60f800bc6ac.png)
![image](https://user-images.githubusercontent.com/1314082/52985944-0006d380-3431-11e9-95a9-2fc698a4871f.png)
      Best Regards,
      Yours Rick

**Comment by trask** [comment]
What do you get when you "Test LDAP authentication" (at bottom of LDAP configuration page) with the user you are trying to log in with?

**Comment by yosaku01** [comment]
Dear trask, 
         If I did not create user account in glowroot, when I execute ldap validation, the error message is shown as below
         
![image](https://user-images.githubusercontent.com/1314082/52986560-ea92a900-3432-11e9-931d-dd508e312454.png)
        And when I create the user account and re-test, the error message is the same, and I can login in successfully.
        And there is a new problem. If I login in with administrator account first and accesses the admin pages(Such as integration page) and re-login with another non-administrator account, the first page is still the last accessed page(admin pages), "An error happened" message will show.
        
![image](https://user-images.githubusercontent.com/1314082/52986810-d7cca400-3433-11e9-9474-63b1c53e8aa1.png)

![image](https://user-images.githubusercontent.com/1314082/52986827-eca93780-3433-11e9-8cac-e81c7676757c.png)
        Can glowroot central creates a main page as every user account's default login page, and when the user accesses other pages,  the glowroot will checks his/her role and judge whether he/she can access these pages?
        Best Regards,
        Yours Rick

**Comment by trask** [comment]
"The LDAP group query did not find any groups for this user" probably means the LDAP "Group search filter" that you configured is not correct.

**Comment by yosaku01** [comment]
Dear trask,
       For LDAP Group Search Filter, I used "(&(cn={0})(objectclass=group))" or "(&(member={0})(objectclass=group)), the error message is the same. How can I config the Group Search Filter?
       In Jenkins, the Group Search Filter is **_(&(memberOf=cn=jenkins,ou=Group,dc=cn,dc=company,dc=com))_** and it works.
      Best Regards,
      Yours Rick

**Comment by trask** [comment]
Hi @yosaku01, can you try in Jenkins using the option [Search for groups containing user](https://wiki.jenkins.io/display/JENKINS/LDAP+Plugin#LDAPPlugin-Searchforgroupscontaininguser) instead of the option [Parse user attribute for list of groups](https://wiki.jenkins.io/display/JENKINS/LDAP+Plugin#LDAPPlugin-Parseuserattributeforlistofgroups). Glowroot LDAP only supports the first option, so if you can get Jenkins to work with the first option I think the same should work with Glowroot.

**Comment by yosaku01** [comment]
Dear trask, 
           Thank you very much, I will try Search for group containing user policy. If there is still some problems I will reply to you.
           Best Regards,
           Yours Rick

**Comment by trask** [comment]
Closing, but please re-open if you are still having any issue. Thanks.
