### ISSUE TITLE
Issue encountered adding new Gauge that contains double quotes in name

### ISSUE THREAD

**Issue by carl-payne** [glowroot/glowroot#529]
Attempted to add org.xnio:type=Xnio,provider="nio",worker="default",address=* to monitor http port usage on WildFly 15 as new Gauge, but glow root fails with error attached and config.json has the following entry:

    {
      "mbeanObjectName": "org.xnio:type=Xnio,provider=\"nio\",worker=\"default\",address=*",
      "mbeanAttributes": [
        {
          "name": "ConnectionCount"
        }
      ]
    }

Suspect issue related to use of double quotes in mbeanObjectName

Please review and advise
[Glowroot-error.txt](https://github.com/glowroot/glowroot/files/2879861/Glowroot-error.txt)

**Comment by trask** [comment]
Hi @carl-payne, thanks for reporting this! I think it should be fixed now in the latest snapshot releases  [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT) and [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT).

**Comment by carl-payne** [comment]
Hi trask, I can confirm the latest snapshot release addresses the issue reported, and thanks again for such a speedy response, keep up the good work !!!

**Comment by trask** [comment]
👍
