### ISSUE TITLE
Glowroot SMTP Configuration - SendFailedException: Invalid Addresses

### ISSUE THREAD

**Issue by ecedwards** [glowroot/glowroot#533]
Hello,

I just recently configured the SMTP settings, (which I tested before with same configuration on version 0.10 and had no problems), and it's giving me the following error. 

SendFailedException: Invalid Addresses

I am using the same SMTP server, and same email address to test this scenario. Unfortunately, I do not see any logs or stacktrace for further troubleshoot.

**Comment by trask** [comment]
Hi @ecedwards, thanks for posting! Do you get this error when sending a test email from the bottom of the SMTP configuration page?

**Comment by ecedwards** [comment]
Yes, that is correct.

**Comment by trask** [comment]
Just want to make sure, you're using a full email address, including the domain, e.g. `test@example.com`?

**Comment by ecedwards** [comment]
Yes, full email. Tried with different addresses as well.

**Comment by trask** [comment]
Hi @ecedwards, is there a stack trace that you can post? Also, are you using the embedded collector or the central collector, and what JVM / Java version are you running with? Thanks.

**Comment by ecedwards** [comment]
No, it seems kind of weird as it doesn't have any catch when the error happens. 

I am using "Central collector version 0.13.1-SNAPSHOT, commit daa1e38d9e", with Java version: "openjdk version "1.8.0 191""

Thanks for the constant updates.

**Comment by trask** [comment]
Hi @ecedwards, I think this error is coming from your SMTP server, see https://stackoverflow.com/a/15132063. Can you confirm that the older version 0.10.0 still works with the same SMTP configuration?

**Comment by ecedwards** [comment]
I will try again with an older version to see if triggers the same error. Will let you know.

**Comment by ecedwards** [comment]
Just tested with an earlier version (0.13.0) and received the same error. Seems it is related to the SMTP server. Was looking into a similar article stating the same. I'll talk with my Sysadmin Team. Thanks for all the assistance.

**Comment by trask** [comment]
Thanks for the update!
