### ISSUE TITLE
How debug  glowroot agent with idea

### ISSUE THREAD

**Issue by linzwgit** [glowroot/glowroot#535]
I want learn your glowroot agent code. but I can't use your code to debug. if you have developer document. can U show me please. thanks

**Comment by trask** [comment]
Hi @linzwgit, thanks for posting! One option is remote debugging, e.g. run your application with `-Xdebug -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=y -javaagent:path/to/glowroot.jar`, and then attach to it from your IDE/debugger. If you download the glowroot source jar https://search.maven.org/remotecontent?filepath=org/glowroot/glowroot-agent/0.13.1/glowroot-agent-0.13.1-sources.jar then you can tell your IDE/debugger where to find the source jar, and then you can put breakpoints on glowroot code and step through it.

**Comment by vancezhao** [comment]
Thanks! @trask Really helps.

**Comment by linzwgit** [comment]
Tks! @trask its goods for mine

**Comment by trask** [comment]
👍
