### ISSUE TITLE
Respons time other function

### ISSUE THREAD

**Issue by ynsdl** [glowroot/glowroot#540]
I spend so many time with other options. What does it means ?
![glowrootcapture](https://user-images.githubusercontent.com/46422366/53566339-ea01bd00-3b6c-11e9-9c3e-46f68fc4a32f.jpg)

**Comment by trask** [comment]
Hi @ynsdl, thanks for posting! Can you look over issue #365 and post back here on this issue with any additional questions?

**Comment by ynsdl** [comment]
Thanks. I understand what is other.

**Comment by trask** [comment]
👍
