### ISSUE TITLE
possibility to do adhoc report with transaction web and background

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#541]
Hi

All in the title :)

Thanks

**Comment by trask** [comment]
Hi @lfen21, just want to clarify, you want to see those results broken out per transaction type? or you want the metrics to represent all transactions of both types? If the latter, can you explain your use case? I'm interested to understand what cases it makes sense to look at a single number that represents both Web and Background transactions. Thanks.

**Comment by lfen21** [comment]
Hi

i have some web transaction which calls background transaction of another application

**Comment by trask** [comment]
Hi @lfen21, it sounds like the other application's transaction is not really a background transaction, see #545?

**Comment by lfen21** [comment]
yes it's the same thing, it's a response of ejb call

**Comment by trask** [comment]
Great! This change (#545) is now available in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).
