### ISSUE TITLE
simpl command_line -> Glowroot not showing transaction timings - #1

### ISSUE THREAD

**Issue by bostjans** [glowroot/glowroot#547]
Hi. Have a simple command-line Java App (one Class). It processes some data via JDBC and Hazelcast.
According to Glowroot instructions I did: Agent install (with Embedded Collector).
.. and Glowroot is normaly accessible via Port 4000.
Ok .. al fine.
Then - according to https://glowroot.org/instrumentation.html - I added:

@Instrumentation.Timer("myprocess")
..

.. to one of my method(s).
And .. nothing is shown in "Transactions" page.
So .. I em not clear .. what else do I need to do, to see the count/timings of my method?

**Comment by trask** [comment]
Hi @bostjans, thanks for posting!

Try `@Instrumentation.Transaction`, that will demarcate a transaction. `@Instrumentation.Timer` is used to create additional timers inside of a transaction.

**Comment by bostjans** [comment]
.. no shit (excuse my language), that helped -> it works! Tnx. :-)
