### ISSUE TITLE
Error HTTP 404 when trying to access to an incident

### ISSUE THREAD

**Issue by calendorn** [glowroot/glowroot#549]
Hello:

We are trying glowroot central collector and we've seen that a new incident was created for one of the agents. When we try to access to the URL in the incident it gives us a 404.

Our glowroot central URL is http://xxxxxx:8080/glowroot-central/

And the link for the incident is "http://xxxxx:8080/error/messages?xxxxx" instead of "http://xxxxx:8080/glowroot-central/error/messages?xxxxx" . It's using full path instead of relative one.

Thanks and regards

**Comment by trask** [comment]
Hi @calendorn, thanks for reporting this! I think it should be fixed now in the latest snapshot release [glowroot-central-0.13.2-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.13.2-SNAPSHOT).
