### ISSUE TITLE
Possibility to check implementation version before weaving class

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#55]
Sometimes you only want to add an advice to a specific class in a specific version of a library. Weaving can be different for Spring 3.0 than for Spring 4.0. Is it interesting to add ImplementationVersion check in `ClassAnalyzer` if a class should be enhanced: `clazz.getPackage().getImplementationVersion()`

Considered should be if the version need to be specific or semantic version can be used, maybe a startWith check?

**Comment by trask** [comment]
Relying on the Implementation-Version in the manifest could be problematic for uber jars.

In cases where the same method exists in both Spring 3.x/4.x but you only want to capture pointcut for one of them, you could try checking which one is present at runtime in a ClassMeta constructor (e.g. via one-time reflection), storing the result in the ClassMeta, and passing the ClassMeta via @BindClassMeta to the pointcut's @IsEnabled method, returning true/false from the @IsEnabled method based on the stored value in the ClassMeta.
