### ISSUE TITLE
Debug the Glowroot Central

### ISSUE THREAD

**Issue by AbleSteven** [glowroot/glowroot#552]
Hi, I want to do a second development on the Glowroot Central . I use IntelliJ Idea . And I have downloaded the source codes . My question is how to run the Glowroot Central in IntelliJ . By the way, I have run the Central Collector using the downloaded jar file on my local host, so it indicates that my local host has the environment to run the Central Collector .
And where can I get some source codes analysis tutorial?
  Excepting the answer. Thanks !!

**Comment by trask** [comment]
Hi @AbleSteven, you can run the Central Collector in your IDE by running `org.glowroot.central.Main`.

**Comment by trask** [comment]
Hi @AbleSteven, I just tried importing Glowroot into Intellij (I normally use Eclipse), and I noticed that Intellij doesn't apply maven profiles that do not have an `<id>` tag, and so the central collector module was not being imported. I fixed this (added `<id>` tag to maven profiles where missing). Try updating to master and re-importing again.

**Comment by AbleSteven** [comment]
Thanks! I appreciate your help!
