### ISSUE TITLE
Differences breaktime mongoquery time and spring controller mongo percentes

### ISSUE THREAD

**Issue by ynsdl** [glowroot/glowroot#556]
Hi,

5149 transactions spend time %99,9 at spring controller and inside thread profile ı can see % 63,9 and %35,8 com.mongodb. I understand that lost of time pass in mongodb. 

![glowrott1](https://user-images.githubusercontent.com/46422366/54692728-8698f880-4b36-11e9-9653-93d32a26187b.jpg)

but at respons time screen mongodb query time seems too short 0,0021 ms or %0. I dont understand differences. if ı spend lots of time in spring controller and spring controller spend much time in mongo why it seems too short or %0 on screen

![glowrott](https://user-images.githubusercontent.com/46422366/54692908-c9f36700-4b36-11e9-8722-05303315f8d0.jpg)

**Comment by trask** [comment]
Hi @ynsdl, thanks for posting! This does seem odd. Can you export a couple of the slow traces and email them to me, maybe the details will give me some clues. Thanks.

**Comment by ynsdl** [comment]
Hi @trask , ı sended an email to you. Thanks for your support

**Comment by trask** [comment]
Thanks @ynsdl, what version of Mongo Java driver are you using?

**Comment by ynsdl** [comment]
we are using mongo java driver 3.2.2

Trask Stalnaker <notifications@github.com>, 20 Mar 2019 Çar, 22:39
tarihinde şunu yazdı:

**Comment by trask** [comment]
Hi @ynsdl, thanks again for reporting this! I think it is fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).

**Comment by ynsdl** [comment]
thank you. I will update
