### ISSUE TITLE
How does the Central Collector work?

### ISSUE THREAD

**Issue by AbleSteven** [glowroot/glowroot#558]
Hi @trask , could you tell me the flows about how the Central Collector receives the data send by an Agent, and how the Central Collector knows whether a certain Agent is health, and how the Central Collector supports high concurrency when there are thousands of agents need to be monitored, please. 
By the way, could you tell me the max agent number the Central Collector can monitor, please?
Looking forward to your answer!
Thanks!

**Comment by AbleSteven** [comment]
Hi @trask , could you tell me the flow about how the Central Collector receives the data send by an Agent, and how the Central Collector knows whether a certain Agent is health, and how the Central Collector supports high concurrency when there are thousands of agents need to be monitored, and the a max agent number the Central Collector can monitor, please?
Looking forward to your answer!
Thanks!

**Comment by trask** [comment]
Hi @AbleSteven,

(1) the agent sends data to the central over gRPC/HTTP2.
(2) there are various alerts you can set up for agent health, e.g. garbage collection time, but if you're talking about the "Heartbeat" alert, that is based on the agent usually sending gauge data every 5 seconds to the central collector.
(3) everything is stored (e.g. sharded) in the central collector based on the agent id, so it scales well. You will need more CPU/memory of course as you add more agents.

Thanks,
Trask

**Comment by AbleSteven** [comment]
Hi @trask , 
I mean:
(1) What is the engine class and method the agent sends heartbeat to the Central Collector?
(2) What is the engine class and method the Central Collector receive the heartbeat from an agent?
Just giving me some hints is OK!
By the way, I am an Java Engineer, and does it need some NodeJS technology to develop the Central Collector?
Thanks a lot,
AbleSteven

**Comment by trask** [comment]
(1) https://github.com/glowroot/glowroot/blob/v0.13.1/agent/core/src/main/java/org/glowroot/agent/init/GaugeCollector.java#L367

(2)
https://github.com/glowroot/glowroot/blob/v0.13.1/central/src/main/java/org/glowroot/central/CollectorServiceImpl.java#L388

NodeJS is only used during the UI compilation (e.g. compiling SASS to CSS).

**Comment by AbleSteven** [comment]
And where is the Kafka used in the Glowroot ?

**Comment by trask** [comment]
It is only used by the tests, in order to test the kafka instrumentation.

**Comment by AbleSteven** [comment]
And do you have any idea about the max agent number the Central Collector can support?
Thanks!

**Comment by AbleSteven** [comment]
And in my IntelliJ, there are some import errors resulted by missing dependences, but in the local maven repository, the certain jar file, `glowroot-wire-api-0.13.2-SNAPSHOT.jar`, is existing in the certain directory, `org\glowroot\glowroot-wire-api\0.13.2-SNAPSHOT`, however, the compilation is success, the Central Collector can be run by IntelliJ, and it works well.
I think maybe something confuse the IntelliJ. Do you have any ideas about this case?
Thanks a lot!
![image](https://user-images.githubusercontent.com/43262036/54777502-67d95580-4c4d-11e9-9728-a06cd8b13432.png)

**Comment by trask** [comment]
I haven't done any scalability benchmarking of the central collector itself.

As a rough point of reference, I'm running ~100 agents pointing to a central collector that has 2 cores and 16 GB memory (it runs both the central collector and Cassandra).

Not sure about the IDE errors, those are generated sources, so I'd try "Generate Sources and Update Folders for All Projects":

![image](https://user-images.githubusercontent.com/218610/54792142-210e4000-4bfa-11e9-9f66-05d292916f7e.png)

**Comment by AbleSteven** [comment]
Hi @trask ,
Unfortunately, the operation above doesn't work for me. However, let it go.
And there is still some questions confuse me:
(1) What are the functions of the annotations, such as `@Instrumentation.Transaction(transactionType = "gRPC", transactionName = "Gauges", traceHeadline = "Collect gauge values: {{0.agentId}}", timer = "gauges")`, where is the engine class or method for detecting these annotations. For example, in the SpringMVC we can use Interceptors to detect whether the called methods have certain annotations, and how about the Central Collector?
(2) When an Agent's "heartbeat" loses, whether does the Central Collector pull the "heartbeat" data on it's own or just check the data update time from the Cassandra. And what method is the engine method?
Thanks a lot!
I appreciate your kindness!

**Comment by gamefundas** [comment]
Hi @trask , I am also planning to move to a central collector architecture and one of the questions I have is how do the agents react in the event of collector outage. Is the application agnostic to the existence of the central collector and can operate fine without it? 

I am assuming the agent might spit out errors indicating the failure to connect but the application wont have any trouble operating on its own and can even start with the agent, without the central collector running.

This is important as I am thinking at no point in time my application services should be affected by the monitoring agents/collector server.

**Comment by trask** [comment]
Hi @AbleSteven,

(1) `@Instrumentation.Transaction` are processed here https://github.com/glowroot/glowroot/blob/v0.13.1/agent/core/src/main/java/org/glowroot/agent/weaving/Weaver.java#L181

(2) https://github.com/glowroot/glowroot/blob/v0.13.1/central/src/main/java/org/glowroot/central/CentralAlertingService.java#L239

**Comment by trask** [comment]
Hi @gamefundas, all of your assumptions are correct!

**Comment by AbleSteven** [comment]
And one more question:
How does Central Collector return pages to browser? I mean in a browser when I enter `localhost:4000` I will get the index.html page, how does it work. I found the index.html file path, but can't find what class and method return the index.html to browser.
And if I change the `gRPC` framework to another framework, such as `netty` which uses `Socket` for data transmission, can the Central Collector still work well? You know `TCP` is much faster and efficient than `HTTP`, and `netty` can use `TCP`. Many main monitoring software prefers to `TCP` rather than `HTTP`, such as Zabbix.

**Comment by trask** [comment]
Hi @AbleSteven,

(1) See https://github.com/glowroot/glowroot/blob/v0.13.1/ui/src/main/java/org/glowroot/ui/CommonHandler.java#L147 and https://github.com/glowroot/glowroot/blob/v0.13.1/ui/src/main/java/org/glowroot/ui/IndexHtmlHttpService.java
(2) gRPC uses HTTP/2, so doesn't suffer HTTP overhead.

**Comment by calendorn** [comment]
> Hi @trask , I am also planning to move to a central collector architecture and one of the questions I have is how do the agents react in the event of collector outage. Is the application agnostic to the existence of the central collector and can operate fine without it?
> 
> I am assuming the agent might spit out errors indicating the failure to connect but the application wont have any trouble operating on its own and can even start with the agent, without the central collector running.
> 
> This is important as I am thinking at no point in time my application services should be affected by the monitoring agents/collector server.

In case of outage the application works perfectly, it only prints the error that it cannot connecto to central collector in the log.

@Trask We are using the Central Collector with 3 Cassandra nodes and 6 glowroot agents that has a lot of traffic (100GB of disk in 3 weeks so far) and we are having problems in Cassandra with compactions, there are a lot of compactions for the trace_entry_v2 table (some of 2GB+) and Cassandra nodes are using a lot of CPUs for these compactions (machines has 4vCPUs and 3GB for the JVM). Any advise on how to tune Cassandra for glowroot?

Thanks and regards

**Comment by gamefundas** [comment]
Thanks @calendorn for clarifying. 

You have an interesting revelation about the central collector utilization. I didn't think about this enough and may across this myself as I start wiring my agents to the central collector. I have more than 100 agents running on my VPC. So this might become bottleneck and hard to manage.

At the same time I dont know where to set the data retention period. Does Cassandra cleanup/purge on its own based on some configuration?

**Comment by trask** [comment]
Hi @calendorn, what version of Glowroot central collector are you running? What's the breakdown of the 100GB per table? Thanks.

**Comment by calendorn** [comment]
Hi @trask, the version of Central Collector is 0.13.2-SNAPSHOT.

This is the breakdown of the tables, as you can see trace_entry_v2 is 85% of the total (86G)

[Table_space_27032019.txt](https://github.com/glowroot/glowroot/files/3012199/Table_space_27032019.txt)

**Comment by trask** [comment]
Thanks @calendorn!

Based on comparing sizes of trace_tt_error_count (229 MB) to trace_tt_slow_point (only 18 MB), I'd guess that most of those trace_entry_v2 records are from error traces.

Are you seeing a huge number of error traces in the Glowroot Central UI, under Error > Error traces? (check the different transaction types, e.g. Web and Background)

Currently, the agent sends _all_ error traces to the central collector. Once I better understand what's happening in your scenario, the solution may be to implement some kind of limit (in the agent) to the number of error traces collected/sent (per minute) to the central collector.

**Comment by calendorn** [comment]
Yes, there are 140k errors traces for the last 24 hours which is a lot. Is there any way to filter or discard a known error? For example one of the errors is repeated for 120k times which is a lot. 

Any way to purge these errors so the table frees some space? 

Thanks!

**Comment by trask** [comment]
There's not an easy way to purge only the errors from the trace_entry_v2 table. You could truncate the whole table (losing all of the trace entries, but it wouldn't affect anything else).

**Comment by calendorn** [comment]
Hi @trask:

We truncated the table because there were too many traces. Is there any way to implement a throttle in the agents so they don't send all the error traces? I've seen that in almost all error from these agents they send trace entries with 3000 lines each so the table starts to growth really fast, almost 10G a day.

**Comment by AbleSteven** [comment]
Hi @calendom:
Maybe you can check the Central Collector's source codes, and do some filter process before the traces are stored into the Cassandra.

**Comment by trask** [comment]
Hi @calendorn, can you open a new issue for this? I agree the agent needs some kind of throttle. Thanks.

**Comment by calendorn** [comment]
@trask Sure, I will open a new issue
