### ISSUE TITLE
glowroot & groovy

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#559]
Hi,

Do you think, glowroot can work on groovy ?

**Comment by trask** [comment]
Hi @lfen21, yes, I use it with groovy!  It works because the groovy engine turns groovy classes turn into bytecode classes, and Glowroot sees and instruments the methods in those classes.

**Comment by lfen21** [comment]
it's good. (automatic instrumentation doesnt work but it's ok)

Great thanks !

**Comment by trask** [comment]
Hi @lfen21, can you explain what you mean by automatic instrumentation doesn't work? I'd like to understand in case others have this question. Thanks.

**Comment by lfen21** [comment]
hm with our applications, we have by default some trace. With my groovy application, i had to instrumente my classes in the configuration.

**Comment by trask** [comment]
Is your groovy application a grails or servlet-based app?

**Comment by lfen21** [comment]
it's a command line application without complexity.

**Comment by trask** [comment]
Ok, that makes sense, thanks for the additional details.
