### ISSUE TITLE
[Improvement] Gauge on UserSession parameter

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#560]
Hi

Is it possible to add a gauge on an user session parameter ?

I want to count how many user ID are using the application at one time.

Thanks

**Comment by trask** [comment]
Hi @lfen21, if your application servers exposes session count as an MBean attribute then you can create a Gauge based on that, e.g. Tomcat does, under `Catalina:type=Manager,host=localhost,context=/`, see https://demo.glowroot.org/jvm/mbean-tree?expanded=Catalina:type%3DManager,host%3Dlocalhost,context%3D%2F

**Comment by lfen21** [comment]
Hi i'm already doing that, but one session <> one user

I have some sessions by user. And i cannot count the amount of user.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
