### ISSUE TITLE
Monitoring microservices in kubernetes

### ISSUE THREAD

**Issue by lukaszun** [glowroot/glowroot#562]
Hi,
we're planning to use K8S as infrastructure for our microservices what means there will be dynamically spawned containers with many replicas of our applications. How can we configure glowroot to monitor them, to aggregate results from many same applications with possibility to view any one of them?

**Comment by trask** [comment]
Hi @lukaszun. sorry for the late reply, have you seen https://github.com/glowroot/glowroot/wiki/Agent-Installation-(for-Central-Collector)#roll-up-data-across-multiple-agents?

**Comment by lukaszun** [comment]
Hi @trask. Thank's for reply. That's what I was looking for.

**Comment by trask** [comment]
👍
