### ISSUE TITLE
Upgrade central collector problem

### ISSUE THREAD

**Issue by ynsdl** [glowroot/glowroot#563]
Hi, 

I try to upgrade central-collector from glowroot-central-0.12.4-SNAPSHOT-dist.zip to glowroot-central-0.13.2-dist.zip. I followed you steps on github but can not connect to cassandra. I dont understant what is problem. I share glowroot.log at attachement
[glowroot.log](https://github.com/glowroot/glowroot/files/3019734/glowroot.log)

**Comment by trask** [comment]
Hi @ynsdl, I haven't seen this before `replied with server error`. Can you post your cassandra log(s) also?

**Comment by trask** [comment]
Also, try starting up the central collector again, it will pick up the upgrade where it left off, and see if it goes through.

**Comment by ynsdl** [comment]
[debug.log](https://github.com/glowroot/glowroot/files/3019777/debug.log)
[system.log](https://github.com/glowroot/glowroot/files/3019778/system.log)

Here cassandra logs

I tired starting up the central collector again but failed with same error

2019-03-28 19:06:19.880 WARN  c.d.driver.core.RequestHandler - /127.0.0.1:9042 replied with server error (java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError), defuncting connection.

**Comment by trask** [comment]
You are getting an `AssertionError` inside of Cassandra itself. Try restarting Cassandra, and then starting the central collector.

**Comment by trask** [comment]
Looks like the same Cassandra error as https://issues.apache.org/jira/browse/CASSANDRA-14460, what version of Cassandra are you running?

**Comment by ynsdl** [comment]
after restarting cassandra, works fine. I use cassandra 3.10

Thanks a lot

**Comment by trask** [comment]
👍

**Comment by ynsdl** [comment]
Hi @trask again. upgrade my agent to glowroot-agent-0.13.2-20190321.055359-14-dist.zip ı see some error on glowroot.log like this 
2019-03-28 19:31:45.524 ERROR o.g.central.CollectorServiceImpl - Wildfly5 - 2019-03-28 19:31:45.508 ERROR org.glowroot.agent.weaving.Weaver - unable to weave io/undertow/servlet/spec/HttpServletResponseImpl: null
java.lang.reflect.InvocationTargetException

is it important or not ?
[glowroot.log](https://github.com/glowroot/glowroot/files/3019859/glowroot.log)

**Comment by trask** [comment]
Yes, this looks like a problem, can you attach the agent log from Wildfly5 agent? And what version of Wildfly is it running? I will see if I can repro. Thanks.

**Comment by ynsdl** [comment]
WildFly Full 9.0.2.Final (WildFly Core 1.0.2.Final)

agent log in attachement
[glowroot.2019-03-28.log](https://github.com/glowroot/glowroot/files/3019879/glowroot.2019-03-28.log)

**Comment by trask** [comment]
Can you post (or email to me) the file `glowroot/tmp/preload-some-super-types-cache`? Thanks.

**Comment by ynsdl** [comment]
ok send you an email

**Comment by ynsdl** [comment]
@trask is there any update ?

**Comment by trask** [comment]
Hi @ynsdl, this should now be fixed in the latest snapshot release [glowroot-agent-0.13.3-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.3-SNAPSHOT).

**Comment by ynsdl** [comment]
Hi @trask first of all thanks for your fix. Upgrade my agent it gives me a warning like this "the central collector version is older than the agent version which could cause unpredictable issues" 
ı think that this is not a big problem for us right ?

central-collector: glowroot-central-0.12.4-SNAPSHOT-dist.zip
agent: glowroot-agent-0.13.3-20190404.183419-1-dist.zip

**Comment by trask** [comment]
Hi @ynsdl, it's likely not a problem, but the warning is emitted because I don't test that combination (when the agent is newer than the central collector). I'd plan to upgrade your central collector soon just to be safe.

**Comment by ynsdl** [comment]
@trask thank you.
