### ISSUE TITLE
GlowRoot Data Deletion

### ISSUE THREAD

**Issue by krishbala** [glowroot/glowroot#566]
Hi

How can we delete the glowroot older data (only we need last 15 days data in the cassandra DB)? Please assist.

We are using below versions : 
GlowRoot - 0.13.1
Central  - 0.13.1
Cassandra - 3.11.4

Thanks
Krishnan

**Comment by trask** [comment]
Hi @krishbala, thanks for posting!

Have you already updated the data retention settings under Administration > Storage?

Those settings will not apply retroactively to old data, however, so if you need to delete old data after updating those settings, run the following:

```
java -jar glowroot-central.jar delete-old-data summary
java -jar glowroot-central.jar delete-old-data overview
java -jar glowroot-central.jar delete-old-data histogram
java -jar glowroot-central.jar delete-old-data throughput
java -jar glowroot-central.jar delete-old-data query
java -jar glowroot-central.jar delete-old-data service_call
java -jar glowroot-central.jar delete-old-data profile
java -jar glowroot-central.jar delete-old-data error_summary
java -jar glowroot-central.jar delete-old-data gauge_value
```

and after that, you'll need to run compaction on the Cassandra tables to release the space associated with the old data.

**Comment by krishbala** [comment]
Hi Trask,

Thanks for your reply.

While executing the java -jar commands am getting the Below exception

**"delete-old-data requires two args (partial table name and rollup level), exiting"**

Please assist.

Thanks
Krishnan

**Comment by trask** [comment]
Oh right, you'll have to run each one 4 times, e.g.

```
java -jar glowroot-central.jar delete-old-data summary 0
java -jar glowroot-central.jar delete-old-data summary 1
java -jar glowroot-central.jar delete-old-data summary 2
java -jar glowroot-central.jar delete-old-data summary 3
```

Actually, you may not need to run it for `0` and `1`, since those are for `1-min` and `5-min` data, depending on what the expiration settings were for that data previously.

**Comment by krishbala** [comment]
Hi Trask, 
Thanks for you assistance.
Wil try that and come back to you.

**Comment by krishbala** [comment]
Hi Trask,

we have run the jar command with the given arguments.it's working as we except. Thanks a lot.

**Comment by trask** [comment]
👍

**Comment by xialanpu** [comment]
Hi

How can we run compaction on the Cassandra tables to release the space associated with the old data? 
And what dos 0/1/2/3 mean after "java -jar glowroot-central.jar delete-old-data summary"?

Thanks
