### ISSUE TITLE
Central collector UI port?

### ISSUE THREAD

**Issue by tstiemerling** [glowroot/glowroot#569]
Running central collector on Apache Tomcat with Cassandra on same server. After startup (which is very slow for some reason), I dont see any UI port:

Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9042          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:36532         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:7000          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:7199          0.0.0.0:*               LISTEN
tcp6       0      0 :::8009                 :::*                    LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::8080                 :::*                    LISTEN
tcp6       0      0 :::8181                 :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:25                  :::*                    LISTEN
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN
udp        0      0 0.0.0.0:944             0.0.0.0:*
udp        0      0 0.0.0.0:111             0.0.0.0:*
udp        0      0 127.0.0.1:323           0.0.0.0:*
udp6       0      0 :::944                  :::*
udp6       0      0 :::111                  :::*
udp6       0      0 ::1:323                 :::*

Remote agent is running and connected to collector.

**Comment by trask** [comment]
Are you using the glowroot central war? If so, the UI is available via the servlet container, so `8080` in your case. As far as startup slowness, can you post the central collector log? Maybe that will give some clue about why.

**Comment by tstiemerling** [comment]
Thanks. Might be good to add that to the wiki. What is the UI path in that case?  Also should I remove the default ROOT app from Tomcat?

**Comment by trask** [comment]
If all you are running in Tomcat is glowroot central, you may want to remove the `ROOT.war` and rename the glowroot central war to `ROOT.war`, so that the UI is available via `http://localhost:8080` (without any path). Otherwise, I believe with Tomcat that the UI path is the same as the war file name (minus the `.war`).

**Comment by tstiemerling** [comment]
ok, will do. Thx!
