### ISSUE TITLE
Collector API

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#57]
Hi,

I'm building an alternative Collector for glowroot. And wondering when the API is final. I'm using the master branch - also because of the new plugins. And see changes that are easy to fix. But can you say something about the final version of this API and maybe some upcoming changes.

I'm also wondering what the new `getAuxThreadProfile` and `getAsyncRootTimerList` data types are for.

**Comment by trask** [comment]
Yeah, the Collector API churn on master has been really high lately.  I think things are better now.  Hoping to mostly stabilize by 0.9 release, though it will continue to evolve beyond then as needed.

`auxThreadRootTimers`, `auxThreadProfile` and `auxThreadStats`, `asyncRootTimers` are part of work-in-progress to support tracing/profiling transactions that use multiple auxiliary threads (e.g. via ExecutorService.submit() and then waiting on results via Future.get() from their main thread), as well as to support non-blocking async frameworks like Play and RxJava which don't even have a "main" thread.

**Comment by ajdevries** [comment]
Okay... Thanks for the answer. I'm working on a Netty plugin, but should probably wait for the aux / async part before moving.

**Comment by trask** [comment]
Great, I'll post an issue with details when the aux / async work is complete.

**Comment by ajdevries** [comment]
That's great. If I can help with something let me know. Interesting stuff

**Comment by trask** [comment]
The auxiliary thread stuff is working, check out the Executor Plugin. A minor part of the async stuff is working, e.g. AsyncHttpClientAspect. What doesn't exist yet is Plugin API to support fully non-blocking async transactions like RxJava and I think Play. And Netty, depending on how it's used. It would be great to put together realistic plugin tests for any/all of these, to model different usage scenarios for each, and then to start building out the pointcuts and thinking through what Plugin API additions are needed to support them. That's really the major work (compared to actually implementing the new Plugin API additions). Any help with the above would be much appreciated.
