### ISSUE TITLE
Improve : group some gauge on same scale

### ISSUE THREAD

**Issue by RonanKER** [glowroot/glowroot#571]
Hi !

I would like to have a way to group some Gauge on same scale. Is it possible ?

For exemple, I would like to see this selection of gauges with same scale :
> Catalina / Executor / tomcatThreadPool / activeCount  
> Catalina / Executor / tomcatThreadPool / maxThreads  
> Catalina / Executor / tomcatThreadPool / poolSize  
> Catalina / ThreadPool / ajp-nio-8009 / currentThreadCount  
> Catalina / ThreadPool / ajp-nio-8009 / currentThreadsBusy  
> Catalina / ThreadPool / ajp-nio-8009 / maxThreads  
> Catalina / ThreadPool / http-nio-8080 / currentThreadCount  
> Catalina / ThreadPool / http-nio-8080 / currentThreadsBusy  
> Catalina / ThreadPool / http-nio-8080 / maxThreads  
> com.mchange.v2.c3p0 / PooledDataSource[*] / threadPoolSize

**Comment by trask** [comment]
Hi @RonanKER, I added a "thread count" grouping for these in the latest snapshot releases [glowroot-agent-0.13.4-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.4-SNAPSHOT)/[glowroot-central-0.13.4-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.4-SNAPSHOT)/[glowroot-central-0.13.4-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.13.4-SNAPSHOT).
