### ISSUE TITLE
Question: how to browse db file

### ISSUE THREAD

**Issue by sadolintw** [glowroot/glowroot#572]
hi~

I find db files in /data folder,
how can I browse records in that files?
like viewing each request cost time record
I checked web ui, it seems to provide average metric

thanks for help

**Comment by trask** [comment]
Hi @sadolintw, you can run `java -jar glowroot.jar h2 console`, and it will launch the h2 database's web console where you can query the database.

Every request is not stored, but you can view arbitrary percentiles in the UI, e.g. https://demo.glowroot.org/transaction/percentiles?transaction-type=Web.

**Comment by sadolintw** [comment]
Hi Trask,

I used h2 console and file some useful info in  AGGREGATE_XXX

Thanks your assistance

Sado

**Comment by trask** [comment]
👍

**Comment by parabinda** [comment]
> Hi @sadolintw, you can run `java -jar glowroot.jar h2 console`, and it will launch the h2 database's web console where you can query the database.
> 
> Every request is not stored, but you can view arbitrary percentiles in the UI, e.g. https://demo.glowroot.org/transaction/percentiles?transaction-type=Web.

-- Thank you Trask The console works. How do I access the - H2 database tables programmatically using - JDBC program. I have a need to do that. Please guide. 
Thank you
Arabinda

**Comment by parabinda** [comment]
Hi Trask,
Continuing the above question. 
I have my - data.h2.db under ~/data.
I want to programmatically access tables in in - trace, etc using h2 JDBC driver. 
Please help.
Thank you
Regards
Arabinda
