### ISSUE TITLE
Question: 'Transactions ' showing where previously ${glowroot.agent.id} was showing.

### ISSUE THREAD

**Issue by ross-everitt** [glowroot/glowroot#573]
Having upgraded from Glowroot 0.10.12 to 0.13.2 I see 'Transactions' listed on the Web screen.  In the past I saw the value specified by ${glowroot.agent.id}, has this feature been replaced, can I still use it somehow?

![image](https://user-images.githubusercontent.com/45071159/56126607-5bf26200-5f73-11e9-8586-cead0c9b3a5b.png)

![image](https://user-images.githubusercontent.com/45071159/56126708-6f053200-5f73-11e9-8919-cd151f9fdec6.png)

**Comment by trask** [comment]
Hi @ross-everitt, thanks for reporting this! It should be fixed now in the latest snapshot release [glowroot-agent-0.13.4-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.4-SNAPSHOT).

**Comment by ross-everitt** [comment]
Great, thanks.
