### ISSUE TITLE
Ignore / hide certain (Spring) Web transations

### ISSUE THREAD

**Issue by danielpaval** [glowroot/glowroot#577]
While our Spring-Boot REST endpoints are perfectly detected, I haven't been able to find a way to ignore a Spring actuator endpoint, especially the continous /actuator/hystrix.stream, that's taking around 95% of the total time in the Web transactions dashboard.

It would be awesome to be able to discard transactions by a specific name or pattern, even if they're configured by a plugin.. Any ideas on a solution besides forking the Spring plugin?

**Comment by trask** [comment]
Hi @danielpaval, thanks for posting! You can assign requests to a different transaction type (e.g. something other than `Web`) by adding custom instrumentation (Glowroot UI > Configuration > Instrumentation) with "Capture kind" of "Other", and the desired "Transaction type". The custom instrumentation would need to be on a class/method that is only called by the request you want to assign the new transaction type (e.g. you could find appropriate class/method from profile tab).

**Comment by danielpaval** [comment]
OK, that makes sense, thank you!!

**Comment by materemias** [comment]
@danielpaval could you find a good instrumentation entry point that would cover all /actuator endpoints? mind to share?
