### ISSUE TITLE
Metrics API on the agent

### ISSUE THREAD

**Issue by cyprix** [glowroot/glowroot#580]
I'm starting glowroot as standalone java agent, without a collector. Is there any RPC or HTTP API(like Jolokia), with which I can get the app metrics?

**Comment by trask** [comment]
Hi @cyprix, thanks for posting! The best option at present is to query the json api that is used by the UI. If you go to the UI page with the metrics you want, you can use your browser dev tools to look at the json api calls that it makes and mimic those.

**Comment by cyprix** [comment]
Hi, @trask  thanks for the help. I found backend queries and will use them for monitoring Java-apps with Glowroot java-agent.
