### ISSUE TITLE
Trigger glowroot agent for a docker Application

### ISSUE THREAD

**Issue by mayankjain9005** [glowroot/glowroot#581]
how can I trigger glowroot agent for an application in docker container ?

**Comment by AndSab** [comment]
You can add glowroot jar into a docker container and just enable it where you want using environment variables that get passed to java as JAVA_OPTS 
`-javaagent:/glowroot-agent.jar`

**Comment by trask** [comment]
@mayankjain9005 are you still having this issue? Thanks.

**Comment by gamefundas** [comment]
This works fine and I have tested it.
