### ISSUE TITLE
Getting a list of active sessions in my webapp

### ISSUE THREAD

**Issue by souf** [glowroot/glowroot#587]
hello  ,
I'm trying  to get active session counts for a web application, but I can not find the information in glowroot.
1. Is it possible to use glowroot to get this kind of information?
2. If yes, how reliable would it be? 
Thanks!

**Comment by trask** [comment]
Hi @souf, thanks for posting! Can you see if your question is the same as #560?

**Comment by souf** [comment]
hi trask,
thanks you, that's what i need.
