### ISSUE TITLE
Monitoring Jberet batch

### ISSUE THREAD

**Issue by gregsting** [glowroot/glowroot#590]
Hello,

I'd like to monitor a JSR352/Jberet batch (https://github.com/jberet/jsr352) running on Jboss. I installed glowroot on the server but unfortunately can't see any trace of the batch itself, I have nothing in "background". 

Is there any configuration to make this work?

Thanks

**Comment by trask** [comment]
Hi @gregsting, Glowroot doesn't have any built-in instrumentation for JSR-352. There's some instrumentation for Spring Batch, see https://github.com/glowroot/glowroot/blob/v0.13.4/agent/plugins/spring-plugin/src/main/resources/META-INF/glowroot.plugin.json#L14-L24. And check out https://glowroot.org/instrumentation.html for various ways you can add your own instrumentation. If you come up with something that works for you, please post it or send a PR!

**Comment by gregsting** [comment]
Thanks for your reply, unfortunately I'm not a java dev, I'm on infrastructure side but I'll give it a shot...

**Comment by gregsting** [comment]
After some trial and errors with the instrumentation UI, I have traces with the following config. Probably possible to improve as I don't quite get the usage of each field, but a really good start to say the least. Thanks for you help!: 

{
  "className": "org.jberet.runtime.runner.ChunkRunner",
  "methodName": "run",
  "methodParameterTypes": [
    ".."
  ],
  "captureKind": "transaction",
  "transactionType": "Background",
  "transactionNameTemplate": "Jberet Batch: {{this}}",
  "transactionSlowThresholdMillis": 1,
  "alreadyInTransactionBehavior": "capture-trace-entry",
  "traceEntryMessageTemplate": "{{_}}",
  "timerName": "ChunkRunner"
}

![image](https://user-images.githubusercontent.com/46812808/61054245-5c25c080-a3ef-11e9-9300-ed86bae00a37.png)

**Comment by gregsting** [comment]
For posterity: I now have something better than the chunk ID in the trace headline, using {{methodName}}{{this.class.name}}
