### ISSUE TITLE
/* criteria query */ showing up in middle of query text

### ISSUE THREAD

**Issue by mikethomas77055** [glowroot/glowroot#593]
Trask, i've noticed on recent releases that when pulling the jdbc query from a trace, that the comment "/* criteria query */" is showing in the middle of the actual query randomly.  I have to remove it before I can run the query in SSMS.

![image](https://user-images.githubusercontent.com/38060296/58350493-aba63200-7e2b-11e9-839c-333e060dd92b.png)

This is coming from 0.13.1.

**Comment by trask** [comment]
Hi @mikethomas77055, thanks for posting! I think this is fixed in 0.13.4 by 84075a4301d7c3af6cdf1b9f6b1919d3a8bd7f35.
