### ISSUE TITLE
Error with GlassFish

### ISSUE THREAD

**Issue by tfcardoso** [glowroot/glowroot#599]
Hi,

I'm trying to place glowroot on Sun GlassFish Communications Server 2.0 ((v2.1 Patch06)(9.1_02 Patch12)) (build local) and not succeeding 

    <java-config...
        <jvm-options>-javaagent:/var/log/company/rsg/rsg-cnvf/logs/glowroot/glowroot.jar</jvm-options>
    </java-config>

Logs: https://gist.github.com/tfcardoso/4d34091a4cbb350dd7685a5b84fbcda5

Any ideia on what I'm doing wrong?

Thanks

**Comment by trask** [comment]
Hi @tfcardoso, thanks for reporting this! I think this is fixed now in the latest snapshot release [glowroot-agent-0.13.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.5-SNAPSHOT).

**Comment by tfcardoso** [comment]
Thanks, it works now

**Comment by trask** [comment]
👍
