### ISSUE TITLE
Smaller package, one jar

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#60]
Is it possible to make a different distribution which is:
- smaller;
- one jar file;
- separated configuration (replacement or plugin like);

Needed for use of glowroot with a different collector and a different endpoint. I'll give it a try myself, but if you have any ideas let me know.

**Comment by trask** [comment]
Producing a smaller jar file has been more effort than it seems worth, but willing to revisit this.

As far as single jar file, are you thinking to embed the plugins inside the single jar? This was the distribution format prior to d65f324c0a022b53dd97adbb3dac4ad25d60d880, a single jar file with plugins embedded inside. The simplicity was nice. I could definitely see reverting back to that format.

Configuration by plugin will happen soon (next week). Most of this is done, but there are some changes coming in the next few days. If you want to open a separate issue for this I will close with details when it's committed, or you can leave this issue open and I'll comment here.

**Comment by ajdevries** [comment]
One of the issues was the big service package for the custom collector. I downsized this one from 5Mb to 750kb. Removing the unnecessary glowroot dependencies (they are already on the classpath). Thing that is left, is one jar file. Easier to install, easier to update

**Comment by trask** [comment]
The `Collector` interface now receives an `AgentConfigUpdater` that can be used to update the agent config.  The config.json file will still be used at startup, but all configuration except Instrumentation can be updated at runtime.  AgentConfigUpdater will update the runtime values and it will also update the config.json file.  Let me know if this works for you or if you run into any issues/questions.

```
public interface Collector {

    void collectInit(ProcessInfo processInfo, AgentConfig agentConfig,
            AgentConfigUpdater agentConfigUpdater) throws Exception;

    ...

    interface AgentConfigUpdater {
        void update(AgentConfig agentConfig);
    }
}
```

**Comment by ajdevries** [comment]
Wow, this is nice. Now there is also the possibility to enable / disable plugins from the collector. Great.

**Comment by ajdevries** [comment]
Is it also possible to extend, use this config. I.e.
- hostname;
- appname;
- enviroment.

**Comment by trask** [comment]
I sort of removed the config-based enable/disable of plugins recently b5d45f279fa402d840646d7ae4d8f357df9b81b4. It didn't seem particularly useful and simplified some things removing it. Let me know if this feature is useful to you, I can bring it back in one form or another (probably enabling or disabling plugin at instrumentation-time, and requiring restart for change to take effect).

**Comment by ajdevries** [comment]
I missed the config removal, but that's okay... For now I'm using my own yaml file and that's working okay, the suggestion in #62 works!

**Comment by ajdevries** [comment]
Build the one-jar distribution today. Not quite working, but getting there. Will make a PR next week. On of the things that isn't working is the `collectInit` call. It is never called from the ThinAgent. I'm expecting the call somewhere over here: https://github.com/glowroot/glowroot/blob/master/agent-parent/agent/src/main/java/org/glowroot/agent/init/GlowrootThinAgentInit.java#L78

**Comment by trask** [comment]
Oops, you're right, `collectInit` is never called for custom collector.  I'll fix and post back here.

**Comment by trask** [comment]
Calling init() on custom collectors is now fixed in c12a553b5f673d2d65b5e01238945f9df73c1200.

**Comment by ajdevries** [comment]
Thanks... Made a PR for the packager plugin #65. And experimented with a smaller zip. Excluding netty and h2 gives me a 5Mb smaller package. But I'm running into some ThinAgent dependencies, like CollectorLogbackAppender#40

**Comment by trask** [comment]
The CollectorLogbackAppender dependency on Netty is now fixed in 4c68387cae53ee1f75deec9440859ec0e5ad3824.  I couldn't repro the original reason why I put that code there, so I removed it :-).

**Comment by ajdevries** [comment]
You documented it in the code (very nice):
```java
// explicit initializations are to work around NullPointerExceptions caused by class init
// ordering, e.g. when running UiSandboxMain against central collector (and debug logging
// enabled at root logger)
```

Smaller package is working, 12MB now.

**Comment by trask** [comment]
Cool, I'm interested in going back to the single jar approach for the main distribution as well.  It makes sense for the core plugins to be bundled, and additional plugins can be dropped in the plugins directory.  Can you submit PR with the packager maven plugin when you have time?  Thanks.

**Comment by ajdevries** [comment]
Sure, will do, for now I used the exclude in de maven-shade plugin for the agent module. Need to move this logic to the package plugin. It is a copy from yours. New maven version and thinking about rewriting it in Maven 3.0 style.
