### ISSUE TITLE
Resource leak detection on auxiliary thread

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#600]
Hi @trask ,

If a JDBC connection(created on an auxiliary thread) is not closed while the main thread is still running, then the resource is logged as leaked and the transaction as ended with error

**Comment by trask** [comment]
Hi @ionutursuleanu, thanks for posting! Can you clarify, does the resource get closed before the request ends?

**Comment by ionutursuleanu** [comment]
Hi,

My use case is the following:

1. start request

**Comment by ionutursuleanu** [comment]
Hi,

My use case is this:

1. start request
2. get db connection
3. do some work
4. log something to db on an auxiliary thread, with it's own connection
5. close db connection from 2
6. finish request & log that an auxiliary thread is still running & the db connection from 4 is not closed

The issue is that the db connection will, eventually, get closed when the auxiliary thread ends . My proposed solution is to simply not track connections from auxiliary threads

**Comment by shark-horse** [comment]
Can someone please explain (ideally with a simple link) how Glowroot determines what threads are auxiliary to one involved in a request or transaction? For our application, it appears to be recognizing many long-running, unrelated threads as auxiliary.

**Comment by shark-horse** [comment]
I enabled `captureConnectionPoolLeakDetails=true` in our config.json so we now have stack traces, with which I can confirm that Glowroot is absolutely complaining about connections in "auxiliary threads" not being closed. They _are_ closed in `finally` blocks, just not before the transaction being tracked is closed. Note that we don't use the same connection or transaction from multiple threads; each "auxiliary thread" is responsible for opening and closing its own thread.

**Comment by shark-horse** [comment]
In the meantime, is there a way to suppress leak detection or auxiliary thread detection?

**Comment by ionutursuleanu** [comment]
Hi @trask ,

Do you have another idea on how to solve this? I tested #602 and the auxiliary threads aren't reporting connection leaks anymore.

**Comment by trask** [comment]
Hi @ionutursuleanu, sorry for the delay getting back to you. I will look at this tomorrow. I agree with you that the current state is no good. Thanks for reporting this.

**Comment by trask** [comment]
This seems tricky to get just right, so for now I have turned off the resource leak detection by default, and you can opt-in via a new JDBC configuration property. This is available in the latest snapshot release [glowroot-agent-0.13.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.5-SNAPSHOT).
