### ISSUE TITLE
Resource leaked

### ISSUE THREAD

**Issue by shashanka89** [glowroot/glowroot#606]
Hello Team,
We are getting below error on Glowroot trace while using Spring 5.1.5.RELEASE with Hibernate 5.0.9.Final-redhat-1 on jboss 7.0.4.

The request comes via REST API implemented using resteasy 3.8.0.Final. The method performs some function and then inserts an audit entry into the table. After the insert, I see the below message as error on Glowroot console. However no errors in the logs.

Looking at the error, should a pooled connection be released after all ? Kindly advise

**Error Message :**
(acquired during the transaction and not released): org.apache.commons.dbcp2.PoolableConnection

**Stack trace :**
log info: stdout - Hibernate: INSERT INTO dbo.EventAudit VALUES (?, ?, ?, ?, ?, ?)
jdbc query: INSERT INTO dbo.EventAudit VALUES (?, ?, ?, ?, ?, ?) ... PI', 2019-06-30 10:40:35.022, 2019-06-30 10:40:35.022, 2019-06-30 10:40:35.022] => 1 row
hibernate commit
jdbc commit
Resource leaked (acquired during the transaction and not released): org.apache.commons.dbcp2.PoolableConnection
 Resource leaked

**Comment by shashanka89** [comment]
Glowroot version 0.13.4

**Comment by trask** [comment]
Resource leak detection seems tricky to get just, so for now I have turned off the resource leak detection by default, and you can opt-in via a new JDBC configuration property. This is available in the latest snapshot release [glowroot-agent-0.13.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.5-SNAPSHOT).
