### ISSUE TITLE
[Question] Annotation support and usage

### ISSUE THREAD

**Issue by gamefundas** [glowroot/glowroot#607]
I see there are three annotations for instrumenting custom code, in my case a Spring/Java application that runs a batch to process a defined set of requests at a certain point in the day and then terminate. Was looking to instrument the application to find bottlenecks and was thinking of the Glowroot API way to capture performance. 

When I started adding the Annotations to the code I got confused as to how should I use the Tracer, Transaction and Timer. Don't see any documentation or examples of the purpose where these would apply. I mean in what combination these 3 annotations should be used to be able to capture the performance, trace and timing of each method and interactions (JDBC, Service etc) in my batch application.

I have a driver class (BatchRunner) with a processRequests(context) method that does everything. My intention is for Glowroot to crawl in to everything that this method does, capture all information of the hundreds of other classes and methods the main processRequests method calls internally. Now in order for me to do this, 

1. Do I need to start with the Tracer annotation on the processRequests() method or Transaction annotation, or both?
2. Do I need to annotate only the driver method (processRequests) and Glowroot can find its way for all nested methods and classes or I will have to annotate every single class and method that I need instrumentation on.

May be its just me, but I am unclear about how to use these annotations effectively.

**Comment by trask** [comment]
Hi @gamefundas, thanks for posting!

1. You need to tell Glowroot that `processRequests()` represents a Transaction. If you want to do this using the Glowroot API, then you will want to annotate that method with `@Instrument.Transaction`
2. Typically you just tell Glowroot about the outer Transaction marker (in your case `processRequests`). Glowroot will then capture jdbc queries, etc anywhere inside of that transaction via the standard built-in instrumentation. Start with that and see if it gives you what you want. If you are wanting more details on other specific method calls in your codebase, then try instrumenting them with `@Instrument.TraceEntry`, and they will show up in the trace entries of your `processRequests` transaction capture.

Hope this helps.

**Comment by gamefundas** [comment]
This makes sense now. I will close the issue for now and will get back in case of any further questions.
