### ISSUE TITLE
Tomcat RemoteIPValve doesn't work with Glowroot captureRequestRemoteAddr

### ISSUE THREAD

**Issue by ReillyProcentive** [glowroot/glowroot#609]
Environment:
Tomcat 8.5.42
Glowroot 0.13.4
JDK 8u212 w/ Openj9 0.14.2

We have our Tomcat servers behind reverse proxies. These reverse proxies are configured to pass along the actual client IP in the `x-forwarded-for` header. We have `RemoteIpValve` configured in Tomcat so that this header is parsed and the value is added to the request object such that methods like `request.getRemoteAddr()` work correctly. When captureRequestRemoteAddr is turned on in the servlet plugin it appears that Glowroot is not capturing the updated request remote address and is instead capturing the proxy address.

Perhaps the instrumentation is capturing the IP before the Tomcat valve has had a chance to modify the value? If so it is likely better to move this part of the instrumentation to just before the actual servlets/filters are ran and after the application server pre-processing.

**Comment by ReillyBrogan** [comment]
My bad, I had RemoteIPValve misconfigured.

**Comment by ReillyProcentive** [comment]
My bad, I had RemoteIpValve misconfigured.

**Comment by trask** [comment]
👍 thanks for following up!
