### ISSUE TITLE
I'm having trouble deploying glowroot on my EC2 instance

### ISSUE THREAD

**Issue by DraeNool** [glowroot/glowroot#611]
I installed tomcat8 with yum "install".

Following the instructions modify the file tomcat8.conf as one sees in the image... this correctly?

![image](https://user-images.githubusercontent.com/32885107/60923277-33bd8b00-a264-11e9-957a-9a9723c06154.png)

I restart the tomcat service, create the admin.json and config.json file and modify it so that I can enter any ip with the (you know 0.0.0.0). Then make sure that port 4000 is allowed in the instance's security rules. But I still can't get into the glowroot.

**Comment by trask** [comment]
Hi @DraeNool, can you post your `glowroot.log` file (under `/usr/share/tomcat8/glowroot/logs`)?

Also, can you `ps -ef | grep java` and confirm that the `-javaagent:...` arg is displayed in your tomcat process listing?

**Comment by DraeNool** [comment]
After reviewing the log, I realized that you have to give permissions to the glowroot folder and also to its contents. In this case, give the config.json and admin.json files full permissions. after that it started to work glowroot. Thank you so much for the help.
![image](https://user-images.githubusercontent.com/32885107/61076698-73aa7c80-a3e2-11e9-8ed9-3cce6f0a4fba.png)

**Comment by trask** [comment]
👍
