### ISSUE TITLE
Using an S3 bucket to store data - possible?

### ISSUE THREAD

**Issue by bidlogix** [glowroot/glowroot#612]
We want to run glowroot in a docker container in aws and use S3 to store the data, has anyone done this?
Has anyone done this?  Any clues on how to define the S3 connection in the glowroot.properties file?

Sorry for the barrage of novice questions.
Cheers
Norman

**Comment by gamefundas** [comment]
@bidlogix I don't think the current version of Glowroot supports anything besides Cassandra (Central Collector) and  H2 (embedded).
I linked my Docker based Central collector with Cassandra and it works fine.

**Comment by trask** [comment]
Thanks @gamefundas, this is correct.
