### ISSUE TITLE
Dockerized Central 0.13.5 is not starting

### ISSUE THREAD

**Issue by Seljuke** [glowroot/glowroot#616]
Hello @trask, thanks for this wonderful product,

I tried to use glowroot-central with docker installation but version 0.13.5 couldn't start and trow error below;

```
[root@aonitoring glowroot-central]# docker run --name glowroot-central \
>            --restart always \
>            --link mon-cassandra:cassandra \
>            -p 4000:4000 \
>            -p 8181:8181 \
>            -v /opt/glowroot-central/glowroot-central.properties:/usr/share/glowroot-central/glowroot-central.properties \
>            -d glowroot/glowroot-central:0.13.5
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

When I switch back to version 0.13.4 everything went okay, but I dont know if the 0.13.5 glowroot agents works with below version central. 

By the way can you add where to mount docker volumes to docs to configure dockerized glowroot-central with glowroot-central.properties.

**Comment by teh-username** [comment]
Ran into the same problem as well, looks like `/usr/local/bin/docker-entrypoint.sh` and `/usr/local/bin/glowroot-central.sh` don't have execution permissions.
