### ISSUE TITLE
OpenID or SAML support

### ISSUE THREAD

**Issue by ReillyProcentive** [glowroot/glowroot#618]
Would it be possible to add either OpenID or SAML support to Glowroot Central? Most IDP platforms do not support LDAP (and even if they do LDAP requires the Glowroot Central server to have knowledge of the users password which is less than ideal).

Most IDP platforms support OpenID and this is typically easier to implement than SAML (though SAML is more widely supported). 

It would be great too if it was possible to match IDP groups (IE group claim) to Glowroot roles so that we can avoid creating users on the Glowroot side and just have temporary users created when a user logs in.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
