### ISSUE TITLE
Can we get report via script/batch in the form of JSON?

### ISSUE THREAD

**Issue by jagadeeshraju** [glowroot/glowroot#621]

**Comment by ionutursuleanu** [comment]
Hi @jagadeeshraju ,

If you take a look at what request is sent to the server when running a report you will see that is returning a JSON:

![image](https://user-images.githubusercontent.com/6136404/63206947-ed5f1580-c0c6-11e9-975c-8c13e98bae47.png)

**Comment by trask** [comment]
👍
