### ISSUE TITLE
Dockerized Central 0.13.5 is not starting

### ISSUE THREAD

**Issue by Nowheresly** [glowroot/glowroot#626]
Hi, the current docker image for the central (0.13.5) is not working, even with the improvements coming from #616 .

After some investigation, I think I'm able to sport the issue:
the very first line in the `docker-entrypoint.sh` contains a ^M at the end, 

`#!/bin/bash^M`

Just remove it and the image works again!

To prove it, run the following command:
`docker run -it -u root --entrypoint '' glowroot/glowroot-central:0.13.5 bash`

A bash is opened inside the image. Try to run the `docker-entrypoint.sh` file:
`/usr/local/bin/docker-entrypoint.sh`

and you get an error:
`bash: docker-entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory`

Now remove all `^M` by running this `sed` command:
`sed -i -e 's/\r$//' /usr/local/bin/docker-entrypoint.sh`

Try to run again the `docker-entrypoint.sh`  -> it works!!

Would it be possible to regenerate the docker image of the central without the trailing ^M chars ?

Thanks a lot

**Comment by gamefundas** [comment]
@trask Any luck resolving this as its a showstopper in using the Docker image.

**Comment by gamefundas** [comment]
Actually #616 and #617 fixes this. I used 0.13.5 in the Docker build and it works fine.
Hopefully a new Docker image is released soon which will fix this officially.

**Comment by MFAshby** [comment]
I've got the same issue. I can work around it by rebuilding the docker image myself, but I'd prefer to use the official build.

**Comment by NoxInmortus** [comment]
Hello,
@trask can this be done ?

**Comment by materemias** [comment]
@trask unfortunately the newly released 0.13.6 suffers from the very same
`standard_init_linux.go:211: exec user process caused "no such file or directory"`
issue

**Comment by NoxInmortus** [comment]
Idk about everyone else, but I cannot build the image myself, as It try to copy
`target/glowroot-central-*.zip` but this doesnt exist ?

**Comment by trask** [comment]
@NoxInmortus you'll need to build the zip first, e.g. `mvn clean package -DskipTests`

**Comment by NoxInmortus** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:22 min
[INFO] Finished at: 2020-03-04T13:08:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:bower (bower-prune) on project glowroot-ui: Failed to run task: 'bower prune' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :glowroot-ui
```
My apologies, I know nothing about java or maven, I just need the dockerfile working :<

**Comment by eostermueller** [comment]
I could also use some help trying to build the image.

https://search.maven.org/search?q=a:grails-taglib

The above maven central URL says 3.2.12 is the latest version of grails-taglib.
But the build is asking for something newer than current?  It sure looks like it.  The build error below is looking for:  org.grails:grails-taglib:jar:3.3.2.

Any suggestions?

`[ERROR] Failed to execute goal on project glowroot-agent-grails-plugin: Could not resolve dependencies for project org.glowroot:glowroot-agent-grails-plugin:jar:0.13.7-SNAPSHOT: The following artifacts could not be resolved: org.grails:grails-taglib:jar:3.3.2, org.grails:grails-web-gsp:jar:3.3.2, org.grails:grails-web-sitemesh:jar:3.3.2, org.grails.plugins:converters:jar:3.3.1, org.grails.plugins:async:jar:3.3.2, org.grails.plugins:gsp:jar:3.3.2: Could not find artifact org.grails:grails-taglib:jar:3.3.2 in epo-maven-dev (https://artifactory.fis.dev/artifactory/epo-maven-dev) -> [Help 1]
`

**Comment by eostermueller** [comment]
@NoxInmortus, was looking at your error.  I've I was in your shoes, I'd suggest to add -e -X to your mvn command line, re-run, and post the output.

Your error mentioned bower
Do you have npm and bower installed?
If not, perhaps these links will help:


curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
npm install -g bower

REFERENCES:

npm/nodejs: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions-1
bower:
https://bower.io/#install-bower
https://www.npmjs.com/package/bower

**Comment by eostermueller** [comment]
vI was getting this error also, trying to launch the docker image on linux:
`bad interpreter: No such file or directory`

I got around this by building the image myself on a redhat box.
But to get that far, I had to build glowroot, which wasn't easy.

There are a number of dependencies of glowroot-agent-grails-plugin that require artifacts from repositories other than maven central.  Our corporate firewall rules wouldn't permit access, so I had to comment out references to glowroot-agent-grails-plugin in the pom.

Then, I had to piece together the command to generate the image -- didn't find that documented anywhere.

Here is what I pieced together that worked for me and got rid of the "No such file" problem:

`docker build -f Dockerfile --tag glowroot-central:0.13.7-SNAPSHOT .`

**Comment by GagouKun** [comment]
Hello everyone

I ran into this issue as I was setting up a Docker environement with glowroot-central 0.13.6.

I grabbed @Nowheresly commands to fix format on `docker-entrypoint.sh` and `glowroot-central.sh` in a Dockerfile based on `glowroot/glowroot-central:0.13.6` (strangely the files on the git repo are correctly formatted since the beginning).

For those interested in, you can now pull `gagoukun/glowroot-central:0.13.6-2` image to run glowroot-central 0.13.6 directly (the image was built by dockerhub from this [Dockerfile](https://github.com/GagouKun/glowroot/blob/v0.13.6-docker-fix/central/Dockerfile.fix.0.13.6)).

@trask Feel free for using this image to provide a fix on the official glowroot repository if you want
