### ISSUE TITLE
Measure Netty / Vertx / Playframework transactions

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#63]
I'm working on measuring Netty / Vertx and the Playframework. I started with Netty and got the Request via a `io.netty.handler.codec.http.HttpObjectDecoder` advice. When adding the Encoder it should be possible the get the Response.

To measure the whole request I guess a `ChannelInboundAdapter` should be added to the Channel Pipeline (first in the list). An option could be adding this Channel with an OnBefore advice in [ServerBootstrap.channelRead](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java#L233)

To measure the end of the eventloop (request). A `ChannelFutureListener` could be added (with an [OperationComplete](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java#L255)

I'm trying to make a small setup using the vertx.io framework, but any input on this is appreciated. The though part in glowroot is getting things in one transaction object. Because a lot is in separated threads it is hard to build a decent state. Maybe the [ChannelHandlerContext](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelHandlerContext.java) could be used to keep state.

**Comment by trask** [comment]
My thought is to start with Vertx/Play specific plugins that do instrumentation at the Vertx/Play level, and not at the lower Netty level.

**Comment by ajdevries** [comment]
I got a Netty plugin working, made a `io.netty.channel.ChannelInboundHandler` and a `io.netty.channel.ChannelOutboundHandler` aspect. That is working for Netty and Vertx. I need to dig in deeper to see if it measures the right things.

This is not working for play, so I'll make some custom aspect for this framework. Are classes written in Scala supported, and do you have any experience with this.

Besides that I'm searching how to link traces and keep 'state' right in these kind of frameworks. Maybe it is good to talk about this, if you would like and got some spare time.

**Comment by trask** [comment]
Cool, I look forward to trying out the Netty plugin on the Glowroot UI itself :-).

I haven't tried instrumenting Scala code, I think it should be the same since all the instrumentation is at the bytecode level, but let me know if you run into anything that would be useful/helpful/idiomatic for Scala in particular.

**Comment by ajdevries** [comment]
That's one thing. It is also instrumenting glowroot itself ;-) When it is ready I make a PR.

**Comment by zggg** [comment]
Does it support vertx now?

**Comment by trask** [comment]
Hi @zggg, thanks for asking, yes it does, I just added it to https://glowroot.org/features.html

**Comment by zggg** [comment]
@trask， thanks for reply ,but when i switch my application to vertx-web ,all Web Transactions view‘s Response time table  has no data， and all transactions  in Slow traces table

**Comment by trask** [comment]
Hi @zggg, can you open a new issue for this?  It definitely looks like there is an issue here.  Please include the version of vertx you are using and what options (if any) you are passing when creating the vertx http server (e.g. SSL/ALPN as in https://github.com/vert-x3/vertx-examples/blob/3.4.2/web-examples/src/main/java/io/vertx/example/web/http2/Server.java#L41). Thanks.

**Comment by gksSBC608** [comment]
Hi @trask, I was unable to monitor transactions for a vert.x application; I build the netty-plugin from plugins directory of the Glowroot repository. I added the generated jar inside the plugins directory at Glowroot's home configured for my application. 
Plugins-list page of Glowroot configuration http://localhost:4001/config/plugin-list does not show any plugin named Netty of Vert.x; can you please help to know the steps required to monitor Vert.x application?
