### ISSUE TITLE
Is there any configuration to include image (graph snapshot for the breached time) in Alert email for Glowroot?

### ISSUE THREAD

**Issue by Pooja2589** [glowroot/glowroot#650]
Hello,

Is there any way or configuration to include an image like a graph or alert details like what was the response time for that transaction and at what time the breach happened etc in the Alert email body.
As of now, I only get below text as a part of the alert email which is not that descriptive or easy to read.
"Average over the last 1 minute is greater than or equal to the alert threshold of 100 milliseconds."

Request your help!!!

Thanks,
Pooja

**Comment by nikhil-govind** [comment]
Use Phantomjs or the headless browser screenshot capture of selenium. 
Example code using phantomjs : 
Install phantomjs
Copy the below code snippet by saving in say test.js
Replace the url ( https://www.facebook.com/ ) with your required page url
Replace the image file name ( github.png ) with your required file path and name
Add the image in the code and send it over the mail
Run the command : phantomjs test.js
Customize your code to call the above from Java / javascript phantomjs / selenium headless
```
var page = require('webpage').create();
page.viewportSize = {width: 1920, height: 1080};
page.open('https://www.facebook.com/',function(){
	page.render('github.png');
	phantom.exit();
});
```

**Comment by Pooja2589** [comment]
Thanks, this helps will add the calls in the alert mail send by customizing it.
