### ISSUE TITLE
Glowrot not starting

### ISSUE THREAD

**Issue by lucasmends** [glowroot/glowroot#674]
The agent glowroot is not starting with these VM these JAVA_OPTS=-Xms256m -Xmx3072m -XX:PermSize=512m -XX:MaxPermSize=512m -Xss228k -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Dsun.lang.ClassLoader.allowArraySyntax=true -Dfile.encoding=utf-8 -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -Djboss.modules.metrics=true 

It is being very hard to discover what is preventing glowroot to start, or the combination of arguments.

**Comment by solio** [comment]
I didn't see the javaagent argument in you JAVA_OPTS.
You can view the glowroot in startup log. In my tomcat case, it print log to catalina.out.

**Comment by lucasmends** [comment]
Found the problem, the user jboss wasn't able to write in glowroot log directory so the javaagent wasn't able to start. Granting the permissions solved it.
