### ISSUE TITLE
How to handle `auxiliary thread extended beyond the transaction`

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#69]
Not sure what happens here. Got a question from a customer, any ideas on this one?
```
2016-02-10 10:57:18.039 WARN  org.glowroot.agent.model.Transaction - auxiliary thread extended beyond the transaction which started it, maybe this should be captured as a background transaction instead -- this message will be logged only once
    java.lang.invoke.LambdaForm$MH/22671767.linkToTargetMethod(LambdaForm$MH)
    customer.package.name.stats.MetricsCollector$MetricRunnable.run(MetricsCollector.java:60)
    java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    java.lang.Thread.run(Thread.java:745)

**Comment by trask** [comment]
Glowroot captures calls to `Future<T> ExecutorService.submit(..)` and tries to associate the work performed inside the ExecutorService auxiliary thread to the original transaction that called `Future<T> ExecutorService.submit(..)`.

It logs this warning when one of these auxiliary threads is still running at the end of original transaction.

I just pushed c96689e0989fcc377b62dfa8a3fb60aed4ab32cc which detaches the auxiliary thread context from the auxiliary thread in this situation and reduces the warn level message to a debug level message.
