### ISSUE TITLE
Setting threshold for logging plugin

### ISSUE THREAD

**Issue by asgerjensen** [glowroot/glowroot#697]
Hi,

My application is extensively configured with JUL logging for entry/exit into functions.

I noticed after (finaally) upgrading from 0.9.22 to 0.13.6 that my traces were now drowned in 

log.finer 
log.finest
etcetc

All of these are guarded by something that checks if the level is configured, so they usually dont take any time.

While i see the benefit of getting, whats basically a complete trace of every function calls entry and exit values whenever something takes more than 2  seconds, i am concerned that the logger entries are pushing out more interesting info in the 2000 max trace entries i have configured.

Also, im a bit concerned if this plugin is suddenly adding overhead to every function call, by forcing the logging level to finest.

Is there a way to tell the logger plugin to either
- disable it self
or
- set the threshold to something more reasonable

**Comment by asgerjensen** [comment]
Sorry, 
I'm an idiot. Someone had enabled a quite extensive log trace specification , which is why all those entries showed up.

**Comment by trask** [comment]
No worries! Thanks for posting follow-up.
