### ISSUE TITLE
Restore URL search filter in glowroot > 0.8.6

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#70]
I tried glowroot 0.9 snapshot and noticed the search filter for URLs has gone and is replaced by a search filter for User. Is it possible to restore the functionality to search for URLs in addition to search for User?

**Comment by trask** [comment]
Hi, I'm happy to bring it back.  May I ask how you are using it?  Normally I drill in on the transaction names in the sidebar and don't need to filter by URL, but I can definitely see uses for it.  Thanks.

**Comment by rolandkool** [comment]
Our site has a lot of different URLs so without the filter, it is kind of hard to filter on URLs that are slow and are within a specific category. I also don't quite understand how the User filter is supposed to work, but the URL filter is very useful to me (specially the contains and starts with filter). So it would be nice to see it back (perhaps as an option to toggle it?)

**Comment by trask** [comment]
Thanks.  It's on its way back shortly.  The user filter works if you have a username in your application that is either accessible via http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal(), or is accessible via an HttpSession attribute/path, which you can tell Glowroot about, e.g. https://demo.glowroot.org/config/plugin?plugin-id=servlet

**Comment by trask** [comment]
Trace filtering on URL is back in the latest snapshot https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip.

Also, I added support for using JSESSION_ID as the user.  Set `Session user attribute` to the special attribute name `::id` on https://demo.glowroot.org/config/plugin?plugin-id=servlet.

**Comment by rolandkool** [comment]
Thanks for bringing back URL filtering. The filtering on JSESSION_ID also works. Nice.

**Comment by parabinda** [comment]
> Trace filtering on URL is back in the latest snapshot https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip.
> 
> Also, I added support for using JSESSION_ID as the user. Set `Session user attribute` to the special attribute name `::id` on https://demo.glowroot.org/config/plugin?plugin-id=servlet.

Hi Trask,
How can I filter traces by any random Session Attribute in Slow traces page?
I can see that the - in slow traces - html page there is a conditional Attribute Name and Attribute Value  pair which is activated if traceAttributeNames is non-empty.  
Please guide - even if I have added "*" to my Capture Session Attributes - still this conditional filter - "Attribute Name" is not showing up. 
Thank you for your guidance.
Arabinda
