### ISSUE TITLE
Tree view in trace entries overview

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#71]
Hi,

Currently, the trace entries may contain (depending on your app ofcourse) 100s of lines. Would it be possible to support a tree view there as well to get a better overview of the flow. Indentation size should be based on time it takes to process the call/trace entry. 
The async calls could be tricky.
The pinpoint APM (https://github.com/naver/pinpoint) does a nice job of creating such a timeline.

**Comment by trask** [comment]
Hi, thanks for the submitting this.  I'm trying out some UI options locally.  What do you think of something like this? (with hover over on the bars for exact timing info)

![image](https://cloud.githubusercontent.com/assets/218610/13382052/1316e4d4-de20-11e5-82c9-571fc4e6fe9f.png)

**Comment by rolandkool** [comment]
Hi, that overview looks better yes. In this example you can quickly see what is taking time, so that is good.
Our main app uses a lot of Async calls, how would these show up in such a flow diagram?
If it is possible to put this trace overview behind a configuration option in the code, I can check it out against our application and provide some better feedback.
Thanks.

**Comment by trask** [comment]
That would be great.  I'll post back, should be able to push something to master in another day that you can try out.

**Comment by trask** [comment]
Try the latest snapshot https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip

**Comment by trask** [comment]
This new graphical view is what made me notice #79 :-)

**Comment by trask** [comment]
Thanks for this suggestion as well
