### ISSUE TITLE
Support JBoss 4

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#72]
Hi,

We're stuck with JBoss 4 and when you add the javaagent, JBoss may not start or glowroot throws an error: javax.management.NotCompliantMBeanException: Class does not expose a management interface: java.lang.Object

We have -Djboss.platform.mbeanserver=true configured for other reasons and can't disable it.

**Comment by trask** [comment]
Thanks for reporting this.  I think I got it working.  Let me know if you run into any further issues.

**Comment by rolandkool** [comment]
I've verified latest build on JBoss 4 and I no longer get any errors related to mbeans. Started JBoss with the -Djboss.platform.mbeanserver=true setting.

**Comment by rolandkool** [comment]
Btw, latest build does give this error, but not just on JBoss:

2016-02-29 14:04:28.279 ERROR org.glowroot.agent.config.ConfigFile - error parsing config node 'advanced': 
org.glowroot.agent.shaded.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "timerWrapperMethods" (class org.glowroot.agent.config.ImmutableAdvancedConfig$Json), not marked as ignorable (7 known properties: "maxAggregateQueriesPerQueryType", "immediatePartialStoreThresholdSeconds", "weavingTimer", "mbeanGaugeNotFoundDelaySeconds", "maxStackTraceSamplesPerTransaction", "maxAggregateTransactionsPerTransactionType", "maxTraceEntriesPerTransaction"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.glowroot.agent.config.Json["timerWrapperMethods"])

**Comment by trask** [comment]
This error is because the config.json file has changed a bit in latest version.  Hoping to handle backwards compatibility starting with 0.9, but for now Glowroot should overwrite your existing config.json with a valid file, and you should only see this error once.  Let me know if you're seeing something different than this.  Thanks.

**Comment by rolandkool** [comment]
Yes indeed, the error occurred only once. Thanks, that explains.
