### ISSUE TITLE
Query bind parameters not captured?

### ISSUE THREAD

**Issue by smx-smx** [glowroot/glowroot#728]
Hello
Thank you for sharing and maintaining this very useful tool, first of all.

I'm not sure if i'm doing something wrong or if it's an unsupported feature, but i can't see query bind parameters from the built-in web UI.

Are they available only for elasticsearch and cassandra plugins?

You can verify the same behaviour on the demo server: [https://demo.glowroot.org](https://demo.glowroot.org)

Pick a query, and you won't be able to see any captured parameter even tho the regex .* is enabled

**Comment by smx-smx** [comment]
Nevermind, i was looking in the wrong place

**Comment by eostermueller** [comment]
I'm looking at my SQL statement on the "Queries" tab (under All Web Transactions), and all I see is question marks, and not the parameters that my code specified.
Am I looking in the wrong place?
Is there additional configuration that I need?

Thanks for sharing Glowroot with us :-).

--Erik

**Comment by dowonderatwill** [comment]
Check the trace entries.
