### ISSUE TITLE
Allow plugins to be disabled/removed

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#75]
Hi,

With latest build I noticed that all plugins are now automatically included in the glowroot.jar file in stead of having a separate plugins dir with a jar per plugin. Having plugins as separate jars, it is easier to keep them out of your distribution if you want to. Would be it be possible to restore this functionality or otherwise have a mechanism where you can disable a plugin completely?

Thanks

**Comment by trask** [comment]
It will help me to understand why you are wanting to disable some of them.  Conflicts with other plugins?  Simplify plugin config UI?  Weaving overhead?  Thanks.

**Comment by rolandkool** [comment]
The JSP plugin is problematic for us, it results in an error leaving our site with only blank pages. This could be related to the fact that we are stuck on java 6 (for now). So disabling the plugin by removing the jar was pretty useful.
Not sure about the overhead of loading plugins for libraries we don't use, like cassandra or struts.

**Comment by trask** [comment]
Is this on JBoss 4?  I tried but wasn't able to repro the issue with blank pages.  Can you give me some more ideas how I can repro?  I'd like to fix that.

In the meantime, you can edit `META-INF/glowroot.plugins.json` inside glowroot.jar and remove the jsp plugin lines:

```
  {
    "id": "jsp",
    "name": "JSP Plugin",
    "aspects": [
      "org.glowroot.agent.plugin.jsp.HttpJspPageAspect"
    ]
  },
```

**Comment by rolandkool** [comment]
Hi,
Not sure if you can repro the issue that we have with JSPs and glowroot. We're using a framework called ATG that seems to do some funky stuff.
Here is part of the stacktrace:
`Caused by: java.lang.NullPointerException
	at atg.servlet.MutableHttpServletRequest.getParameterMap(MutableHttpServletRequest.java:460)
	at org.glowroot.agent.plugin.servlet.RequestParameterAspect$GetParameterAdvice.onAfter(RequestParameterAspect.java:44)
	at atg.taglib.dspjsp.RequestWrapper.getParameter(RequestWrapper.java:436)
`

**Comment by ajdevries** [comment]
Hi Roland,

Thanks for the stacktrace. This is an issue in the Servlet plugin. It expects a request, but this is probably `null` in your case. An additional null check good help.

If you can rebuild glowroot by yourself you could try this small fix:

```java
...
  if (request == null) {
    return;
  }
  Map<String, String[]> parameterMap = request.getParameterMap();
  if (parameterMap == null) {
    return;
  }
...
```

On this line https://github.com/glowroot/glowroot/blob/master/agent-parent/plugins/servlet-plugin/src/main/java/org/glowroot/agent/plugin/servlet/RequestParameterAspect.java#L44

**Comment by rolandkool** [comment]
I've tried that patch and did a mvn clean install and put the result jar on the server, but unfortunately, still the same error.

**Comment by trask** [comment]
It looks like that version of ATG has a bad `HttpServletRequest.getParameterMap()` implementation. The glowroot servlet plugin calls that method to capture the request parameters, but I changed it to use `HttpServletRequest.getParameterNames()` and `HttpServletRequest.getParameterValues()` instead in this case. Can you try the latest snapshot https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip?

**Comment by rolandkool** [comment]
I've tested the snapshot version with our application and this version works. The JSP plugin enriches the traces nicely. I do think there is a small issue with the calculation of totals in the breakdown:

Duration: 823.6 milliseconds
Breakdown (Main Thread): 	total (ms) 	count 	
http request	4604.1 	236 	
jsp render	3999.0 	100

If you switch to tree view, it changes to:
Breakdown (Main Thread): 	total (ms) 	count 	
http request	823.6 	1 	
  jsp render	809.7 	1 	
     http request	800.3 	13 	
       jsp render	745.6 	5
etc

**Comment by trask** [comment]
Thanks, should be fixed in latest snapshot https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip
