### ISSUE TITLE
How to get data present on glowroot UI ?

### ISSUE THREAD

**Issue by anurag4869** [glowroot/glowroot#764]
We can see the traces details on glowroot UI (localhost:4000). I have to get that data (traces, stack trace, queries etc.) using API calls to glowroot.

Is the API for glowroot available? If not what are the ways to get that data.

@trask can you help me on this.

**Comment by anurag4869** [comment]
Hello @trask can you help me on this

**Comment by trask** [comment]
hi @anurag4869, the glowroot UI gets all of its data via JSON over REST API. It's not documented, but if you open Developer Tools in your browser, you can see the requests that are made by the UI and follow those as examples.
