### ISSUE TITLE
Add 'Service calls' overview for external http/etc service calls, similar to 'Queries' tab

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#77]
Hi,

The external queries overview shows all SQL statements that were done. Would it be possible to have a similar overview for http calls to external services?

**Comment by trask** [comment]
This is a nice idea, and should work well. Trying it currently.

**Comment by trask** [comment]
First pass is committed. I think it's a bit confusing under the Queries tab though, so I'm going to create a new tab called Services and move HTTP calls (and other future non-database stuff) over there.

**Comment by trask** [comment]
This turned out nicely I think, try it out when you have a chance, and thanks for the suggestion.
