### ISSUE TITLE
glowroot in the application pom.xml

### ISSUE THREAD

**Issue by mattjerry** [glowroot/glowroot#775]
hi - instead of adding glowroot jar separately and run it as part of jvm which means it needs glowroot to be downloaded and installed on server, can glowroot be clubbed with the code? can we have it in pom.xml and use it?

**Comment by trask** [comment]
hi @mattjerry, I haven't tried it with glowroot, but there is a way that might work, check out https://github.com/microsoft/ApplicationInsights-Java/blob/main/test/smoke/testApps/SpringBootAttachInMain/src/main/java/com/microsoft/applicationinsights/smoketestapp/AttachInFirstLineOfMain.java and https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/runtime-attach/src/main/java/io/opentelemetry/contrib/attach/RuntimeAttach.java for some ideas and feel free to post back here if you try it out with any success or problems
