### ISSUE TITLE
Info required on logging plugin

### ISSUE THREAD

**Issue by aslam-ahmed** [glowroot/glowroot#778]
First of all thanks for creating such a wonderful tool. It really helps a lot in troubleshooting performance issues.

Followup of issue: [https://github.com/glowroot/glowroot/issues/525](url)

1. Is there any way to turn off logging completely?
2. How to configure logging levels for this plugin? It seems like it capture trace level logs by default.
3. If there is a way to configure logging, is it possible to tune for certain classes or packages?

Please do let me know if the above features are not available then how to contribute for them. Happy to be a part of this, keep doing the good work.

**Comment by trask** [comment]
hi @aslam-ahmed, the logging plugin should only capture things that match your logging framework's configuration and are actually getting logged to some appender.

> It seems like it capture trace level logs by default

can you post your logging configuration? e.g. logback.xml, log4j.properties, log4j2.xml, etc

**Comment by aslam-ahmed** [comment]
Hi @trask, yes you are right, indeed the settings were configured for debug logging, i realized after we setup glowroot on a different environment.
