### ISSUE TITLE
Glowroot agent not starting on Openshift environment.

### ISSUE THREAD

**Issue by pankajcode0** [glowroot/glowroot#780]
Glowroot central is running on a VM and glowroot agent is deployed on openshift. but glowroot agent is not starting on openshift environment. sample docker file is added below.

#dockerfile-agent
FROM tomcat:8.0-alpine
WORKDIR /usr/local

#copy glow root agent to docker container, from specific path

COPY ./glowroot ./glowroot
RUN chmod 775 /usr/local/glowroot
RUN chmod +x /usr/local/glowroot/glowroot.jar

#Copy UI and Backend war

COPY ./sample.war /usr/local/tomcat/webapps/
#RUN chmod 775 /usr/local/tomcat/webapps
#EXPOSE 8080

ENV JAVA_OPTS="-javaagent:/usr/local/glowroot/glowroot.jar -Dglowroot.agent.id=sampleAgent"

**Comment by trask** [comment]
hi @pankajcode0, are you getting any error messages that might help narrow down where the problem is?
