### ISSUE TITLE
Glowroot agent not working for application on docker and central collector on linux

### ISSUE THREAD

**Issue by aakanksham31** [glowroot/glowroot#782]
Hi, we are having problem with setting up agent for an application on docker. we have central collector setup on linux machines and are have added agent jar as gradle dependency. below are the arguments added to jvm:

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /<application_jar>.jar -p 5185:5185 -javaagent:/glowroot-agent-0.13.4.jar -Dglowroot.agent.id=<agent id> -Dcollector.address=<collector address> -Dmulti.dir=true" ]

Application starts properly but there is no traffic flow to collector. Please help if there is something wrong in the setup

**Comment by dowonderatwill** [comment]
Do you see glowroot screen?
If not try below:
-javaagent for glowroot shall be first parameter, put it at leftmost parameter of Java.

If glowroot screen is appearing and you don’t see data then Change  the drop down from web to background
