### ISSUE TITLE
Dynamic slow transaction threshold

### ISSUE THREAD

**Issue by goldyliang** [glowroot/glowroot#786]
The slow transaction threshold can be set and that is great and it can be overwritten to other values for some transactions, or when instrument exists and gets hit.  That is great.

However, in many cases, a fixed number does not fit the need. For example, if the service transfers file content, whether it is slow or fast does not just consider the response time, but also the request/response body size. When we set a fixed threshold, a lot of long requests got traced as well which is not necessary, and also hard to isolate which is really slow and which not.

Suggestion:  in the instrument session, can we store the value from the argument/return value of a method call into a temp "variable", and then use that variable as the slow trace threshold? This requires some work from the application to adapt to this in order to expose the metrics, however, it is easier to implement compared to a more complex solution.

**Comment by trask** [comment]
hi @goldyliang, the slow threshold can be set programmatically on each transaction using:

https://glowroot.org/javadoc/agent-plugin-api/0.13.6/org/glowroot/agent/plugin/api/ThreadContext.html#setTransactionSlowThreshold-long-java.util.concurrent.TimeUnit-int-
