### ISSUE TITLE
Support more external authentication tools, like keycloak.

### ISSUE THREAD

**Issue by MFAshby** [glowroot/glowroot#793]
Hi!

We use glowroot for monitoring our java apps in production. Our org uses google logins for everything, and we use [keycloak](https://www.keycloak.org/) with users federated from google for securing any internal services that our staff need access to.

Unfortunately we have to use a VPN and shared login for glowroot, because it only supports LDAP for external authentication. This incurs extra operations and administrative overhead.

I think it would be great for glowroot to support keycloak for authentication. In turn users can be managed inside keycloak itself, or they can be federated from a number of upstream sources, like LDAP, social logins & active directory.

**Comment by MFAshby** [comment]
If glowroot were to fully switch to using keycloak, this would also remove the need for all the authentication handling code in glowroot, which is tangential to the actual purpose of glowroot. However it would also mean that keycloak becomes mandatory for securing glowroot, which isn't suitable for everyone.

**Comment by alex-klimov** [comment]
Hello! Would love to chat more on the exact design of authentication mechanism. Send me something to alex@abberit.io, we will talk through the options.

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
