### ISSUE TITLE
Glowroot suport Neo4j?

### ISSUE THREAD

**Issue by lucasalexsandrosoares** [glowroot/glowroot#800]
It is possible to monitor queries the Neo4j using glowroot?

**Comment by alex-klimov** [comment]
Until full support is provided - there is a way to enable custom instrumentation using this method:
https://demo.glowroot.org/config/instrumentation?new

Would that work for you?

**Comment by lucasalexsandrosoares** [comment]
What configuration should i use in Instrumentation?

**Comment by alex-klimov** [comment]
To use the instrumentation API I referenced - I would recommend to look at Neo4j jar with disasembly tool. That would allow you to measure the performance of Neo4j calls, alert on slow queries, etc.

That wouldn't give you the query itself though. That would require to create Plugin for the agent as described here:
https://glowroot.org/instrumentation.html

**Comment by trask** [comment]
Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).
