### ISSUE TITLE
Glowroot causing some issues with the spring boot application

### ISSUE THREAD

**Issue by anurag4869** [glowroot/glowroot#804]
After successful configuration of glowroot agent for a spring boot application. I am getting error as class not found. The deployment environment is a unix machine. The detailed error is :

WARN 7759 --- [main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'sampleBeanName' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed;

Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate

**Comment by trask** [comment]
hi @anurag4869, can you see if this is resolved in the latest 0.14.0-beta.2 release? and if not, can you provide a repro that I can use to troubleshoot the issue? thx
