### ISSUE TITLE
documentation : understanding glowroot flame graph

### ISSUE THREAD

**Issue by bgranier** [glowroot/glowroot#806]
Hi,

I did not see a documentation page to explain how to interpret glowroot flame graph and flame graph color.

It would very help full to get one, since all documentations i looked on the web explain a lot's of details about flame graphs : theirs origin, how to produce them, what is a call stack and so on. All of that is usefull but i did not find a simple page explaining briefly how to interpret flam graphs. 

Since this a key tool of glowroot, a such documentation page would be interesting.

Sincerly,

B. Granier

**Comment by trask** [comment]
hi @bgranier, there's more info here that will hopefully be helpful: https://github.com/spiermar/d3-flame-graph
