### ISSUE TITLE
heartbeat notification issue

### ISSUE THREAD

**Issue by siyanor** [glowroot/glowroot#808]
we have configured glowroot for one of our production environment.

we have been receiving many heartbeat notification, our heartbeat threshold is configured for 5 seconds but at the same time we are not finding any issue issue with our network connectivity.

is there a way to find out why these notification are being sent and to confirm the root cause of them. ?

**Comment by siyanor** [comment]
hello there,

is there anyone who can at least provide me a hint or guide me in the right direction.

**Comment by trask** [comment]
> our heartbeat threshold is configured for 5 seconds

This is too low. Heartbeats are normally received every 5 seconds, so there's no room for the smallest delay here. I would set it to at least 10 seconds, and even that is very aggressive.
