### ISSUE TITLE
Role setup for app deployed in k8s that only allow check rollup

### ISSUE THREAD

**Issue by hktv-tonyNg** [glowroot/glowroot#814]
We are using glowroot in k8s and i am setting up new Role that target developers can check all data for all pod one by one

Role setup 
![image](https://user-images.githubusercontent.com/64999070/126441814-4c6be4d2-3dd0-4580-8fb9-fedd690b4b53.png)
Agents setup
![image](https://user-images.githubusercontent.com/64999070/126443378-30c91e46-9f48-4e2c-b741-8c2b6b95d9a8.png)

We have 4 pods in k8s cluster and the user only allow select rollup to check gauges
![image](https://user-images.githubusercontent.com/64999070/126443317-ec0a8756-a03b-44f2-8e0d-6cec8b142bc5.png)

May i konw if how to setup that allow user to check each pod one by one? As k8s will auto start stop pod, it is not possible that we update permission select for each name of agent of pod.

**Comment by trask** [comment]
hi @hktv-tonyNg, permissions on rollups should be inherited by their children, is that not working for you, or am I not understanding the question? thx

**Comment by TONYHOKAN** [comment]
@trask in the UI behavior, we cannot select exactly that pod but only Rollup, so in the graph we will see all 4 pod data, if i only want to see 1 pod, the UI not allow to select.

**Comment by trask** [comment]
re-opening
