### ISSUE TITLE
admin.json being ignored

### ISSUE THREAD

**Issue by acholt** [glowroot/glowroot#815]
Hi

I've combed through the issues and followed the documentation regarding storage retention. I've configured the `admin.json` and place it in the same location as my Glowroot properties file, by following this documentation [1].

I did a simple test by setting everything to 24, but my configuration just seems to be ignored after checking the portal.
`{
  "users": [
    {
      "username": "anonymous",
      "roles": [
        "Administrator"
      ]
    }
  ],
  "roles": [
    {
      "name": "Administrator",
      "permissions": [
        "admin",
        "agent:*:config",
        "agent:*:error",
        "agent:*:incident",
        "agent:*:jvm",
        "agent:*:syntheticMonitor",
        "agent:*:transaction"
      ]
    }
  ],
  "web": {
    "sessionTimeoutMinutes": 30,
    "sessionCookieName": "GLOWROOT_SESSION_ID"
  },
  "storage": {
    "rollupExpirationHours": [
      24,
      24,
      24,
      24
    ],
    "queryAndServiceCallRollupExpirationHours": [
      24,
      24,
      24,
      24
    ],
    "profileRollupExpirationHours": [
      24,
      24,
      24,
      24
    ],
    "traceExpirationHours": 24
  }
}`

Glowroot version: v0.13.6
Running in: Kubernetes 1.20

[1] https://github.com/glowroot/glowroot/wiki/Agent-Installation-(with-Embedded-Collector)

Regards,
Andrew

**Comment by trask** [comment]
hi @acholt, I tried with the json above and got this error:

```
2021-11-07 14:16:07.287 ERROR org.glowroot.agent.config.ConfigFile - error parsing config json node 'storage':
org.glowroot.agent.shaded.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "queryAndServiceCallRollupExpirationHours" (class org.glowroot.agent.embedded.shaded.org.glowroot.common2.config.ImmutableEmbeddedStorageConfig$Json), not marked as ignorable (5 known properties: "rollupExpirationHours", "fullQueryTextExpirationHours", "traceExpirationHours", "rollupCappedDatabaseSizesMb", "traceCappedDatabaseSizeMb"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.glowroot.agent.embedded.shaded.org.glowroot.common2.config.Json["queryAndServiceCallRollupExpirationHours"])
```

It looks like you need to remove `queryAndServiceCallRollupExpirationHours` and `profileRollupExpirationHours` nodes from your `storage` configuration.
