### ISSUE TITLE
Support async servlets

### ISSUE THREAD

**Issue by trask** [glowroot/glowroot#82]
Currently glowroot transaction capture ends when the main thread is done processing the request/response loop. Some changes are needed to mark that the glowroot transaction should remain active waiting for async work to complete. The async work itself should already be captured by the executor plugin, though that plugin is currently limited to `ExecutorService.submit()` methods (which return a `Future`) and the plugin doesn't capture `Executor.execute()`, which is common for true async work where the main thread does not sit and wait on a `Future` to complete.

**Comment by ajdevries** [comment]
See https://github.com/glowroot/glowroot/pull/83
