### ISSUE TITLE
Glowroot agent not working with Java15

### ISSUE THREAD

**Issue by iam8139** [glowroot/glowroot#821]
Integrating Glowroot agent with Java application built on java 15 stops the application but the application does work without Glowroot agent. 
**Error** ->
**java.lang.VerifyError: Stack map does not match the one at exception handler 143
Exception Details:
   Location:
       com/sun/proxy/$Proxy208.update(Ljava/lang/String;Ljava/lang/Object;)V @143: iload_3
   Reason:
       Type 'java/lang/Throwable' (current frame, locals[1]) is not assignable to 'java/lang/String'
   Current Frame:
        locals: { 'com/sun/proxy/$Proxy208', 'java/lang/Throwable', 'java/lang/Object', integer, 'org/glowroot/agent/bytecode/api/ThreadContextThreadLocal$Holder', 'org/glowroot/agent/bytecode/api/ThreadContextPlus', integer, 'org/glowroot/agent/bytecode/api/Timer' }**

I tried updating the 'asm' library to 9.1 but this does not works !!

Please help me with this issue !!

**Comment by trask** [comment]
this should be resolved by #853 and #857
