### ISSUE TITLE
how to load redis plugin?

### ISSUE THREAD

**Issue by alexKeleon** [glowroot/glowroot#823]
accord this doc https://glowroot.org/instrumentation.html,  drop the  glowroot-agent-redis-plugin-0.13.6.jar to xxx/glowroot/plugins/ and restart the java vm, but the plugin not loaded

(base) deepctrl@CZ-WD-DL-7820-Tower-1:/data/lib/hx-platform-service/glowroot$ ls
admin.json  config.json  data  glowroot.jar  lib  LICENSE  logs  NOTICE  plugins  tmp

(base) deepctrl@CZ-WD-DL-7820-Tower-1:/data/lib/hx-platform-service/glowroot/plugins$ ls
glowroot-agent-redis-plugin-0.13.6.jar

**Comment by trask** [comment]
hi @alexKeleon, all of the plugins that are part of this repo are installed by default, no need to drop them into the `plugins` directory
