### ISSUE TITLE
Hibernate query not in trace entries overview

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#85]
Hi

I build a glowroot binary from latest code and noticed that the trace entries overview doesn't show any hibernate query entries. Is that correct?

The breakdown looks like:
` http request	9479.3 	1 `
`hibernate query	1956.9 	3 `
`hibernate commit	591.1 	4 `
`jdbc get connection	268.5 	10 `
`hibernate flush	211.9  1`

But trace entries only shows 5 entries: 4 hibernate commit and one hibernate flush.

**Comment by trask** [comment]
Trace entries are currently not captured for hibernate queries (only timer
data). My guess would be in this trace there were hibernate queries that
were served from cache and did not generate jdbc query? I'm thinking to add
timer for serving hibernate query from cache to make that scenario clearer.

**Comment by rolandkool** [comment]
Ok, curious that fetching 3 queries from cache takes almost 2 seconds. But if I understand correctly, a hibernate trace should also show jdbc calls when applicable?

**Comment by trask** [comment]
Yes, it should show the jdbc query in both the breakdown and in the trace entries.  Can you check the trace profile to see if any indication where the time is spent (maybe possible in jdbc that glowroot isn't capturing)?

**Comment by trask** [comment]
Closing, feel free to re-open if there is any update, thanks
