### ISSUE TITLE
Response body is deleted by Glowroot agent when an error occurs

### ISSUE THREAD

**Issue by bcourtine** [glowroot/glowroot#854]
Hello,

We spotted a strange behaviour.

On one of our webapps, when a functional error occurs, we send an error (status 4XX), with an explanation in the response body (which is printed to the user).

- Without glowroot agent, it works as intended.
- With glowroot agent, we get the good response code, but the response body becomes empty.

We reproduce this with latest Glowroot version (0.14.0-beta).
The bug also exists on 0.13.6 version.

Thanks a lot for your help.

I can investigate the bug, but I don't know Glowroot codebase and would appreciate some advice (where to look at).

**Comment by trask** [comment]
> With these information, I will try to create a minimal reproducible test case.

awesome, that would be super helpful, thx

**Comment by bcourtine** [comment]
Hi Trask,

These error-page management seems to be the cause of the bug.

Here is the minimum test case I promised: https://github.com/bcourtine/glowroot-test-case

- `mvn clean package`
- launch the main `org.courtine.JettyLauncher` class.
- Go to localhost:8080 and click on the "error" link: the custom error jspx page is displayed.

Same scenario, with Glowroot agent : the error page is not displayed anymore.

**Comment by trask** [comment]
@bcourtine great repro, thx!

**Comment by bcourtine** [comment]
Thanks a lot @trask !

Fix works perfectly.
