### ISSUE TITLE
Add export option on instrumentation configuration page

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#86]
Hi,

When managing instrumentations, there is an Import button, but no export, only one per instrumentation item. Would it be an idea to export all instrumentations with one button for easier importing later on?

**Comment by trask** [comment]
Thanks, this is nice idea, and is implemented now in the latest snapshot https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip
