### ISSUE TITLE
glowroot fail to start in domain jboss eap 7.2

### ISSUE THREAD

**Issue by victorssnc** [glowroot/glowroot#862]
On host.xml file under /opt/jboss-eap-7.2/domain/configuration/ path , have added the required jvm args :
<option value="-javaagent:/opt/jboss-eap-7.2/glowroot/glowroot.jar"/  and under system.properties as well 
glowroot.agent.id=appglow01
Could see the -Dglowroot.agent.id=appglow01 attach to the application process as well. But , could not see access the path -
http://localhost:4000 nor dont see any folders created under ../glowroot/  with agent name . I dont see any errors in application logs . What could be the wrong in the above set up ?  Kindly have a look.

**Comment by trask** [comment]
hi @victorssnc, are there any errors logged which may help narrow down the issue?

**Comment by victorssnc** [comment]
There was no errors logged in application server log or host or process controller log files  ..Is there any specific log for glowroot that we can check ?

**Comment by trask** [comment]
is there anything in the `glowroot.log`?

**Comment by victorssnc** [comment]
I don't see any such log file created under glowroot folder path .. don't see any errors also while the glowrooth jar has been to attached to application jvm

**Comment by trask** [comment]
can you tell if the JVM even starts up? if not, that would indicate that the `-javaagent` arg is incorrect (the JVM will fail to start on incorrect args)

**Comment by victorssnc** [comment]
Yes , application did start up fine :
20268 /opt/jboss-eap-7.2/jboss-modules.jar -mp /opt/jboss-eap-7.2/modules org.jboss.as.server -D[Server:XXXserver1] -D[pcid:1587408145] -Xms4096m -Xmx4096m -Dsun.lang.ClassLoader.allowArraySyntax=true -DMAX_HTTP_CONNECTIONS=200 -DMAX_HTTP_CONNECTIONS_PER_ROOT=20 -DXXXbidb.datasource.url=jdbc:oracle:thin:@XXXXXXX -DXXX.password=XXXXX -DXXX.username=XXX -DXXXdb.datasource.url=jdbc:oracle:thin:@XXXXXX -DXXX.max.pool.size=100 -DXXX.password=XXX -DXXXdb.username=XXXpowner -Dcom.atomikos.icatch.max_actives=100 -Ddb.connection.timeout=600 -Ddb.max.pool.size=20 -Ddb.min.pool.size=5 -Ddb.xaDataSource=oracle -**Dglowroot.agent.id=appglow01** -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djavax.net.ssl.keyStore=/opt/dst/bfmf-nonprod-keystore.jks -Djavax.net.ssl.keyStorePassword=XXXXXX -Djavax.net.ssl.trustStore=/opt/dst/bfmf-nonprod-truststore.jks -Djavax.net.ssl.trustStorePassword=XXXXXX -Djboss.home.dir=/opt/jboss-eap-7.2 -Djboss.modules.system.pkgs=org.jboss.byteman -Djdbc.XXXbidb.borrowConnectionTimeout=${db.connection.timeout} -Djdbc.XXXbi

**Comment by trask** [comment]
@victorssnc I don't see any `-javaagent:...` arg above, which would explain why the glowroot agent is not starting up

**Comment by victorssnc** [comment]
Yes , -javaagent was missing , so apart from making changes in host.xml , I have added "-javaagent:/opt/jboss-eap-7.2/domain/glowroot/glowroot.jar"/> under the domain.xml file and could see the javaagent popping up in the process list:
-Dglowroot.agent.id=**glowperfagent** -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djavaagent=**/opt/jboss-eap-7.2/domain/glowroot/glowroot.jar** -Djavax.
But, despite this , i dont see any log files under /opt/jboss-eap-7.2/domain/glowroot path nor could i access the url : http://localhost:4000 or http://127.0.0.1:4000

**Comment by trask** [comment]
`-Djavaagent=/opt/jboss-eap-7.2/domain/glowroot/glowroot.jar` should not have the `D`, and should have a `:` instead of `=`, e.g. 

```
-javaagent:/opt/jboss-eap-7.2/domain/glowroot/glowroot.jar
```

**Comment by victorssnc** [comment]
As per the user guide , if we had the below in host.xml only  ,  the javaagent is not picking up after application restart .. but if we add the same on domain.xml , it appears in the jvm process but with the Djavaagent**
**host.xml:** 
 <jvm name="default">
            <heap size="64m" max-size="256m"/>
            <permgen size="256m" max-size="256m"/>
            <jvm-options>
                <option value="-server"/>
                <option value="-javaagent:/opt/jboss-eap-7.2/domain/glowroot/glowroot.jar"/>
                <option value="-XX:MetaspaceSize=96m"/>
                <option value="-XX:MaxMetaspaceSize=256m"/>
             </jvm-options>
        </jvm>
**domain.xml:**
 <system-properties>
<property name="javaagent" value="/opt/jboss-eap-7.2/domain/glowroot/glowroot.jar" boot-time="true"/>

Not sure what is actually wrong why the javaagent is not  picking from host.xml file.

**Comment by trask** [comment]
hey @victorssnc, this part is not correct, and explains where the `-Djavaagent=...` is coming from

domain.xml:

```
<system-properties
<property name="javaagent" value="/opt/jboss-eap-7.2/domain/glowroot/glowroot.jar" boot-time="true"
```

I'm not sure why it's not getting picked up from the host.xml file. I would suggest searching for how to add JVM args to jboss eap maybe you can find some tips.

**Comment by victorssnc** [comment]
The jvm options has been added under the individual server level , with this the glowroot.jar has been picked up successfully..working fine finally ...glowroot user guide may need to change slightly for jboss domain mode..
