### ISSUE TITLE
log.error messages not showing under error tab

### ISSUE THREAD

**Issue by thulasi29n** [glowroot/glowroot#874]
Hi,

I configured 13.6 as java agent to my app. 

I am able to see log.error message in log trace of transactions tab, is there something that needs to done to pull / segregate log.error messages to get display under errors tab.

Please provide your thoughts on this, if you have been in this scenario previously

**Comment by trask** [comment]
hi @thulasi29n, checkout https://demo.glowroot.org/config/plugin?plugin-id=logger, this has some options that you can use to influence when a trace is marked as an error (which will cause it to show up under the errors tab)

**Comment by thulasi29n** [comment]
Hi trask,

Thank you, I am able to pull the details using logger plugin
