### ISSUE TITLE
Implement AWS Keyspaces support

### ISSUE THREAD

**Issue by rweintraub-cycleon** [glowroot/glowroot#875]
Hello Trask,

we're running glowroot in AWS to monitor our application performance across all microservices. We currently have set up Glowroot & cassandra in simple docker containers without proper persistence.
We initially tried to use the managed AWS cassandra service (AWS keyspaces) we found that it's not 100% compatible with Cassandra.
We've tried to play around a bit with it and found that a few things arent supported:

- Smoothly creating tables on first start up
- Creating an index in cassandra
- Doing a table count 
More detailed info from AWS: https://docs.aws.amazon.com/keyspaces/latest/devguide/cassandra-apis.html

Is it realistic to expect AWS keyspaces support for glowroot or should we just set up proper cassandra cluster in AWS?

Note: In case it would be helpful we could test Snapshot version of that to provide feedback on this feature

**Comment by ionutursuleanu** [comment]
Hi @rweintraub-cycleon ,

You can follow #700 for updates

**Comment by ionutursuleanu** [comment]
Hi @rweintraub-cycleon ,

AWS keyspaces does not implement some important apache cassandra features and it's not posible to use it for glowroot. See more details on #700

**Comment by rweintraub-cycleon** [comment]
Hi @ionutursuleanu, 
thanks for looking into this. For now I would consider this topic as closed then as I don't expect AWS to provide the missing features soon.
