### ISSUE TITLE
OpenShift permission error

### ISSUE THREAD

**Issue by robinroos** [glowroot/glowroot#934]
This is an Issue, instead of a PR, because I can't authenticate against Github right now to submit the PR.

In OpenShift, the 14.0.0-beta3 still fails with:

`sed: couldn't open temporary file ./sedJXX4LH: Permission denied`

I believe this to be because the Dockerfile invokes sed before changing the working directory.  At the point that sed is invoked, the current working directory is one which is not writable by the user, so sed fails to create its temporary file.

Referring to the edition of the file tagged for 14.0.0-beta3, here: https://github.com/glowroot/glowroot/blob/v0.14.0-beta.3/central/Dockerfile

I propose that the WORKDIR directive at line 23 be moved to be between lines 15 and 16, i.e. before the RUN which invokes sed, but after the COPY which establishes the directory.

I will try to sort out my authentication issues and submit a PR, but if anyone else can do the same more quickly then that would be great.

Naturally I would hope this will solve the issues in OpenShift and make it into the formal 14.0.0 release.  I have commented #933 accordingly.

**Comment by Nowheresly** [comment]
Hi @robinroos 
that's strange, I'm not able to reproduce your issue. Which setup are you using ?
I'm not sure moving the WORKDIR statement could help here.
I tried to come with a proposal yet. Could you try to reproduce this issue with the new Dockerfile version included in PR #935 please ?

**Comment by robinroos** [comment]
Hi @Nowheresly, many container platforms will respect a USER directive and allow nomination of user "root".  OpenShift will not do so.  OpenShift will run the container as a numberd user which cannot possibly exist on the underlying physical host, but guarantees that the numbered user will be a member of the "root" group.

That is why your PR will not solve my issue - you add a USER directive which will be ignored by OpenShift.

I believe the correct approach is to move the WORKDIR directive such that sed is executed from a directory which is known to be writable.

**Comment by robinroos** [comment]
I sorted out my Personal Access Token.  PR #936 submitted.
