### ISSUE TITLE
PathVariable are not replaced with * since springBoot Migration

### ISSUE THREAD

**Issue by chjourdain** [glowroot/glowroot#949]
We move from spring boot 2.4 to spring boot 2.6, 
And since then, the `@PathVariable` define in spring controller are not replace with "*" in transactionName.

This cause that a new TransactionName is created for every variable, which mean a lot more of work for our central-collector (now rebooting several time a day)

I'm currently looking at `ControllerAspect.HandlerMethodMappingAdvice.onBefore` to see what change in new spring Version

**Comment by chjourdain** [comment]
In fact `RequestMappingInfo` is now using `pathPatternsCondition` and not `PatternsRequestCondition`

**Comment by Nowheresly** [comment]
Thanks @chjourdain 
I've created an unofficial release of the glowroot agent which includes your fix.
You can get it here:
https://github.com/Nowheresly/glowroot/releases/tag/v0.14.0-beta.4.snapshot2
