### ISSUE TITLE
Hi, which `Transactions` will be display in glowroot?

### ISSUE THREAD

**Issue by littletiny** [glowroot/glowroot#96]
I start tomcat with glowroot, but i can't see any `Transactions` in localhost:4000
what Transactions glowroot collect? 

![info](https://cloud.githubusercontent.com/assets/5719999/14438076/d45baf6e-0056-11e6-8ce4-5668e0cfb332.jpg)

**Comment by trask** [comment]
Hi, it should capture and display aggregates (at the end of each minute) for all http requests, and specific traces for any http request that exceeds the configured threshold (Configuration > Transactions > Slow threshold).

Is there anything interesting logged in the `glowroot.log` file?

Thanks,
Trask

**Comment by trask** [comment]
Closing, but please re-open if you are still having any issue.  Thanks.
