### ISSUE TITLE
Alerts: E-Mail title

### ISSUE THREAD

**Issue by CengizS** [glowroot/glowroot#960]
Hello,

we do make heavy use of the cool Alert-Feature of glowroot but my operations team told me, that it's impossible to determine whether an Incident in upcoming or already resolved by just looking into the title. They want those mails to be filtered in their mail-system but that does not work quite well.

Would it be possible to have keywords "OPEN" and "RESOLVED" in the mail title?

**Comment by kumlali** [comment]
+1

This feature is already implemented for PagerDuty and Slack alerts in [AlertingService.java](common2/src/main/java/org/glowroot/common2/repo/util/AlertingService.java):  
* PagerDuty: https://github.com/glowroot/glowroot/blob/2b3b97c60936dfaba8cfaea4bc8ed734fa7d334b/common2/src/main/java/org/glowroot/common2/repo/util/AlertingService.java#L643-L646
* Slack: https://github.com/glowroot/glowroot/blob/2b3b97c60936dfaba8cfaea4bc8ed734fa7d334b/common2/src/main/java/org/glowroot/common2/repo/util/AlertingService.java#L403

Following steps would do the same thing for e-mail alerts:
* Passing "ok" status to `sendEmail()`
* Adding `" - triggered"` or `" - resolved"` to the end of subject regarding the status.

Here is what I did in this regard: https://github.com/glowroot/glowroot/commit/3bc8eae19c991b3b147d7b1fbd3ca5e25cc71ea3
