### ISSUE TITLE
Support for Spring's KafkaListener

### ISSUE THREAD

**Issue by andreldm** [glowroot/glowroot#969]
Currently Glowroot can trace `KafkaProducer#send` unfortunately listeners in Spring applications using `@KafkaListener` are not supported.

**Comment by Nowheresly** [comment]
We've added support for Kafkalistener in the main branch. This will be included in the next release.

**Comment by andreldm** [comment]
Thank you very much, I'll give it a try as soon as the release is available.

**Comment by Nowheresly** [comment]
Your feedback would be really appreciated.
In case you would like to test it without waiting for the next release, just add a file `kafkalistener.json` like this one:

```
{
  "name": "KafkaListener Plugin",
  "id": "myapp",
  "instrumentation": [
    {
      "classAnnotation": "org.springframework.stereotype.Component|org.springframework.stereotype.Service",
      "methodAnnotation": "org.springframework.kafka.annotation.KafkaListener",
      "methodParameterTypes": [
        ".."
      ],
      "captureKind": "transaction",
      "transactionType": "Background",
      "transactionNameTemplate": "Spring kafka: {{this.class.simpleName}}#{{methodName}}",
      "traceEntryMessageTemplate": "Spring kafka: {{this.class.name}}.{{methodName}}()",
      "timerName": "spring kafka"
    }
  ]
}
```

in your plugin folder as [explained in the documentation](https://glowroot.org/instrumentation.html).

With the next release of glowroot agent, this would be no more required.

**Comment by andreldm** [comment]
I confirm it's working, thanks again!
