### ISSUE TITLE
Additional search filters

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#98]
Hi,

Currently, glowroot can filter traces based on time, URL and user. I found that sometimes it would help if there were more ways to find requests, for instance by allowing you to search for/in:
- request parameters and/or cookie data
- requests with X amount of (http/jdbc/...) calls or minimum number of trace entries
- free form (grep like) to match any text of trace entries (or profile data)

Would you consider this being useful? With a central collector in place, these kinds of filters could be useful too I can imagine.

**Comment by rolandkool** [comment]
Perhaps auditing for these searches would be a good idea too (see https://github.com/glowroot/glowroot/issues/99)

**Comment by trask** [comment]
I like this idea, but it never seems to make the priority list.  Closing for now.
