### ISSUE TITLE
Support LDAP logins and auditing

### ISSUE THREAD

**Issue by rolandkool** [glowroot/glowroot#99]
Hi,

We would like to see support for personalized logins, preferably through LDAP. Based on group membership you get Admin or Readonly access to the GUI.

Also, some sort of auditing (additional logging) would be nice. A good start would be login, logout, session timeouts and all operations around instrumentation and trace exports.

**Comment by trask** [comment]
Hi, individual user logins and configurable roles are now added.  Also initial LDAP integration is added.  For the initial LDAP integration, you still have to create users and assign roles in glowroot.  The LDAP integration is just for password authentication at the moment.  After configuring LDAP (a new sidebar item under Configuration), you will see "Use LDAP for password" checkbox when configuring users, e.g.

![user](https://cloud.githubusercontent.com/assets/218610/15770210/93925d00-2916-11e6-95f2-228a63b6631b.png)

I'm not totally sure what to do about mapping LDAP group membership to Glowroot roles.  I'm using Apache Shiro, and they leave coding this mapping up to the application developer:

https://github.com/apache/shiro/blob/shiro-root-1.2.5/core/src/main/java/org/apache/shiro/realm/ldap/JndiLdapRealm.java#L426

which makes me think that this may not be easy to do consistently across different LDAP servers.

Interestingly, Shiro does have support for mapping LDAP group membership to roles in its Active Directory specific LDAP integration:

https://github.com/apache/shiro/blob/shiro-root-1.2.5/core/src/main/java/org/apache/shiro/realm/activedirectory/ActiveDirectoryRealm.java#L136

If you have ideas on this let me know.  And of course, let me know if you run into any issues testing.  Thanks.

**Comment by trask** [comment]
Much better LDAP support now, including LDAP group to Glowroot role mapping:

![ldap](https://cloud.githubusercontent.com/assets/218610/17143403/02d63860-5308-11e6-9973-e850152c6ca3.png)

**Comment by trask** [comment]
LDAP work is complete.  Moved auditing portion of this to a separate issue (#106).
