### ISSUE TITLE
Latest Beta - maven build error - Obfuscation failed - agent-embedded

### ISSUE THREAD

**Issue by parabinda** [glowroot/glowroot#998]
Hi,
I cloned the latest beta release and did a maven compile locally and my compilation has an error - Obfuscation failed 
---------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.6.0:proguard (default) on project glowroot-agent-embedded: Obfuscation failed (result=1) -> [Help 1]
[ERROR]
----------------------------------------------------------------------------
Please guide how to remove this error.
.
Thank you
Arabinda

**Comment by Nowheresly** [comment]
Hi @parabinda 
Maybe could you provide the full maven output from your attempt to build the project ?

**Comment by parabinda** [comment]
Hi Richard,
Thank you for a quick reply.
I avoided the issue by skipping the proguard check using 
-Dproguard.skip=true to Maven command line.
So, my build completed successfully, but obfuscation did not happen.

I will share the entire Maven build output, with you shortly with proguard check on.

Thank you
Arabinda

**Comment by parabinda** [comment]
Hi @Nowheresly,
Please find the complete Maven output attached.
The maven command used was - 
$ mvn -T2 clean install -DskipTests=true -l build.out

The build fails due to proguard error.

Please help.

Regards
Arabinda
[build.zip](https://github.com/glowroot/glowroot/files/11264882/build.zip)

**Comment by Nowheresly** [comment]
Hi @parabinda 
from the log you provided, it seems pretty clear the issue comes with the parallel execution.
Here are the kind of message we can see:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but this         *
[WARNING] * project contains the following plugin(s) that have goals not  *
[WARNING] * marked as thread-safe to support parallel execution.          *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against Apache Maven.                           *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked as thread-safe in Glowroot Central Collector:
[WARNING]   de.dentrassi.maven:rpm:1.8.0
[WARNING]   com.github.os72:protoc-jar-maven-plugin:3.11.4
[WARNING] 
[WARNING] Enable debug to see precisely which goals are not marked as thread-safe.
```

Thus you should avoid option -T with the maven command as it is unfortunately not supported...
