### ISSUE TITLE
Glowroot with Payara micro 6

### ISSUE THREAD

**Issue by lc-david-junyent** [glowroot/glowroot#999]
Hello everybody,

I have a possible issue... but I don't know if is a Glowroot problem or a new Payara version issue.

With Payara micro 5 the transactions and errors view are working well... but with Payara micro 6 it doesn't working. With this version it seems than only work the JVM panel.

Anyone having the same problem or know if Payara 6 is supported? 

Thanks for advanced.
Best reggards
David

**Comment by lc-david-junyent** [comment]
Hello again!,

I tryed to find differences with debugging a transaction. I saw that the GlowrootServiceImpl.setTransactionType method with Payara 5 give me the transaction but with Payara 6 not (when call transactionRegistry.getCurrentTransaction()).

I don't know the reason could be, I hope that this helps a bit.

Best reggards.
David

**Comment by Nowheresly** [comment]
Hello,  
which version of glowroot did you try with payara 6?
You should use version at least 0.14-beta4 available here: 
https://github.com/glowroot/glowroot/releases/tag/v0.14.0-beta.4

**Comment by lc-david-junyent** [comment]
Hello,

With this version works perfectly!
Thank you!

Best Reggards
David

**Comment by Nowheresly** [comment]
Thanks @lc-david-junyent for your feedback. This is really appreciated. v0.14 is now available.
